port module Backup exposing (Config, Flags, Model, Msg, Step, main)

{-| Downloads any new backups from the production server and then checks that the
newest one still decodes and still contains the same old messages it did last
time.

This used to be an [Eco](https://eco-lang.org/) program, which gave it direct
access to the file system and to subprocesses. Eco can't compile Lamdera projects
though, and the integrity check needs `Types.w3_decode_BackendModel` (generated by
the Lamdera compiler) to read a backup. So the program is now compiled by
`lamdera make` and run by `run.js`, which provides the same capabilities over
ports.

The check works by exporting a random handful of channels with the same
`ChannelExport` code the "Export channel" button uses, and comparing each export
against a reference stored alongside the backups. The first time a channel is
picked there's nothing to compare against, so its export becomes the reference.

-}

import Base64
import Bytes.Decode
import ChannelExport
import ChannelName
import Discord
import ExportComparison
import GuildName
import Id exposing (ChannelId, GuildId, Id)
import Json.Decode
import Json.Encode
import LocalState exposing (BackendChannel, BackendGuild, DiscordBackendChannel, DiscordBackendGuild)
import Platform
import Random
import SeqDict
import Time
import Types exposing (BackendModel)
import WireHelper


{-| Requests for the JavaScript host. Every request is a JSON object with a
`tag` field saying which one it is.
-}
port toJs : Json.Encode.Value -> Cmd msg


{-| Replies from the JavaScript host, tagged the same way as the request that
caused them. The program only ever has one request in flight, so replies are
matched against whatever step the program is currently on.
-}
port fromJs : (Json.Decode.Value -> msg) -> Sub msg


{-| How many channels of each kind (normal guilds and Discord guilds) to check
per run. Checking every channel would mean decoding and re-encoding the entire
history on every run, so instead each run picks a few at random and coverage
builds up over time.
-}
channelsPerRun : Int
channelsPerRun =
    3


main : Program Flags Model Msg
main =
    Platform.worker
        { init = init
        , update = update
        , subscriptions = \_ -> fromJs GotResponse
        }


type alias Flags =
    { source : String
    , dest : String
    , referenceDir : String
    , sshKey : Maybe String
    , time : Int
    , seed : Int
    }


type alias Config =
    { source : String
    , dest : String
    , referenceDir : String
    , sshKey : Maybe String
    , cutoff : Time.Posix
    , seed : Random.Seed
    }


type alias Model =
    { config : Config
    , step : Step
    }


type Step
    = CheckingRsync
    | CheckingDestDir
    | CreatingDestDir
    | Syncing
    | ListingBackups
    | ReadingBackup String
    | Verifying Verify
    | Exiting


type alias Verify =
    { awaiting : Awaiting
    , remaining : List ChannelToCheck
    , created : List String
    , verified : List String
    , failures : List String
    }


type Awaiting
    = AwaitingReference ChannelToCheck
    | AwaitingWrite


type alias ChannelToCheck =
    { name : String
    , referencePath : String
    , json : String
    }


type Msg
    = GotResponse Json.Decode.Value


init : Flags -> ( Model, Cmd Msg )
init flags =
    ( { config =
            { source = flags.source
            , dest = flags.dest
            , referenceDir = flags.referenceDir
            , sshKey = flags.sshKey
            , cutoff = Time.millisToPosix (flags.time - ExportComparison.oneWeek)
            , seed = Random.initialSeed flags.seed
            }
      , step = CheckingRsync
      }
    , Cmd.batch
        [ stdout ("Syncing " ++ flags.source ++ " -> " ++ flags.dest)
        , request "findExecutable" [ ( "name", Json.Encode.string "rsync" ) ]
        ]
    )


update : Msg -> Model -> ( Model, Cmd Msg )
update (GotResponse value) model =
    case Json.Decode.decodeValue decodeResponse value of
        Ok response ->
            handleResponse response model

        Err error ->
            fail model ("Could not understand the reply from run.js: " ++ Json.Decode.errorToString error)


handleResponse : Response -> Model -> ( Model, Cmd Msg )
handleResponse response model =
    case ( model.step, response ) of
        ( CheckingRsync, FoundExecutable True ) ->
            ( { model | step = CheckingDestDir }
            , request "dirExists" [ ( "path", Json.Encode.string model.config.dest ) ]
            )

        ( CheckingRsync, FoundExecutable False ) ->
            fail model "rsync was not found on PATH. Install rsync (and ssh) to use this backup downloader."

        ( CheckingDestDir, DirExists True ) ->
            startSync model

        ( CheckingDestDir, DirExists False ) ->
            ( { model | step = CreatingDestDir }
            , request "createDir" [ ( "path", Json.Encode.string model.config.dest ) ]
            )

        ( CreatingDestDir, DirCreated Nothing ) ->
            startSync model

        ( CreatingDestDir, DirCreated (Just error) ) ->
            fail model ("Could not create destination " ++ model.config.dest ++ ": " ++ error)

        ( Syncing, ProcessFinished 0 _ ) ->
            ( { model | step = ListingBackups }
            , Cmd.batch
                [ stdout "Done. Any new backups have been downloaded."
                , request "listDir" [ ( "path", Json.Encode.string model.config.dest ) ]
                ]
            )

        ( Syncing, ProcessFinished code maybeError ) ->
            ( { model | step = Exiting }
            , Cmd.batch
                [ stderr
                    (case maybeError of
                        Just error ->
                            "Failed to start rsync: " ++ error

                        Nothing ->
                            "rsync exited with code " ++ String.fromInt code
                    )
                , exit
                    (if code == 0 then
                        1

                     else
                        code
                    )
                ]
            )

        ( ListingBackups, DirListed (Ok files) ) ->
            case latestBackup files of
                Just fileName ->
                    ( { model | step = ReadingBackup fileName }
                    , Cmd.batch
                        [ stdout ("Checking the integrity of " ++ fileName)
                        , request
                            "readFileBase64"
                            [ ( "path", Json.Encode.string (model.config.dest ++ "/" ++ fileName) ) ]
                        ]
                    )

                Nothing ->
                    -- Nothing to verify isn't a failure. It just means this is a fresh
                    -- machine that hasn't downloaded a backup yet.
                    ( { model | step = Exiting }
                    , Cmd.batch
                        [ stdout "No backups to check yet."
                        , exit 0
                        ]
                    )

        ( ListingBackups, DirListed (Err error) ) ->
            fail model ("Could not list " ++ model.config.dest ++ ": " ++ error)

        ( ReadingBackup fileName, FileContents (Just base64) ) ->
            case Maybe.andThen (Bytes.Decode.decode WireHelper.decodeStreamedBackendModel) (Base64.toBytes base64) of
                Just backendModel ->
                    startVerifying backendModel model

                Nothing ->
                    fail
                        model
                        (fileName
                            ++ " could not be decoded. Either the backup is corrupt or it was written by a"
                            ++ " different version of at-chat than the one this program was compiled from."
                        )

        ( ReadingBackup fileName, FileContents Nothing ) ->
            fail model ("Could not read " ++ fileName)

        ( Verifying verify, FileContents contents ) ->
            case verify.awaiting of
                AwaitingReference channel ->
                    gotReference model verify channel contents

                AwaitingWrite ->
                    unexpected model response

        ( Verifying verify, FileWritten maybeError ) ->
            case ( verify.awaiting, maybeError ) of
                ( AwaitingWrite, Nothing ) ->
                    nextChannel model verify

                ( AwaitingWrite, Just error ) ->
                    nextChannel
                        model
                        { verify | failures = ("Could not write a reference export: " ++ error) :: verify.failures }

                ( AwaitingReference _, _ ) ->
                    unexpected model response

        _ ->
            unexpected model response


startSync : Model -> ( Model, Cmd Msg )
startSync model =
    ( { model | step = Syncing }
    , request
        "runProcess"
        [ ( "command", Json.Encode.string "rsync" )
        , ( "args"
          , Json.Encode.list Json.Encode.string
                [ "--archive" -- preserve timestamps/permissions
                , "--compress" -- compress during transfer
                , "--partial" -- keep partially transferred files so a re-run resumes them
                , "--ignore-existing" -- only download backups we don't already have
                , "--human-readable"
                , "--stats"
                , "-e"
                , sshCommand model.config
                , model.config.source
                , model.config.dest
                ]
          )
        ]
    )


{-| BatchMode makes ssh fail instead of prompting for a password, so an
unattended run can't hang waiting for input.
-}
sshCommand : Config -> String
sshCommand config =
    "ssh"
        ++ (case config.sshKey of
                Just key ->
                    " -i " ++ key

                Nothing ->
                    ""
           )
        ++ " -o BatchMode=yes -o StrictHostKeyChecking=accept-new -o ConnectTimeout=30"


{-| Backups are named `backend-export-<year>-<month>-<day>-<hour>:<minute>:<second>.bin`,
so the newest one is also the last one alphabetically.
-}
latestBackup : List String -> Maybe String
latestBackup files =
    List.filter (\file -> String.startsWith "backend-export-" file && String.endsWith ".bin" file) files
        |> List.maximum


startVerifying : BackendModel -> Model -> ( Model, Cmd Msg )
startVerifying backendModel model =
    let
        channels : List ChannelToCheck
        channels =
            channelsToCheck model.config backendModel
    in
    nextChannel
        model
        { -- Replaced straight away by nextChannel. There's nothing in flight yet.
          awaiting = AwaitingWrite
        , remaining = channels
        , created = []
        , verified = []
        , failures = []
        }
        |> Tuple.mapSecond
            (\cmd ->
                Cmd.batch
                    [ stdout
                        ("Exporting "
                            ++ String.fromInt (List.length channels)
                            ++ " randomly picked channels to compare against their reference exports"
                        )
                    , cmd
                    ]
            )


nextChannel : Model -> Verify -> ( Model, Cmd Msg )
nextChannel model verify =
    case verify.remaining of
        channel :: rest ->
            ( { model | step = Verifying { verify | awaiting = AwaitingReference channel, remaining = rest } }
            , request "readFile" [ ( "path", Json.Encode.string channel.referencePath ) ]
            )

        [] ->
            finish model verify


gotReference : Model -> Verify -> ChannelToCheck -> Maybe String -> ( Model, Cmd Msg )
gotReference model verify channel maybeReference =
    let
        writeReference : Verify -> ( Model, Cmd Msg )
        writeReference verify2 =
            ( { model | step = Verifying { verify2 | awaiting = AwaitingWrite } }
            , request
                "writeFile"
                [ ( "path", Json.Encode.string channel.referencePath )
                , ( "contents", Json.Encode.string channel.json )
                ]
            )
    in
    case maybeReference of
        Nothing ->
            writeReference { verify | created = channel.name :: verify.created }

        Just reference ->
            case ExportComparison.compareExports model.config.cutoff reference channel.json of
                Ok [] ->
                    -- Nothing older than a week changed, so the newer messages in this
                    -- export are safe to fold into the reference for the next run.
                    writeReference { verify | verified = channel.name :: verify.verified }

                Ok differences ->
                    nextChannel
                        model
                        { verify
                            | failures =
                                (channel.name
                                    ++ " no longer matches "
                                    ++ channel.referencePath
                                    ++ "\n  "
                                    ++ String.join "\n  " (List.map ExportComparison.differenceToString differences)
                                )
                                    :: verify.failures
                        }

                Err error ->
                    nextChannel
                        model
                        { verify | failures = (channel.name ++ ": " ++ error) :: verify.failures }


finish : Model -> Verify -> ( Model, Cmd Msg )
finish model verify =
    ( { model | step = Exiting }
    , Cmd.batch
        [ stdout
            ("Verified "
                ++ String.fromInt (List.length verify.verified)
                ++ " channels against their reference export and created "
                ++ String.fromInt (List.length verify.created)
                ++ " new reference exports in "
                ++ model.config.referenceDir
            )
        , if List.isEmpty verify.failures then
            exit 0

          else
            Cmd.batch
                [ stderr
                    ("The latest backup does not match the reference exports:\n"
                        ++ String.join "\n" (List.reverse verify.failures)
                    )
                , exit 1
                ]
        ]
    )


fail : Model -> String -> ( Model, Cmd Msg )
fail model error =
    ( { model | step = Exiting }, Cmd.batch [ stderr error, exit 1 ] )


unexpected : Model -> Response -> ( Model, Cmd Msg )
unexpected model response =
    fail model ("run.js replied with " ++ responseName response ++ " but that isn't what the program asked for")



-- PICKING CHANNELS


{-| Everything needed to produce one channel export, kept unevaluated until the
channel is actually picked so that a run only exports a handful of channels
instead of the entire history.
-}
type Candidate
    = GuildChannel (Id GuildId) BackendGuild (Id ChannelId) BackendChannel
    | DiscordGuildChannel (Discord.Id Discord.GuildId) DiscordBackendGuild (Discord.Id Discord.ChannelId) DiscordBackendChannel


channelsToCheck : Config -> BackendModel -> List ChannelToCheck
channelsToCheck config backendModel =
    let
        guildCandidates : List Candidate
        guildCandidates =
            SeqDict.toList backendModel.guilds
                |> List.concatMap
                    (\( guildId, guild ) ->
                        SeqDict.toList guild.channels
                            |> List.map (\( channelId, channel ) -> GuildChannel guildId guild channelId channel)
                    )

        discordCandidates : List Candidate
        discordCandidates =
            SeqDict.toList backendModel.discordGuilds
                |> List.concatMap
                    (\( guildId, guild ) ->
                        SeqDict.toList guild.channels
                            |> List.map (\( channelId, channel ) -> DiscordGuildChannel guildId guild channelId channel)
                    )

        ( guilds, seed ) =
            pickRandom channelsPerRun guildCandidates config.seed

        ( discordGuilds, _ ) =
            pickRandom channelsPerRun discordCandidates seed
    in
    List.map (candidateToCheck config backendModel) (guilds ++ discordGuilds)


candidateToCheck : Config -> BackendModel -> Candidate -> ChannelToCheck
candidateToCheck config backendModel candidate =
    case candidate of
        GuildChannel guildId guild channelId channel ->
            { name =
                "guild \""
                    ++ GuildName.toString guild.name
                    ++ "\" channel \""
                    ++ ChannelName.toString channel.name
                    ++ "\""
            , referencePath =
                config.referenceDir
                    ++ "/guild-"
                    ++ Id.toString guildId
                    ++ "-channel-"
                    ++ Id.toString channelId
                    ++ ".json"
            , json = ChannelExport.guildChannel backendModel.users guild channel
            }

        DiscordGuildChannel guildId guild channelId channel ->
            { name =
                "Discord guild \""
                    ++ GuildName.toString guild.name
                    ++ "\" channel \""
                    ++ ChannelName.toString channel.name
                    ++ "\""
            , referencePath =
                config.referenceDir
                    ++ "/discord-guild-"
                    ++ Discord.idToString guildId
                    ++ "-channel-"
                    ++ Discord.idToString channelId
                    ++ ".json"
            , json = ChannelExport.discordGuildChannel backendModel.discordUsers guildId guild channel
            }


pickRandom : Int -> List a -> Random.Seed -> ( List a, Random.Seed )
pickRandom count list seed =
    let
        ( weights, seed2 ) =
            Random.step (Random.list (List.length list) (Random.float 0 1)) seed
    in
    ( List.map2 Tuple.pair list weights
        |> List.sortBy Tuple.second
        |> List.take count
        |> List.map Tuple.first
    , seed2
    )



-- PORTS


request : String -> List ( String, Json.Encode.Value ) -> Cmd msg
request tag fields =
    toJs (Json.Encode.object (( "tag", Json.Encode.string tag ) :: fields))


stdout : String -> Cmd msg
stdout text =
    request "stdout" [ ( "text", Json.Encode.string text ) ]


stderr : String -> Cmd msg
stderr text =
    request "stderr" [ ( "text", Json.Encode.string text ) ]


exit : Int -> Cmd msg
exit code =
    request "exit" [ ( "code", Json.Encode.int code ) ]


type Response
    = FoundExecutable Bool
    | DirExists Bool
    | DirCreated (Maybe String)
    | ProcessFinished Int (Maybe String)
    | DirListed (Result String (List String))
    | FileContents (Maybe String)
    | FileWritten (Maybe String)


responseName : Response -> String
responseName response =
    case response of
        FoundExecutable _ ->
            "findExecutable"

        DirExists _ ->
            "dirExists"

        DirCreated _ ->
            "createDir"

        ProcessFinished _ _ ->
            "runProcess"

        DirListed _ ->
            "listDir"

        FileContents _ ->
            "readFile"

        FileWritten _ ->
            "writeFile"


decodeResponse : Json.Decode.Decoder Response
decodeResponse =
    Json.Decode.field "tag" Json.Decode.string
        |> Json.Decode.andThen
            (\tag ->
                case tag of
                    "findExecutable" ->
                        Json.Decode.map FoundExecutable (Json.Decode.field "found" Json.Decode.bool)

                    "dirExists" ->
                        Json.Decode.map DirExists (Json.Decode.field "exists" Json.Decode.bool)

                    "createDir" ->
                        Json.Decode.map DirCreated decodeMaybeError

                    "runProcess" ->
                        Json.Decode.map2
                            ProcessFinished
                            (Json.Decode.field "exitCode" Json.Decode.int)
                            decodeMaybeError

                    "listDir" ->
                        Json.Decode.map2
                            (\files maybeError ->
                                case maybeError of
                                    Just error ->
                                        DirListed (Err error)

                                    Nothing ->
                                        DirListed (Ok files)
                            )
                            (Json.Decode.oneOf
                                [ Json.Decode.field "files" (Json.Decode.list Json.Decode.string)
                                , Json.Decode.succeed []
                                ]
                            )
                            decodeMaybeError

                    "readFile" ->
                        Json.Decode.map FileContents decodeContents

                    "readFileBase64" ->
                        Json.Decode.map FileContents decodeContents

                    "writeFile" ->
                        Json.Decode.map FileWritten decodeMaybeError

                    _ ->
                        Json.Decode.fail ("Unknown tag " ++ tag)
            )


decodeContents : Json.Decode.Decoder (Maybe String)
decodeContents =
    Json.Decode.field "contents" (Json.Decode.nullable Json.Decode.string)


decodeMaybeError : Json.Decode.Decoder (Maybe String)
decodeMaybeError =
    Json.Decode.oneOf
        [ Json.Decode.field "error" (Json.Decode.nullable Json.Decode.string)
        , Json.Decode.succeed Nothing
        ]
