port module Backup exposing (Config, Flags, Model, Msg, Step, main)

{-| Downloads any new backups from the production server and then checks that the
newest one still decodes and still contains the same old messages it did last
time.

This used to be an [Eco](https://eco-lang.org/) program, which gave it direct
access to the file system and to subprocesses. Eco can't compile Lamdera projects
though, and the integrity check needs `Types.w3_decode_BackendModel` (generated by
the Lamdera compiler) to read a backup. So the program is now compiled by
`lamdera make` and run by `run.js`, which provides the same capabilities over
ports.

The check works by exporting a random handful of channels with the same
`ChannelExport` code the "Export channel" button uses, and comparing each export
against a reference stored alongside the backups. The first time a channel is
picked there's nothing to compare against, so its export becomes the reference.

-}

import Bytes exposing (Bytes)
import Bytes.Decode
import ChannelExport
import ChannelName
import Discord
import DiscordUserData exposing (DiscordUserData)
import ExportComparison
import GuildName
import Id exposing (GuildId, Id, UserId)
import Json.Decode
import Json.Encode
import LocalState exposing (BackendGuild, DiscordBackendGuild)
import NonemptyDict exposing (NonemptyDict)
import Platform
import Random
import SeqDict exposing (SeqDict)
import Time
import User exposing (BackendUser)
import WireHelper


{-| Requests for the JavaScript host. Every request is a JSON object with a
`tag` field saying which one it is.
-}
port toJs : Json.Encode.Value -> Cmd msg


{-| Replies from the JavaScript host, tagged the same way as the request that
caused them. The program only ever has one request in flight, so replies are
matched against whatever step the program is currently on.
-}
port fromJs : (Json.Decode.Value -> msg) -> Sub msg


{-| Lamdera lets `Bytes` cross a port, which is how a backup gets into Elm
without being copied or re-encoded on the way. Sending it as base64 instead
turned a 21 MB backup into 2.3 GB of intermediate encoders, because
`Base64.toBytes` allocates one per three bytes.
-}
port backupFileFromJs : (Bytes -> msg) -> Sub msg


{-| How many channels of each kind (normal guilds and Discord guilds) to check
per run. Checking every channel would mean decoding and re-encoding the entire
history on every run, so instead each run picks a few at random and coverage
builds up over time.
-}
channelsPerRun : Int
channelsPerRun =
    3


main : Program Flags Model Msg
main =
    Platform.worker
        { init = init
        , update = update
        , subscriptions =
            \_ -> Sub.batch [ fromJs GotResponse, backupFileFromJs GotBackupFile ]
        }


type alias Flags =
    { source : String
    , dest : String
    , referenceDir : String
    , sshKey : Maybe String
    , time : Int
    , seed : Int
    }


type alias Config =
    { source : String
    , dest : String
    , referenceDir : String
    , sshKey : Maybe String
    , cutoff : Time.Posix
    , seed : Random.Seed
    }


type alias Model =
    { config : Config
    , step : Step
    }


type Step
    = CheckingRsync
    | CheckingDestDir
    | CreatingDestDir
    | Syncing
    | ListingBackups
    | ReadingBackup String
    | Verifying Verify
    | Exiting


type alias Verify =
    { awaiting : Awaiting
    , remaining : List ChannelToCheck
    , created : List String
    , verified : List String
    , failures : List String
    }


type Awaiting
    = AwaitingReference ChannelToCheck
    | AwaitingWrite


type alias ChannelToCheck =
    { name : String
    , referencePath : String
    , json : String
    }


type Msg
    = GotResponse Json.Decode.Value
    | GotBackupFile Bytes


init : Flags -> ( Model, Cmd Msg )
init flags =
    ( { config =
            { source = flags.source
            , dest = flags.dest
            , referenceDir = flags.referenceDir
            , sshKey = flags.sshKey
            , cutoff = Time.millisToPosix (flags.time - ExportComparison.oneWeek)
            , seed = Random.initialSeed flags.seed
            }
      , step = CheckingRsync
      }
    , Cmd.batch
        [ stdout ("Syncing " ++ flags.source ++ " -> " ++ flags.dest)
        , request "findExecutable" [ ( "name", Json.Encode.string "rsync" ) ]
        ]
    )


update : Msg -> Model -> ( Model, Cmd Msg )
update msg model =
    case msg of
        GotResponse value ->
            case Json.Decode.decodeValue decodeResponse value of
                Ok response ->
                    handleResponse response model

                Err error ->
                    fail model ("Could not understand the reply from run.js: " ++ Json.Decode.errorToString error)

        GotBackupFile bytes ->
            case Bytes.Decode.decode (decodeBackup model.config) bytes of
                Just channels ->
                    startVerifying channels model

                Nothing ->
                    fail
                        model
                        ((case model.step of
                            ReadingBackup fileName ->
                                fileName

                            _ ->
                                "The backup"
                         )
                            ++ " could not be decoded. Either it is corrupt or it was written by a different"
                            ++ " version of at-chat than the one this program was compiled from."
                        )


handleResponse : Response -> Model -> ( Model, Cmd Msg )
handleResponse response model =
    case ( model.step, response ) of
        ( CheckingRsync, FoundExecutable True ) ->
            ( { model | step = CheckingDestDir }
            , request "dirExists" [ ( "path", Json.Encode.string model.config.dest ) ]
            )

        ( CheckingRsync, FoundExecutable False ) ->
            fail model "rsync was not found on PATH. Install rsync (and ssh) to use this backup downloader."

        ( CheckingDestDir, DirExists True ) ->
            startSync model

        ( CheckingDestDir, DirExists False ) ->
            ( { model | step = CreatingDestDir }
            , request "createDir" [ ( "path", Json.Encode.string model.config.dest ) ]
            )

        ( CreatingDestDir, DirCreated Nothing ) ->
            startSync model

        ( CreatingDestDir, DirCreated (Just error) ) ->
            fail model ("Could not create destination " ++ model.config.dest ++ ": " ++ error)

        ( Syncing, ProcessFinished 0 _ ) ->
            ( { model | step = ListingBackups }
            , Cmd.batch
                [ stdout "Done. Any new backups have been downloaded."
                , request "listDir" [ ( "path", Json.Encode.string model.config.dest ) ]
                ]
            )

        ( Syncing, ProcessFinished code maybeError ) ->
            ( { model | step = Exiting }
            , Cmd.batch
                [ stderr
                    (case maybeError of
                        Just error ->
                            "Failed to start rsync: " ++ error

                        Nothing ->
                            "rsync exited with code " ++ String.fromInt code
                    )
                , exit
                    (if code == 0 then
                        1

                     else
                        code
                    )
                ]
            )

        ( ListingBackups, DirListed (Ok files) ) ->
            case latestBackup files of
                Just fileName ->
                    ( { model | step = ReadingBackup fileName }
                    , Cmd.batch
                        [ stdout ("Checking the integrity of " ++ fileName)
                        , request
                            "readBackupFile"
                            [ ( "path", Json.Encode.string (model.config.dest ++ "/" ++ fileName) ) ]
                        ]
                    )

                Nothing ->
                    -- Nothing to verify isn't a failure. It just means this is a fresh
                    -- machine that hasn't downloaded a backup yet.
                    ( { model | step = Exiting }
                    , Cmd.batch
                        [ stdout "No backups to check yet."
                        , exit 0
                        ]
                    )

        ( ListingBackups, DirListed (Err error) ) ->
            fail model ("Could not list " ++ model.config.dest ++ ": " ++ error)

        -- Only sent when the read failed. A successful read arrives on the bytes port.
        ( ReadingBackup fileName, BackupFileFailed error ) ->
            fail model ("Could not read " ++ fileName ++ ": " ++ error)

        ( Verifying verify, FileContents contents ) ->
            case verify.awaiting of
                AwaitingReference channel ->
                    gotReference model verify channel contents

                AwaitingWrite ->
                    unexpected model response

        ( Verifying verify, FileWritten maybeError ) ->
            case ( verify.awaiting, maybeError ) of
                ( AwaitingWrite, Nothing ) ->
                    nextChannel model verify

                ( AwaitingWrite, Just error ) ->
                    nextChannel
                        model
                        { verify | failures = ("Could not write a reference export: " ++ error) :: verify.failures }

                ( AwaitingReference _, _ ) ->
                    unexpected model response

        _ ->
            unexpected model response


startSync : Model -> ( Model, Cmd Msg )
startSync model =
    ( { model | step = Syncing }
    , request
        "runProcess"
        [ ( "command", Json.Encode.string "rsync" )
        , ( "args"
          , Json.Encode.list Json.Encode.string
                [ "--archive" -- preserve timestamps/permissions
                , "--compress" -- compress during transfer
                , "--partial" -- keep partially transferred files so a re-run resumes them
                , "--ignore-existing" -- only download backups we don't already have
                , "--human-readable"
                , "--stats"
                , "-e"
                , sshCommand model.config
                , model.config.source
                , model.config.dest
                ]
          )
        ]
    )


{-| BatchMode makes ssh fail instead of prompting for a password, so an
unattended run can't hang waiting for input.
-}
sshCommand : Config -> String
sshCommand config =
    "ssh"
        ++ (case config.sshKey of
                Just key ->
                    " -i " ++ key

                Nothing ->
                    ""
           )
        ++ " -o BatchMode=yes -o StrictHostKeyChecking=accept-new -o ConnectTimeout=30"


startVerifying : List ChannelToCheck -> Model -> ( Model, Cmd Msg )
startVerifying channels model =
    nextChannel
        model
        { -- Replaced straight away by nextChannel. There's nothing in flight yet.
          awaiting = AwaitingWrite
        , remaining = channels
        , created = []
        , verified = []
        , failures = []
        }
        |> Tuple.mapSecond
            (\cmd ->
                Cmd.batch
                    [ stdout
                        ("Exporting "
                            ++ String.fromInt (List.length channels)
                            ++ " randomly picked channels to compare against their reference exports"
                        )
                    , cmd
                    ]
            )


nextChannel : Model -> Verify -> ( Model, Cmd Msg )
nextChannel model verify =
    case verify.remaining of
        channel :: rest ->
            ( { model | step = Verifying { verify | awaiting = AwaitingReference channel, remaining = rest } }
            , request "readFile" [ ( "path", Json.Encode.string channel.referencePath ) ]
            )

        [] ->
            finish model verify


gotReference : Model -> Verify -> ChannelToCheck -> Maybe String -> ( Model, Cmd Msg )
gotReference model verify channel maybeReference =
    let
        writeReference : Verify -> ( Model, Cmd Msg )
        writeReference verify2 =
            ( { model | step = Verifying { verify2 | awaiting = AwaitingWrite } }
            , request
                "writeFile"
                [ ( "path", Json.Encode.string channel.referencePath )
                , ( "contents", Json.Encode.string channel.json )
                ]
            )
    in
    case maybeReference of
        Nothing ->
            writeReference { verify | created = channel.name :: verify.created }

        Just reference ->
            case ExportComparison.compareExports model.config.cutoff reference channel.json of
                Ok [] ->
                    -- Nothing older than a week changed, so the newer messages in this
                    -- export are safe to fold into the reference for the next run.
                    writeReference { verify | verified = channel.name :: verify.verified }

                Ok differences ->
                    nextChannel
                        model
                        { verify
                            | failures =
                                (channel.name
                                    ++ " no longer matches "
                                    ++ channel.referencePath
                                    ++ "\n  "
                                    ++ String.join "\n  " (List.map ExportComparison.differenceToString differences)
                                )
                                    :: verify.failures
                        }

                Err error ->
                    nextChannel
                        model
                        { verify | failures = (channel.name ++ ": " ++ error) :: verify.failures }


finish : Model -> Verify -> ( Model, Cmd Msg )
finish model verify =
    ( { model | step = Exiting }
    , Cmd.batch
        [ stdout
            ("Verified "
                ++ String.fromInt (List.length verify.verified)
                ++ " channels against their reference export and created "
                ++ String.fromInt (List.length verify.created)
                ++ " new reference exports in "
                ++ model.config.referenceDir
            )
        , if List.isEmpty verify.failures then
            exit 0

          else
            Cmd.batch
                [ stderr
                    ("The latest backup does not match the reference exports:\n"
                        ++ String.join "\n" (List.reverse verify.failures)
                    )
                , exit 1
                ]
        ]
    )


fail : Model -> String -> ( Model, Cmd Msg )
fail model error =
    ( { model | step = Exiting }, Cmd.batch [ stderr error, exit 1 ] )


unexpected : Model -> Response -> ( Model, Cmd Msg )
unexpected model response =
    fail model ("run.js replied with " ++ responseName response ++ " but that isn't what the program asked for")



-- READING THE BACKUP


{-| Backups are named `backend-export-<year>-<month>-<day>-<hour>:<minute>:<second>.bin`,
so the newest one is also the last one alphabetically.
-}
latestBackup : List String -> Maybe String
latestBackup files =
    List.filter (\file -> String.startsWith "backend-export-" file && String.endsWith ".bin" file) files
        |> List.maximum



-- PICKING CHANNELS


{-| Picking the channels while the backup is being decoded, rather than decoding
it into a `BackendModel` and picking afterwards, is what keeps this program's
memory use in proportion to the biggest guild instead of to the whole backup.
-}
type alias Sampling =
    { users : NonemptyDict (Id UserId) BackendUser
    , discordUsers : SeqDict (Discord.Id Discord.UserId) DiscordUserData
    , guilds : Sampler
    , discordGuilds : Sampler
    }


type alias Sampler =
    { seed : Random.Seed
    , seen : Int
    , picked : List ChannelToCheck
    }


decodeBackup : Config -> Bytes.Decode.Decoder (List ChannelToCheck)
decodeBackup config =
    let
        ( guildSeed, discordSeed ) =
            Random.step Random.independentSeed config.seed
    in
    WireHelper.foldStreamedBackendModel
        { init =
            \backendModel ->
                { users = backendModel.users
                , discordUsers = backendModel.discordUsers
                , guilds = { seed = guildSeed, seen = 0, picked = [] }
                , discordGuilds = { seed = discordSeed, seen = 0, picked = [] }
                }
        , guild = foldGuild config
        , discordGuild = foldDiscordGuild config
        }
        |> Bytes.Decode.map
            (\sampling -> List.reverse sampling.guilds.picked ++ List.reverse sampling.discordGuilds.picked)


foldGuild : Config -> ( Id GuildId, BackendGuild ) -> Sampling -> Sampling
foldGuild config ( guildId, guild ) sampling =
    { sampling
        | guilds =
            SeqDict.foldl
                (\channelId channel sampler ->
                    sample
                        (\() ->
                            { name =
                                "guild \""
                                    ++ GuildName.toString guild.name
                                    ++ "\" channel \""
                                    ++ ChannelName.toString channel.name
                                    ++ "\""
                            , referencePath =
                                config.referenceDir
                                    ++ "/guild-"
                                    ++ Id.toString guildId
                                    ++ "-channel-"
                                    ++ Id.toString channelId
                                    ++ ".json"
                            , json = ChannelExport.guildChannel sampling.users guild channel
                            }
                        )
                        sampler
                )
                sampling.guilds
                guild.channels
    }


foldDiscordGuild : Config -> ( Discord.Id Discord.GuildId, DiscordBackendGuild ) -> Sampling -> Sampling
foldDiscordGuild config ( guildId, guild ) sampling =
    { sampling
        | discordGuilds =
            SeqDict.foldl
                (\channelId channel sampler ->
                    sample
                        (\() ->
                            { name =
                                "Discord guild \""
                                    ++ GuildName.toString guild.name
                                    ++ "\" channel \""
                                    ++ ChannelName.toString channel.name
                                    ++ "\""
                            , referencePath =
                                config.referenceDir
                                    ++ "/discord-guild-"
                                    ++ Discord.idToString guildId
                                    ++ "-channel-"
                                    ++ Discord.idToString channelId
                                    ++ ".json"
                            , json = ChannelExport.discordGuildChannel sampling.discordUsers guildId guild channel
                            }
                        )
                        sampler
                )
                sampling.discordGuilds
                guild.channels
    }


{-| Reservoir sampling. Every channel in the backup gets the same chance of being
picked without knowing up front how many there are, and no more than
`channelsPerRun` of them are ever held. The export is only generated for a channel
that is actually kept, since generating one renders every message in the channel.
-}
sample : (() -> ChannelToCheck) -> Sampler -> Sampler
sample toChannel sampler =
    let
        seen : Int
        seen =
            sampler.seen + 1
    in
    if List.length sampler.picked < channelsPerRun then
        { sampler | seen = seen, picked = toChannel () :: sampler.picked }

    else
        let
            ( index, seed ) =
                Random.step (Random.int 0 (seen - 1)) sampler.seed
        in
        { sampler
            | seen = seen
            , seed = seed
            , picked =
                if index < channelsPerRun then
                    List.indexedMap
                        (\pickedIndex picked ->
                            if pickedIndex == index then
                                toChannel ()

                            else
                                picked
                        )
                        sampler.picked

                else
                    sampler.picked
        }



-- PORTS


request : String -> List ( String, Json.Encode.Value ) -> Cmd msg
request tag fields =
    toJs (Json.Encode.object (( "tag", Json.Encode.string tag ) :: fields))


stdout : String -> Cmd msg
stdout text =
    request "stdout" [ ( "text", Json.Encode.string text ) ]


stderr : String -> Cmd msg
stderr text =
    request "stderr" [ ( "text", Json.Encode.string text ) ]


exit : Int -> Cmd msg
exit code =
    request "exit" [ ( "code", Json.Encode.int code ) ]


type Response
    = FoundExecutable Bool
    | DirExists Bool
    | DirCreated (Maybe String)
    | ProcessFinished Int (Maybe String)
    | DirListed (Result String (List String))
    | FileContents (Maybe String)
    | FileWritten (Maybe String)
    | BackupFileFailed String


responseName : Response -> String
responseName response =
    case response of
        FoundExecutable _ ->
            "findExecutable"

        DirExists _ ->
            "dirExists"

        DirCreated _ ->
            "createDir"

        ProcessFinished _ _ ->
            "runProcess"

        DirListed _ ->
            "listDir"

        FileContents _ ->
            "readFile"

        FileWritten _ ->
            "writeFile"

        BackupFileFailed _ ->
            "readBackupFile"


decodeResponse : Json.Decode.Decoder Response
decodeResponse =
    Json.Decode.field "tag" Json.Decode.string
        |> Json.Decode.andThen
            (\tag ->
                case tag of
                    "findExecutable" ->
                        Json.Decode.map FoundExecutable (Json.Decode.field "found" Json.Decode.bool)

                    "dirExists" ->
                        Json.Decode.map DirExists (Json.Decode.field "exists" Json.Decode.bool)

                    "createDir" ->
                        Json.Decode.map DirCreated decodeMaybeError

                    "runProcess" ->
                        Json.Decode.map2
                            ProcessFinished
                            (Json.Decode.field "exitCode" Json.Decode.int)
                            decodeMaybeError

                    "listDir" ->
                        Json.Decode.map2
                            (\files maybeError ->
                                case maybeError of
                                    Just error ->
                                        DirListed (Err error)

                                    Nothing ->
                                        DirListed (Ok files)
                            )
                            (Json.Decode.oneOf
                                [ Json.Decode.field "files" (Json.Decode.list Json.Decode.string)
                                , Json.Decode.succeed []
                                ]
                            )
                            decodeMaybeError

                    "readFile" ->
                        Json.Decode.map FileContents decodeContents

                    "writeFile" ->
                        Json.Decode.map FileWritten decodeMaybeError

                    "readBackupFile" ->
                        Json.Decode.map
                            (\maybeError -> BackupFileFailed (Maybe.withDefault "unknown error" maybeError))
                            decodeMaybeError

                    _ ->
                        Json.Decode.fail ("Unknown tag " ++ tag)
            )


decodeContents : Json.Decode.Decoder (Maybe String)
decodeContents =
    Json.Decode.field "contents" (Json.Decode.nullable Json.Decode.string)


decodeMaybeError : Json.Decode.Decoder (Maybe String)
decodeMaybeError =
    Json.Decode.oneOf
        [ Json.Decode.field "error" (Json.Decode.nullable Json.Decode.string)
        , Json.Decode.succeed Nothing
        ]
