port module Backup exposing (Config, Flags, Model, Msg, Step, main)

{-| Downloads any new backups from the production server and then checks that the
newest one still decodes and still contains the same old messages it did last
time.

This used to be an [Eco](https://eco-lang.org/) program, which gave it direct
access to the file system and to subprocesses. Eco can't compile Lamdera projects
though, and the integrity check needs `Types.w3_decode_BackendModel` (generated by
the Lamdera compiler) to read a backup. So the program is now compiled by
`lamdera make` and run by `run.js`, which provides the same capabilities over
ports.

The check works by exporting the busiest channel of each of the first few guilds
with the same `ChannelExport` code the "Export channel" button uses, and comparing
each export against a reference stored alongside the backups. The first time a
channel is picked there's nothing to compare against, so its export becomes the
reference.

-}

import Bytes exposing (Bytes)
import Bytes.Decode
import ChannelExport
import ChannelName
import Discord
import DiscordUserData exposing (DiscordUserData)
import ExportComparison
import GuildName
import Id exposing (ChannelId, GuildId, Id, UserId)
import IdArray exposing (IdArray)
import Json.Decode
import Json.Encode
import LocalState exposing (BackendGuild, DiscordBackendGuild)
import NonemptyDict exposing (NonemptyDict)
import Platform
import SeqDict exposing (SeqDict)
import Set exposing (Set)
import Time
import User exposing (BackendUser)
import WireHelper


{-| Requests for the JavaScript host. Every request is a JSON object with a
`tag` field saying which one it is.
-}
port toJs : Json.Encode.Value -> Cmd msg


{-| Replies from the JavaScript host, tagged the same way as the request that
caused them. The program only ever has one request in flight, so replies are
matched against whatever step the program is currently on.
-}
port fromJs : (Json.Decode.Value -> msg) -> Sub msg


{-| Lamdera lets `Bytes` cross a port, which is how a backup gets into Elm
without being copied or re-encoded on the way. Sending it as base64 instead
turned a 21 MB backup into 2.3 GB of intermediate encoders, because
`Base64.toBytes` allocates one per three bytes.
-}
port backupFileFromJs : (Bytes -> msg) -> Sub msg


{-| How many guilds of each kind (normal and Discord) to check per run, taken
from the front of the backup. Checking every channel would mean rendering the
entire history on every run.
-}
guildsPerRun : Int
guildsPerRun =
    5


main : Program Flags Model Msg
main =
    Platform.worker
        { init = init
        , update = update
        , subscriptions =
            \_ -> Sub.batch [ fromJs GotResponse, backupFileFromJs GotBackupFile ]
        }


type alias Flags =
    { source : String
    , dest : String
    , referenceDir : String
    , sshKey : Maybe String
    , time : Int
    }


type alias Config =
    { source : String
    , dest : String
    , referenceDir : String
    , sshKey : Maybe String
    , cutoff : Time.Posix
    }


type alias Model =
    { config : Config
    , step : Step
    }


type Step
    = CheckingRsync
    | CheckingDestDir
    | CreatingDestDir
    | Syncing
    | ListingBackups
    | ReadingBackup String
    | ListingReferences Backup
    | Verifying Verify
    | Exiting


type alias Verify =
    { awaiting : Awaiting
    , remaining : List ChannelToCheck
    , created : List String
    , verified : List String
    , failures : List String
    }


{-| A reference export's file name doubles as the identity of the channel it
belongs to, which is what lets a run notice that a channel has gone missing.
-}
type alias ChannelToCheck =
    { name : String
    , referenceName : String
    , json : String
    }


type Awaiting
    = AwaitingReference ChannelToCheck
    | AwaitingWrite


type Msg
    = GotResponse Json.Decode.Value
    | GotBackupFile Bytes


init : Flags -> ( Model, Cmd Msg )
init flags =
    ( { config =
            { source = flags.source
            , dest = flags.dest
            , referenceDir = flags.referenceDir
            , sshKey = flags.sshKey
            , cutoff = Time.millisToPosix (flags.time - ExportComparison.oneWeek)
            }
      , step = CheckingRsync
      }
    , Cmd.batch
        [ stdout ("Syncing " ++ flags.source ++ " -> " ++ flags.dest)
        , request "findExecutable" [ ( "name", Json.Encode.string "rsync" ) ]
        ]
    )


update : Msg -> Model -> ( Model, Cmd Msg )
update msg model =
    case msg of
        GotResponse value ->
            case Json.Decode.decodeValue decodeResponse value of
                Ok response ->
                    handleResponse response model

                Err error ->
                    fail model ("Could not understand the reply from run.js: " ++ Json.Decode.errorToString error)

        GotBackupFile bytes ->
            case Bytes.Decode.decode decodeBackup bytes of
                Just backup ->
                    ( { model | step = ListingReferences backup }
                    , request "listDir" [ ( "path", Json.Encode.string model.config.referenceDir ) ]
                    )

                Nothing ->
                    fail
                        model
                        ((case model.step of
                            ReadingBackup fileName ->
                                fileName

                            _ ->
                                "The backup"
                         )
                            ++ " could not be decoded. Either it is corrupt or it was written by a different"
                            ++ " version of at-chat than the one this program was compiled from."
                        )


handleResponse : Response -> Model -> ( Model, Cmd Msg )
handleResponse response model =
    case ( model.step, response ) of
        ( CheckingRsync, FoundExecutable True ) ->
            ( { model | step = CheckingDestDir }
            , request "dirExists" [ ( "path", Json.Encode.string model.config.dest ) ]
            )

        ( CheckingRsync, FoundExecutable False ) ->
            fail model "rsync was not found on PATH. Install rsync (and ssh) to use this backup downloader."

        ( CheckingDestDir, DirExists True ) ->
            startSync model

        ( CheckingDestDir, DirExists False ) ->
            ( { model | step = CreatingDestDir }
            , request "createDir" [ ( "path", Json.Encode.string model.config.dest ) ]
            )

        ( CreatingDestDir, DirCreated Nothing ) ->
            startSync model

        ( CreatingDestDir, DirCreated (Just error) ) ->
            fail model ("Could not create destination " ++ model.config.dest ++ ": " ++ error)

        ( Syncing, ProcessFinished 0 _ ) ->
            ( { model | step = ListingBackups }
            , Cmd.batch
                [ stdout "Done. Any new backups have been downloaded."
                , request "listDir" [ ( "path", Json.Encode.string model.config.dest ) ]
                ]
            )

        ( Syncing, ProcessFinished code maybeError ) ->
            ( { model | step = Exiting }
            , Cmd.batch
                [ stderr
                    (case maybeError of
                        Just error ->
                            "Failed to start rsync: " ++ error

                        Nothing ->
                            "rsync exited with code " ++ String.fromInt code
                    )
                , exit
                    (if code == 0 then
                        1

                     else
                        code
                    )
                ]
            )

        ( ListingBackups, DirListed (Ok files) ) ->
            case latestBackup files of
                Just fileName ->
                    ( { model | step = ReadingBackup fileName }
                    , Cmd.batch
                        [ stdout ("Checking the integrity of " ++ fileName)
                        , request
                            "readBackupFile"
                            [ ( "path", Json.Encode.string (model.config.dest ++ "/" ++ fileName) ) ]
                        ]
                    )

                Nothing ->
                    -- Nothing to verify isn't a failure. It just means this is a fresh
                    -- machine that hasn't downloaded a backup yet.
                    ( { model | step = Exiting }
                    , Cmd.batch
                        [ stdout "No backups to check yet."
                        , exit 0
                        ]
                    )

        ( ListingBackups, DirListed (Err error) ) ->
            fail model ("Could not list " ++ model.config.dest ++ ": " ++ error)

        -- Only sent when the read failed. A successful read arrives on the bytes port.
        ( ReadingBackup fileName, BackupFileFailed error ) ->
            fail model ("Could not read " ++ fileName ++ ": " ++ error)

        ( ListingReferences backup, DirListed referenceFiles ) ->
            -- A missing reference folder is just a first run, so an error listing
            -- it is treated as "no references yet" rather than a failure.
            startVerifying backup (Result.withDefault [] referenceFiles) model

        ( Verifying verify, FileContents contents ) ->
            case verify.awaiting of
                AwaitingReference channel ->
                    gotReference model verify channel contents

                AwaitingWrite ->
                    unexpected model response

        ( Verifying verify, FileWritten maybeError ) ->
            case ( verify.awaiting, maybeError ) of
                ( AwaitingWrite, Nothing ) ->
                    nextChannel model verify

                ( AwaitingWrite, Just error ) ->
                    nextChannel
                        model
                        { verify | failures = ("Could not write a reference export: " ++ error) :: verify.failures }

                ( AwaitingReference _, _ ) ->
                    unexpected model response

        _ ->
            unexpected model response


startSync : Model -> ( Model, Cmd Msg )
startSync model =
    ( { model | step = Syncing }
    , request
        "runProcess"
        [ ( "command", Json.Encode.string "rsync" )
        , ( "args"
          , Json.Encode.list Json.Encode.string
                [ "--archive" -- preserve timestamps/permissions
                , "--compress" -- compress during transfer
                , "--partial" -- keep partially transferred files so a re-run resumes them
                , "--ignore-existing" -- only download backups we don't already have
                , "--human-readable"
                , "--stats"
                , "-e"
                , sshCommand model.config
                , model.config.source
                , model.config.dest
                ]
          )
        ]
    )


{-| BatchMode makes ssh fail instead of prompting for a password, so an
unattended run can't hang waiting for input.
-}
sshCommand : Config -> String
sshCommand config =
    "ssh"
        ++ (case config.sshKey of
                Just key ->
                    " -i " ++ key

                Nothing ->
                    ""
           )
        ++ " -o BatchMode=yes -o StrictHostKeyChecking=accept-new -o ConnectTimeout=30"


startVerifying : Backup -> List String -> Model -> ( Model, Cmd Msg )
startVerifying backup referenceFiles model =
    let
        orphans : List String
        orphans =
            orphanedReferences backup.channelsInBackup referenceFiles
    in
    nextChannel
        model
        { -- Replaced straight away by nextChannel. There's nothing in flight yet.
          awaiting = AwaitingWrite
        , remaining = backup.channels
        , created = []
        , verified = []
        , failures =
            List.map
                (\orphan ->
                    referencePath model.config orphan
                        ++ " has a reference export but the channel is no longer in the backup"
                )
                orphans
        }
        |> Tuple.mapSecond
            (\cmd ->
                Cmd.batch
                    [ stdout
                        ("Exporting the busiest channel of "
                            ++ String.fromInt (List.length backup.channels)
                            ++ " guilds to compare against their reference exports"
                        )
                    , cmd
                    ]
            )


referencePath : Config -> String -> String
referencePath config referenceName =
    config.referenceDir ++ "/" ++ referenceName


nextChannel : Model -> Verify -> ( Model, Cmd Msg )
nextChannel model verify =
    case verify.remaining of
        channel :: rest ->
            ( { model | step = Verifying { verify | awaiting = AwaitingReference channel, remaining = rest } }
            , request "readFile" [ ( "path", Json.Encode.string (referencePath model.config channel.referenceName) ) ]
            )

        [] ->
            finish model verify


gotReference : Model -> Verify -> ChannelToCheck -> Maybe String -> ( Model, Cmd Msg )
gotReference model verify channel maybeReference =
    let
        writeReference : Verify -> ( Model, Cmd Msg )
        writeReference verify2 =
            ( { model | step = Verifying { verify2 | awaiting = AwaitingWrite } }
            , request
                "writeFile"
                [ ( "path", Json.Encode.string (referencePath model.config channel.referenceName) )
                , ( "contents", Json.Encode.string channel.json )
                ]
            )
    in
    case maybeReference of
        Nothing ->
            writeReference { verify | created = channel.name :: verify.created }

        Just reference ->
            case ExportComparison.compareExports model.config.cutoff reference channel.json of
                Ok [] ->
                    -- Nothing older than a week changed, so the newer messages in this
                    -- export are safe to fold into the reference for the next run.
                    writeReference { verify | verified = channel.name :: verify.verified }

                Ok differences ->
                    nextChannel
                        model
                        { verify
                            | failures =
                                (channel.name
                                    ++ " no longer matches "
                                    ++ referencePath model.config channel.referenceName
                                    ++ "\n  "
                                    ++ String.join "\n  " (List.map ExportComparison.differenceToString differences)
                                )
                                    :: verify.failures
                        }

                Err error ->
                    nextChannel
                        model
                        { verify | failures = (channel.name ++ ": " ++ error) :: verify.failures }


finish : Model -> Verify -> ( Model, Cmd Msg )
finish model verify =
    ( { model | step = Exiting }
    , Cmd.batch
        [ stdout
            ("Verified "
                ++ String.fromInt (List.length verify.verified)
                ++ " channels against their reference export and created "
                ++ String.fromInt (List.length verify.created)
                ++ " new reference exports in "
                ++ model.config.referenceDir
            )
        , if List.isEmpty verify.failures then
            exit 0

          else
            Cmd.batch
                [ stderr
                    ("The latest backup does not match the reference exports:\n"
                        ++ String.join "\n" (List.reverse verify.failures)
                    )
                , exit 1
                ]
        ]
    )


fail : Model -> String -> ( Model, Cmd Msg )
fail model error =
    ( { model | step = Exiting }, Cmd.batch [ stderr error, exit 1 ] )


unexpected : Model -> Response -> ( Model, Cmd Msg )
unexpected model response =
    fail model ("run.js replied with " ++ responseName response ++ " but that isn't what the program asked for")



-- READING THE BACKUP


{-| Backups are named `backend-export-<year>-<month>-<day>-<hour>:<minute>:<second>.bin`,
so the newest one is also the last one alphabetically.
-}
latestBackup : List String -> Maybe String
latestBackup files =
    List.filter (\file -> String.startsWith "backend-export-" file && String.endsWith ".bin" file) files
        |> List.maximum



-- PICKING CHANNELS


{-| Built up while the backup is decoded, so that no more than one guild is ever
alive at a time.
-}
type alias Collected =
    { users : NonemptyDict (Id UserId) BackendUser
    , discordUsers : SeqDict (Discord.Id Discord.UserId) DiscordUserData
    , guildsSeen : Int
    , discordGuildsSeen : Int
    , picked : List ChannelToCheck
    , discordPicked : List ChannelToCheck

    -- Every channel in the backup, whether or not it was picked. A reference
    -- export whose channel isn't in here belongs to a channel that's gone.
    , channelsInBackup : Set String
    }


type alias Backup =
    { channels : List ChannelToCheck
    , channelsInBackup : Set String
    }


decodeBackup : Bytes.Decode.Decoder Backup
decodeBackup =
    WireHelper.foldStreamedBackendModel
        { init =
            \backendModel ->
                { users = backendModel.users
                , discordUsers = backendModel.discordUsers
                , guildsSeen = 0
                , discordGuildsSeen = 0
                , picked = []
                , discordPicked = []
                , channelsInBackup = Set.empty
                }
        , guild = foldGuild
        , discordGuild = foldDiscordGuild
        }
        |> Bytes.Decode.map
            (\collected ->
                { channels = List.reverse collected.picked ++ List.reverse collected.discordPicked
                , channelsInBackup = collected.channelsInBackup
                }
            )


foldGuild : ( Id GuildId, BackendGuild ) -> Collected -> Collected
foldGuild ( guildId, guild ) collected =
    { collected
        | guildsSeen = collected.guildsSeen + 1
        , channelsInBackup =
            SeqDict.foldl
                (\channelId _ names -> Set.insert (guildReferenceName guildId channelId) names)
                collected.channelsInBackup
                guild.channels
        , picked =
            case
                ( collected.guildsSeen < guildsPerRun
                , mostMessages guild.channels
                )
            of
                ( True, Just ( channelId, channel ) ) ->
                    { name =
                        "guild \""
                            ++ GuildName.toString guild.name
                            ++ "\" channel \""
                            ++ ChannelName.toString channel.name
                            ++ "\""
                    , referenceName = guildReferenceName guildId channelId
                    , json = ChannelExport.guildChannel collected.users guild channel
                    }
                        :: collected.picked

                _ ->
                    collected.picked
    }


foldDiscordGuild : ( Discord.Id Discord.GuildId, DiscordBackendGuild ) -> Collected -> Collected
foldDiscordGuild ( guildId, guild ) collected =
    { collected
        | discordGuildsSeen = collected.discordGuildsSeen + 1
        , channelsInBackup =
            SeqDict.foldl
                (\channelId _ names -> Set.insert (discordReferenceName guildId channelId) names)
                collected.channelsInBackup
                guild.channels
        , discordPicked =
            case
                ( collected.discordGuildsSeen < guildsPerRun
                , mostMessages guild.channels
                )
            of
                ( True, Just ( channelId, channel ) ) ->
                    { name =
                        "Discord guild \""
                            ++ GuildName.toString guild.name
                            ++ "\" channel \""
                            ++ ChannelName.toString channel.name
                            ++ "\""
                    , referenceName = discordReferenceName guildId channelId
                    , json = ChannelExport.discordGuildChannel collected.discordUsers guildId guild channel
                    }
                        :: collected.discordPicked

                _ ->
                    collected.discordPicked
    }


{-| The busiest channel is the one worth checking, and picking by message count
rather than at random means a run checks the same channel as the last one did.
Ties go to whichever channel comes first in the backup, so the choice only moves
when the guild's traffic does.
-}
mostMessages :
    SeqDict key { channel | messages : IdArray messageId message }
    -> Maybe ( key, { channel | messages : IdArray messageId message } )
mostMessages channels =
    SeqDict.foldl
        (\channelId channel best ->
            case best of
                Just ( _, bestSoFar ) ->
                    if IdArray.length channel.messages > IdArray.length bestSoFar.messages then
                        Just ( channelId, channel )

                    else
                        best

                Nothing ->
                    Just ( channelId, channel )
        )
        Nothing
        channels


guildReferenceName : Id GuildId -> Id ChannelId -> String
guildReferenceName guildId channelId =
    "guild-" ++ Id.toString guildId ++ "-channel-" ++ Id.toString channelId ++ ".json"


discordReferenceName : Discord.Id Discord.GuildId -> Discord.Id Discord.ChannelId -> String
discordReferenceName guildId channelId =
    "discord-guild-" ++ Discord.idToString guildId ++ "-channel-" ++ Discord.idToString channelId ++ ".json"


{-| Reference exports left behind by channels that are no longer in the backup.
Either the channel was deleted, which is worth saying out loud, or the backup
lost it, which is exactly what this program is here to catch. It can't tell the
two apart, so it reports and lets a human decide.
-}
orphanedReferences : Set String -> List String -> List String
orphanedReferences channelsInBackup referenceFiles =
    List.filter
        (\file -> String.endsWith ".json" file && not (Set.member file channelsInBackup))
        referenceFiles



-- PORTS


request : String -> List ( String, Json.Encode.Value ) -> Cmd msg
request tag fields =
    toJs (Json.Encode.object (( "tag", Json.Encode.string tag ) :: fields))


stdout : String -> Cmd msg
stdout text =
    request "stdout" [ ( "text", Json.Encode.string text ) ]


stderr : String -> Cmd msg
stderr text =
    request "stderr" [ ( "text", Json.Encode.string text ) ]


exit : Int -> Cmd msg
exit code =
    request "exit" [ ( "code", Json.Encode.int code ) ]


type Response
    = FoundExecutable Bool
    | DirExists Bool
    | DirCreated (Maybe String)
    | ProcessFinished Int (Maybe String)
    | DirListed (Result String (List String))
    | FileContents (Maybe String)
    | FileWritten (Maybe String)
    | BackupFileFailed String


responseName : Response -> String
responseName response =
    case response of
        FoundExecutable _ ->
            "findExecutable"

        DirExists _ ->
            "dirExists"

        DirCreated _ ->
            "createDir"

        ProcessFinished _ _ ->
            "runProcess"

        DirListed _ ->
            "listDir"

        FileContents _ ->
            "readFile"

        FileWritten _ ->
            "writeFile"

        BackupFileFailed _ ->
            "readBackupFile"


decodeResponse : Json.Decode.Decoder Response
decodeResponse =
    Json.Decode.field "tag" Json.Decode.string
        |> Json.Decode.andThen
            (\tag ->
                case tag of
                    "findExecutable" ->
                        Json.Decode.map FoundExecutable (Json.Decode.field "found" Json.Decode.bool)

                    "dirExists" ->
                        Json.Decode.map DirExists (Json.Decode.field "exists" Json.Decode.bool)

                    "createDir" ->
                        Json.Decode.map DirCreated decodeMaybeError

                    "runProcess" ->
                        Json.Decode.map2
                            ProcessFinished
                            (Json.Decode.field "exitCode" Json.Decode.int)
                            decodeMaybeError

                    "listDir" ->
                        Json.Decode.map2
                            (\files maybeError ->
                                case maybeError of
                                    Just error ->
                                        DirListed (Err error)

                                    Nothing ->
                                        DirListed (Ok files)
                            )
                            (Json.Decode.oneOf
                                [ Json.Decode.field "files" (Json.Decode.list Json.Decode.string)
                                , Json.Decode.succeed []
                                ]
                            )
                            decodeMaybeError

                    "readFile" ->
                        Json.Decode.map FileContents decodeContents

                    "writeFile" ->
                        Json.Decode.map FileWritten decodeMaybeError

                    "readBackupFile" ->
                        Json.Decode.map
                            (\maybeError -> BackupFileFailed (Maybe.withDefault "unknown error" maybeError))
                            decodeMaybeError

                    _ ->
                        Json.Decode.fail ("Unknown tag " ++ tag)
            )


decodeContents : Json.Decode.Decoder (Maybe String)
decodeContents =
    Json.Decode.field "contents" (Json.Decode.nullable Json.Decode.string)


decodeMaybeError : Json.Decode.Decoder (Maybe String)
decodeMaybeError =
    Json.Decode.oneOf
        [ Json.Decode.field "error" (Json.Decode.nullable Json.Decode.string)
        , Json.Decode.succeed Nothing
        ]
