module Evergreen.Migrate.V112 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Array
import Dict
import Effect.Lamdera
import Evergreen.V109.AiChat
import Evergreen.V109.ChannelName
import Evergreen.V109.Coord
import Evergreen.V109.CssPixels
import Evergreen.V109.Discord
import Evergreen.V109.Discord.Id
import Evergreen.V109.DmChannel
import Evergreen.V109.Editable
import Evergreen.V109.EmailAddress
import Evergreen.V109.Emoji
import Evergreen.V109.FileName
import Evergreen.V109.FileStatus
import Evergreen.V109.Geometry.Types
import Evergreen.V109.GuildName
import Evergreen.V109.Id
import Evergreen.V109.Internal.Model2
import Evergreen.V109.Internal.Teleport
import Evergreen.V109.Local
import Evergreen.V109.LocalState
import Evergreen.V109.Log
import Evergreen.V109.LoginForm
import Evergreen.V109.Message
import Evergreen.V109.MessageInput
import Evergreen.V109.MessageView
import Evergreen.V109.NonemptyDict
import Evergreen.V109.NonemptySet
import Evergreen.V109.OneOrGreater
import Evergreen.V109.OneToOne
import Evergreen.V109.Pages.Admin
import Evergreen.V109.Pagination
import Evergreen.V109.PersonName
import Evergreen.V109.Point2d
import Evergreen.V109.Ports
import Evergreen.V109.Postmark
import Evergreen.V109.RichText
import Evergreen.V109.Route
import Evergreen.V109.SecretId
import Evergreen.V109.SessionIdHash
import Evergreen.V109.Slack
import Evergreen.V109.Table
import Evergreen.V109.TextEditor
import Evergreen.V109.Touch
import Evergreen.V109.TwoFactorAuthentication
import Evergreen.V109.Types
import Evergreen.V109.Ui.Anim
import Evergreen.V109.User
import Evergreen.V109.UserAgent
import Evergreen.V109.UserSession
import Evergreen.V109.VisibleMessages
import Evergreen.V112.AiChat
import Evergreen.V112.ChannelName
import Evergreen.V112.Coord
import Evergreen.V112.CssPixels
import Evergreen.V112.Discord
import Evergreen.V112.Discord.Id
import Evergreen.V112.DmChannel
import Evergreen.V112.Editable
import Evergreen.V112.EmailAddress
import Evergreen.V112.Emoji
import Evergreen.V112.FileName
import Evergreen.V112.FileStatus
import Evergreen.V112.Geometry.Types
import Evergreen.V112.GuildName
import Evergreen.V112.Id
import Evergreen.V112.Internal.Model2
import Evergreen.V112.Internal.Teleport
import Evergreen.V112.Local
import Evergreen.V112.LocalState
import Evergreen.V112.Log
import Evergreen.V112.LoginForm
import Evergreen.V112.Message
import Evergreen.V112.MessageInput
import Evergreen.V112.MessageView
import Evergreen.V112.NonemptyDict
import Evergreen.V112.NonemptySet
import Evergreen.V112.OneOrGreater
import Evergreen.V112.OneToOne
import Evergreen.V112.Pages.Admin
import Evergreen.V112.Pagination
import Evergreen.V112.PersonName
import Evergreen.V112.Point2d
import Evergreen.V112.Ports
import Evergreen.V112.Postmark
import Evergreen.V112.RichText
import Evergreen.V112.Route
import Evergreen.V112.SecretId
import Evergreen.V112.SessionIdHash
import Evergreen.V112.Slack
import Evergreen.V112.Table
import Evergreen.V112.TextEditor
import Evergreen.V112.Thread
import Evergreen.V112.Touch
import Evergreen.V112.TwoFactorAuthentication
import Evergreen.V112.Types
import Evergreen.V112.Ui.Anim
import Evergreen.V112.User
import Evergreen.V112.UserAgent
import Evergreen.V112.UserSession
import Evergreen.V112.VisibleMessages
import Lamdera.Migrations exposing (..)
import List
import List.Nonempty
import Maybe
import Quantity
import SeqDict
import SeqSet
import UInt64


frontendModel : Evergreen.V109.Types.FrontendModel -> ModelMigration Evergreen.V112.Types.FrontendModel Evergreen.V112.Types.FrontendMsg
frontendModel old =
    ModelReset


backendModel : Evergreen.V109.Types.BackendModel -> ModelMigration Evergreen.V112.Types.BackendModel Evergreen.V112.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V109.Types.FrontendMsg -> MsgMigration Evergreen.V112.Types.FrontendMsg Evergreen.V112.Types.FrontendMsg
frontendMsg old =
    MsgOldValueIgnored


toBackend : Evergreen.V109.Types.ToBackend -> MsgMigration Evergreen.V112.Types.ToBackend Evergreen.V112.Types.BackendMsg
toBackend old =
    MsgOldValueIgnored


backendMsg : Evergreen.V109.Types.BackendMsg -> MsgMigration Evergreen.V112.Types.BackendMsg Evergreen.V112.Types.BackendMsg
backendMsg old =
    MsgMigrated ( migrate_Types_BackendMsg old, Cmd.none )


toFrontend : Evergreen.V109.Types.ToFrontend -> MsgMigration Evergreen.V112.Types.ToFrontend Evergreen.V112.Types.FrontendMsg
toFrontend old =
    MsgOldValueIgnored


migrate_Types_BackendModel : Evergreen.V109.Types.BackendModel -> Evergreen.V112.Types.BackendModel
migrate_Types_BackendModel old =
    { users = old.users |> migrate_NonemptyDict_NonemptyDictMaybe migrate_Id_Id migrate_User_BackendUser
    , sessions = old.sessions |> SeqDict.map (\k -> migrate_UserSession_UserSession)
    , connections = old.connections |> SeqDict.map (\k -> migrate_NonemptyDict_NonemptyDict identity migrate_Types_LastRequest)
    , secretCounter = old.secretCounter
    , pendingLogins = old.pendingLogins |> SeqDict.map (\k -> migrate_Types_LoginTokenData)
    , logs =
        old.logs
            |> Array.map
                (\rec ->
                    { time = rec.time
                    , log = rec.log |> migrate_Log_Log
                    }
                )
    , emailNotificationsEnabled = old.emailNotificationsEnabled
    , lastErrorLogEmail = old.lastErrorLogEmail
    , twoFactorAuthentication = old.twoFactorAuthentication |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Id_Id migrate_TwoFactorAuthentication_TwoFactorAuthentication) |> SeqDict.fromList
    , twoFactorAuthenticationSetup = old.twoFactorAuthenticationSetup |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Id_Id migrate_TwoFactorAuthentication_TwoFactorAuthenticationSetup) |> SeqDict.fromList
    , guilds = old.guilds |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Id_Id migrate_LocalState_BackendGuild) |> SeqDict.fromList
    , backendInitialized = old.backendInitialized
    , discordGuilds = SeqDict.empty
    , dmChannels = old.dmChannels |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_DmChannel_DmChannelId migrate_DmChannel_DmChannel) |> SeqDict.fromList
    , discordDmChannels = SeqDict.empty
    , slackDms = old.slackDms |> migrate_OneToOne_OneToOne migrate_Slack_Id migrate_DmChannel_DmChannelId
    , slackWorkspaces = old.slackWorkspaces |> migrate_OneToOne_OneToOne identity migrate_Id_Id
    , slackUsers = old.slackUsers |> migrate_OneToOne_OneToOne migrate_Slack_Id migrate_Id_Id
    , slackServers = old.slackServers |> migrate_OneToOne_OneToOne migrate_Slack_Id migrate_Id_Id
    , slackToken = old.slackToken |> Maybe.map migrate_Slack_AuthToken
    , files = old.files |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_FileStatus_FileHash migrate_Types_BackendFileData) |> SeqDict.fromList
    , privateVapidKey = old.privateVapidKey |> migrate_LocalState_PrivateVapidKey
    , publicVapidKey = old.publicVapidKey
    , slackClientSecret = old.slackClientSecret |> Maybe.map migrate_Slack_ClientSecret
    , openRouterKey = old.openRouterKey
    , textEditor = old.textEditor |> migrate_TextEditor_LocalState
    , discordUsers = SeqDict.empty
    , pendingDiscordCreateMessages = SeqDict.empty
    , pendingDiscordCreateDmMessages = SeqDict.empty
    }


migrate_AiChat_AiModelsStatus : Evergreen.V109.AiChat.AiModelsStatus -> Evergreen.V112.AiChat.AiModelsStatus
migrate_AiChat_AiModelsStatus old =
    case old of
        Evergreen.V109.AiChat.LoadingAiModels ->
            Evergreen.V112.AiChat.LoadingAiModels

        Evergreen.V109.AiChat.LoadedAiModels p0 ->
            Evergreen.V112.AiChat.LoadedAiModels p0

        Evergreen.V109.AiChat.LoadingFailed p0 ->
            Evergreen.V112.AiChat.LoadingFailed p0


migrate_AiChat_BackendMsg : Evergreen.V109.AiChat.BackendMsg -> Evergreen.V112.AiChat.BackendMsg
migrate_AiChat_BackendMsg old =
    case old of
        Evergreen.V109.AiChat.GotAiMessage p0 p1 p2 ->
            Evergreen.V112.AiChat.GotAiMessage p0 (p1 |> migrate_AiChat_ResponseId) p2


migrate_AiChat_FrontendModel : Evergreen.V109.AiChat.FrontendModel -> Evergreen.V112.AiChat.FrontendModel
migrate_AiChat_FrontendModel old =
    { message = old.message
    , chatHistory = old.chatHistory
    , pendingResponses = old.pendingResponses |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_AiChat_ResponseId migrate_AiChat_PendingResponse) |> SeqDict.fromList
    , responseCounter = old.responseCounter
    , showOptions = old.showOptions
    , selectedModel = old.selectedModel
    , userPrefix = old.userPrefix
    , botPrefix = old.botPrefix
    , debounceCounter = old.debounceCounter
    , sendMessageWith = old.sendMessageWith |> migrate_AiChat_SendMessageWith
    , aiModels = old.aiModels |> migrate_AiChat_AiModelsStatus
    }


migrate_AiChat_Message : Evergreen.V109.AiChat.Message -> Evergreen.V112.AiChat.Message
migrate_AiChat_Message old =
    case old of
        Evergreen.V109.AiChat.TextMessage p0 ->
            Evergreen.V112.AiChat.TextMessage p0

        Evergreen.V109.AiChat.ImageUrlMessage p0 ->
            Evergreen.V112.AiChat.ImageUrlMessage p0


migrate_AiChat_Msg : Evergreen.V109.AiChat.Msg -> Evergreen.V112.AiChat.Msg
migrate_AiChat_Msg old =
    case old of
        Evergreen.V109.AiChat.TypedMessage p0 ->
            Evergreen.V112.AiChat.TypedMessage p0

        Evergreen.V109.AiChat.PressedSend ->
            Evergreen.V112.AiChat.PressedSend

        Evergreen.V109.AiChat.TypedChatHistory p0 ->
            Evergreen.V112.AiChat.TypedChatHistory p0

        Evergreen.V109.AiChat.PressedKeep p0 ->
            Evergreen.V112.AiChat.PressedKeep (p0 |> migrate_AiChat_ResponseId)

        Evergreen.V109.AiChat.PressedDelete p0 ->
            Evergreen.V112.AiChat.PressedDelete (p0 |> migrate_AiChat_ResponseId)

        Evergreen.V109.AiChat.PressedRetry p0 ->
            Evergreen.V112.AiChat.PressedRetry (p0 |> migrate_AiChat_ResponseId)

        Evergreen.V109.AiChat.PressedChatHistoryContainer ->
            Evergreen.V112.AiChat.PressedChatHistoryContainer

        Evergreen.V109.AiChat.PressedClearChatHistory ->
            Evergreen.V112.AiChat.PressedClearChatHistory

        Evergreen.V109.AiChat.PressedOptionsButton ->
            Evergreen.V112.AiChat.PressedOptionsButton

        Evergreen.V109.AiChat.SelectedAiModel p0 ->
            Evergreen.V112.AiChat.SelectedAiModel p0

        Evergreen.V109.AiChat.SelectedSendMessageWith p0 ->
            Evergreen.V112.AiChat.SelectedSendMessageWith (p0 |> migrate_AiChat_SendMessageWith)

        Evergreen.V109.AiChat.TypedUserPrefix p0 ->
            Evergreen.V112.AiChat.TypedUserPrefix p0

        Evergreen.V109.AiChat.TypedBotPrefix p0 ->
            Evergreen.V112.AiChat.TypedBotPrefix p0

        Evergreen.V109.AiChat.CheckDebounce p0 ->
            Evergreen.V112.AiChat.CheckDebounce p0

        Evergreen.V109.AiChat.GotLocalStorage p0 ->
            Evergreen.V112.AiChat.GotLocalStorage p0

        Evergreen.V109.AiChat.EditedResponse p0 p1 ->
            Evergreen.V112.AiChat.EditedResponse (p0 |> migrate_AiChat_ResponseId) p1

        Evergreen.V109.AiChat.NoOp ->
            Evergreen.V112.AiChat.NoOp

        Evergreen.V109.AiChat.GotAiModels p0 ->
            Evergreen.V112.AiChat.GotAiModels p0


migrate_AiChat_PendingResponse : Evergreen.V109.AiChat.PendingResponse -> Evergreen.V112.AiChat.PendingResponse
migrate_AiChat_PendingResponse old =
    case old of
        Evergreen.V109.AiChat.Pending ->
            Evergreen.V112.AiChat.Pending

        Evergreen.V109.AiChat.GotResponse p0 ->
            Evergreen.V112.AiChat.GotResponse p0

        Evergreen.V109.AiChat.GotError p0 ->
            Evergreen.V112.AiChat.GotError p0


migrate_AiChat_ResponseId : Evergreen.V109.AiChat.ResponseId -> Evergreen.V112.AiChat.ResponseId
migrate_AiChat_ResponseId old =
    case old of
        Evergreen.V109.AiChat.RespondId p0 ->
            Evergreen.V112.AiChat.RespondId p0


migrate_AiChat_SendMessageWith : Evergreen.V109.AiChat.SendMessageWith -> Evergreen.V112.AiChat.SendMessageWith
migrate_AiChat_SendMessageWith old =
    case old of
        Evergreen.V109.AiChat.SendWithEnter ->
            Evergreen.V112.AiChat.SendWithEnter

        Evergreen.V109.AiChat.SendWithShiftEnter ->
            Evergreen.V112.AiChat.SendWithShiftEnter


migrate_AiChat_ToBackend : Evergreen.V109.AiChat.ToBackend -> Evergreen.V112.AiChat.ToBackend
migrate_AiChat_ToBackend old =
    case old of
        Evergreen.V109.AiChat.AiMessageRequest p0 p1 p2 ->
            Evergreen.V112.AiChat.AiMessageRequest p0
                (p1 |> migrate_AiChat_ResponseId)
                (p2 |> List.map migrate_AiChat_Message)

        Evergreen.V109.AiChat.AiMessageRequestSimple p0 p1 p2 ->
            Evergreen.V112.AiChat.AiMessageRequestSimple p0 (p1 |> migrate_AiChat_ResponseId) p2


migrate_AiChat_ToFrontend : Evergreen.V109.AiChat.ToFrontend -> Evergreen.V112.AiChat.ToFrontend
migrate_AiChat_ToFrontend old =
    case old of
        Evergreen.V109.AiChat.AiMessageResponse p0 p1 ->
            Evergreen.V112.AiChat.AiMessageResponse (p0 |> migrate_AiChat_ResponseId) p1


migrate_ChannelName_ChannelName : Evergreen.V109.ChannelName.ChannelName -> Evergreen.V112.ChannelName.ChannelName
migrate_ChannelName_ChannelName old =
    case old of
        Evergreen.V109.ChannelName.ChannelName p0 ->
            Evergreen.V112.ChannelName.ChannelName p0


migrate_Coord_Coord : (units_old -> units_new) -> Evergreen.V109.Coord.Coord units_old -> Evergreen.V112.Coord.Coord units_new
migrate_Coord_Coord migrate_units old =
    old |> Tuple.mapBoth migrate_Quantity_Quantity migrate_Quantity_Quantity


migrate_CssPixels_CssPixels : Evergreen.V109.CssPixels.CssPixels -> Evergreen.V112.CssPixels.CssPixels
migrate_CssPixels_CssPixels old =
    case old of
        Evergreen.V109.CssPixels.CssPixels p0 ->
            Evergreen.V112.CssPixels.CssPixels p0


migrate_Discord_ErrorCode : Evergreen.V109.Discord.ErrorCode -> Evergreen.V112.Discord.ErrorCode
migrate_Discord_ErrorCode old =
    case old of
        Evergreen.V109.Discord.GeneralError0 ->
            Evergreen.V112.Discord.GeneralError0

        Evergreen.V109.Discord.UnknownAccount10001 ->
            Evergreen.V112.Discord.UnknownAccount10001

        Evergreen.V109.Discord.UnknownApp10002 ->
            Evergreen.V112.Discord.UnknownApp10002

        Evergreen.V109.Discord.UnknownChannel10003 ->
            Evergreen.V112.Discord.UnknownChannel10003

        Evergreen.V109.Discord.UnknownGuild10004 ->
            Evergreen.V112.Discord.UnknownGuild10004

        Evergreen.V109.Discord.UnknownIntegration1005 ->
            Evergreen.V112.Discord.UnknownIntegration1005

        Evergreen.V109.Discord.UnknownInvite10006 ->
            Evergreen.V112.Discord.UnknownInvite10006

        Evergreen.V109.Discord.UnknownMember10007 ->
            Evergreen.V112.Discord.UnknownMember10007

        Evergreen.V109.Discord.UnknownMessage10008 ->
            Evergreen.V112.Discord.UnknownMessage10008

        Evergreen.V109.Discord.UnknownPermissionOverwrite10009 ->
            Evergreen.V112.Discord.UnknownPermissionOverwrite10009

        Evergreen.V109.Discord.UnknownProvider10010 ->
            Evergreen.V112.Discord.UnknownProvider10010

        Evergreen.V109.Discord.UnknownRole10011 ->
            Evergreen.V112.Discord.UnknownRole10011

        Evergreen.V109.Discord.UnknownToken10012 ->
            Evergreen.V112.Discord.UnknownToken10012

        Evergreen.V109.Discord.UnknownUser10013 ->
            Evergreen.V112.Discord.UnknownUser10013

        Evergreen.V109.Discord.UnknownEmoji10014 ->
            Evergreen.V112.Discord.UnknownEmoji10014

        Evergreen.V109.Discord.UnknownWebhook10015 ->
            Evergreen.V112.Discord.UnknownWebhook10015

        Evergreen.V109.Discord.UnknownBan10026 ->
            Evergreen.V112.Discord.UnknownBan10026

        Evergreen.V109.Discord.UnknownSku10027 ->
            Evergreen.V112.Discord.UnknownSku10027

        Evergreen.V109.Discord.UnknownStoreListing10028 ->
            Evergreen.V112.Discord.UnknownStoreListing10028

        Evergreen.V109.Discord.UnknownEntitlement10029 ->
            Evergreen.V112.Discord.UnknownEntitlement10029

        Evergreen.V109.Discord.UnknownBuild10030 ->
            Evergreen.V112.Discord.UnknownBuild10030

        Evergreen.V109.Discord.UnknownLobby10031 ->
            Evergreen.V112.Discord.UnknownLobby10031

        Evergreen.V109.Discord.UnknownBranch10032 ->
            Evergreen.V112.Discord.UnknownBranch10032

        Evergreen.V109.Discord.UnknownRedistributable10036 ->
            Evergreen.V112.Discord.UnknownRedistributable10036

        Evergreen.V109.Discord.BotsCannotUseThisEndpoint20001 ->
            Evergreen.V112.Discord.BotsCannotUseThisEndpoint20001

        Evergreen.V109.Discord.OnlyBotsCanUseThisEndpoint20002 ->
            Evergreen.V112.Discord.OnlyBotsCanUseThisEndpoint20002

        Evergreen.V109.Discord.MaxNumberOfGuilds30001 ->
            Evergreen.V112.Discord.MaxNumberOfGuilds30001

        Evergreen.V109.Discord.MaxNumberOfFriends30002 ->
            Evergreen.V112.Discord.MaxNumberOfFriends30002

        Evergreen.V109.Discord.MaxNumberOfPinsForChannel30003 ->
            Evergreen.V112.Discord.MaxNumberOfPinsForChannel30003

        Evergreen.V109.Discord.MaxNumberOfGuildsRoles30005 ->
            Evergreen.V112.Discord.MaxNumberOfGuildsRoles30005

        Evergreen.V109.Discord.MaxNumberOfWebhooks30007 ->
            Evergreen.V112.Discord.MaxNumberOfWebhooks30007

        Evergreen.V109.Discord.MaxNumberOfReactions30010 ->
            Evergreen.V112.Discord.MaxNumberOfReactions30010

        Evergreen.V109.Discord.MaxNumberOfGuildChannels30013 ->
            Evergreen.V112.Discord.MaxNumberOfGuildChannels30013

        Evergreen.V109.Discord.MaxNumberOfAttachmentsInAMessage30015 ->
            Evergreen.V112.Discord.MaxNumberOfAttachmentsInAMessage30015

        Evergreen.V109.Discord.MaxNumberOfInvitesReached30016 ->
            Evergreen.V112.Discord.MaxNumberOfInvitesReached30016

        Evergreen.V109.Discord.UnauthorizedProvideAValidTokenAndTryAgain40001 ->
            Evergreen.V112.Discord.UnauthorizedProvideAValidTokenAndTryAgain40001

        Evergreen.V109.Discord.VerifyYourAccount40002 ->
            Evergreen.V112.Discord.VerifyYourAccount40002

        Evergreen.V109.Discord.RequestEntityTooLarge40005 ->
            Evergreen.V112.Discord.RequestEntityTooLarge40005

        Evergreen.V109.Discord.FeatureTemporarilyDisabledServerSide40006 ->
            Evergreen.V112.Discord.FeatureTemporarilyDisabledServerSide40006

        Evergreen.V109.Discord.UserIsBannedFromThisGuild40007 ->
            Evergreen.V112.Discord.UserIsBannedFromThisGuild40007

        Evergreen.V109.Discord.MissingAccess50001 ->
            Evergreen.V112.Discord.MissingAccess50001

        Evergreen.V109.Discord.InvalidAccountType50002 ->
            Evergreen.V112.Discord.InvalidAccountType50002

        Evergreen.V109.Discord.CannotExecuteActionOnADmChannel50003 ->
            Evergreen.V112.Discord.CannotExecuteActionOnADmChannel50003

        Evergreen.V109.Discord.GuildWidgetDisabled50004 ->
            Evergreen.V112.Discord.GuildWidgetDisabled50004

        Evergreen.V109.Discord.CannotEditAMessageAuthoredByAnotherUser50005 ->
            Evergreen.V112.Discord.CannotEditAMessageAuthoredByAnotherUser50005

        Evergreen.V109.Discord.CannotSendAnEmptyMessage50006 ->
            Evergreen.V112.Discord.CannotSendAnEmptyMessage50006

        Evergreen.V109.Discord.CannotSendMessagesToThisUser50007 ->
            Evergreen.V112.Discord.CannotSendMessagesToThisUser50007

        Evergreen.V109.Discord.CannotSendMessagesInAVoiceChannel50008 ->
            Evergreen.V112.Discord.CannotSendMessagesInAVoiceChannel50008

        Evergreen.V109.Discord.ChannelVerificationLevelTooHigh50009 ->
            Evergreen.V112.Discord.ChannelVerificationLevelTooHigh50009

        Evergreen.V109.Discord.OAuth2AppDoesNotHaveABot50010 ->
            Evergreen.V112.Discord.OAuth2AppDoesNotHaveABot50010

        Evergreen.V109.Discord.OAuth2AppLimitReached50011 ->
            Evergreen.V112.Discord.OAuth2AppLimitReached50011

        Evergreen.V109.Discord.InvalidOAuth2State50012 ->
            Evergreen.V112.Discord.InvalidOAuth2State50012

        Evergreen.V109.Discord.YouLackPermissionsToPerformThatAction50013 ->
            Evergreen.V112.Discord.YouLackPermissionsToPerformThatAction50013

        Evergreen.V109.Discord.InvalidAuthenticationTokenProvided50014 ->
            Evergreen.V112.Discord.InvalidAuthenticationTokenProvided50014

        Evergreen.V109.Discord.NoteWasTooLong50015 ->
            Evergreen.V112.Discord.NoteWasTooLong50015

        Evergreen.V109.Discord.ProvidedTooFewOrTooManyMessagesToDelete50016 ->
            Evergreen.V112.Discord.ProvidedTooFewOrTooManyMessagesToDelete50016

        Evergreen.V109.Discord.MessageCanOnlyBePinnedToChannelItIsIn50019 ->
            Evergreen.V112.Discord.MessageCanOnlyBePinnedToChannelItIsIn50019

        Evergreen.V109.Discord.InviteCodeWasEitherInvalidOrTaken50020 ->
            Evergreen.V112.Discord.InviteCodeWasEitherInvalidOrTaken50020

        Evergreen.V109.Discord.CannotExecuteActionOnASystemMessage50021 ->
            Evergreen.V112.Discord.CannotExecuteActionOnASystemMessage50021

        Evergreen.V109.Discord.InvalidOAuth2AccessTokenProvided50025 ->
            Evergreen.V112.Discord.InvalidOAuth2AccessTokenProvided50025

        Evergreen.V109.Discord.MessageProvidedWasTooOldToBulkDelete50034 ->
            Evergreen.V112.Discord.MessageProvidedWasTooOldToBulkDelete50034

        Evergreen.V109.Discord.InvalidFormBody50035 ->
            Evergreen.V112.Discord.InvalidFormBody50035

        Evergreen.V109.Discord.InviteWasAcceptedToAGuildTheAppsBotIsNotIn50036 ->
            Evergreen.V112.Discord.InviteWasAcceptedToAGuildTheAppsBotIsNotIn50036

        Evergreen.V109.Discord.InvalidApiVersionProvided50041 ->
            Evergreen.V112.Discord.InvalidApiVersionProvided50041

        Evergreen.V109.Discord.ReactionWasBlocked90001 ->
            Evergreen.V112.Discord.ReactionWasBlocked90001

        Evergreen.V109.Discord.ApiIsCurrentlyOverloaded130000 ->
            Evergreen.V112.Discord.ApiIsCurrentlyOverloaded130000


migrate_Discord_HttpError : Evergreen.V109.Discord.HttpError -> Evergreen.V112.Discord.HttpError
migrate_Discord_HttpError old =
    case old of
        Evergreen.V109.Discord.NotModified304 p0 ->
            Evergreen.V112.Discord.NotModified304 (p0 |> migrate_Discord_ErrorCode)

        Evergreen.V109.Discord.Unauthorized401 p0 ->
            Evergreen.V112.Discord.Unauthorized401 (p0 |> migrate_Discord_ErrorCode)

        Evergreen.V109.Discord.Forbidden403 p0 ->
            Evergreen.V112.Discord.Forbidden403 (p0 |> migrate_Discord_ErrorCode)

        Evergreen.V109.Discord.NotFound404 p0 ->
            Evergreen.V112.Discord.NotFound404 (p0 |> migrate_Discord_ErrorCode)

        Evergreen.V109.Discord.TooManyRequests429 p0 ->
            Evergreen.V112.Discord.TooManyRequests429 (p0 |> migrate_Discord_RateLimit)

        Evergreen.V109.Discord.GatewayUnavailable502 p0 ->
            Evergreen.V112.Discord.GatewayUnavailable502 (p0 |> migrate_Discord_ErrorCode)

        Evergreen.V109.Discord.ServerError5xx p0 ->
            Evergreen.V112.Discord.ServerError5xx
                { statusCode = p0.statusCode
                , errorCode = p0.errorCode |> migrate_Discord_ErrorCode
                }

        Evergreen.V109.Discord.NetworkError ->
            Evergreen.V112.Discord.NetworkError

        Evergreen.V109.Discord.Timeout ->
            Evergreen.V112.Discord.Timeout

        Evergreen.V109.Discord.UnexpectedError p0 ->
            Evergreen.V112.Discord.UnexpectedError p0


migrate_Discord_Id_Id : Evergreen.V109.Id.Id a_old -> Evergreen.V112.Discord.Id.Id idType_new
migrate_Discord_Id_Id old =
    case old of
        Evergreen.V109.Id.Id p0 ->
            Evergreen.V112.Discord.Id.Id (p0 |> UInt64.fromInt)


migrate_Discord_RateLimit : Evergreen.V109.Discord.RateLimit -> Evergreen.V112.Discord.RateLimit
migrate_Discord_RateLimit old =
    old


migrate_DmChannel_DmChannel : Evergreen.V109.DmChannel.DmChannel -> Evergreen.V112.DmChannel.DmChannel
migrate_DmChannel_DmChannel old =
    { messages = old.messages |> Array.map (migrate_Message_Message migrate_Id_ChannelMessageId)
    , lastTypedAt = old.lastTypedAt |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Id_Id (migrate_Thread_LastTypedAt migrate_Id_ChannelMessageId)) |> SeqDict.fromList
    , threads = old.threads |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Id_Id migrate_Thread_BackendThread) |> SeqDict.fromList
    }


migrate_DmChannel_DmChannelId : Evergreen.V109.DmChannel.DmChannelId -> Evergreen.V112.DmChannel.DmChannelId
migrate_DmChannel_DmChannelId old =
    case old of
        Evergreen.V109.DmChannel.DirectMessageChannelId p0 p1 ->
            Evergreen.V112.DmChannel.DmChannelId (migrate_Id_Id p0) (migrate_Id_Id p1)


migrate_DmChannel_FrontendDmChannel : Evergreen.V109.DmChannel.FrontendDmChannel -> Evergreen.V112.DmChannel.FrontendDmChannel
migrate_DmChannel_FrontendDmChannel old =
    { messages = old.messages |> Array.map (migrate_Message_MessageState migrate_Id_ChannelMessageId)
    , visibleMessages = old.visibleMessages |> migrate_VisibleMessages_VisibleMessages migrate_Id_ChannelMessageId
    , lastTypedAt = old.lastTypedAt |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Id_Id (migrate_Thread_LastTypedAt migrate_Id_ChannelMessageId)) |> SeqDict.fromList
    , threads = old.threads |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Id_Id migrate_Thread_FrontendThread) |> SeqDict.fromList
    }


migrate_Editable_Editing : Evergreen.V109.Editable.Editing -> Evergreen.V112.Editable.Editing
migrate_Editable_Editing old =
    case old of
        Evergreen.V109.Editable.NotEditing ->
            Evergreen.V112.Editable.NotEditing

        Evergreen.V109.Editable.Editing p0 ->
            Evergreen.V112.Editable.Editing p0


migrate_Editable_Model : Evergreen.V109.Editable.Model -> Evergreen.V112.Editable.Model
migrate_Editable_Model old =
    { editing = old.editing |> migrate_Editable_Editing
    , pressedSubmit = old.pressedSubmit
    , showSecret = old.showSecret
    }


migrate_Editable_Msg : (value_old -> value_new) -> Evergreen.V109.Editable.Msg value_old -> Evergreen.V112.Editable.Msg value_new
migrate_Editable_Msg migrate_value old =
    case old of
        Evergreen.V109.Editable.Edit p0 ->
            Evergreen.V112.Editable.Edit (p0 |> migrate_Editable_Model)

        Evergreen.V109.Editable.PressedAcceptEdit p0 ->
            Evergreen.V112.Editable.PressedAcceptEdit (p0 |> migrate_value)


migrate_EmailAddress_EmailAddress : Evergreen.V109.EmailAddress.EmailAddress -> Evergreen.V112.EmailAddress.EmailAddress
migrate_EmailAddress_EmailAddress old =
    case old of
        Evergreen.V109.EmailAddress.EmailAddress p0 ->
            Evergreen.V112.EmailAddress.EmailAddress p0


migrate_Emoji_Emoji : Evergreen.V109.Emoji.Emoji -> Evergreen.V112.Emoji.Emoji
migrate_Emoji_Emoji old =
    case old of
        Evergreen.V109.Emoji.UnicodeEmoji p0 ->
            Evergreen.V112.Emoji.UnicodeEmoji p0


migrate_FileName_FileName : Evergreen.V109.FileName.FileName -> Evergreen.V112.FileName.FileName
migrate_FileName_FileName old =
    case old of
        Evergreen.V109.FileName.FileName p0 ->
            Evergreen.V112.FileName.FileName p0


migrate_FileStatus_ContentType : Evergreen.V109.FileStatus.ContentType -> Evergreen.V112.FileStatus.ContentType
migrate_FileStatus_ContentType old =
    case old of
        Evergreen.V109.FileStatus.ContentType p0 ->
            Evergreen.V112.FileStatus.ContentType p0


migrate_FileStatus_FileData : Evergreen.V109.FileStatus.FileData -> Evergreen.V112.FileStatus.FileData
migrate_FileStatus_FileData old =
    { fileName = old.fileName |> migrate_FileName_FileName
    , fileSize = old.fileSize
    , imageMetadata = old.imageMetadata |> Maybe.map migrate_FileStatus_ImageMetadata
    , contentType = old.contentType |> migrate_FileStatus_ContentType
    , fileHash = old.fileHash |> migrate_FileStatus_FileHash
    }


migrate_FileStatus_FileDataWithImage : Evergreen.V109.FileStatus.FileDataWithImage -> Evergreen.V112.FileStatus.FileDataWithImage
migrate_FileStatus_FileDataWithImage old =
    { fileName = old.fileName |> migrate_FileName_FileName
    , fileSize = old.fileSize
    , imageMetadata = old.imageMetadata |> migrate_FileStatus_ImageMetadata
    , contentType = old.contentType |> migrate_FileStatus_ContentType
    , fileHash = old.fileHash |> migrate_FileStatus_FileHash
    }


migrate_FileStatus_FileHash : Evergreen.V109.FileStatus.FileHash -> Evergreen.V112.FileStatus.FileHash
migrate_FileStatus_FileHash old =
    case old of
        Evergreen.V109.FileStatus.FileHash p0 ->
            Evergreen.V112.FileStatus.FileHash p0


migrate_FileStatus_FileStatus : Evergreen.V109.FileStatus.FileStatus -> Evergreen.V112.FileStatus.FileStatus
migrate_FileStatus_FileStatus old =
    case old of
        Evergreen.V109.FileStatus.FileUploading p0 p1 p2 ->
            Evergreen.V112.FileStatus.FileUploading (p0 |> migrate_FileName_FileName)
                p1
                (p2 |> migrate_FileStatus_ContentType)

        Evergreen.V109.FileStatus.FileUploaded p0 ->
            Evergreen.V112.FileStatus.FileUploaded (p0 |> migrate_FileStatus_FileData)

        Evergreen.V109.FileStatus.FileError p0 p1 p2 p3 ->
            Evergreen.V112.FileStatus.FileError (p0 |> migrate_FileName_FileName)
                p1
                (p2 |> migrate_FileStatus_ContentType)
                p3


migrate_FileStatus_ImageMetadata : Evergreen.V109.FileStatus.ImageMetadata -> Evergreen.V112.FileStatus.ImageMetadata
migrate_FileStatus_ImageMetadata old =
    { imageSize = old.imageSize |> migrate_Coord_Coord migrate_CssPixels_CssPixels
    , orientation = old.orientation |> Maybe.map migrate_FileStatus_Orientation
    , gpsLocation = old.gpsLocation
    , cameraOwner = old.cameraOwner
    , exposureTime = old.exposureTime
    , fNumber = old.fNumber
    , focalLength = old.focalLength
    , isoSpeedRating = old.isoSpeedRating
    , make = old.make
    , model = old.model
    , software = old.software
    , userComment = old.userComment
    }


migrate_FileStatus_Orientation : Evergreen.V109.FileStatus.Orientation -> Evergreen.V112.FileStatus.Orientation
migrate_FileStatus_Orientation old =
    case old of
        Evergreen.V109.FileStatus.NoChange ->
            Evergreen.V112.FileStatus.NoChange

        Evergreen.V109.FileStatus.Rotation90 ->
            Evergreen.V112.FileStatus.Rotation90

        Evergreen.V109.FileStatus.Rotation180 ->
            Evergreen.V112.FileStatus.Rotation180

        Evergreen.V109.FileStatus.Rotation270 ->
            Evergreen.V112.FileStatus.Rotation270

        Evergreen.V109.FileStatus.Mirrored ->
            Evergreen.V112.FileStatus.Mirrored

        Evergreen.V109.FileStatus.MirroredRotation90 ->
            Evergreen.V112.FileStatus.MirroredRotation90

        Evergreen.V109.FileStatus.MirroredRotation180 ->
            Evergreen.V112.FileStatus.MirroredRotation180

        Evergreen.V109.FileStatus.MirroredRotation270 ->
            Evergreen.V112.FileStatus.MirroredRotation270


migrate_FileStatus_UploadResponse : Evergreen.V109.FileStatus.UploadResponse -> Evergreen.V112.FileStatus.UploadResponse
migrate_FileStatus_UploadResponse old =
    { fileHash = old.fileHash |> migrate_FileStatus_FileHash
    , imageSize = old.imageSize |> Maybe.map migrate_FileStatus_ImageMetadata
    }


migrate_Geometry_Types_Point2d : Evergreen.V109.Geometry.Types.Point2d units_old coordinates_old -> Evergreen.V112.Geometry.Types.Point2d units_new coordinates_new
migrate_Geometry_Types_Point2d old =
    case old of
        Evergreen.V109.Geometry.Types.Point2d p0 ->
            Evergreen.V112.Geometry.Types.Point2d p0


migrate_GuildName_GuildName : Evergreen.V109.GuildName.GuildName -> Evergreen.V112.GuildName.GuildName
migrate_GuildName_GuildName old =
    case old of
        Evergreen.V109.GuildName.GuildName p0 ->
            Evergreen.V112.GuildName.GuildName p0


migrate_Id_AnyGuildOrDmId : Evergreen.V109.Id.GuildOrDmId -> Evergreen.V112.Id.AnyGuildOrDmId
migrate_Id_AnyGuildOrDmId ( old, oldThreadRoute ) =
    (case old of
        Evergreen.V109.Id.GuildOrDmId_Guild p0 p1 ->
            Evergreen.V112.Id.GuildOrDmId_Guild (migrate_Id_Id p0) (migrate_Id_Id p1)

        Evergreen.V109.Id.GuildOrDmId_Dm p0 ->
            Evergreen.V112.Id.GuildOrDmId_Dm (migrate_Id_Id p0)
    )
        |> Evergreen.V112.Id.GuildOrDmId


migrate_Id_ChannelMessageId : Evergreen.V109.Id.ChannelMessageId -> Evergreen.V112.Id.ChannelMessageId
migrate_Id_ChannelMessageId old =
    case old of
        Evergreen.V109.Id.ChannelMessageId p0 ->
            Evergreen.V112.Id.ChannelMessageId p0


migrate_Id_GuildOrDmId : Evergreen.V109.Id.GuildOrDmId -> Evergreen.V112.Id.GuildOrDmId
migrate_Id_GuildOrDmId ( old, oldThreadRoute ) =
    case old of
        Evergreen.V109.Id.GuildOrDmId_Guild p0 p1 ->
            Evergreen.V112.Id.GuildOrDmId_Guild (p0 |> migrate_Id_Id) (p1 |> migrate_Id_Id)

        Evergreen.V109.Id.GuildOrDmId_Dm p0 ->
            Evergreen.V112.Id.GuildOrDmId_Dm (p0 |> migrate_Id_Id)


migrate_Id_Id : Evergreen.V109.Id.Id a_old -> Evergreen.V112.Id.Id a_new
migrate_Id_Id old =
    case old of
        Evergreen.V109.Id.Id p0 ->
            Evergreen.V112.Id.Id p0


migrate_Id_ThreadMessageId : Evergreen.V109.Id.ThreadMessageId -> Evergreen.V112.Id.ThreadMessageId
migrate_Id_ThreadMessageId old =
    case old of
        Evergreen.V109.Id.ThreadMessageId p0 ->
            Evergreen.V112.Id.ThreadMessageId p0


migrate_Id_ThreadRoute : Evergreen.V109.Id.ThreadRoute -> Evergreen.V112.Id.ThreadRoute
migrate_Id_ThreadRoute old =
    case old of
        Evergreen.V109.Id.NoThread ->
            Evergreen.V112.Id.NoThread

        Evergreen.V109.Id.ViewThread p0 ->
            Evergreen.V112.Id.ViewThread (p0 |> migrate_Id_Id)


migrate_Id_ThreadRouteWithMaybeMessage : Evergreen.V109.Id.ThreadRouteWithMaybeMessage -> Evergreen.V112.Id.ThreadRouteWithMaybeMessage
migrate_Id_ThreadRouteWithMaybeMessage old =
    case old of
        Evergreen.V109.Id.NoThreadWithMaybeMessage p0 ->
            Evergreen.V112.Id.NoThreadWithMaybeMessage (p0 |> Maybe.map migrate_Id_Id)

        Evergreen.V109.Id.ViewThreadWithMaybeMessage p0 p1 ->
            Evergreen.V112.Id.ViewThreadWithMaybeMessage (p0 |> migrate_Id_Id)
                (p1 |> Maybe.map migrate_Id_Id)


migrate_Id_ThreadRouteWithMessage : Evergreen.V109.Id.ThreadRouteWithMessage -> Evergreen.V112.Id.ThreadRouteWithMessage
migrate_Id_ThreadRouteWithMessage old =
    case old of
        Evergreen.V109.Id.NoThreadWithMessage p0 ->
            Evergreen.V112.Id.NoThreadWithMessage (p0 |> migrate_Id_Id)

        Evergreen.V109.Id.ViewThreadWithMessage p0 p1 ->
            Evergreen.V112.Id.ViewThreadWithMessage (p0 |> migrate_Id_Id) (p1 |> migrate_Id_Id)


migrate_Internal_Model2_Msg : Evergreen.V109.Internal.Model2.Msg -> Evergreen.V112.Internal.Model2.Msg
migrate_Internal_Model2_Msg old =
    case old of
        Evergreen.V109.Internal.Model2.Tick p0 ->
            Evergreen.V112.Internal.Model2.Tick p0

        Evergreen.V109.Internal.Model2.Teleported p0 p1 ->
            Evergreen.V112.Internal.Model2.Teleported (p0 |> migrate_Internal_Teleport_Trigger)
                (p1 |> migrate_Internal_Teleport_Event)


migrate_Internal_Model2_State : Evergreen.V109.Internal.Model2.State -> Evergreen.V112.Internal.Model2.State
migrate_Internal_Model2_State old =
    case old of
        Evergreen.V109.Internal.Model2.State p0 ->
            Evergreen.V112.Internal.Model2.State p0


migrate_Internal_Teleport_CssAnimation : Evergreen.V109.Internal.Teleport.CssAnimation -> Evergreen.V112.Internal.Teleport.CssAnimation
migrate_Internal_Teleport_CssAnimation old =
    old


migrate_Internal_Teleport_Data : Evergreen.V109.Internal.Teleport.Data -> Evergreen.V112.Internal.Teleport.Data
migrate_Internal_Teleport_Data old =
    case old of
        Evergreen.V109.Internal.Teleport.Css p0 ->
            Evergreen.V112.Internal.Teleport.Css (p0 |> migrate_Internal_Teleport_CssAnimation)

        Evergreen.V109.Internal.Teleport.ParentTrigger p0 ->
            Evergreen.V112.Internal.Teleport.ParentTrigger (p0 |> migrate_Internal_Teleport_ParentTriggerDetails)


migrate_Internal_Teleport_Event : Evergreen.V109.Internal.Teleport.Event -> Evergreen.V112.Internal.Teleport.Event
migrate_Internal_Teleport_Event old =
    { timestamp = old.timestamp
    , data = old.data |> List.map migrate_Internal_Teleport_Data
    }


migrate_Internal_Teleport_ParentTriggerDetails : Evergreen.V109.Internal.Teleport.ParentTriggerDetails -> Evergreen.V112.Internal.Teleport.ParentTriggerDetails
migrate_Internal_Teleport_ParentTriggerDetails old =
    old


migrate_Internal_Teleport_Trigger : Evergreen.V109.Internal.Teleport.Trigger -> Evergreen.V112.Internal.Teleport.Trigger
migrate_Internal_Teleport_Trigger old =
    case old of
        Evergreen.V109.Internal.Teleport.OnHover ->
            Evergreen.V112.Internal.Teleport.OnHover

        Evergreen.V109.Internal.Teleport.OnRender ->
            Evergreen.V112.Internal.Teleport.OnRender

        Evergreen.V109.Internal.Teleport.OnFocus ->
            Evergreen.V112.Internal.Teleport.OnFocus

        Evergreen.V109.Internal.Teleport.OnFocusWithin ->
            Evergreen.V112.Internal.Teleport.OnFocusWithin

        Evergreen.V109.Internal.Teleport.OnActive ->
            Evergreen.V112.Internal.Teleport.OnActive

        Evergreen.V109.Internal.Teleport.OnDismount ->
            Evergreen.V112.Internal.Teleport.OnDismount


migrate_List_Nonempty_Nonempty : (a_old -> a_new) -> List.Nonempty.Nonempty a_old -> List.Nonempty.Nonempty a_new
migrate_List_Nonempty_Nonempty migrate_a old =
    old |> List.Nonempty.map migrate_a


migrate_LocalState_Archived : Evergreen.V109.LocalState.Archived -> Evergreen.V112.LocalState.Archived
migrate_LocalState_Archived old =
    { archivedAt = old.archivedAt
    , archivedBy = old.archivedBy |> migrate_Id_Id
    }


migrate_LocalState_BackendChannel : Evergreen.V109.LocalState.BackendChannel -> Evergreen.V112.LocalState.BackendChannel
migrate_LocalState_BackendChannel old =
    { createdAt = old.createdAt
    , createdBy = old.createdBy |> migrate_Id_Id
    , name = old.name |> migrate_ChannelName_ChannelName
    , messages = old.messages |> Array.map (migrate_Message_Message migrate_Id_ChannelMessageId)
    , status = old.status |> migrate_LocalState_ChannelStatus
    , lastTypedAt = old.lastTypedAt |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Id_Id (migrate_Thread_LastTypedAt migrate_Id_ChannelMessageId)) |> SeqDict.fromList
    , threads = old.threads |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Id_Id migrate_Thread_BackendThread) |> SeqDict.fromList
    }


migrate_LocalState_BackendGuild : Evergreen.V109.LocalState.BackendGuild -> Evergreen.V112.LocalState.BackendGuild
migrate_LocalState_BackendGuild old =
    { createdAt = old.createdAt
    , createdBy = old.createdBy |> migrate_Id_Id
    , name = old.name |> migrate_GuildName_GuildName
    , icon = old.icon |> Maybe.map migrate_FileStatus_FileHash
    , channels = old.channels |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Id_Id migrate_LocalState_BackendChannel) |> SeqDict.fromList
    , members = old.members |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Id_Id (\rec -> rec)) |> SeqDict.fromList
    , owner = old.owner |> migrate_Id_Id
    , invites =
        old.invites
            |> SeqDict.toList
            |> List.map
                (Tuple.mapBoth migrate_SecretId_SecretId
                    (\rec ->
                        { createdAt = rec.createdAt
                        , createdBy = rec.createdBy |> migrate_Id_Id
                        }
                    )
                )
            |> SeqDict.fromList
    }


migrate_LocalState_ChannelStatus : Evergreen.V109.LocalState.ChannelStatus -> Evergreen.V112.LocalState.ChannelStatus
migrate_LocalState_ChannelStatus old =
    case old of
        Evergreen.V109.LocalState.ChannelActive ->
            Evergreen.V112.LocalState.ChannelActive

        Evergreen.V109.LocalState.ChannelDeleted p0 ->
            Evergreen.V112.LocalState.ChannelDeleted
                { deletedAt = p0.deletedAt
                , deletedBy = p0.deletedBy |> migrate_Id_Id
                }


migrate_LocalState_FrontendChannel : Evergreen.V109.LocalState.FrontendChannel -> Evergreen.V112.LocalState.FrontendChannel
migrate_LocalState_FrontendChannel old =
    { createdAt = old.createdAt
    , createdBy = old.createdBy |> migrate_Id_Id
    , name = old.name |> migrate_ChannelName_ChannelName
    , messages = old.messages |> Array.map (migrate_Message_MessageState migrate_Id_ChannelMessageId)
    , visibleMessages = old.visibleMessages |> migrate_VisibleMessages_VisibleMessages migrate_Id_ChannelMessageId
    , isArchived = old.isArchived |> Maybe.map migrate_LocalState_Archived
    , lastTypedAt = old.lastTypedAt |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Id_Id (migrate_Thread_LastTypedAt migrate_Id_ChannelMessageId)) |> SeqDict.fromList
    , threads = old.threads |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Id_Id migrate_Thread_FrontendThread) |> SeqDict.fromList
    }


migrate_LocalState_FrontendGuild : Evergreen.V109.LocalState.FrontendGuild -> Evergreen.V112.LocalState.FrontendGuild
migrate_LocalState_FrontendGuild old =
    { createdAt = old.createdAt
    , createdBy = old.createdBy |> migrate_Id_Id
    , name = old.name |> migrate_GuildName_GuildName
    , icon = old.icon |> Maybe.map migrate_FileStatus_FileHash
    , channels = old.channels |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Id_Id migrate_LocalState_FrontendChannel) |> SeqDict.fromList
    , members = old.members |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Id_Id (\rec -> rec)) |> SeqDict.fromList
    , owner = old.owner |> migrate_Id_Id
    , invites =
        old.invites
            |> SeqDict.toList
            |> List.map
                (Tuple.mapBoth migrate_SecretId_SecretId
                    (\rec ->
                        { createdAt = rec.createdAt
                        , createdBy = rec.createdBy |> migrate_Id_Id
                        }
                    )
                )
            |> SeqDict.fromList
    }


migrate_LocalState_JoinGuildError : Evergreen.V109.LocalState.JoinGuildError -> Evergreen.V112.LocalState.JoinGuildError
migrate_LocalState_JoinGuildError old =
    case old of
        Evergreen.V109.LocalState.AlreadyJoined ->
            Evergreen.V112.LocalState.AlreadyJoined

        Evergreen.V109.LocalState.InviteIsInvalid ->
            Evergreen.V112.LocalState.InviteIsInvalid


migrate_LocalState_LogWithTime : Evergreen.V109.LocalState.LogWithTime -> Evergreen.V112.LocalState.LogWithTime
migrate_LocalState_LogWithTime old =
    { time = old.time
    , log = old.log |> migrate_Log_Log
    }


migrate_LocalState_PrivateVapidKey : Evergreen.V109.LocalState.PrivateVapidKey -> Evergreen.V112.LocalState.PrivateVapidKey
migrate_LocalState_PrivateVapidKey old =
    case old of
        Evergreen.V109.LocalState.PrivateVapidKey p0 ->
            Evergreen.V112.LocalState.PrivateVapidKey p0


migrate_Local_ChangeId : Evergreen.V109.Local.ChangeId -> Evergreen.V112.Local.ChangeId
migrate_Local_ChangeId old =
    case old of
        Evergreen.V109.Local.ChangeId p0 ->
            Evergreen.V112.Local.ChangeId p0


migrate_Local_Local : (msg_old -> msg_new) -> (model_old -> model_new) -> Evergreen.V109.Local.Local msg_old model_old -> Evergreen.V112.Local.Local msg_new model_new
migrate_Local_Local migrate_msg migrate_model old =
    case old of
        Evergreen.V109.Local.Local p0 ->
            Evergreen.V112.Local.Local
                { localMsgs =
                    p0.localMsgs
                        |> Dict.map
                            (\k ->
                                \rec1 ->
                                    { createdAt = rec1.createdAt
                                    , msg = rec1.msg |> migrate_msg
                                    }
                            )
                , localModel = p0.localModel |> migrate_model
                , serverModel = p0.serverModel |> migrate_model
                , counter = p0.counter |> migrate_Local_ChangeId
                }


migrate_Log_Log : Evergreen.V109.Log.Log -> Evergreen.V112.Log.Log
migrate_Log_Log old =
    case old of
        Evergreen.V109.Log.LoginEmail p0 p1 ->
            Evergreen.V112.Log.LoginEmail (p0 |> Result.mapError migrate_Postmark_SendEmailError)
                (p1 |> migrate_EmailAddress_EmailAddress)

        Evergreen.V109.Log.LoginsRateLimited p0 ->
            Evergreen.V112.Log.LoginsRateLimited (p0 |> migrate_Id_Id)

        Evergreen.V109.Log.ChangedUsers p0 ->
            Evergreen.V112.Log.ChangedUsers (p0 |> migrate_Id_Id)

        Evergreen.V109.Log.SendLogErrorEmailFailed p0 p1 ->
            Evergreen.V112.Log.SendLogErrorEmailFailed (p0 |> migrate_Postmark_SendEmailError)
                (p1 |> migrate_EmailAddress_EmailAddress)

        Evergreen.V109.Log.PushNotificationError p0 p1 ->
            Evergreen.V112.Log.PushNotificationError (p0 |> migrate_Id_Id) p1


migrate_LoginForm_CodeStatus : Evergreen.V109.LoginForm.CodeStatus -> Evergreen.V112.LoginForm.CodeStatus
migrate_LoginForm_CodeStatus old =
    case old of
        Evergreen.V109.LoginForm.Checking ->
            Evergreen.V112.LoginForm.Checking

        Evergreen.V109.LoginForm.NotValid ->
            Evergreen.V112.LoginForm.NotValid


migrate_LoginForm_EnterEmail2 : Evergreen.V109.LoginForm.EnterEmail2 -> Evergreen.V112.LoginForm.EnterEmail2
migrate_LoginForm_EnterEmail2 old =
    old


migrate_LoginForm_EnterLoginCode2 : Evergreen.V109.LoginForm.EnterLoginCode2 -> Evergreen.V112.LoginForm.EnterLoginCode2
migrate_LoginForm_EnterLoginCode2 old =
    { sentTo = old.sentTo |> migrate_EmailAddress_EmailAddress
    , code = old.code
    , attempts = old.attempts |> SeqDict.map (\k -> migrate_LoginForm_CodeStatus)
    }


migrate_LoginForm_EnterTwoFactorCode2 : Evergreen.V109.LoginForm.EnterTwoFactorCode2 -> Evergreen.V112.LoginForm.EnterTwoFactorCode2
migrate_LoginForm_EnterTwoFactorCode2 old =
    { code = old.code
    , attempts = old.attempts |> SeqDict.map (\k -> migrate_LoginForm_CodeStatus)
    , attemptCount = old.attemptCount
    }


migrate_LoginForm_EnterUserData2 : Evergreen.V109.LoginForm.EnterUserData2 -> Evergreen.V112.LoginForm.EnterUserData2
migrate_LoginForm_EnterUserData2 old =
    { name = old.name
    , pressedSubmit = old.pressedSubmit |> migrate_LoginForm_SubmitStatus
    }


migrate_LoginForm_LoginForm : Evergreen.V109.LoginForm.LoginForm -> Evergreen.V112.LoginForm.LoginForm
migrate_LoginForm_LoginForm old =
    case old of
        Evergreen.V109.LoginForm.EnterEmail p0 ->
            Evergreen.V112.LoginForm.EnterEmail (p0 |> migrate_LoginForm_EnterEmail2)

        Evergreen.V109.LoginForm.EnterLoginCode p0 ->
            Evergreen.V112.LoginForm.EnterLoginCode (p0 |> migrate_LoginForm_EnterLoginCode2)

        Evergreen.V109.LoginForm.EnterTwoFactorCode p0 ->
            Evergreen.V112.LoginForm.EnterTwoFactorCode (p0 |> migrate_LoginForm_EnterTwoFactorCode2)

        Evergreen.V109.LoginForm.EnterUserData p0 ->
            Evergreen.V112.LoginForm.EnterUserData (p0 |> migrate_LoginForm_EnterUserData2)


migrate_LoginForm_Msg : Evergreen.V109.LoginForm.Msg -> Evergreen.V112.LoginForm.Msg
migrate_LoginForm_Msg old =
    case old of
        Evergreen.V109.LoginForm.PressedSubmitEmail ->
            Evergreen.V112.LoginForm.PressedSubmitEmail

        Evergreen.V109.LoginForm.PressedCancelLogin ->
            Evergreen.V112.LoginForm.PressedCancelLogin

        Evergreen.V109.LoginForm.TypedLoginFormEmail p0 ->
            Evergreen.V112.LoginForm.TypedLoginFormEmail p0

        Evergreen.V109.LoginForm.TypedLoginCode p0 ->
            Evergreen.V112.LoginForm.TypedLoginCode p0

        Evergreen.V109.LoginForm.TypedTwoFactorCode p0 ->
            Evergreen.V112.LoginForm.TypedTwoFactorCode p0

        Evergreen.V109.LoginForm.TypedName p0 ->
            Evergreen.V112.LoginForm.TypedName p0

        Evergreen.V109.LoginForm.PressedSubmitUserData ->
            Evergreen.V112.LoginForm.PressedSubmitUserData


migrate_LoginForm_SubmitStatus : Evergreen.V109.LoginForm.SubmitStatus -> Evergreen.V112.LoginForm.SubmitStatus
migrate_LoginForm_SubmitStatus old =
    case old of
        Evergreen.V109.LoginForm.NotSubmitted p0 ->
            Evergreen.V112.LoginForm.NotSubmitted p0

        Evergreen.V109.LoginForm.Submitting ->
            Evergreen.V112.LoginForm.Submitting


migrate_MessageInput_MentionUserDropdown : Evergreen.V109.MessageInput.MentionUserDropdown -> Evergreen.V112.MessageInput.MentionUserDropdown
migrate_MessageInput_MentionUserDropdown old =
    { charIndex = old.charIndex
    , dropdownIndex = old.dropdownIndex
    , inputElement =
        old.inputElement
            |> (\rec -> rec)
    , target = old.target |> migrate_MessageInput_MentionUserTarget
    }


migrate_MessageInput_MentionUserTarget : Evergreen.V109.MessageInput.MentionUserTarget -> Evergreen.V112.MessageInput.MentionUserTarget
migrate_MessageInput_MentionUserTarget old =
    case old of
        Evergreen.V109.MessageInput.NewMessage ->
            Evergreen.V112.MessageInput.NewMessage

        Evergreen.V109.MessageInput.EditMessage ->
            Evergreen.V112.MessageInput.EditMessage


migrate_MessageView_MessageViewMsg : Evergreen.V109.MessageView.MessageViewMsg -> Evergreen.V112.MessageView.MessageViewMsg
migrate_MessageView_MessageViewMsg old =
    case old of
        Evergreen.V109.MessageView.MessageView_PressedSpoiler p0 ->
            Evergreen.V112.MessageView.MessageView_PressedSpoiler p0

        Evergreen.V109.MessageView.MessageView_MouseEnteredMessage ->
            Evergreen.V112.MessageView.MessageView_MouseEnteredMessage

        Evergreen.V109.MessageView.MessageView_MouseExitedMessage ->
            Evergreen.V112.MessageView.MessageView_MouseExitedMessage

        Evergreen.V109.MessageView.MessageView_TouchStart p0 p1 p2 ->
            Evergreen.V112.MessageView.MessageView_TouchStart p0
                p1
                (p2 |> migrate_NonemptyDict_NonemptyDict identity migrate_Touch_Touch)

        Evergreen.V109.MessageView.MessageView_AltPressedMessage p0 p1 ->
            Evergreen.V112.MessageView.MessageView_AltPressedMessage p0
                (p1 |> migrate_Coord_Coord migrate_CssPixels_CssPixels)

        Evergreen.V109.MessageView.MessageView_PressedReactionEmoji_Remove p0 ->
            Evergreen.V112.MessageView.MessageView_PressedReactionEmoji_Remove (p0 |> migrate_Emoji_Emoji)

        Evergreen.V109.MessageView.MessageView_PressedReactionEmoji_Add p0 ->
            Evergreen.V112.MessageView.MessageView_PressedReactionEmoji_Add (p0 |> migrate_Emoji_Emoji)

        Evergreen.V109.MessageView.MessageView_PressedReplyLink ->
            Evergreen.V112.MessageView.MessageView_PressedReplyLink

        Evergreen.V109.MessageView.MessageViewMsg_PressedShowReactionEmojiSelector ->
            Evergreen.V112.MessageView.MessageViewMsg_PressedShowReactionEmojiSelector

        Evergreen.V109.MessageView.MessageViewMsg_PressedEditMessage ->
            Evergreen.V112.MessageView.MessageViewMsg_PressedEditMessage

        Evergreen.V109.MessageView.MessageViewMsg_PressedReply ->
            Evergreen.V112.MessageView.MessageViewMsg_PressedReply

        Evergreen.V109.MessageView.MessageViewMsg_PressedShowFullMenu p0 p1 ->
            Evergreen.V112.MessageView.MessageViewMsg_PressedShowFullMenu p0
                (p1 |> migrate_Coord_Coord migrate_CssPixels_CssPixels)

        Evergreen.V109.MessageView.MessageView_PressedViewThreadLink ->
            Evergreen.V112.MessageView.MessageView_PressedViewThreadLink


migrate_Message_Message : (messageId_old -> messageId_new) -> Evergreen.V109.Message.Message messageId_old -> Evergreen.V112.Message.Message messageId_new (Evergreen.V112.Id.Id Evergreen.V112.Id.UserId)
migrate_Message_Message migrate_messageId old =
    case old of
        Evergreen.V109.Message.UserTextMessage p0 ->
            Evergreen.V112.Message.UserTextMessage (p0 |> migrate_Message_UserTextMessageData migrate_messageId)

        Evergreen.V109.Message.UserJoinedMessage p0 p1 p2 ->
            Evergreen.V112.Message.UserJoinedMessage p0
                (p1 |> migrate_Id_Id)
                (p2 |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Emoji_Emoji (migrate_NonemptySet_NonemptySet migrate_Id_Id)) |> SeqDict.fromList)

        Evergreen.V109.Message.DeletedMessage p0 ->
            Evergreen.V112.Message.DeletedMessage p0


migrate_Message_MessageState : (messageId_old -> messageId_new) -> Evergreen.V109.Message.MessageState messageId_old -> Evergreen.V112.Message.MessageState messageId_new (Evergreen.V112.Id.Id Evergreen.V112.Id.UserId)
migrate_Message_MessageState migrate_messageId old =
    case old of
        Evergreen.V109.Message.MessageLoaded p0 ->
            Evergreen.V112.Message.MessageLoaded (p0 |> migrate_Message_Message migrate_messageId)

        Evergreen.V109.Message.MessageUnloaded ->
            Evergreen.V112.Message.MessageUnloaded


migrate_Message_UserTextMessageData : (messageId_old -> messageId_new) -> Evergreen.V109.Message.UserTextMessageData messageId_old -> Evergreen.V112.Message.UserTextMessageData messageId_new (Evergreen.V112.Id.Id Evergreen.V112.Id.UserId)
migrate_Message_UserTextMessageData migrate_messageId old =
    { createdAt = old.createdAt
    , createdBy = old.createdBy |> migrate_Id_Id
    , content = old.content |> migrate_List_Nonempty_Nonempty migrate_RichText_RichText
    , reactions = old.reactions |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Emoji_Emoji (migrate_NonemptySet_NonemptySet migrate_Id_Id)) |> SeqDict.fromList
    , editedAt = old.editedAt
    , repliedTo = old.repliedTo |> Maybe.map migrate_Id_Id
    , attachedFiles = old.attachedFiles |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Id_Id migrate_FileStatus_FileData) |> SeqDict.fromList
    }


migrate_NonemptyDict_NonemptyDict : (id_old -> id_new) -> (a_old -> a_new) -> Evergreen.V109.NonemptyDict.NonemptyDict id_old a_old -> Evergreen.V112.NonemptyDict.NonemptyDict id_new a_new
migrate_NonemptyDict_NonemptyDict migrate_id migrate_a old =
    case old of
        Evergreen.V109.NonemptyDict.NonemptyDict p0 p1 p2 ->
            Evergreen.V112.NonemptyDict.NonemptyDict (p0 |> migrate_id)
                (p1 |> migrate_a)
                (p2 |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_id migrate_a) |> SeqDict.fromList)


migrate_NonemptyDict_NonemptyDictMaybe : (id_old -> id_new) -> (a_old -> Maybe a_new) -> Evergreen.V109.NonemptyDict.NonemptyDict id_old a_old -> Evergreen.V112.NonemptyDict.NonemptyDict id_new a_new
migrate_NonemptyDict_NonemptyDictMaybe migrate_id migrate_a old =
    case old of
        Evergreen.V109.NonemptyDict.NonemptyDict p0 p1 p2 ->
            case
                ( p0 |> migrate_id, p1 |> migrate_a )
                    :: (p2 |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_id migrate_a))
                    |> List.filterMap (\( id, a ) -> a |> Maybe.map (Tuple.pair id))
            of
                ( key, value ) :: rest ->
                    Evergreen.V112.NonemptyDict.NonemptyDict key value (SeqDict.fromList rest)

                [] ->
                    unreachable 0


unreachable : Int -> a
unreachable v =
    unreachable (causeStackOverflow v)


causeStackOverflow : Int -> Int
causeStackOverflow value =
    causeStackOverflow value + 1


migrate_NonemptySet_NonemptySet : (a_old -> a_new) -> Evergreen.V109.NonemptySet.NonemptySet a_old -> Evergreen.V112.NonemptySet.NonemptySet a_new
migrate_NonemptySet_NonemptySet migrate_a old =
    case old of
        Evergreen.V109.NonemptySet.NonemptySet p0 p1 ->
            Evergreen.V112.NonemptySet.NonemptySet (p0 |> migrate_a) (p1 |> SeqSet.map migrate_a)


migrate_OneOrGreater_OneOrGreater : Evergreen.V109.OneOrGreater.OneOrGreater -> Evergreen.V112.OneOrGreater.OneOrGreater
migrate_OneOrGreater_OneOrGreater old =
    case old of
        Evergreen.V109.OneOrGreater.OneOrGreater p0 ->
            Evergreen.V112.OneOrGreater.OneOrGreater p0


migrate_OneToOne_OneToOne : (a_old -> a_new) -> (b_old -> b_new) -> Evergreen.V109.OneToOne.OneToOne a_old b_old -> Evergreen.V112.OneToOne.OneToOne a_new b_new
migrate_OneToOne_OneToOne migrate_a migrate_b old =
    case old of
        Evergreen.V109.OneToOne.OneToOne p0 p1 ->
            Evergreen.V112.OneToOne.OneToOne (p0 |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_a migrate_b) |> SeqDict.fromList)
                (p1 |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_b migrate_a) |> SeqDict.fromList)


migrate_PersonName_PersonName : Evergreen.V109.PersonName.PersonName -> Evergreen.V112.PersonName.PersonName
migrate_PersonName_PersonName old =
    case old of
        Evergreen.V109.PersonName.PersonName p0 ->
            Evergreen.V112.PersonName.PersonName p0


migrate_Point2d_Point2d : (units_old -> units_new) -> (coordinates_old -> coordinates_new) -> Evergreen.V109.Point2d.Point2d units_old coordinates_old -> Evergreen.V112.Point2d.Point2d units_new coordinates_new
migrate_Point2d_Point2d migrate_units migrate_coordinates old =
    old |> migrate_Geometry_Types_Point2d


migrate_Ports_NotificationPermission : Evergreen.V109.Ports.NotificationPermission -> Evergreen.V112.Ports.NotificationPermission
migrate_Ports_NotificationPermission old =
    case old of
        Evergreen.V109.Ports.NotAsked ->
            Evergreen.V112.Ports.NotAsked

        Evergreen.V109.Ports.Denied ->
            Evergreen.V112.Ports.Denied

        Evergreen.V109.Ports.Granted ->
            Evergreen.V112.Ports.Granted

        Evergreen.V109.Ports.Unsupported ->
            Evergreen.V112.Ports.Unsupported


migrate_Ports_PwaStatus : Evergreen.V109.Ports.PwaStatus -> Evergreen.V112.Ports.PwaStatus
migrate_Ports_PwaStatus old =
    case old of
        Evergreen.V109.Ports.InstalledPwa ->
            Evergreen.V112.Ports.InstalledPwa

        Evergreen.V109.Ports.BrowserView ->
            Evergreen.V112.Ports.BrowserView


migrate_Postmark_PostmarkSendResponse : Evergreen.V109.Postmark.PostmarkSendResponse -> Evergreen.V112.Postmark.PostmarkSendResponse
migrate_Postmark_PostmarkSendResponse old =
    { errorCode = old.errorCode
    , message = old.message
    , to = old.to |> List.map migrate_EmailAddress_EmailAddress
    }


migrate_Postmark_SendEmailError : Evergreen.V109.Postmark.SendEmailError -> Evergreen.V112.Postmark.SendEmailError
migrate_Postmark_SendEmailError old =
    case old of
        Evergreen.V109.Postmark.UnknownError p0 ->
            Evergreen.V112.Postmark.UnknownError p0

        Evergreen.V109.Postmark.PostmarkError p0 ->
            Evergreen.V112.Postmark.PostmarkError (p0 |> migrate_Postmark_PostmarkSendResponse)

        Evergreen.V109.Postmark.NetworkError ->
            Evergreen.V112.Postmark.NetworkError

        Evergreen.V109.Postmark.Timeout ->
            Evergreen.V112.Postmark.Timeout

        Evergreen.V109.Postmark.BadUrl p0 ->
            Evergreen.V112.Postmark.BadUrl p0


migrate_Quantity_Quantity : Quantity.Quantity number units -> Quantity.Quantity number units2
migrate_Quantity_Quantity old =
    Quantity.unwrap old |> Quantity.unsafe


migrate_RichText_Language : Evergreen.V109.RichText.Language -> Evergreen.V112.RichText.Language
migrate_RichText_Language old =
    case old of
        Evergreen.V109.RichText.Language p0 ->
            Evergreen.V112.RichText.Language p0

        Evergreen.V109.RichText.NoLanguage ->
            Evergreen.V112.RichText.NoLanguage


migrate_RichText_Range : Evergreen.V109.RichText.Range -> Evergreen.V112.RichText.Range
migrate_RichText_Range old =
    old


migrate_RichText_RichText : Evergreen.V109.RichText.RichText -> Evergreen.V112.RichText.RichText (Evergreen.V112.Id.Id Evergreen.V112.Id.UserId)
migrate_RichText_RichText old =
    case old of
        Evergreen.V109.RichText.UserMention p0 ->
            Evergreen.V112.RichText.UserMention (p0 |> migrate_Id_Id)

        Evergreen.V109.RichText.NormalText p0 p1 ->
            Evergreen.V112.RichText.NormalText p0 p1

        Evergreen.V109.RichText.Bold p0 ->
            Evergreen.V112.RichText.Bold (p0 |> migrate_List_Nonempty_Nonempty migrate_RichText_RichText)

        Evergreen.V109.RichText.Italic p0 ->
            Evergreen.V112.RichText.Italic (p0 |> migrate_List_Nonempty_Nonempty migrate_RichText_RichText)

        Evergreen.V109.RichText.Underline p0 ->
            Evergreen.V112.RichText.Underline (p0 |> migrate_List_Nonempty_Nonempty migrate_RichText_RichText)

        Evergreen.V109.RichText.Strikethrough p0 ->
            Evergreen.V112.RichText.Strikethrough (p0 |> migrate_List_Nonempty_Nonempty migrate_RichText_RichText)

        Evergreen.V109.RichText.Spoiler p0 ->
            Evergreen.V112.RichText.Spoiler (p0 |> migrate_List_Nonempty_Nonempty migrate_RichText_RichText)

        Evergreen.V109.RichText.Hyperlink p0 p1 ->
            Evergreen.V112.RichText.Hyperlink p0 p1

        Evergreen.V109.RichText.InlineCode p0 p1 ->
            Evergreen.V112.RichText.InlineCode p0 p1

        Evergreen.V109.RichText.CodeBlock p0 p1 ->
            Evergreen.V112.RichText.CodeBlock (p0 |> migrate_RichText_Language) p1

        Evergreen.V109.RichText.AttachedFile p0 ->
            Evergreen.V112.RichText.AttachedFile (p0 |> migrate_Id_Id)


migrate_Route_ShowMembersTab : Evergreen.V109.Route.ShowMembersTab -> Evergreen.V112.Route.ShowMembersTab
migrate_Route_ShowMembersTab old =
    case old of
        Evergreen.V109.Route.ShowMembersTab ->
            Evergreen.V112.Route.ShowMembersTab

        Evergreen.V109.Route.HideMembersTab ->
            Evergreen.V112.Route.HideMembersTab


migrate_Route_ThreadRouteWithFriends : Evergreen.V109.Route.ThreadRouteWithFriends -> Evergreen.V112.Route.ThreadRouteWithFriends
migrate_Route_ThreadRouteWithFriends old =
    case old of
        Evergreen.V109.Route.NoThreadWithFriends p0 p1 ->
            Evergreen.V112.Route.NoThreadWithFriends (p0 |> Maybe.map migrate_Id_Id)
                (p1 |> migrate_Route_ShowMembersTab)

        Evergreen.V109.Route.ViewThreadWithFriends p0 p1 p2 ->
            Evergreen.V112.Route.ViewThreadWithFriends (p0 |> migrate_Id_Id)
                (p1 |> Maybe.map migrate_Id_Id)
                (p2 |> migrate_Route_ShowMembersTab)


migrate_SecretId_SecretId : Evergreen.V109.SecretId.SecretId a_old -> Evergreen.V112.SecretId.SecretId a_new
migrate_SecretId_SecretId old =
    case old of
        Evergreen.V109.SecretId.SecretId p0 ->
            Evergreen.V112.SecretId.SecretId p0


migrate_SessionIdHash_SessionIdHash : Evergreen.V109.SessionIdHash.SessionIdHash -> Evergreen.V112.SessionIdHash.SessionIdHash
migrate_SessionIdHash_SessionIdHash old =
    case old of
        Evergreen.V109.SessionIdHash.SessionIdHash p0 ->
            Evergreen.V112.SessionIdHash.SessionIdHash p0


migrate_Slack_AuthToken : Evergreen.V109.Slack.AuthToken -> Evergreen.V112.Slack.AuthToken
migrate_Slack_AuthToken old =
    case old of
        Evergreen.V109.Slack.SlackAuth p0 ->
            Evergreen.V112.Slack.SlackAuth p0


migrate_Slack_Block : Evergreen.V109.Slack.Block -> Evergreen.V112.Slack.Block
migrate_Slack_Block old =
    case old of
        Evergreen.V109.Slack.RichTextBlock p0 ->
            Evergreen.V112.Slack.RichTextBlock (p0 |> List.map migrate_Slack_BlockElement)


migrate_Slack_BlockElement : Evergreen.V109.Slack.BlockElement -> Evergreen.V112.Slack.BlockElement
migrate_Slack_BlockElement old =
    case old of
        Evergreen.V109.Slack.RichTextSection p0 ->
            Evergreen.V112.Slack.RichTextSection (p0 |> List.map migrate_Slack_RichTextElement)

        Evergreen.V109.Slack.RichTextPreformattedSection p0 ->
            Evergreen.V112.Slack.RichTextPreformattedSection (p0 |> List.map migrate_Slack_RichTextElement)


migrate_Slack_Channel : Evergreen.V109.Slack.Channel -> Evergreen.V112.Slack.Channel
migrate_Slack_Channel old =
    case old of
        Evergreen.V109.Slack.NormalChannel p0 ->
            Evergreen.V112.Slack.NormalChannel (p0 |> migrate_Slack_NormalChannelData)

        Evergreen.V109.Slack.ImChannel p0 ->
            Evergreen.V112.Slack.ImChannel (p0 |> migrate_Slack_ImChannelData)


migrate_Slack_ClientSecret : Evergreen.V109.Slack.ClientSecret -> Evergreen.V112.Slack.ClientSecret
migrate_Slack_ClientSecret old =
    case old of
        Evergreen.V109.Slack.ClientSecret p0 ->
            Evergreen.V112.Slack.ClientSecret p0


migrate_Slack_CurrentUser : Evergreen.V109.Slack.CurrentUser -> Evergreen.V112.Slack.CurrentUser
migrate_Slack_CurrentUser old =
    { userId = old.userId |> migrate_Slack_Id
    , teamId = old.teamId |> migrate_Slack_Id
    , url = old.url
    , team = old.team
    , user = old.user
    , enterpriseId = old.enterpriseId
    }


migrate_Slack_Id : Evergreen.V109.Slack.Id a_old -> Evergreen.V112.Slack.Id a_new
migrate_Slack_Id old =
    case old of
        Evergreen.V109.Slack.Id p0 ->
            Evergreen.V112.Slack.Id p0


migrate_Slack_ImChannelData : Evergreen.V109.Slack.ImChannelData -> Evergreen.V112.Slack.ImChannelData
migrate_Slack_ImChannelData old =
    { id = old.id |> migrate_Slack_Id
    , isArchived = old.isArchived
    , user = old.user |> migrate_Slack_Id
    , isUserDeleted = old.isUserDeleted
    , isOrgShared = old.isOrgShared
    , created = old.created
    }


migrate_Slack_Message : Evergreen.V109.Slack.Message -> Evergreen.V112.Slack.Message
migrate_Slack_Message old =
    { createdBy = old.createdBy |> migrate_Slack_Id
    , createdAt = old.createdAt
    , messageType = old.messageType |> migrate_Slack_MessageType
    }


migrate_Slack_MessageType : Evergreen.V109.Slack.MessageType -> Evergreen.V112.Slack.MessageType
migrate_Slack_MessageType old =
    case old of
        Evergreen.V109.Slack.UserJoinedMessage ->
            Evergreen.V112.Slack.UserJoinedMessage

        Evergreen.V109.Slack.UserMessage p0 p1 ->
            Evergreen.V112.Slack.UserMessage (p0 |> migrate_Slack_Id)
                (p1 |> List.map migrate_Slack_Block)

        Evergreen.V109.Slack.JoinerNotificationForInviter ->
            Evergreen.V112.Slack.JoinerNotificationForInviter

        Evergreen.V109.Slack.BotMessage ->
            Evergreen.V112.Slack.BotMessage


migrate_Slack_NormalChannelData : Evergreen.V109.Slack.NormalChannelData -> Evergreen.V112.Slack.NormalChannelData
migrate_Slack_NormalChannelData old =
    { id = old.id |> migrate_Slack_Id
    , isArchived = old.isArchived
    , name = old.name
    , isMember = old.isMember
    , isPrivate = old.isPrivate
    , created = old.created
    }


migrate_Slack_OAuthCode : Evergreen.V109.Slack.OAuthCode -> Evergreen.V112.Slack.OAuthCode
migrate_Slack_OAuthCode old =
    case old of
        Evergreen.V109.Slack.OAuthCode p0 ->
            Evergreen.V112.Slack.OAuthCode p0


migrate_Slack_RichTextElement : Evergreen.V109.Slack.RichTextElement -> Evergreen.V112.Slack.RichTextElement
migrate_Slack_RichTextElement old =
    case old of
        Evergreen.V109.Slack.RichText_Text p0 ->
            Evergreen.V112.Slack.RichText_Text (p0 |> migrate_Slack_RichText_Text_Data)

        Evergreen.V109.Slack.RichText_Emoji p0 ->
            Evergreen.V112.Slack.RichText_Emoji (p0 |> migrate_Slack_RichText_Emoji_Data)

        Evergreen.V109.Slack.RichText_UserMention p0 ->
            Evergreen.V112.Slack.RichText_UserMention (p0 |> migrate_Slack_Id)


migrate_Slack_RichText_Emoji_Data : Evergreen.V109.Slack.RichText_Emoji_Data -> Evergreen.V112.Slack.RichText_Emoji_Data
migrate_Slack_RichText_Emoji_Data old =
    old


migrate_Slack_RichText_Text_Data : Evergreen.V109.Slack.RichText_Text_Data -> Evergreen.V112.Slack.RichText_Text_Data
migrate_Slack_RichText_Text_Data old =
    old


migrate_Slack_Team : Evergreen.V109.Slack.Team -> Evergreen.V112.Slack.Team
migrate_Slack_Team old =
    { id = old.id |> migrate_Slack_Id
    , name = old.name
    , domain = old.domain
    , image132 = old.image132
    }


migrate_Slack_TokenResponse : Evergreen.V109.Slack.TokenResponse -> Evergreen.V112.Slack.TokenResponse
migrate_Slack_TokenResponse old =
    { botAccessToken = old.botAccessToken |> migrate_Slack_AuthToken
    , userAccessToken = old.userAccessToken |> migrate_Slack_AuthToken
    , userId = old.userId |> migrate_Slack_Id
    , teamId = old.teamId |> migrate_Slack_Id
    , teamName = old.teamName
    }


migrate_Slack_User : Evergreen.V109.Slack.User -> Evergreen.V112.Slack.User
migrate_Slack_User old =
    { id = old.id |> migrate_Slack_Id
    , name = old.name
    , isBot = old.isBot
    , isDeleted = old.isDeleted
    , profile = old.profile
    }


migrate_Table_Model : Evergreen.V109.Table.Model -> Evergreen.V112.Table.Model
migrate_Table_Model old =
    old


migrate_Table_Msg : Evergreen.V109.Table.Msg -> Evergreen.V112.Table.Msg
migrate_Table_Msg old =
    case old of
        Evergreen.V109.Table.PressedSortBy p0 ->
            Evergreen.V112.Table.PressedSortBy p0

        Evergreen.V109.Table.PressedShowAll ->
            Evergreen.V112.Table.PressedShowAll


migrate_TextEditor_EditChange : Evergreen.V109.TextEditor.EditChange -> Evergreen.V112.TextEditor.EditChange
migrate_TextEditor_EditChange old =
    case old of
        Evergreen.V109.TextEditor.Edit_TypedText p0 p1 ->
            Evergreen.V112.TextEditor.Edit_TypedText (p0 |> migrate_RichText_Range) p1


migrate_TextEditor_LocalState : Evergreen.V109.TextEditor.LocalState -> Evergreen.V112.TextEditor.LocalState
migrate_TextEditor_LocalState old =
    { undoPoint = old.undoPoint |> SeqDict.toList |> List.map (Tuple.mapFirst migrate_Id_Id) |> SeqDict.fromList
    , history = old.history |> Array.map (Tuple.mapBoth migrate_Id_Id migrate_TextEditor_EditChange)
    , cursorPosition = old.cursorPosition |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Id_Id migrate_RichText_Range) |> SeqDict.fromList
    }


migrate_Thread_BackendThread : Evergreen.V109.DmChannel.Thread -> Evergreen.V112.Thread.BackendThread
migrate_Thread_BackendThread old =
    { messages = old.messages |> Array.map (migrate_Message_Message migrate_Id_ThreadMessageId)
    , lastTypedAt = old.lastTypedAt |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Id_Id (migrate_Thread_LastTypedAt migrate_Id_ThreadMessageId)) |> SeqDict.fromList
    }


migrate_Thread_FrontendThread : Evergreen.V109.DmChannel.FrontendThread -> Evergreen.V112.Thread.FrontendThread
migrate_Thread_FrontendThread old =
    { messages = old.messages |> Array.map (migrate_Message_MessageState migrate_Id_ThreadMessageId)
    , visibleMessages = old.visibleMessages |> migrate_VisibleMessages_VisibleMessages migrate_Id_ThreadMessageId
    , lastTypedAt = old.lastTypedAt |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Id_Id (migrate_Thread_LastTypedAt migrate_Id_ThreadMessageId)) |> SeqDict.fromList
    }


migrate_Thread_LastTypedAt : (messageId_old -> messageId_new) -> Evergreen.V109.DmChannel.LastTypedAt messageId_old -> Evergreen.V112.Thread.LastTypedAt messageId_new
migrate_Thread_LastTypedAt migrate_messageId old =
    { time = old.time
    , messageIndex = old.messageIndex |> Maybe.map migrate_Id_Id
    }


migrate_Touch_ScreenCoordinate : Evergreen.V109.Touch.ScreenCoordinate -> Evergreen.V112.Touch.ScreenCoordinate
migrate_Touch_ScreenCoordinate old =
    case old of
        Evergreen.V109.Touch.ScreenCoordinate p0 ->
            Evergreen.V112.Touch.ScreenCoordinate p0


migrate_Touch_Touch : Evergreen.V109.Touch.Touch -> Evergreen.V112.Touch.Touch
migrate_Touch_Touch old =
    { client = old.client |> migrate_Point2d_Point2d migrate_CssPixels_CssPixels migrate_Touch_ScreenCoordinate
    , target = old.target
    }


migrate_TwoFactorAuthentication_Msg : Evergreen.V109.TwoFactorAuthentication.Msg -> Evergreen.V112.TwoFactorAuthentication.Msg
migrate_TwoFactorAuthentication_Msg old =
    case old of
        Evergreen.V109.TwoFactorAuthentication.PressedStart2FaSetup ->
            Evergreen.V112.TwoFactorAuthentication.PressedStart2FaSetup

        Evergreen.V109.TwoFactorAuthentication.PressedCopy p0 ->
            Evergreen.V112.TwoFactorAuthentication.PressedCopy p0

        Evergreen.V109.TwoFactorAuthentication.TypedTwoFactorCode p0 ->
            Evergreen.V112.TwoFactorAuthentication.TypedTwoFactorCode p0


migrate_TwoFactorAuthentication_ToBackend : Evergreen.V109.TwoFactorAuthentication.ToBackend -> Evergreen.V112.TwoFactorAuthentication.ToBackend
migrate_TwoFactorAuthentication_ToBackend old =
    case old of
        Evergreen.V109.TwoFactorAuthentication.EnableTwoFactorAuthenticationRequest ->
            Evergreen.V112.TwoFactorAuthentication.EnableTwoFactorAuthenticationRequest

        Evergreen.V109.TwoFactorAuthentication.ConfirmTwoFactorAuthenticationRequest p0 ->
            Evergreen.V112.TwoFactorAuthentication.ConfirmTwoFactorAuthenticationRequest p0


migrate_TwoFactorAuthentication_ToFrontend : Evergreen.V109.TwoFactorAuthentication.ToFrontend -> Evergreen.V112.TwoFactorAuthentication.ToFrontend
migrate_TwoFactorAuthentication_ToFrontend old =
    case old of
        Evergreen.V109.TwoFactorAuthentication.EnableTwoFactorAuthenticationResponse p0 ->
            Evergreen.V112.TwoFactorAuthentication.EnableTwoFactorAuthenticationResponse p0

        Evergreen.V109.TwoFactorAuthentication.ConfirmTwoFactorAuthenticationResponse p0 p1 ->
            Evergreen.V112.TwoFactorAuthentication.ConfirmTwoFactorAuthenticationResponse p0 p1


migrate_TwoFactorAuthentication_TwoFactorAuthentication : Evergreen.V109.TwoFactorAuthentication.TwoFactorAuthentication -> Evergreen.V112.TwoFactorAuthentication.TwoFactorAuthentication
migrate_TwoFactorAuthentication_TwoFactorAuthentication old =
    { secret = old.secret |> migrate_SecretId_SecretId
    , finishedAt = old.finishedAt
    }


migrate_TwoFactorAuthentication_TwoFactorAuthenticationSetup : Evergreen.V109.TwoFactorAuthentication.TwoFactorAuthenticationSetup -> Evergreen.V112.TwoFactorAuthentication.TwoFactorAuthenticationSetup
migrate_TwoFactorAuthentication_TwoFactorAuthenticationSetup old =
    { secret = old.secret |> migrate_SecretId_SecretId
    , startedAt = old.startedAt
    }


migrate_TwoFactorAuthentication_TwoFactorSetupData : Evergreen.V109.TwoFactorAuthentication.TwoFactorSetupData -> Evergreen.V112.TwoFactorAuthentication.TwoFactorSetupData
migrate_TwoFactorAuthentication_TwoFactorSetupData old =
    { qrCodeUrl = old.qrCodeUrl
    , code = old.code
    , attempts = old.attempts |> SeqDict.map (\k -> migrate_LoginForm_CodeStatus)
    }


migrate_TwoFactorAuthentication_TwoFactorState : Evergreen.V109.TwoFactorAuthentication.TwoFactorState -> Evergreen.V112.TwoFactorAuthentication.TwoFactorState
migrate_TwoFactorAuthentication_TwoFactorState old =
    case old of
        Evergreen.V109.TwoFactorAuthentication.TwoFactorNotStarted ->
            Evergreen.V112.TwoFactorAuthentication.TwoFactorNotStarted

        Evergreen.V109.TwoFactorAuthentication.TwoFactorLoading ->
            Evergreen.V112.TwoFactorAuthentication.TwoFactorLoading

        Evergreen.V109.TwoFactorAuthentication.TwoFactorSetup p0 ->
            Evergreen.V112.TwoFactorAuthentication.TwoFactorSetup (p0 |> migrate_TwoFactorAuthentication_TwoFactorSetupData)

        Evergreen.V109.TwoFactorAuthentication.TwoFactorComplete ->
            Evergreen.V112.TwoFactorAuthentication.TwoFactorComplete

        Evergreen.V109.TwoFactorAuthentication.TwoFactorAlreadyComplete p0 ->
            Evergreen.V112.TwoFactorAuthentication.TwoFactorAlreadyComplete p0


migrate_Types_BackendFileData : Evergreen.V109.Types.BackendFileData -> Evergreen.V112.Types.BackendFileData
migrate_Types_BackendFileData old =
    { fileSize = old.fileSize
    , imageSize = old.imageSize |> Maybe.map (migrate_Coord_Coord migrate_CssPixels_CssPixels)
    }


migrate_Types_BackendMsg : Evergreen.V109.Types.BackendMsg -> Evergreen.V112.Types.BackendMsg
migrate_Types_BackendMsg old =
    case old of
        Evergreen.V109.Types.SentLoginEmail p0 p1 p2 ->
            Evergreen.V112.Types.SentLoginEmail p0
                (p1 |> migrate_EmailAddress_EmailAddress)
                (p2 |> Result.mapError migrate_Postmark_SendEmailError)

        Evergreen.V109.Types.UserConnected p0 p1 ->
            Evergreen.V112.Types.UserConnected p0 p1

        Evergreen.V109.Types.UserDisconnected p0 p1 ->
            Evergreen.V112.Types.UserDisconnected p0 p1

        Evergreen.V109.Types.BackendGotTime p0 p1 p2 p3 ->
            Evergreen.V112.Types.UserDisconnected (Effect.Lamdera.sessionIdFromString "") (Effect.Lamdera.clientIdFromString "")

        Evergreen.V109.Types.SentLogErrorEmail p0 p1 p2 ->
            Evergreen.V112.Types.SentLogErrorEmail p0
                (p1 |> migrate_EmailAddress_EmailAddress)
                (p2 |> Result.mapError migrate_Postmark_SendEmailError)

        Evergreen.V109.Types.AiChatBackendMsg p0 ->
            Evergreen.V112.Types.AiChatBackendMsg (p0 |> migrate_AiChat_BackendMsg)

        Evergreen.V109.Types.GotDiscordUserAvatars p0 ->
            Evergreen.V112.Types.UserDisconnected (Effect.Lamdera.sessionIdFromString "") (Effect.Lamdera.clientIdFromString "")

        Evergreen.V109.Types.SentNotification p0 p1 p2 p3 ->
            Evergreen.V112.Types.SentNotification p0 (p1 |> migrate_Id_Id) p2 p3

        Evergreen.V109.Types.GotVapidKeys p0 ->
            Evergreen.V112.Types.GotVapidKeys p0

        Evergreen.V109.Types.GotSlackChannels p0 p1 p2 ->
            Evergreen.V112.Types.GotSlackChannels p0
                (p1 |> migrate_Id_Id)
                (p2
                    |> Result.map
                        (\rec1 ->
                            { currentUser = rec1.currentUser |> migrate_Slack_CurrentUser
                            , team = rec1.team |> migrate_Slack_Team
                            , users = rec1.users |> List.map migrate_Slack_User
                            , channels = rec1.channels |> List.map (Tuple.mapBoth migrate_Slack_Channel (List.map migrate_Slack_Message))
                            }
                        )
                )

        Evergreen.V109.Types.GotSlackOAuth p0 p1 p2 ->
            Evergreen.V112.Types.GotSlackOAuth p0
                (p1 |> migrate_Id_Id)
                (p2 |> Result.map migrate_Slack_TokenResponse)

        Evergreen.V109.Types.WebsocketCreatedHandle connection ->
            Evergreen.V112.Types.UserDisconnected (Effect.Lamdera.sessionIdFromString "") (Effect.Lamdera.clientIdFromString "")

        Evergreen.V109.Types.WebsocketSentData result ->
            Evergreen.V112.Types.UserDisconnected (Effect.Lamdera.sessionIdFromString "") (Effect.Lamdera.clientIdFromString "")

        Evergreen.V109.Types.WebsocketClosedByBackend bool ->
            Evergreen.V112.Types.UserDisconnected (Effect.Lamdera.sessionIdFromString "") (Effect.Lamdera.clientIdFromString "")

        Evergreen.V109.Types.DiscordWebsocketMsg msg ->
            Evergreen.V112.Types.UserDisconnected (Effect.Lamdera.sessionIdFromString "") (Effect.Lamdera.clientIdFromString "")

        Evergreen.V109.Types.GotCurrentUserGuilds posix discordBotToken result ->
            Evergreen.V112.Types.UserDisconnected (Effect.Lamdera.sessionIdFromString "") (Effect.Lamdera.clientIdFromString "")

        Evergreen.V109.Types.GotDiscordGuilds posix id result ->
            Evergreen.V112.Types.UserDisconnected (Effect.Lamdera.sessionIdFromString "") (Effect.Lamdera.clientIdFromString "")

        Evergreen.V109.Types.SentGuildMessageToDiscord id _ threadRouteWithMessage result ->
            Evergreen.V112.Types.UserDisconnected (Effect.Lamdera.sessionIdFromString "") (Effect.Lamdera.clientIdFromString "")

        Evergreen.V109.Types.DeletedDiscordMessage ->
            Evergreen.V112.Types.UserDisconnected (Effect.Lamdera.sessionIdFromString "") (Effect.Lamdera.clientIdFromString "")

        Evergreen.V109.Types.EditedDiscordMessage ->
            Evergreen.V112.Types.UserDisconnected (Effect.Lamdera.sessionIdFromString "") (Effect.Lamdera.clientIdFromString "")

        Evergreen.V109.Types.SentDirectMessageToDiscord dmChannelId id result ->
            Evergreen.V112.Types.UserDisconnected (Effect.Lamdera.sessionIdFromString "") (Effect.Lamdera.clientIdFromString "")


migrate_Types_ChannelSidebarMode : Evergreen.V109.Types.ChannelSidebarMode -> Evergreen.V112.Types.ChannelSidebarMode
migrate_Types_ChannelSidebarMode old =
    case old of
        Evergreen.V109.Types.ChannelSidebarClosed ->
            Evergreen.V112.Types.ChannelSidebarClosed

        Evergreen.V109.Types.ChannelSidebarOpened ->
            Evergreen.V112.Types.ChannelSidebarOpened

        Evergreen.V109.Types.ChannelSidebarClosing p0 ->
            Evergreen.V112.Types.ChannelSidebarClosing p0

        Evergreen.V109.Types.ChannelSidebarOpening p0 ->
            Evergreen.V112.Types.ChannelSidebarOpening p0

        Evergreen.V109.Types.ChannelSidebarDragging p0 ->
            Evergreen.V112.Types.ChannelSidebarDragging p0


migrate_Types_Drag : Evergreen.V109.Types.Drag -> Evergreen.V112.Types.Drag
migrate_Types_Drag old =
    case old of
        Evergreen.V109.Types.NoDrag ->
            Evergreen.V112.Types.NoDrag

        Evergreen.V109.Types.DragStart p0 p1 ->
            Evergreen.V112.Types.DragStart p0
                (p1 |> migrate_NonemptyDict_NonemptyDict identity migrate_Touch_Touch)

        Evergreen.V109.Types.Dragging p0 ->
            Evergreen.V112.Types.Dragging
                { horizontalStart = p0.horizontalStart
                , touches = p0.touches |> migrate_NonemptyDict_NonemptyDict identity migrate_Touch_Touch
                }


migrate_Types_EditMessage : Evergreen.V109.Types.EditMessage -> Evergreen.V112.Types.EditMessage
migrate_Types_EditMessage old =
    { messageIndex = old.messageIndex |> migrate_Id_Id
    , text = old.text
    , attachedFiles = old.attachedFiles |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Id_Id migrate_FileStatus_FileStatus) |> SeqDict.fromList
    }


migrate_Types_LastRequest : Evergreen.V109.Types.LastRequest -> Evergreen.V112.Types.LastRequest
migrate_Types_LastRequest old =
    case old of
        Evergreen.V109.Types.NoRequestsMade ->
            Evergreen.V112.Types.NoRequestsMade

        Evergreen.V109.Types.LastRequest p0 ->
            Evergreen.V112.Types.LastRequest p0


migrate_Types_LoginTokenData : Evergreen.V109.Types.LoginTokenData -> Evergreen.V112.Types.LoginTokenData
migrate_Types_LoginTokenData old =
    case old of
        Evergreen.V109.Types.WaitingForLoginToken p0 ->
            Evergreen.V112.Types.WaitingForLoginToken (p0 |> migrate_Types_WaitingForLoginTokenData)

        Evergreen.V109.Types.WaitingForTwoFactorToken p0 ->
            Evergreen.V112.Types.WaitingForTwoFactorToken
                { creationTime = p0.creationTime
                , userId = p0.userId |> migrate_Id_Id
                , loginAttempts = p0.loginAttempts
                }

        Evergreen.V109.Types.WaitingForLoginTokenForSignup p0 ->
            Evergreen.V112.Types.WaitingForLoginTokenForSignup
                { creationTime = p0.creationTime
                , emailAddress = p0.emailAddress |> migrate_EmailAddress_EmailAddress
                , loginAttempts = p0.loginAttempts
                , loginCode = p0.loginCode
                }

        Evergreen.V109.Types.WaitingForUserDataForSignup p0 ->
            Evergreen.V112.Types.WaitingForUserDataForSignup
                { creationTime = p0.creationTime
                , emailAddress = p0.emailAddress |> migrate_EmailAddress_EmailAddress
                }


migrate_Types_ScrollPosition : Evergreen.V109.Types.ScrollPosition -> Evergreen.V112.Types.ScrollPosition
migrate_Types_ScrollPosition old =
    case old of
        Evergreen.V109.Types.ScrolledToBottom ->
            Evergreen.V112.Types.ScrolledToBottom

        Evergreen.V109.Types.ScrolledToTop ->
            Evergreen.V112.Types.ScrolledToTop

        Evergreen.V109.Types.ScrolledToMiddle ->
            Evergreen.V112.Types.ScrolledToMiddle


migrate_Types_UserOptionsModel : Evergreen.V109.Types.UserOptionsModel -> Evergreen.V112.Types.UserOptionsModel
migrate_Types_UserOptionsModel old =
    { name = old.name |> migrate_Editable_Model
    , slackClientSecret = old.slackClientSecret |> migrate_Editable_Model
    , publicVapidKey = old.publicVapidKey |> migrate_Editable_Model
    , privateVapidKey = old.privateVapidKey |> migrate_Editable_Model
    , openRouterKey = old.openRouterKey |> migrate_Editable_Model
    , showLinkDiscordSetup = False
    , linkDiscordSubmit = Evergreen.V112.Types.LinkDiscordNotSubmitted { attemptCount = 0 }
    }


migrate_Types_WaitingForLoginTokenData : Evergreen.V109.Types.WaitingForLoginTokenData -> Evergreen.V112.Types.WaitingForLoginTokenData
migrate_Types_WaitingForLoginTokenData old =
    { creationTime = old.creationTime
    , userId = old.userId |> migrate_Id_Id
    , loginAttempts = old.loginAttempts
    , loginCode = old.loginCode
    }


migrate_Ui_Anim_Msg : Evergreen.V109.Ui.Anim.Msg -> Evergreen.V112.Ui.Anim.Msg
migrate_Ui_Anim_Msg old =
    old |> migrate_Internal_Model2_Msg


migrate_Ui_Anim_State : Evergreen.V109.Ui.Anim.State -> Evergreen.V112.Ui.Anim.State
migrate_Ui_Anim_State old =
    old |> migrate_Internal_Model2_State


migrate_UserAgent_Browser : Evergreen.V109.UserAgent.Browser -> Evergreen.V112.UserAgent.Browser
migrate_UserAgent_Browser old =
    case old of
        Evergreen.V109.UserAgent.Chrome ->
            Evergreen.V112.UserAgent.Chrome

        Evergreen.V109.UserAgent.Firefox ->
            Evergreen.V112.UserAgent.Firefox

        Evergreen.V109.UserAgent.Safari ->
            Evergreen.V112.UserAgent.Safari

        Evergreen.V109.UserAgent.Edge ->
            Evergreen.V112.UserAgent.Edge

        Evergreen.V109.UserAgent.Opera ->
            Evergreen.V112.UserAgent.Opera

        Evergreen.V109.UserAgent.UnknownBrowser ->
            Evergreen.V112.UserAgent.UnknownBrowser


migrate_UserAgent_Device : Evergreen.V109.UserAgent.Device -> Evergreen.V112.UserAgent.Device
migrate_UserAgent_Device old =
    case old of
        Evergreen.V109.UserAgent.Desktop ->
            Evergreen.V112.UserAgent.Desktop

        Evergreen.V109.UserAgent.Mobile ->
            Evergreen.V112.UserAgent.Mobile

        Evergreen.V109.UserAgent.Tablet ->
            Evergreen.V112.UserAgent.Tablet


migrate_UserAgent_UserAgent : Evergreen.V109.UserAgent.UserAgent -> Evergreen.V112.UserAgent.UserAgent
migrate_UserAgent_UserAgent old =
    { browser = old.browser |> migrate_UserAgent_Browser
    , device = old.device |> migrate_UserAgent_Device
    }


migrate_UserSession_NotificationMode : Evergreen.V109.UserSession.NotificationMode -> Evergreen.V112.UserSession.NotificationMode
migrate_UserSession_NotificationMode old =
    case old of
        Evergreen.V109.UserSession.NoNotifications ->
            Evergreen.V112.UserSession.NoNotifications

        Evergreen.V109.UserSession.NotifyWhenRunning ->
            Evergreen.V112.UserSession.NotifyWhenRunning

        Evergreen.V109.UserSession.PushNotifications ->
            Evergreen.V112.UserSession.PushNotifications


migrate_UserSession_PushSubscription : Evergreen.V109.UserSession.PushSubscription -> Evergreen.V112.UserSession.PushSubscription
migrate_UserSession_PushSubscription old =
    case old of
        Evergreen.V109.UserSession.NotSubscribed ->
            Evergreen.V112.UserSession.NotSubscribed

        Evergreen.V109.UserSession.Subscribed p0 ->
            Evergreen.V112.UserSession.Subscribed (p0 |> migrate_UserSession_SubscribeData)

        Evergreen.V109.UserSession.SubscriptionError p0 ->
            Evergreen.V112.UserSession.SubscriptionError p0


migrate_UserSession_SetViewing : Evergreen.V109.UserSession.SetViewing -> Evergreen.V112.UserSession.SetViewing
migrate_UserSession_SetViewing old =
    case old of
        Evergreen.V109.UserSession.ViewDm p0 p1 ->
            Evergreen.V112.UserSession.ViewDm (p0 |> migrate_Id_Id)
                (p1 |> migrate_UserSession_ToBeFilledInByBackend (\a -> SeqDict.toList a |> List.map (Tuple.mapBoth migrate_Id_Id (migrate_Message_Message migrate_Id_ChannelMessageId)) |> SeqDict.fromList))

        Evergreen.V109.UserSession.ViewDmThread p0 p1 p2 ->
            Evergreen.V112.UserSession.ViewDmThread (p0 |> migrate_Id_Id)
                (p1 |> migrate_Id_Id)
                (p2 |> migrate_UserSession_ToBeFilledInByBackend (\a -> SeqDict.toList a |> List.map (Tuple.mapBoth migrate_Id_Id (migrate_Message_Message migrate_Id_ThreadMessageId)) |> SeqDict.fromList))

        Evergreen.V109.UserSession.ViewChannel p0 p1 p2 ->
            Evergreen.V112.UserSession.ViewChannel (p0 |> migrate_Id_Id)
                (p1 |> migrate_Id_Id)
                (p2 |> migrate_UserSession_ToBeFilledInByBackend (\a -> SeqDict.toList a |> List.map (Tuple.mapBoth migrate_Id_Id (migrate_Message_Message migrate_Id_ChannelMessageId)) |> SeqDict.fromList))

        Evergreen.V109.UserSession.ViewChannelThread p0 p1 p2 p3 ->
            Evergreen.V112.UserSession.ViewChannelThread (p0 |> migrate_Id_Id)
                (p1 |> migrate_Id_Id)
                (p2 |> migrate_Id_Id)
                (p3 |> migrate_UserSession_ToBeFilledInByBackend (\a -> SeqDict.toList a |> List.map (Tuple.mapBoth migrate_Id_Id (migrate_Message_Message migrate_Id_ThreadMessageId)) |> SeqDict.fromList))

        Evergreen.V109.UserSession.StopViewingChannel ->
            Evergreen.V112.UserSession.StopViewingChannel


migrate_UserSession_SubscribeData : Evergreen.V109.UserSession.SubscribeData -> Evergreen.V112.UserSession.SubscribeData
migrate_UserSession_SubscribeData old =
    old


migrate_UserSession_ToBeFilledInByBackend : (a_old -> a_new) -> Evergreen.V109.UserSession.ToBeFilledInByBackend a_old -> Evergreen.V112.UserSession.ToBeFilledInByBackend a_new
migrate_UserSession_ToBeFilledInByBackend migrate_a old =
    case old of
        Evergreen.V109.UserSession.EmptyPlaceholder ->
            Evergreen.V112.UserSession.EmptyPlaceholder

        Evergreen.V109.UserSession.FilledInByBackend p0 ->
            Evergreen.V112.UserSession.FilledInByBackend (p0 |> migrate_a)


migrate_UserSession_UserSession : Evergreen.V109.UserSession.UserSession -> Evergreen.V112.UserSession.UserSession
migrate_UserSession_UserSession old =
    { userId = old.userId |> migrate_Id_Id
    , notificationMode = old.notificationMode |> migrate_UserSession_NotificationMode
    , pushSubscription = old.pushSubscription |> migrate_UserSession_PushSubscription
    , currentlyViewing = Nothing
    , userAgent = old.userAgent |> migrate_UserAgent_UserAgent
    , sessionIdHash = old.sessionIdHash |> migrate_SessionIdHash_SessionIdHash
    }


migrate_User_AdminUiSection : Evergreen.V109.User.AdminUiSection -> Evergreen.V112.User.AdminUiSection
migrate_User_AdminUiSection old =
    case old of
        Evergreen.V109.User.UsersSection ->
            Evergreen.V112.User.UsersSection

        Evergreen.V109.User.LogSection ->
            Evergreen.V112.User.LogSection


migrate_User_BackendUser : Evergreen.V109.User.BackendUser -> Maybe Evergreen.V112.User.BackendUser
migrate_User_BackendUser old =
    case old.email of
        Evergreen.V109.User.RegisteredDirectly emailAddress ->
            { name = old.name |> migrate_PersonName_PersonName
            , isAdmin = old.isAdmin
            , email = migrate_EmailAddress_EmailAddress emailAddress
            , recentLoginEmails = old.recentLoginEmails
            , lastLogPageViewed = old.lastLogPageViewed
            , expandedSections = old.expandedSections |> SeqSet.map migrate_User_AdminUiSection
            , createdAt = old.createdAt
            , emailNotifications = old.emailNotifications |> migrate_User_EmailNotifications
            , lastEmailNotification = old.lastEmailNotification
            , lastViewed = SeqDict.empty
            , lastViewedThreads = SeqDict.empty
            , lastDmViewed = Evergreen.V112.User.NoLastDmViewed
            , lastChannelViewed = old.lastChannelViewed |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Id_Id (Tuple.mapBoth migrate_Id_Id migrate_Id_ThreadRoute)) |> SeqDict.fromList
            , lastDiscordChannelViewed = SeqDict.empty
            , icon = old.icon |> Maybe.map migrate_FileStatus_FileHash
            , notifyOnAllMessages = old.notifyOnAllMessages |> SeqSet.map migrate_Id_Id
            , discordNotifyOnAllMessages = SeqSet.empty
            , directMentions = old.directMentions |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Id_Id (migrate_NonemptyDict_NonemptyDict (Tuple.mapBoth migrate_Id_Id migrate_Id_ThreadRoute) migrate_OneOrGreater_OneOrGreater)) |> SeqDict.fromList
            , discordDirectMentions = SeqDict.empty
            , lastPushNotification = old.lastPushNotification
            }
                |> Just

        Evergreen.V109.User.RegisteredFromDiscord ->
            Nothing

        Evergreen.V109.User.RegisteredFromSlack ->
            Nothing


migrate_User_EmailNotifications : Evergreen.V109.User.EmailNotifications -> Evergreen.V112.User.EmailNotifications
migrate_User_EmailNotifications old =
    case old of
        Evergreen.V109.User.CheckEvery5Minutes ->
            Evergreen.V112.User.CheckEvery5Minutes


migrate_User_FrontendUser : Evergreen.V109.User.FrontendUser -> Evergreen.V112.User.FrontendUser
migrate_User_FrontendUser old =
    { name = old.name |> migrate_PersonName_PersonName
    , isAdmin = old.isAdmin
    , createdAt = old.createdAt
    , icon = old.icon |> Maybe.map migrate_FileStatus_FileHash
    }


migrate_User_NotificationLevel : Evergreen.V109.User.NotificationLevel -> Evergreen.V112.User.NotificationLevel
migrate_User_NotificationLevel old =
    case old of
        Evergreen.V109.User.NotifyOnEveryMessage ->
            Evergreen.V112.User.NotifyOnEveryMessage

        Evergreen.V109.User.NotifyOnMention ->
            Evergreen.V112.User.NotifyOnMention


migrate_VisibleMessages_VisibleMessages : (messageId_old -> messageId_new) -> Evergreen.V109.VisibleMessages.VisibleMessages messageId_old -> Evergreen.V112.VisibleMessages.VisibleMessages messageId_new
migrate_VisibleMessages_VisibleMessages migrate_messageId old =
    { oldest = old.oldest |> migrate_Id_Id
    , count = old.count
    }
