module Evergreen.Migrate.V114 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Array
import Dict
import Evergreen.V112.AiChat
import Evergreen.V112.ChannelName
import Evergreen.V112.Coord
import Evergreen.V112.CssPixels
import Evergreen.V112.Discord
import Evergreen.V112.Discord.Id
import Evergreen.V112.DmChannel
import Evergreen.V112.Editable
import Evergreen.V112.EmailAddress
import Evergreen.V112.Emoji
import Evergreen.V112.FileName
import Evergreen.V112.FileStatus
import Evergreen.V112.Geometry.Types
import Evergreen.V112.GuildName
import Evergreen.V112.Id
import Evergreen.V112.ImageEditor
import Evergreen.V112.Internal.Model2
import Evergreen.V112.Local
import Evergreen.V112.LocalState
import Evergreen.V112.Log
import Evergreen.V112.LoginForm
import Evergreen.V112.Message
import Evergreen.V112.MessageInput
import Evergreen.V112.NonemptyDict
import Evergreen.V112.NonemptySet
import Evergreen.V112.OneOrGreater
import Evergreen.V112.Pages.Admin
import Evergreen.V112.Pagination
import Evergreen.V112.PersonName
import Evergreen.V112.Point2d
import Evergreen.V112.Ports
import Evergreen.V112.Postmark
import Evergreen.V112.RichText
import Evergreen.V112.Route
import Evergreen.V112.SecretId
import Evergreen.V112.SessionIdHash
import Evergreen.V112.Slack
import Evergreen.V112.Table
import Evergreen.V112.TextEditor
import Evergreen.V112.Thread
import Evergreen.V112.Touch
import Evergreen.V112.TwoFactorAuthentication
import Evergreen.V112.Types
import Evergreen.V112.Ui.Anim
import Evergreen.V112.User
import Evergreen.V112.UserAgent
import Evergreen.V112.UserSession
import Evergreen.V112.VisibleMessages
import Evergreen.V114.AiChat
import Evergreen.V114.ChannelName
import Evergreen.V114.Coord
import Evergreen.V114.CssPixels
import Evergreen.V114.Discord
import Evergreen.V114.Discord.Id
import Evergreen.V114.DmChannel
import Evergreen.V114.Editable
import Evergreen.V114.EmailAddress
import Evergreen.V114.Emoji
import Evergreen.V114.FileName
import Evergreen.V114.FileStatus
import Evergreen.V114.Geometry.Types
import Evergreen.V114.GuildName
import Evergreen.V114.Id
import Evergreen.V114.ImageEditor
import Evergreen.V114.Internal.Model2
import Evergreen.V114.Local
import Evergreen.V114.LocalState
import Evergreen.V114.Log
import Evergreen.V114.LoginForm
import Evergreen.V114.Message
import Evergreen.V114.MessageInput
import Evergreen.V114.NonemptyDict
import Evergreen.V114.NonemptySet
import Evergreen.V114.OneOrGreater
import Evergreen.V114.Pages.Admin
import Evergreen.V114.Pagination
import Evergreen.V114.PersonName
import Evergreen.V114.Point2d
import Evergreen.V114.Ports
import Evergreen.V114.Postmark
import Evergreen.V114.RichText
import Evergreen.V114.Route
import Evergreen.V114.SecretId
import Evergreen.V114.SessionIdHash
import Evergreen.V114.Slack
import Evergreen.V114.Table
import Evergreen.V114.TextEditor
import Evergreen.V114.Thread
import Evergreen.V114.Touch
import Evergreen.V114.TwoFactorAuthentication
import Evergreen.V114.Types
import Evergreen.V114.Ui.Anim
import Evergreen.V114.User
import Evergreen.V114.UserAgent
import Evergreen.V114.UserSession
import Evergreen.V114.VisibleMessages
import Lamdera.Migrations exposing (..)
import List
import List.Nonempty
import Maybe
import Quantity
import SeqDict
import SeqSet


frontendModel : Evergreen.V112.Types.FrontendModel -> ModelMigration Evergreen.V114.Types.FrontendModel Evergreen.V114.Types.FrontendMsg
frontendModel old =
    ModelReset


backendModel : Evergreen.V112.Types.BackendModel -> ModelMigration Evergreen.V114.Types.BackendModel Evergreen.V114.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V112.Types.FrontendMsg -> MsgMigration Evergreen.V114.Types.FrontendMsg Evergreen.V114.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V112.Types.ToBackend -> MsgMigration Evergreen.V114.Types.ToBackend Evergreen.V114.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V112.Types.BackendMsg -> MsgMigration Evergreen.V114.Types.BackendMsg Evergreen.V114.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V112.Types.ToFrontend -> MsgMigration Evergreen.V114.Types.ToFrontend Evergreen.V114.Types.FrontendMsg
toFrontend old =
    MsgUnchanged
