module Evergreen.Migrate.V144 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Dict
import Evergreen.V138.AiChat
import Evergreen.V138.Coord
import Evergreen.V138.CssPixels
import Evergreen.V138.Discord
import Evergreen.V138.Discord.Id
import Evergreen.V138.Editable
import Evergreen.V138.Emoji
import Evergreen.V138.FileStatus
import Evergreen.V138.Geometry.Types
import Evergreen.V138.Id
import Evergreen.V138.ImageEditor
import Evergreen.V138.Internal.Model2
import Evergreen.V138.Internal.Teleport
import Evergreen.V138.LocalState
import Evergreen.V138.LoginForm
import Evergreen.V138.MessageInput
import Evergreen.V138.MessageView
import Evergreen.V138.NonemptyDict
import Evergreen.V138.Pages.Admin
import Evergreen.V138.PersonName
import Evergreen.V138.Point2d
import Evergreen.V138.Ports
import Evergreen.V138.RichText
import Evergreen.V138.Route
import Evergreen.V138.SafeJson
import Evergreen.V138.SecretId
import Evergreen.V138.SessionIdHash
import Evergreen.V138.Slack
import Evergreen.V138.Table
import Evergreen.V138.TextEditor
import Evergreen.V138.Touch
import Evergreen.V138.TwoFactorAuthentication
import Evergreen.V138.Types
import Evergreen.V138.Ui.Anim
import Evergreen.V138.User
import Evergreen.V138.UserAgent
import Evergreen.V138.UserSession
import Evergreen.V144.AiChat
import Evergreen.V144.Coord
import Evergreen.V144.CssPixels
import Evergreen.V144.Discord
import Evergreen.V144.Editable
import Evergreen.V144.Emoji
import Evergreen.V144.FileStatus
import Evergreen.V144.Geometry.Types
import Evergreen.V144.Id
import Evergreen.V144.ImageEditor
import Evergreen.V144.Internal.Model2
import Evergreen.V144.Internal.Teleport
import Evergreen.V144.LocalState
import Evergreen.V144.LoginForm
import Evergreen.V144.MessageInput
import Evergreen.V144.MessageView
import Evergreen.V144.NonemptyDict
import Evergreen.V144.Pages.Admin
import Evergreen.V144.PersonName
import Evergreen.V144.Point2d
import Evergreen.V144.Ports
import Evergreen.V144.RichText
import Evergreen.V144.Route
import Evergreen.V144.SafeJson
import Evergreen.V144.SecretId
import Evergreen.V144.SessionIdHash
import Evergreen.V144.Slack
import Evergreen.V144.Table
import Evergreen.V144.TextEditor
import Evergreen.V144.Touch
import Evergreen.V144.TwoFactorAuthentication
import Evergreen.V144.Types
import Evergreen.V144.Ui.Anim
import Evergreen.V144.User
import Evergreen.V144.UserAgent
import Evergreen.V144.UserSession
import Lamdera.Migrations exposing (..)
import List
import Maybe
import Quantity
import SeqDict


frontendModel : Evergreen.V138.Types.FrontendModel -> ModelMigration Evergreen.V144.Types.FrontendModel Evergreen.V144.Types.FrontendMsg
frontendModel old =
    ModelUnchanged


backendModel : Evergreen.V138.Types.BackendModel -> ModelMigration Evergreen.V144.Types.BackendModel Evergreen.V144.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V138.Types.FrontendMsg -> MsgMigration Evergreen.V144.Types.FrontendMsg Evergreen.V144.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V138.Types.ToBackend -> MsgMigration Evergreen.V144.Types.ToBackend Evergreen.V144.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V138.Types.BackendMsg -> MsgMigration Evergreen.V144.Types.BackendMsg Evergreen.V144.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V138.Types.ToFrontend -> MsgMigration Evergreen.V144.Types.ToFrontend Evergreen.V144.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_AiChat_Msg : Evergreen.V138.AiChat.Msg -> Evergreen.V144.AiChat.Msg
migrate_AiChat_Msg old =
    case old of
        Evergreen.V138.AiChat.TypedMessage p0 ->
            Evergreen.V144.AiChat.TypedMessage p0

        Evergreen.V138.AiChat.PressedSend ->
            Evergreen.V144.AiChat.PressedSend

        Evergreen.V138.AiChat.TypedChatHistory p0 ->
            Evergreen.V144.AiChat.TypedChatHistory p0

        Evergreen.V138.AiChat.PressedKeep p0 ->
            Evergreen.V144.AiChat.PressedKeep (p0 |> migrate_AiChat_ResponseId)

        Evergreen.V138.AiChat.PressedDelete p0 ->
            Evergreen.V144.AiChat.PressedDelete (p0 |> migrate_AiChat_ResponseId)

        Evergreen.V138.AiChat.PressedRetry p0 ->
            Evergreen.V144.AiChat.PressedRetry (p0 |> migrate_AiChat_ResponseId)

        Evergreen.V138.AiChat.PressedChatHistoryContainer ->
            Evergreen.V144.AiChat.PressedChatHistoryContainer

        Evergreen.V138.AiChat.PressedClearChatHistory ->
            Evergreen.V144.AiChat.PressedClearChatHistory

        Evergreen.V138.AiChat.PressedOptionsButton ->
            Evergreen.V144.AiChat.PressedOptionsButton

        Evergreen.V138.AiChat.SelectedAiModel p0 ->
            Evergreen.V144.AiChat.SelectedAiModel p0

        Evergreen.V138.AiChat.SelectedSendMessageWith p0 ->
            Evergreen.V144.AiChat.SelectedSendMessageWith (p0 |> migrate_AiChat_SendMessageWith)

        Evergreen.V138.AiChat.TypedUserPrefix p0 ->
            Evergreen.V144.AiChat.TypedUserPrefix p0

        Evergreen.V138.AiChat.TypedBotPrefix p0 ->
            Evergreen.V144.AiChat.TypedBotPrefix p0

        Evergreen.V138.AiChat.CheckDebounce p0 ->
            Evergreen.V144.AiChat.CheckDebounce p0

        Evergreen.V138.AiChat.GotLocalStorage p0 ->
            Evergreen.V144.AiChat.GotLocalStorage p0

        Evergreen.V138.AiChat.EditedResponse p0 p1 ->
            Evergreen.V144.AiChat.EditedResponse (p0 |> migrate_AiChat_ResponseId) p1

        Evergreen.V138.AiChat.NoOp ->
            Evergreen.V144.AiChat.NoOp

        Evergreen.V138.AiChat.GotAiModels p0 ->
            Evergreen.V144.AiChat.GotAiModels p0


migrate_AiChat_ResponseId : Evergreen.V138.AiChat.ResponseId -> Evergreen.V144.AiChat.ResponseId
migrate_AiChat_ResponseId old =
    case old of
        Evergreen.V138.AiChat.RespondId p0 ->
            Evergreen.V144.AiChat.RespondId p0


migrate_AiChat_SendMessageWith : Evergreen.V138.AiChat.SendMessageWith -> Evergreen.V144.AiChat.SendMessageWith
migrate_AiChat_SendMessageWith old =
    case old of
        Evergreen.V138.AiChat.SendWithEnter ->
            Evergreen.V144.AiChat.SendWithEnter

        Evergreen.V138.AiChat.SendWithShiftEnter ->
            Evergreen.V144.AiChat.SendWithShiftEnter


migrate_Coord_Coord : (units_old -> units_new) -> Evergreen.V138.Coord.Coord units_old -> Evergreen.V144.Coord.Coord units_new
migrate_Coord_Coord migrate_units old =
    old |> Tuple.mapBoth migrate_Quantity_Quantity migrate_Quantity_Quantity


migrate_CssPixels_CssPixels : Evergreen.V138.CssPixels.CssPixels -> Evergreen.V144.CssPixels.CssPixels
migrate_CssPixels_CssPixels old =
    case old of
        Evergreen.V138.CssPixels.CssPixels p0 ->
            Evergreen.V144.CssPixels.CssPixels p0


migrate_Discord_Id : Evergreen.V138.Discord.Id.Id idType_old -> Evergreen.V144.Discord.Id idType_new
migrate_Discord_Id old =
    case old of
        Evergreen.V138.Discord.Id.Id p0 ->
            Evergreen.V144.Discord.Id p0


migrate_Discord_UserAuth : Evergreen.V138.Discord.UserAuth -> Evergreen.V144.Discord.UserAuth
migrate_Discord_UserAuth old =
    { token = old.token
    , userAgent = old.userAgent
    , xSuperProperties = old.xSuperProperties |> migrate_SafeJson_SafeJson
    }


migrate_Editable_Editing : Evergreen.V138.Editable.Editing -> Evergreen.V144.Editable.Editing
migrate_Editable_Editing old =
    case old of
        Evergreen.V138.Editable.NotEditing ->
            Evergreen.V144.Editable.NotEditing

        Evergreen.V138.Editable.Editing p0 ->
            Evergreen.V144.Editable.Editing p0


migrate_Editable_Model : Evergreen.V138.Editable.Model -> Evergreen.V144.Editable.Model
migrate_Editable_Model old =
    { editing = old.editing |> migrate_Editable_Editing
    , pressedSubmit = old.pressedSubmit
    , showSecret = old.showSecret
    }


migrate_Editable_Msg : (value_old -> value_new) -> Evergreen.V138.Editable.Msg value_old -> Evergreen.V144.Editable.Msg value_new
migrate_Editable_Msg migrate_value old =
    case old of
        Evergreen.V138.Editable.Edit p0 ->
            Evergreen.V144.Editable.Edit (p0 |> migrate_Editable_Model)

        Evergreen.V138.Editable.PressedAcceptEdit p0 ->
            Evergreen.V144.Editable.PressedAcceptEdit (p0 |> migrate_value)


migrate_Emoji_Emoji : Evergreen.V138.Emoji.Emoji -> Evergreen.V144.Emoji.Emoji
migrate_Emoji_Emoji old =
    case old of
        Evergreen.V138.Emoji.UnicodeEmoji p0 ->
            Evergreen.V144.Emoji.UnicodeEmoji p0


migrate_FileStatus_FileHash : Evergreen.V138.FileStatus.FileHash -> Evergreen.V144.FileStatus.FileHash
migrate_FileStatus_FileHash old =
    case old of
        Evergreen.V138.FileStatus.FileHash p0 ->
            Evergreen.V144.FileStatus.FileHash p0


migrate_FileStatus_ImageMetadata : Evergreen.V138.FileStatus.ImageMetadata -> Evergreen.V144.FileStatus.ImageMetadata
migrate_FileStatus_ImageMetadata old =
    { imageSize = old.imageSize |> migrate_Coord_Coord migrate_CssPixels_CssPixels
    , orientation = old.orientation |> Maybe.map migrate_FileStatus_Orientation
    , gpsLocation = old.gpsLocation
    , cameraOwner = old.cameraOwner
    , exposureTime = old.exposureTime
    , fNumber = old.fNumber
    , focalLength = old.focalLength
    , isoSpeedRating = old.isoSpeedRating
    , make = old.make
    , model = old.model
    , software = old.software
    , userComment = old.userComment
    }


migrate_FileStatus_Orientation : Evergreen.V138.FileStatus.Orientation -> Evergreen.V144.FileStatus.Orientation
migrate_FileStatus_Orientation old =
    case old of
        Evergreen.V138.FileStatus.NoChange ->
            Evergreen.V144.FileStatus.NoChange

        Evergreen.V138.FileStatus.Rotation90 ->
            Evergreen.V144.FileStatus.Rotation90

        Evergreen.V138.FileStatus.Rotation180 ->
            Evergreen.V144.FileStatus.Rotation180

        Evergreen.V138.FileStatus.Rotation270 ->
            Evergreen.V144.FileStatus.Rotation270

        Evergreen.V138.FileStatus.Mirrored ->
            Evergreen.V144.FileStatus.Mirrored

        Evergreen.V138.FileStatus.MirroredRotation90 ->
            Evergreen.V144.FileStatus.MirroredRotation90

        Evergreen.V138.FileStatus.MirroredRotation180 ->
            Evergreen.V144.FileStatus.MirroredRotation180

        Evergreen.V138.FileStatus.MirroredRotation270 ->
            Evergreen.V144.FileStatus.MirroredRotation270


migrate_FileStatus_UploadResponse : Evergreen.V138.FileStatus.UploadResponse -> Evergreen.V144.FileStatus.UploadResponse
migrate_FileStatus_UploadResponse old =
    { fileHash = old.fileHash |> migrate_FileStatus_FileHash
    , imageSize = old.imageSize |> Maybe.map migrate_FileStatus_ImageMetadata
    }


migrate_Geometry_Types_Point2d : Evergreen.V138.Geometry.Types.Point2d units_old coordinates_old -> Evergreen.V144.Geometry.Types.Point2d units_new coordinates_new
migrate_Geometry_Types_Point2d old =
    case old of
        Evergreen.V138.Geometry.Types.Point2d p0 ->
            Evergreen.V144.Geometry.Types.Point2d p0


migrate_Id_AnyGuildOrDmId : Evergreen.V138.Id.AnyGuildOrDmId -> Evergreen.V144.Id.AnyGuildOrDmId
migrate_Id_AnyGuildOrDmId old =
    case old of
        Evergreen.V138.Id.GuildOrDmId p0 ->
            Evergreen.V144.Id.GuildOrDmId (p0 |> migrate_Id_GuildOrDmId)

        Evergreen.V138.Id.DiscordGuildOrDmId p0 ->
            Evergreen.V144.Id.DiscordGuildOrDmId (p0 |> migrate_Id_DiscordGuildOrDmId)


migrate_Id_DiscordGuildOrDmId : Evergreen.V138.Id.DiscordGuildOrDmId -> Evergreen.V144.Id.DiscordGuildOrDmId
migrate_Id_DiscordGuildOrDmId old =
    case old of
        Evergreen.V138.Id.DiscordGuildOrDmId_Guild p0 p1 p2 ->
            Evergreen.V144.Id.DiscordGuildOrDmId_Guild (p0 |> migrate_Discord_Id)
                (p1 |> migrate_Discord_Id)
                (p2 |> migrate_Discord_Id)

        Evergreen.V138.Id.DiscordGuildOrDmId_Dm p0 ->
            Evergreen.V144.Id.DiscordGuildOrDmId_Dm (p0 |> migrate_Id_DiscordGuildOrDmId_DmData)


migrate_Id_DiscordGuildOrDmId_DmData : Evergreen.V138.Id.DiscordGuildOrDmId_DmData -> Evergreen.V144.Id.DiscordGuildOrDmId_DmData
migrate_Id_DiscordGuildOrDmId_DmData old =
    { currentUserId = old.currentUserId |> migrate_Discord_Id
    , channelId = old.channelId |> migrate_Discord_Id
    }


migrate_Id_GuildOrDmId : Evergreen.V138.Id.GuildOrDmId -> Evergreen.V144.Id.GuildOrDmId
migrate_Id_GuildOrDmId old =
    case old of
        Evergreen.V138.Id.GuildOrDmId_Guild p0 p1 ->
            Evergreen.V144.Id.GuildOrDmId_Guild (p0 |> migrate_Id_Id) (p1 |> migrate_Id_Id)

        Evergreen.V138.Id.GuildOrDmId_Dm p0 ->
            Evergreen.V144.Id.GuildOrDmId_Dm (p0 |> migrate_Id_Id)


migrate_Id_Id : Evergreen.V138.Id.Id a_old -> Evergreen.V144.Id.Id a_new
migrate_Id_Id old =
    case old of
        Evergreen.V138.Id.Id p0 ->
            Evergreen.V144.Id.Id p0


migrate_Id_ThreadRoute : Evergreen.V138.Id.ThreadRoute -> Evergreen.V144.Id.ThreadRoute
migrate_Id_ThreadRoute old =
    case old of
        Evergreen.V138.Id.NoThread ->
            Evergreen.V144.Id.NoThread

        Evergreen.V138.Id.ViewThread p0 ->
            Evergreen.V144.Id.ViewThread (p0 |> migrate_Id_Id)


migrate_Id_ThreadRouteWithMessage : Evergreen.V138.Id.ThreadRouteWithMessage -> Evergreen.V144.Id.ThreadRouteWithMessage
migrate_Id_ThreadRouteWithMessage old =
    case old of
        Evergreen.V138.Id.NoThreadWithMessage p0 ->
            Evergreen.V144.Id.NoThreadWithMessage (p0 |> migrate_Id_Id)

        Evergreen.V138.Id.ViewThreadWithMessage p0 p1 ->
            Evergreen.V144.Id.ViewThreadWithMessage (p0 |> migrate_Id_Id) (p1 |> migrate_Id_Id)


migrate_ImageEditor_Msg : Evergreen.V138.ImageEditor.Msg -> Evergreen.V144.ImageEditor.Msg
migrate_ImageEditor_Msg old =
    case old of
        Evergreen.V138.ImageEditor.PressedProfileImage ->
            Evergreen.V144.ImageEditor.PressedProfileImage

        Evergreen.V138.ImageEditor.SelectedImage p0 ->
            Evergreen.V144.ImageEditor.SelectedImage p0

        Evergreen.V138.ImageEditor.GotImageUrl p0 ->
            Evergreen.V144.ImageEditor.GotImageUrl p0

        Evergreen.V138.ImageEditor.MouseDownImageEditor p0 p1 ->
            Evergreen.V144.ImageEditor.MouseDownImageEditor p0 p1

        Evergreen.V138.ImageEditor.MouseUpImageEditor ->
            Evergreen.V144.ImageEditor.MouseUpImageEditor

        Evergreen.V138.ImageEditor.MovedImageEditor p0 p1 ->
            Evergreen.V144.ImageEditor.MovedImageEditor p0 p1

        Evergreen.V138.ImageEditor.TouchEndImageEditor ->
            Evergreen.V144.ImageEditor.TouchEndImageEditor

        Evergreen.V138.ImageEditor.PressedConfirmImage ->
            Evergreen.V144.ImageEditor.PressedConfirmImage

        Evergreen.V138.ImageEditor.GotImageSize p0 ->
            Evergreen.V144.ImageEditor.GotImageSize p0

        Evergreen.V138.ImageEditor.CroppedImage p0 ->
            Evergreen.V144.ImageEditor.CroppedImage p0

        Evergreen.V138.ImageEditor.PressedCancel ->
            Evergreen.V144.ImageEditor.PressedCancel

        Evergreen.V138.ImageEditor.UploadedImage p0 ->
            Evergreen.V144.ImageEditor.UploadedImage (p0 |> Result.map migrate_FileStatus_UploadResponse)


migrate_Internal_Model2_Msg : Evergreen.V138.Internal.Model2.Msg -> Evergreen.V144.Internal.Model2.Msg
migrate_Internal_Model2_Msg old =
    case old of
        Evergreen.V138.Internal.Model2.Tick p0 ->
            Evergreen.V144.Internal.Model2.Tick p0

        Evergreen.V138.Internal.Model2.Teleported p0 p1 ->
            Evergreen.V144.Internal.Model2.Teleported (p0 |> migrate_Internal_Teleport_Trigger)
                (p1 |> migrate_Internal_Teleport_Event)


migrate_Internal_Teleport_CssAnimation : Evergreen.V138.Internal.Teleport.CssAnimation -> Evergreen.V144.Internal.Teleport.CssAnimation
migrate_Internal_Teleport_CssAnimation old =
    old


migrate_Internal_Teleport_Data : Evergreen.V138.Internal.Teleport.Data -> Evergreen.V144.Internal.Teleport.Data
migrate_Internal_Teleport_Data old =
    case old of
        Evergreen.V138.Internal.Teleport.Css p0 ->
            Evergreen.V144.Internal.Teleport.Css (p0 |> migrate_Internal_Teleport_CssAnimation)

        Evergreen.V138.Internal.Teleport.ParentTrigger p0 ->
            Evergreen.V144.Internal.Teleport.ParentTrigger (p0 |> migrate_Internal_Teleport_ParentTriggerDetails)


migrate_Internal_Teleport_Event : Evergreen.V138.Internal.Teleport.Event -> Evergreen.V144.Internal.Teleport.Event
migrate_Internal_Teleport_Event old =
    { timestamp = old.timestamp
    , data = old.data |> List.map migrate_Internal_Teleport_Data
    }


migrate_Internal_Teleport_ParentTriggerDetails : Evergreen.V138.Internal.Teleport.ParentTriggerDetails -> Evergreen.V144.Internal.Teleport.ParentTriggerDetails
migrate_Internal_Teleport_ParentTriggerDetails old =
    old


migrate_Internal_Teleport_Trigger : Evergreen.V138.Internal.Teleport.Trigger -> Evergreen.V144.Internal.Teleport.Trigger
migrate_Internal_Teleport_Trigger old =
    case old of
        Evergreen.V138.Internal.Teleport.OnHover ->
            Evergreen.V144.Internal.Teleport.OnHover

        Evergreen.V138.Internal.Teleport.OnRender ->
            Evergreen.V144.Internal.Teleport.OnRender

        Evergreen.V138.Internal.Teleport.OnFocus ->
            Evergreen.V144.Internal.Teleport.OnFocus

        Evergreen.V138.Internal.Teleport.OnFocusWithin ->
            Evergreen.V144.Internal.Teleport.OnFocusWithin

        Evergreen.V138.Internal.Teleport.OnActive ->
            Evergreen.V144.Internal.Teleport.OnActive

        Evergreen.V138.Internal.Teleport.OnDismount ->
            Evergreen.V144.Internal.Teleport.OnDismount


migrate_LocalState_PrivateVapidKey : Evergreen.V138.LocalState.PrivateVapidKey -> Evergreen.V144.LocalState.PrivateVapidKey
migrate_LocalState_PrivateVapidKey old =
    case old of
        Evergreen.V138.LocalState.PrivateVapidKey p0 ->
            Evergreen.V144.LocalState.PrivateVapidKey p0


migrate_LoginForm_Msg : Evergreen.V138.LoginForm.Msg -> Evergreen.V144.LoginForm.Msg
migrate_LoginForm_Msg old =
    case old of
        Evergreen.V138.LoginForm.PressedSubmitEmail ->
            Evergreen.V144.LoginForm.PressedSubmitEmail

        Evergreen.V138.LoginForm.PressedCancelLogin ->
            Evergreen.V144.LoginForm.PressedCancelLogin

        Evergreen.V138.LoginForm.TypedLoginFormEmail p0 ->
            Evergreen.V144.LoginForm.TypedLoginFormEmail p0

        Evergreen.V138.LoginForm.TypedLoginCode p0 ->
            Evergreen.V144.LoginForm.TypedLoginCode p0

        Evergreen.V138.LoginForm.TypedTwoFactorCode p0 ->
            Evergreen.V144.LoginForm.TypedTwoFactorCode p0

        Evergreen.V138.LoginForm.TypedName p0 ->
            Evergreen.V144.LoginForm.TypedName p0

        Evergreen.V138.LoginForm.PressedSubmitUserData ->
            Evergreen.V144.LoginForm.PressedSubmitUserData


migrate_MessageInput_MentionUserDropdown : Evergreen.V138.MessageInput.MentionUserDropdown -> Evergreen.V144.MessageInput.MentionUserDropdown
migrate_MessageInput_MentionUserDropdown old =
    { charIndex = old.charIndex
    , dropdownIndex = old.dropdownIndex
    , inputElement =
        old.inputElement
            |> (\rec -> rec)
    , target = old.target |> migrate_MessageInput_MentionUserTarget
    }


migrate_MessageInput_MentionUserTarget : Evergreen.V138.MessageInput.MentionUserTarget -> Evergreen.V144.MessageInput.MentionUserTarget
migrate_MessageInput_MentionUserTarget old =
    case old of
        Evergreen.V138.MessageInput.NewMessage ->
            Evergreen.V144.MessageInput.NewMessage

        Evergreen.V138.MessageInput.EditMessage ->
            Evergreen.V144.MessageInput.EditMessage


migrate_MessageView_MessageViewMsg : Evergreen.V138.MessageView.MessageViewMsg -> Evergreen.V144.MessageView.MessageViewMsg
migrate_MessageView_MessageViewMsg old =
    case old of
        Evergreen.V138.MessageView.MessageView_PressedSpoiler p0 ->
            Evergreen.V144.MessageView.MessageView_PressedSpoiler p0

        Evergreen.V138.MessageView.MessageView_MouseEnteredMessage ->
            Evergreen.V144.MessageView.MessageView_MouseEnteredMessage

        Evergreen.V138.MessageView.MessageView_MouseExitedMessage ->
            Evergreen.V144.MessageView.MessageView_MouseExitedMessage

        Evergreen.V138.MessageView.MessageView_TouchStart p0 p1 p2 ->
            Evergreen.V144.MessageView.MessageView_TouchStart p0
                p1
                (p2 |> migrate_NonemptyDict_NonemptyDict identity migrate_Touch_Touch)

        Evergreen.V138.MessageView.MessageView_AltPressedMessage p0 p1 ->
            Evergreen.V144.MessageView.MessageView_AltPressedMessage p0
                (p1 |> migrate_Coord_Coord migrate_CssPixels_CssPixels)

        Evergreen.V138.MessageView.MessageView_PressedReactionEmoji_Remove p0 ->
            Evergreen.V144.MessageView.MessageView_PressedReactionEmoji_Remove (p0 |> migrate_Emoji_Emoji)

        Evergreen.V138.MessageView.MessageView_PressedReactionEmoji_Add p0 ->
            Evergreen.V144.MessageView.MessageView_PressedReactionEmoji_Add (p0 |> migrate_Emoji_Emoji)

        Evergreen.V138.MessageView.MessageView_PressedReplyLink ->
            Evergreen.V144.MessageView.MessageView_PressedReplyLink

        Evergreen.V138.MessageView.MessageViewMsg_PressedShowReactionEmojiSelector ->
            Evergreen.V144.MessageView.MessageViewMsg_PressedShowReactionEmojiSelector

        Evergreen.V138.MessageView.MessageViewMsg_PressedEditMessage ->
            Evergreen.V144.MessageView.MessageViewMsg_PressedEditMessage

        Evergreen.V138.MessageView.MessageViewMsg_PressedReply ->
            Evergreen.V144.MessageView.MessageViewMsg_PressedReply

        Evergreen.V138.MessageView.MessageViewMsg_PressedShowFullMenu p0 p1 ->
            Evergreen.V144.MessageView.MessageViewMsg_PressedShowFullMenu p0
                (p1 |> migrate_Coord_Coord migrate_CssPixels_CssPixels)

        Evergreen.V138.MessageView.MessageView_PressedViewThreadLink ->
            Evergreen.V144.MessageView.MessageView_PressedViewThreadLink


migrate_NonemptyDict_NonemptyDict : (id_old -> id_new) -> (a_old -> a_new) -> Evergreen.V138.NonemptyDict.NonemptyDict id_old a_old -> Evergreen.V144.NonemptyDict.NonemptyDict id_new a_new
migrate_NonemptyDict_NonemptyDict migrate_id migrate_a old =
    case old of
        Evergreen.V138.NonemptyDict.NonemptyDict p0 p1 p2 ->
            Evergreen.V144.NonemptyDict.NonemptyDict (p0 |> migrate_id)
                (p1 |> migrate_a)
                (p2 |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_id migrate_a) |> SeqDict.fromList)


migrate_Pages_Admin_Msg : Evergreen.V138.Pages.Admin.Msg -> Evergreen.V144.Pages.Admin.Msg
migrate_Pages_Admin_Msg old =
    case old of
        Evergreen.V138.Pages.Admin.PressedLogPage p0 ->
            Evergreen.V144.Pages.Admin.PressedLogPage p0

        Evergreen.V138.Pages.Admin.PressedCopyLogLink p0 ->
            Evergreen.V144.Pages.Admin.PressedCopyLogLink p0

        Evergreen.V138.Pages.Admin.PressedCollapseSection p0 ->
            Evergreen.V144.Pages.Admin.PressedCollapseSection (p0 |> migrate_User_AdminUiSection)

        Evergreen.V138.Pages.Admin.DoublePressedCollapseSection p0 ->
            Evergreen.V144.Pages.Admin.DoublePressedCollapseSection (p0 |> migrate_User_AdminUiSection)

        Evergreen.V138.Pages.Admin.PressedExpandSection p0 ->
            Evergreen.V144.Pages.Admin.PressedExpandSection (p0 |> migrate_User_AdminUiSection)

        Evergreen.V138.Pages.Admin.PressedEditCell p0 p1 ->
            Evergreen.V144.Pages.Admin.PressedEditCell (p0 |> migrate_Pages_Admin_UserTableId)
                (p1 |> migrate_Pages_Admin_UserColumn)

        Evergreen.V138.Pages.Admin.TypedEditCell p0 ->
            Evergreen.V144.Pages.Admin.TypedEditCell p0

        Evergreen.V138.Pages.Admin.EditCellLostFocus p0 p1 ->
            Evergreen.V144.Pages.Admin.EditCellLostFocus (p0 |> migrate_Pages_Admin_UserTableId)
                (p1 |> migrate_Pages_Admin_UserColumn)

        Evergreen.V138.Pages.Admin.FocusedOnEditCell ->
            Evergreen.V144.Pages.Admin.FocusedOnEditCell

        Evergreen.V138.Pages.Admin.EnterKeyInEditCell p0 p1 ->
            Evergreen.V144.Pages.Admin.EnterKeyInEditCell (p0 |> migrate_Pages_Admin_UserTableId)
                (p1 |> migrate_Pages_Admin_UserColumn)

        Evergreen.V138.Pages.Admin.PressedSaveUserChanges ->
            Evergreen.V144.Pages.Admin.PressedSaveUserChanges

        Evergreen.V138.Pages.Admin.TabKeyInEditCell p0 ->
            Evergreen.V144.Pages.Admin.TabKeyInEditCell p0

        Evergreen.V138.Pages.Admin.PressedResetUserChanges ->
            Evergreen.V144.Pages.Admin.PressedResetUserChanges

        Evergreen.V138.Pages.Admin.EscapeKeyInEditCell ->
            Evergreen.V144.Pages.Admin.EscapeKeyInEditCell

        Evergreen.V138.Pages.Admin.PressedAddUserRow ->
            Evergreen.V144.Pages.Admin.PressedAddUserRow

        Evergreen.V138.Pages.Admin.PressedDeleteUser p0 ->
            Evergreen.V144.Pages.Admin.PressedDeleteUser (p0 |> migrate_Pages_Admin_UserTableId)

        Evergreen.V138.Pages.Admin.PressedResetUser p0 ->
            Evergreen.V144.Pages.Admin.PressedResetUser (p0 |> migrate_Id_Id)

        Evergreen.V138.Pages.Admin.ScrolledToSection ->
            Evergreen.V144.Pages.Admin.ScrolledToSection

        Evergreen.V138.Pages.Admin.UserTableMsg p0 ->
            Evergreen.V144.Pages.Admin.UserTableMsg (p0 |> migrate_Table_Msg)

        Evergreen.V138.Pages.Admin.ToggledEmailNotifications p0 ->
            Evergreen.V144.Pages.Admin.ToggledEmailNotifications p0

        Evergreen.V138.Pages.Admin.ToggledSignupsEnabled p0 ->
            Evergreen.V144.Pages.Admin.ToggledSignupsEnabled p0

        Evergreen.V138.Pages.Admin.ToggleIsAdmin p0 p1 ->
            Evergreen.V144.Pages.Admin.ToggleIsAdmin (p0 |> migrate_Pages_Admin_UserTableId) p1

        Evergreen.V138.Pages.Admin.PressedDeleteDiscordDmChannel p0 ->
            Evergreen.V144.Pages.Admin.PressedDeleteDiscordDmChannel (p0 |> migrate_Discord_Id)

        Evergreen.V138.Pages.Admin.PressedDeleteDiscordGuild p0 ->
            Evergreen.V144.Pages.Admin.PressedDeleteDiscordGuild (p0 |> migrate_Discord_Id)

        Evergreen.V138.Pages.Admin.PressedExpandDiscordGuild p0 ->
            Evergreen.V144.Pages.Admin.PressedExpandDiscordGuild (p0 |> migrate_Discord_Id)

        Evergreen.V138.Pages.Admin.PressedExpandGuild p0 ->
            Evergreen.V144.Pages.Admin.PressedExpandGuild (p0 |> migrate_Id_Id)

        Evergreen.V138.Pages.Admin.PressedDeleteGuild p0 ->
            Evergreen.V144.Pages.Admin.PressedDeleteGuild (p0 |> migrate_Id_Id)

        Evergreen.V138.Pages.Admin.SlackClientSecretEditableMsg p0 ->
            Evergreen.V144.Pages.Admin.SlackClientSecretEditableMsg (p0 |> migrate_Editable_Msg (Maybe.map migrate_Slack_ClientSecret))

        Evergreen.V138.Pages.Admin.PublicVapidKeyEditableMsg p0 ->
            Evergreen.V144.Pages.Admin.PublicVapidKeyEditableMsg (p0 |> migrate_Editable_Msg identity)

        Evergreen.V138.Pages.Admin.PrivateVapidKeyEditableMsg p0 ->
            Evergreen.V144.Pages.Admin.PrivateVapidKeyEditableMsg (p0 |> migrate_Editable_Msg migrate_LocalState_PrivateVapidKey)

        Evergreen.V138.Pages.Admin.OpenRouterKeyEditableMsg p0 ->
            Evergreen.V144.Pages.Admin.OpenRouterKeyEditableMsg (p0 |> migrate_Editable_Msg identity)

        Evergreen.V138.Pages.Admin.PressedHomepageLink ->
            Evergreen.V144.Pages.Admin.PressedHomepageLink

        Evergreen.V138.Pages.Admin.PressedReloadDiscordChannel p0 p1 p2 ->
            Evergreen.V144.Pages.Admin.PressedReloadDiscordChannel (p0 |> migrate_Discord_Id)
                (p1 |> migrate_Discord_Id)
                (p2 |> migrate_Discord_Id)

        Evergreen.V138.Pages.Admin.PressedReloadDiscordDmChannel p0 p1 ->
            Evergreen.V144.Pages.Admin.PressedReloadDiscordDmChannel (p0 |> migrate_Discord_Id)
                (p1 |> migrate_Discord_Id)

        Evergreen.V138.Pages.Admin.PressedCopyText p0 ->
            Evergreen.V144.Pages.Admin.PressedCopyText p0

        Evergreen.V138.Pages.Admin.TypedInReadOnlyTextInput ->
            Evergreen.V144.Pages.Admin.TypedInReadOnlyTextInput

        Evergreen.V138.Pages.Admin.PressedExportBackend ->
            Evergreen.V144.Pages.Admin.PressedExportBackend

        Evergreen.V138.Pages.Admin.PressedExportSubsetBackend ->
            Evergreen.V144.Pages.Admin.PressedExportSubsetBackend

        Evergreen.V138.Pages.Admin.PressedImportBackend ->
            Evergreen.V144.Pages.Admin.PressedImportBackend

        Evergreen.V138.Pages.Admin.ImportBackendFileSelected p0 ->
            Evergreen.V144.Pages.Admin.ImportBackendFileSelected p0

        Evergreen.V138.Pages.Admin.GotImportBackendFileContent p0 ->
            Evergreen.V144.Pages.Admin.GotImportBackendFileContent p0


migrate_Pages_Admin_UserColumn : Evergreen.V138.Pages.Admin.UserColumn -> Evergreen.V144.Pages.Admin.UserColumn
migrate_Pages_Admin_UserColumn old =
    case old of
        Evergreen.V138.Pages.Admin.NameColumn ->
            Evergreen.V144.Pages.Admin.NameColumn

        Evergreen.V138.Pages.Admin.EmailAddressColumn ->
            Evergreen.V144.Pages.Admin.EmailAddressColumn


migrate_Pages_Admin_UserTableId : Evergreen.V138.Pages.Admin.UserTableId -> Evergreen.V144.Pages.Admin.UserTableId
migrate_Pages_Admin_UserTableId old =
    case old of
        Evergreen.V138.Pages.Admin.ExistingUserId p0 ->
            Evergreen.V144.Pages.Admin.ExistingUserId (p0 |> migrate_Id_Id)

        Evergreen.V138.Pages.Admin.NewUserId p0 ->
            Evergreen.V144.Pages.Admin.NewUserId p0


migrate_PersonName_PersonName : Evergreen.V138.PersonName.PersonName -> Evergreen.V144.PersonName.PersonName
migrate_PersonName_PersonName old =
    case old of
        Evergreen.V138.PersonName.PersonName p0 ->
            Evergreen.V144.PersonName.PersonName p0


migrate_Point2d_Point2d : (units_old -> units_new) -> (coordinates_old -> coordinates_new) -> Evergreen.V138.Point2d.Point2d units_old coordinates_old -> Evergreen.V144.Point2d.Point2d units_new coordinates_new
migrate_Point2d_Point2d migrate_units migrate_coordinates old =
    old |> migrate_Geometry_Types_Point2d


migrate_Ports_NotificationPermission : Evergreen.V138.Ports.NotificationPermission -> Evergreen.V144.Ports.NotificationPermission
migrate_Ports_NotificationPermission old =
    case old of
        Evergreen.V138.Ports.NotAsked ->
            Evergreen.V144.Ports.NotAsked

        Evergreen.V138.Ports.Denied ->
            Evergreen.V144.Ports.Denied

        Evergreen.V138.Ports.Granted ->
            Evergreen.V144.Ports.Granted

        Evergreen.V138.Ports.Unsupported ->
            Evergreen.V144.Ports.Unsupported


migrate_Ports_PwaStatus : Evergreen.V138.Ports.PwaStatus -> Evergreen.V144.Ports.PwaStatus
migrate_Ports_PwaStatus old =
    case old of
        Evergreen.V138.Ports.InstalledPwa ->
            Evergreen.V144.Ports.InstalledPwa

        Evergreen.V138.Ports.BrowserView ->
            Evergreen.V144.Ports.BrowserView


migrate_Quantity_Quantity : Quantity.Quantity number units -> Quantity.Quantity number units2
migrate_Quantity_Quantity old =
    Quantity.unwrap old |> Quantity.unsafe


migrate_RichText_Range : Evergreen.V138.RichText.Range -> Evergreen.V144.RichText.Range
migrate_RichText_Range old =
    old


migrate_Route_ChannelRoute : Evergreen.V138.Route.ChannelRoute -> Evergreen.V144.Route.ChannelRoute
migrate_Route_ChannelRoute old =
    case old of
        Evergreen.V138.Route.ChannelRoute p0 p1 ->
            Evergreen.V144.Route.ChannelRoute (p0 |> migrate_Id_Id)
                (p1 |> migrate_Route_ThreadRouteWithFriends)

        Evergreen.V138.Route.NewChannelRoute ->
            Evergreen.V144.Route.NewChannelRoute

        Evergreen.V138.Route.EditChannelRoute p0 ->
            Evergreen.V144.Route.EditChannelRoute (p0 |> migrate_Id_Id)

        Evergreen.V138.Route.GuildSettingsRoute ->
            Evergreen.V144.Route.GuildSettingsRoute

        Evergreen.V138.Route.JoinRoute p0 ->
            Evergreen.V144.Route.JoinRoute (p0 |> migrate_SecretId_SecretId)


migrate_Route_DiscordChannelRoute : Evergreen.V138.Route.DiscordChannelRoute -> Evergreen.V144.Route.DiscordChannelRoute
migrate_Route_DiscordChannelRoute old =
    case old of
        Evergreen.V138.Route.DiscordChannel_ChannelRoute p0 p1 ->
            Evergreen.V144.Route.DiscordChannel_ChannelRoute (p0 |> migrate_Discord_Id)
                (p1 |> migrate_Route_ThreadRouteWithFriends)

        Evergreen.V138.Route.DiscordChannel_NewChannelRoute ->
            Evergreen.V144.Route.DiscordChannel_NewChannelRoute

        Evergreen.V138.Route.DiscordChannel_EditChannelRoute p0 ->
            Evergreen.V144.Route.DiscordChannel_EditChannelRoute (p0 |> migrate_Discord_Id)

        Evergreen.V138.Route.DiscordChannel_GuildSettingsRoute ->
            Evergreen.V144.Route.DiscordChannel_GuildSettingsRoute


migrate_Route_DiscordDmRouteData : Evergreen.V138.Route.DiscordDmRouteData -> Evergreen.V144.Route.DiscordDmRouteData
migrate_Route_DiscordDmRouteData old =
    { currentDiscordUserId = old.currentDiscordUserId |> migrate_Discord_Id
    , channelId = old.channelId |> migrate_Discord_Id
    , viewingMessage = old.viewingMessage |> Maybe.map migrate_Id_Id
    , showMembersTab = old.showMembersTab |> migrate_Route_ShowMembersTab
    }


migrate_Route_DiscordGuildRouteData : Evergreen.V138.Route.DiscordGuildRouteData -> Evergreen.V144.Route.DiscordGuildRouteData
migrate_Route_DiscordGuildRouteData old =
    { currentDiscordUserId = old.currentDiscordUserId |> migrate_Discord_Id
    , guildId = old.guildId |> migrate_Discord_Id
    , channelRoute = old.channelRoute |> migrate_Route_DiscordChannelRoute
    }


migrate_Route_LinkDiscordError : Evergreen.V138.Route.LinkDiscordError -> Evergreen.V144.Route.LinkDiscordError
migrate_Route_LinkDiscordError old =
    case old of
        Evergreen.V138.Route.LinkDiscordExpired ->
            Evergreen.V144.Route.LinkDiscordExpired

        Evergreen.V138.Route.LinkDiscordServerError ->
            Evergreen.V144.Route.LinkDiscordServerError

        Evergreen.V138.Route.LinkDiscordInvalidData ->
            Evergreen.V144.Route.LinkDiscordInvalidData


migrate_Route_Route : Evergreen.V138.Route.Route -> Evergreen.V144.Route.Route
migrate_Route_Route old =
    case old of
        Evergreen.V138.Route.HomePageRoute ->
            Evergreen.V144.Route.HomePageRoute

        Evergreen.V138.Route.AdminRoute p0 ->
            Evergreen.V144.Route.AdminRoute p0

        Evergreen.V138.Route.GuildRoute p0 p1 ->
            Evergreen.V144.Route.GuildRoute (p0 |> migrate_Id_Id)
                (p1 |> migrate_Route_ChannelRoute)

        Evergreen.V138.Route.DiscordGuildRoute p0 ->
            Evergreen.V144.Route.DiscordGuildRoute (p0 |> migrate_Route_DiscordGuildRouteData)

        Evergreen.V138.Route.DmRoute p0 p1 ->
            Evergreen.V144.Route.DmRoute (p0 |> migrate_Id_Id)
                (p1 |> migrate_Route_ThreadRouteWithFriends)

        Evergreen.V138.Route.DiscordDmRoute p0 ->
            Evergreen.V144.Route.DiscordDmRoute (p0 |> migrate_Route_DiscordDmRouteData)

        Evergreen.V138.Route.AiChatRoute ->
            Evergreen.V144.Route.AiChatRoute

        Evergreen.V138.Route.SlackOAuthRedirect p0 ->
            Evergreen.V144.Route.SlackOAuthRedirect (p0 |> Result.map (Tuple.mapBoth migrate_Slack_OAuthCode migrate_SessionIdHash_SessionIdHash))

        Evergreen.V138.Route.TextEditorRoute ->
            Evergreen.V144.Route.TextEditorRoute

        Evergreen.V138.Route.LinkDiscord p0 ->
            Evergreen.V144.Route.LinkDiscord (p0 |> Result.mapError migrate_Route_LinkDiscordError >> Result.map migrate_Discord_UserAuth)


migrate_Route_ShowMembersTab : Evergreen.V138.Route.ShowMembersTab -> Evergreen.V144.Route.ShowMembersTab
migrate_Route_ShowMembersTab old =
    case old of
        Evergreen.V138.Route.ShowMembersTab ->
            Evergreen.V144.Route.ShowMembersTab

        Evergreen.V138.Route.HideMembersTab ->
            Evergreen.V144.Route.HideMembersTab


migrate_Route_ThreadRouteWithFriends : Evergreen.V138.Route.ThreadRouteWithFriends -> Evergreen.V144.Route.ThreadRouteWithFriends
migrate_Route_ThreadRouteWithFriends old =
    case old of
        Evergreen.V138.Route.NoThreadWithFriends p0 p1 ->
            Evergreen.V144.Route.NoThreadWithFriends (p0 |> Maybe.map migrate_Id_Id)
                (p1 |> migrate_Route_ShowMembersTab)

        Evergreen.V138.Route.ViewThreadWithFriends p0 p1 p2 ->
            Evergreen.V144.Route.ViewThreadWithFriends (p0 |> migrate_Id_Id)
                (p1 |> Maybe.map migrate_Id_Id)
                (p2 |> migrate_Route_ShowMembersTab)


migrate_SafeJson_SafeJson : Evergreen.V138.SafeJson.SafeJson -> Evergreen.V144.SafeJson.SafeJson
migrate_SafeJson_SafeJson old =
    case old of
        Evergreen.V138.SafeJson.JsonString p0 ->
            Evergreen.V144.SafeJson.JsonString p0

        Evergreen.V138.SafeJson.JsonNumber p0 ->
            Evergreen.V144.SafeJson.JsonNumber p0

        Evergreen.V138.SafeJson.JsonBool p0 ->
            Evergreen.V144.SafeJson.JsonBool p0

        Evergreen.V138.SafeJson.JsonObject p0 ->
            Evergreen.V144.SafeJson.JsonObject (p0 |> Dict.map (\k -> migrate_SafeJson_SafeJson))

        Evergreen.V138.SafeJson.JsonArray p0 ->
            Evergreen.V144.SafeJson.JsonArray (p0 |> List.map migrate_SafeJson_SafeJson)

        Evergreen.V138.SafeJson.JsonNull ->
            Evergreen.V144.SafeJson.JsonNull


migrate_SecretId_SecretId : Evergreen.V138.SecretId.SecretId a_old -> Evergreen.V144.SecretId.SecretId a_new
migrate_SecretId_SecretId old =
    case old of
        Evergreen.V138.SecretId.SecretId p0 ->
            Evergreen.V144.SecretId.SecretId p0


migrate_SessionIdHash_SessionIdHash : Evergreen.V138.SessionIdHash.SessionIdHash -> Evergreen.V144.SessionIdHash.SessionIdHash
migrate_SessionIdHash_SessionIdHash old =
    case old of
        Evergreen.V138.SessionIdHash.SessionIdHash p0 ->
            Evergreen.V144.SessionIdHash.SessionIdHash p0


migrate_Slack_ClientSecret : Evergreen.V138.Slack.ClientSecret -> Evergreen.V144.Slack.ClientSecret
migrate_Slack_ClientSecret old =
    case old of
        Evergreen.V138.Slack.ClientSecret p0 ->
            Evergreen.V144.Slack.ClientSecret p0


migrate_Slack_OAuthCode : Evergreen.V138.Slack.OAuthCode -> Evergreen.V144.Slack.OAuthCode
migrate_Slack_OAuthCode old =
    case old of
        Evergreen.V138.Slack.OAuthCode p0 ->
            Evergreen.V144.Slack.OAuthCode p0


migrate_Table_Msg : Evergreen.V138.Table.Msg -> Evergreen.V144.Table.Msg
migrate_Table_Msg old =
    case old of
        Evergreen.V138.Table.PressedSortBy p0 ->
            Evergreen.V144.Table.PressedSortBy p0

        Evergreen.V138.Table.PressedShowAll ->
            Evergreen.V144.Table.PressedShowAll


migrate_TextEditor_Msg : Evergreen.V138.TextEditor.Msg -> Evergreen.V144.TextEditor.Msg
migrate_TextEditor_Msg old =
    case old of
        Evergreen.V138.TextEditor.TypedText p0 ->
            Evergreen.V144.TextEditor.TypedText p0

        Evergreen.V138.TextEditor.MovedCursor p0 ->
            Evergreen.V144.TextEditor.MovedCursor (p0 |> migrate_RichText_Range)

        Evergreen.V138.TextEditor.PressedReset ->
            Evergreen.V144.TextEditor.PressedReset

        Evergreen.V138.TextEditor.UndoChange ->
            Evergreen.V144.TextEditor.UndoChange

        Evergreen.V138.TextEditor.RedoChange ->
            Evergreen.V144.TextEditor.RedoChange


migrate_Touch_ScreenCoordinate : Evergreen.V138.Touch.ScreenCoordinate -> Evergreen.V144.Touch.ScreenCoordinate
migrate_Touch_ScreenCoordinate old =
    case old of
        Evergreen.V138.Touch.ScreenCoordinate p0 ->
            Evergreen.V144.Touch.ScreenCoordinate p0


migrate_Touch_Touch : Evergreen.V138.Touch.Touch -> Evergreen.V144.Touch.Touch
migrate_Touch_Touch old =
    { client = old.client |> migrate_Point2d_Point2d migrate_CssPixels_CssPixels migrate_Touch_ScreenCoordinate
    , target = old.target
    }


migrate_TwoFactorAuthentication_Msg : Evergreen.V138.TwoFactorAuthentication.Msg -> Evergreen.V144.TwoFactorAuthentication.Msg
migrate_TwoFactorAuthentication_Msg old =
    case old of
        Evergreen.V138.TwoFactorAuthentication.PressedStart2FaSetup ->
            Evergreen.V144.TwoFactorAuthentication.PressedStart2FaSetup

        Evergreen.V138.TwoFactorAuthentication.PressedCopy p0 ->
            Evergreen.V144.TwoFactorAuthentication.PressedCopy p0

        Evergreen.V138.TwoFactorAuthentication.TypedTwoFactorCode p0 ->
            Evergreen.V144.TwoFactorAuthentication.TypedTwoFactorCode p0


migrate_Types_FrontendMsg : Evergreen.V138.Types.FrontendMsg -> Evergreen.V144.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V138.Types.UrlClicked p0 ->
            Evergreen.V144.Types.UrlClicked p0

        Evergreen.V138.Types.UrlChanged p0 ->
            Evergreen.V144.Types.UrlChanged p0

        Evergreen.V138.Types.GotTime p0 ->
            Evergreen.V144.Types.GotTime p0

        Evergreen.V138.Types.GotWindowSize p0 p1 ->
            Evergreen.V144.Types.GotWindowSize p0 p1

        Evergreen.V138.Types.GotTimezone p0 ->
            Evergreen.V144.Types.GotTimezone p0

        Evergreen.V138.Types.LoginFormMsg p0 ->
            Evergreen.V144.Types.LoginFormMsg (p0 |> migrate_LoginForm_Msg)

        Evergreen.V138.Types.PressedShowLogin ->
            Evergreen.V144.Types.PressedShowLogin

        Evergreen.V138.Types.AdminPageMsg p0 ->
            Evergreen.V144.Types.AdminPageMsg (p0 |> migrate_Pages_Admin_Msg)

        Evergreen.V138.Types.PressedLogOut ->
            Evergreen.V144.Types.PressedLogOut

        Evergreen.V138.Types.ElmUiMsg p0 ->
            Evergreen.V144.Types.ElmUiMsg (p0 |> migrate_Ui_Anim_Msg)

        Evergreen.V138.Types.ScrolledToLogSection ->
            Evergreen.V144.Types.ScrolledToLogSection

        Evergreen.V138.Types.PressedLink p0 ->
            Evergreen.V144.Types.PressedLink (p0 |> migrate_Route_Route)

        Evergreen.V138.Types.PressedTextInput ->
            Evergreen.V144.Types.PressedTextInput

        Evergreen.V138.Types.TypedMessage p0 p1 ->
            Evergreen.V144.Types.TypedMessage (p0 |> Tuple.mapBoth migrate_Id_AnyGuildOrDmId migrate_Id_ThreadRoute)
                p1

        Evergreen.V138.Types.PressedSendMessage p0 p1 ->
            Evergreen.V144.Types.PressedSendMessage (p0 |> migrate_Id_AnyGuildOrDmId)
                (p1 |> migrate_Id_ThreadRoute)

        Evergreen.V138.Types.PressedAttachFiles p0 ->
            Evergreen.V144.Types.PressedAttachFiles (p0 |> Tuple.mapBoth migrate_Id_AnyGuildOrDmId migrate_Id_ThreadRoute)

        Evergreen.V138.Types.SelectedFilesToAttach p0 p1 p2 ->
            Evergreen.V144.Types.SelectedFilesToAttach (p0 |> Tuple.mapBoth migrate_Id_AnyGuildOrDmId migrate_Id_ThreadRoute)
                p1
                p2

        Evergreen.V138.Types.NewChannelFormChanged p0 p1 ->
            Evergreen.V144.Types.NewChannelFormChanged (p0 |> migrate_Id_Id)
                (p1 |> migrate_Types_NewChannelForm)

        Evergreen.V138.Types.PressedSubmitNewChannel p0 p1 ->
            Evergreen.V144.Types.PressedSubmitNewChannel (p0 |> migrate_Id_Id)
                (p1 |> migrate_Types_NewChannelForm)

        Evergreen.V138.Types.MouseEnteredChannelName p0 p1 p2 ->
            Evergreen.V144.Types.MouseEnteredChannelName (p0 |> migrate_Id_Id)
                (p1 |> migrate_Id_Id)
                (p2 |> migrate_Id_ThreadRoute)

        Evergreen.V138.Types.MouseExitedChannelName p0 p1 p2 ->
            Evergreen.V144.Types.MouseExitedChannelName (p0 |> migrate_Id_Id)
                (p1 |> migrate_Id_Id)
                (p2 |> migrate_Id_ThreadRoute)

        Evergreen.V138.Types.MouseEnteredDiscordChannelName p0 p1 p2 ->
            Evergreen.V144.Types.MouseEnteredDiscordChannelName (p0 |> migrate_Discord_Id)
                (p1 |> migrate_Discord_Id)
                (p2 |> migrate_Id_ThreadRoute)

        Evergreen.V138.Types.MouseExitedDiscordChannelName p0 p1 p2 ->
            Evergreen.V144.Types.MouseExitedDiscordChannelName (p0 |> migrate_Discord_Id)
                (p1 |> migrate_Discord_Id)
                (p2 |> migrate_Id_ThreadRoute)

        Evergreen.V138.Types.EditChannelFormChanged p0 p1 p2 ->
            Evergreen.V144.Types.EditChannelFormChanged (p0 |> migrate_Id_Id)
                (p1 |> migrate_Id_Id)
                (p2 |> migrate_Types_NewChannelForm)

        Evergreen.V138.Types.PressedCancelEditChannelChanges p0 p1 ->
            Evergreen.V144.Types.PressedCancelEditChannelChanges (p0 |> migrate_Id_Id) (p1 |> migrate_Id_Id)

        Evergreen.V138.Types.PressedSubmitEditChannelChanges p0 p1 p2 ->
            Evergreen.V144.Types.PressedSubmitEditChannelChanges (p0 |> migrate_Id_Id)
                (p1 |> migrate_Id_Id)
                (p2 |> migrate_Types_NewChannelForm)

        Evergreen.V138.Types.PressedDeleteChannel p0 p1 ->
            Evergreen.V144.Types.PressedDeleteChannel (p0 |> migrate_Id_Id) (p1 |> migrate_Id_Id)

        Evergreen.V138.Types.PressedCreateInviteLink p0 ->
            Evergreen.V144.Types.PressedCreateInviteLink (p0 |> migrate_Id_Id)

        Evergreen.V138.Types.FrontendNoOp ->
            Evergreen.V144.Types.FrontendNoOp

        Evergreen.V138.Types.PressedCopyText p0 ->
            Evergreen.V144.Types.PressedCopyText p0

        Evergreen.V138.Types.PressedCreateGuild ->
            Evergreen.V144.Types.PressedCreateGuild

        Evergreen.V138.Types.NewGuildFormChanged p0 ->
            Evergreen.V144.Types.NewGuildFormChanged (p0 |> migrate_Types_NewGuildForm)

        Evergreen.V138.Types.PressedSubmitNewGuild p0 ->
            Evergreen.V144.Types.PressedSubmitNewGuild (p0 |> migrate_Types_NewGuildForm)

        Evergreen.V138.Types.PressedCancelNewGuild ->
            Evergreen.V144.Types.PressedCancelNewGuild

        Evergreen.V138.Types.DebouncedTyping ->
            Evergreen.V144.Types.DebouncedTyping

        Evergreen.V138.Types.GotPingUserPosition p0 ->
            Evergreen.V144.Types.GotPingUserPosition (p0 |> Result.map migrate_MessageInput_MentionUserDropdown)

        Evergreen.V138.Types.PressedPingUser p0 p1 ->
            Evergreen.V144.Types.PressedPingUser (p0 |> Tuple.mapBoth migrate_Id_AnyGuildOrDmId migrate_Id_ThreadRoute)
                p1

        Evergreen.V138.Types.SetFocus ->
            Evergreen.V144.Types.SetFocus

        Evergreen.V138.Types.RemoveFocus ->
            Evergreen.V144.Types.RemoveFocus

        Evergreen.V138.Types.PressedArrowInDropdown p0 p1 ->
            Evergreen.V144.Types.PressedArrowInDropdown (p0 |> migrate_Id_AnyGuildOrDmId) p1

        Evergreen.V138.Types.TextInputGotFocus p0 ->
            Evergreen.V144.Types.TextInputGotFocus p0

        Evergreen.V138.Types.TextInputLostFocus p0 ->
            Evergreen.V144.Types.TextInputLostFocus p0

        Evergreen.V138.Types.KeyDown p0 ->
            Evergreen.V144.Types.KeyDown p0

        Evergreen.V138.Types.MessageMenu_PressedShowReactionEmojiSelector p0 p1 p2 ->
            Evergreen.V144.Types.MessageMenu_PressedShowReactionEmojiSelector (p0 |> migrate_Id_AnyGuildOrDmId)
                (p1 |> migrate_Id_ThreadRouteWithMessage)
                (p2 |> migrate_Coord_Coord migrate_CssPixels_CssPixels)

        Evergreen.V138.Types.MessageMenu_PressedEditMessage p0 p1 ->
            Evergreen.V144.Types.MessageMenu_PressedEditMessage (p0 |> migrate_Id_AnyGuildOrDmId)
                (p1 |> migrate_Id_ThreadRouteWithMessage)

        Evergreen.V138.Types.PressedEmojiSelectorEmoji p0 ->
            Evergreen.V144.Types.PressedEmojiSelectorEmoji (p0 |> migrate_Emoji_Emoji)

        Evergreen.V138.Types.GotPingUserPositionForEditMessage p0 ->
            Evergreen.V144.Types.GotPingUserPositionForEditMessage (p0 |> Result.map migrate_MessageInput_MentionUserDropdown)

        Evergreen.V138.Types.TypedEditMessage p0 p1 ->
            Evergreen.V144.Types.TypedEditMessage (p0 |> Tuple.mapBoth migrate_Id_AnyGuildOrDmId migrate_Id_ThreadRoute)
                p1

        Evergreen.V138.Types.PressedSendEditMessage p0 ->
            Evergreen.V144.Types.PressedSendEditMessage (p0 |> Tuple.mapBoth migrate_Id_AnyGuildOrDmId migrate_Id_ThreadRoute)

        Evergreen.V138.Types.PressedArrowInDropdownForEditMessage p0 p1 ->
            Evergreen.V144.Types.PressedArrowInDropdownForEditMessage (p0 |> migrate_Id_AnyGuildOrDmId) p1

        Evergreen.V138.Types.PressedPingUserForEditMessage p0 p1 ->
            Evergreen.V144.Types.PressedPingUserForEditMessage (p0 |> Tuple.mapBoth migrate_Id_AnyGuildOrDmId migrate_Id_ThreadRoute)
                p1

        Evergreen.V138.Types.PressedArrowUpInEmptyInput p0 ->
            Evergreen.V144.Types.PressedArrowUpInEmptyInput (p0 |> Tuple.mapBoth migrate_Id_AnyGuildOrDmId migrate_Id_ThreadRoute)

        Evergreen.V138.Types.MessageMenu_PressedReply p0 ->
            Evergreen.V144.Types.MessageMenu_PressedReply (p0 |> migrate_Id_ThreadRouteWithMessage)

        Evergreen.V138.Types.MessageMenu_PressedOpenThread p0 ->
            Evergreen.V144.Types.MessageMenu_PressedOpenThread (p0 |> migrate_Id_Id)

        Evergreen.V138.Types.PressedCloseReplyTo p0 ->
            Evergreen.V144.Types.PressedCloseReplyTo (p0 |> Tuple.mapBoth migrate_Id_AnyGuildOrDmId migrate_Id_ThreadRoute)

        Evergreen.V138.Types.VisibilityChanged p0 ->
            Evergreen.V144.Types.VisibilityChanged p0

        Evergreen.V138.Types.CheckedNotificationPermission p0 ->
            Evergreen.V144.Types.CheckedNotificationPermission (p0 |> migrate_Ports_NotificationPermission)

        Evergreen.V138.Types.CheckedPwaStatus p0 ->
            Evergreen.V144.Types.CheckedPwaStatus (p0 |> migrate_Ports_PwaStatus)

        Evergreen.V138.Types.TouchStart p0 p1 p2 ->
            Evergreen.V144.Types.TouchStart (p0 |> Maybe.map (\( t1, t2, t3 ) -> ( t1 |> migrate_Id_AnyGuildOrDmId, t2 |> migrate_Id_ThreadRouteWithMessage, t3 )))
                p1
                (p2 |> migrate_NonemptyDict_NonemptyDict identity migrate_Touch_Touch)

        Evergreen.V138.Types.TouchMoved p0 p1 ->
            Evergreen.V144.Types.TouchMoved p0
                (p1 |> migrate_NonemptyDict_NonemptyDict identity migrate_Touch_Touch)

        Evergreen.V138.Types.TouchEnd p0 ->
            Evergreen.V144.Types.TouchEnd p0

        Evergreen.V138.Types.TouchCancel p0 ->
            Evergreen.V144.Types.TouchCancel p0

        Evergreen.V138.Types.ChannelSidebarAnimated p0 ->
            Evergreen.V144.Types.ChannelSidebarAnimated p0

        Evergreen.V138.Types.MessageMenuAnimated p0 ->
            Evergreen.V144.Types.MessageMenuAnimated p0

        Evergreen.V138.Types.SetScrollToBottom ->
            Evergreen.V144.Types.SetScrollToBottom

        Evergreen.V138.Types.PressedChannelHeaderBackButton ->
            Evergreen.V144.Types.PressedChannelHeaderBackButton

        Evergreen.V138.Types.PressedShowMembers ->
            Evergreen.V144.Types.PressedShowMembers

        Evergreen.V138.Types.UserScrolled p0 p1 p2 ->
            Evergreen.V144.Types.UserScrolled (p0 |> migrate_Id_AnyGuildOrDmId)
                (p1 |> migrate_Id_ThreadRoute)
                (p2 |> migrate_Types_ScrollPosition)

        Evergreen.V138.Types.PressedBody ->
            Evergreen.V144.Types.PressedBody

        Evergreen.V138.Types.PressedReactionEmojiContainer ->
            Evergreen.V144.Types.PressedReactionEmojiContainer

        Evergreen.V138.Types.MessageMenu_PressedDeleteMessage p0 p1 ->
            Evergreen.V144.Types.MessageMenu_PressedDeleteMessage (p0 |> migrate_Id_AnyGuildOrDmId)
                (p1 |> migrate_Id_ThreadRouteWithMessage)

        Evergreen.V138.Types.ScrolledToMessage ->
            Evergreen.V144.Types.ScrolledToMessage

        Evergreen.V138.Types.MessageMenu_PressedClose ->
            Evergreen.V144.Types.MessageMenu_PressedClose

        Evergreen.V138.Types.MessageMenu_PressedContainer ->
            Evergreen.V144.Types.MessageMenu_PressedContainer

        Evergreen.V138.Types.PressedCancelMessageEdit p0 ->
            Evergreen.V144.Types.PressedCancelMessageEdit (p0 |> Tuple.mapBoth migrate_Id_AnyGuildOrDmId migrate_Id_ThreadRoute)

        Evergreen.V138.Types.PressedPingDropdownContainer ->
            Evergreen.V144.Types.PressedPingDropdownContainer

        Evergreen.V138.Types.PressedEditMessagePingDropdownContainer ->
            Evergreen.V144.Types.PressedEditMessagePingDropdownContainer

        Evergreen.V138.Types.CheckMessageAltPress p0 p1 p2 p3 ->
            Evergreen.V144.Types.CheckMessageAltPress p0
                (p1 |> migrate_Id_AnyGuildOrDmId)
                (p2 |> migrate_Id_ThreadRouteWithMessage)
                p3

        Evergreen.V138.Types.PressedShowUserOption ->
            Evergreen.V144.Types.PressedShowUserOption

        Evergreen.V138.Types.PressedCloseUserOptions ->
            Evergreen.V144.Types.PressedCloseUserOptions

        Evergreen.V138.Types.TwoFactorMsg p0 ->
            Evergreen.V144.Types.TwoFactorMsg (p0 |> migrate_TwoFactorAuthentication_Msg)

        Evergreen.V138.Types.AiChatMsg p0 ->
            Evergreen.V144.Types.AiChatMsg (p0 |> migrate_AiChat_Msg)

        Evergreen.V138.Types.UserNameEditableMsg p0 ->
            Evergreen.V144.Types.UserNameEditableMsg (p0 |> migrate_Editable_Msg migrate_PersonName_PersonName)

        Evergreen.V138.Types.ProfilePictureEditorMsg p0 ->
            Evergreen.V144.Types.ProfilePictureEditorMsg (p0 |> migrate_ImageEditor_Msg)

        Evergreen.V138.Types.OneFrameAfterDragEnd ->
            Evergreen.V144.Types.OneFrameAfterDragEnd

        Evergreen.V138.Types.GotFileHashName p0 p1 p2 ->
            Evergreen.V144.Types.GotFileHashName (p0 |> Tuple.mapBoth migrate_Id_AnyGuildOrDmId migrate_Id_ThreadRoute)
                (p1 |> migrate_Id_Id)
                (p2 |> Result.map migrate_FileStatus_UploadResponse)

        Evergreen.V138.Types.PressedDeleteAttachedFile p0 p1 ->
            Evergreen.V144.Types.PressedDeleteAttachedFile (p0 |> Tuple.mapBoth migrate_Id_AnyGuildOrDmId migrate_Id_ThreadRoute)
                (p1 |> migrate_Id_Id)

        Evergreen.V138.Types.PressedViewAttachedFileInfo p0 p1 ->
            Evergreen.V144.Types.PressedViewAttachedFileInfo (p0 |> Tuple.mapBoth migrate_Id_AnyGuildOrDmId migrate_Id_ThreadRoute)
                (p1 |> migrate_Id_Id)

        Evergreen.V138.Types.EditMessage_PressedDeleteAttachedFile p0 p1 ->
            Evergreen.V144.Types.EditMessage_PressedDeleteAttachedFile (p0 |> Tuple.mapBoth migrate_Id_AnyGuildOrDmId migrate_Id_ThreadRoute)
                (p1 |> migrate_Id_Id)

        Evergreen.V138.Types.EditMessage_PressedViewAttachedFileInfo p0 p1 ->
            Evergreen.V144.Types.EditMessage_PressedViewAttachedFileInfo (p0 |> Tuple.mapBoth migrate_Id_AnyGuildOrDmId migrate_Id_ThreadRoute)
                (p1 |> migrate_Id_Id)

        Evergreen.V138.Types.EditMessage_PressedAttachFiles p0 ->
            Evergreen.V144.Types.EditMessage_PressedAttachFiles (p0 |> Tuple.mapBoth migrate_Id_AnyGuildOrDmId migrate_Id_ThreadRoute)

        Evergreen.V138.Types.EditMessage_SelectedFilesToAttach p0 p1 p2 ->
            Evergreen.V144.Types.EditMessage_SelectedFilesToAttach (p0 |> Tuple.mapBoth migrate_Id_AnyGuildOrDmId migrate_Id_ThreadRoute)
                p1
                p2

        Evergreen.V138.Types.EditMessage_GotFileHashName p0 p1 p2 p3 ->
            Evergreen.V144.Types.EditMessage_GotFileHashName (p0 |> Tuple.mapBoth migrate_Id_AnyGuildOrDmId migrate_Id_ThreadRoute)
                (p1 |> migrate_Id_Id)
                (p2 |> migrate_Id_Id)
                (p3 |> Result.map migrate_FileStatus_UploadResponse)

        Evergreen.V138.Types.EditMessage_PastedFiles p0 p1 ->
            Evergreen.V144.Types.EditMessage_PastedFiles (p0 |> Tuple.mapBoth migrate_Id_AnyGuildOrDmId migrate_Id_ThreadRoute)
                p1

        Evergreen.V138.Types.PastedFiles p0 p1 ->
            Evergreen.V144.Types.PastedFiles (p0 |> Tuple.mapBoth migrate_Id_AnyGuildOrDmId migrate_Id_ThreadRoute)
                p1

        Evergreen.V138.Types.FileUploadProgress p0 p1 p2 ->
            Evergreen.V144.Types.FileUploadProgress (p0 |> Tuple.mapBoth migrate_Id_AnyGuildOrDmId migrate_Id_ThreadRoute)
                (p1 |> migrate_Id_Id)
                p2

        Evergreen.V138.Types.MessageViewMsg p0 p1 p2 ->
            Evergreen.V144.Types.MessageViewMsg (p0 |> migrate_Id_AnyGuildOrDmId)
                (p1 |> migrate_Id_ThreadRouteWithMessage)
                (p2 |> migrate_MessageView_MessageViewMsg)

        Evergreen.V138.Types.GotRegisterPushSubscription p0 ->
            Evergreen.V144.Types.GotRegisterPushSubscription p0

        Evergreen.V138.Types.SelectedNotificationMode p0 ->
            Evergreen.V144.Types.SelectedNotificationMode (p0 |> migrate_UserSession_NotificationMode)

        Evergreen.V138.Types.PressedGuildNotificationLevel p0 p1 ->
            Evergreen.V144.Types.PressedGuildNotificationLevel (p0 |> migrate_Id_Id)
                (p1 |> migrate_User_NotificationLevel)

        Evergreen.V138.Types.GotScrollbarWidth p0 ->
            Evergreen.V144.Types.GotScrollbarWidth p0

        Evergreen.V138.Types.PressedCloseImageInfo ->
            Evergreen.V144.Types.PressedCloseImageInfo

        Evergreen.V138.Types.PressedMemberListBack ->
            Evergreen.V144.Types.PressedMemberListBack

        Evergreen.V138.Types.GotUserAgent p0 ->
            Evergreen.V144.Types.GotUserAgent (p0 |> migrate_UserAgent_UserAgent)

        Evergreen.V138.Types.PageHasFocusChanged p0 ->
            Evergreen.V144.Types.PageHasFocusChanged p0

        Evergreen.V138.Types.GotServiceWorkerMessage p0 ->
            Evergreen.V144.Types.GotServiceWorkerMessage p0

        Evergreen.V138.Types.VisualViewportResized p0 ->
            Evergreen.V144.Types.VisualViewportResized p0

        Evergreen.V138.Types.TextEditorMsg p0 ->
            Evergreen.V144.Types.TextEditorMsg (p0 |> migrate_TextEditor_Msg)

        Evergreen.V138.Types.PressedLinkDiscordUser ->
            Evergreen.V144.Types.PressedLinkDiscordUser

        Evergreen.V138.Types.PressedReloadDiscordUser p0 ->
            Evergreen.V144.Types.PressedReloadDiscordUser (p0 |> migrate_Discord_Id)

        Evergreen.V138.Types.PressedUnlinkDiscordUser p0 ->
            Evergreen.V144.Types.PressedUnlinkDiscordUser (p0 |> migrate_Discord_Id)

        Evergreen.V138.Types.PressedDiscordGuildMemberLabel p0 ->
            Evergreen.V144.Types.PressedDiscordGuildMemberLabel
                { currentUserId = p0.currentUserId |> migrate_Discord_Id
                , otherUserId = p0.otherUserId |> migrate_Discord_Id
                }

        Evergreen.V138.Types.PressedDiscordFriendLabel p0 ->
            Evergreen.V144.Types.TypedDiscordLinkBookmarklet

        Evergreen.V138.Types.TypedDiscordLinkBookmarklet ->
            Evergreen.V144.Types.TypedDiscordLinkBookmarklet

        Evergreen.V138.Types.GotVersionNumber p0 ->
            Evergreen.V144.Types.GotVersionNumber p0


migrate_Types_NewChannelForm : Evergreen.V138.Types.NewChannelForm -> Evergreen.V144.Types.NewChannelForm
migrate_Types_NewChannelForm old =
    old


migrate_Types_NewGuildForm : Evergreen.V138.Types.NewGuildForm -> Evergreen.V144.Types.NewGuildForm
migrate_Types_NewGuildForm old =
    old


migrate_Types_ScrollPosition : Evergreen.V138.Types.ScrollPosition -> Evergreen.V144.Types.ScrollPosition
migrate_Types_ScrollPosition old =
    case old of
        Evergreen.V138.Types.ScrolledToBottom ->
            Evergreen.V144.Types.ScrolledToBottom

        Evergreen.V138.Types.ScrolledToTop ->
            Evergreen.V144.Types.ScrolledToTop

        Evergreen.V138.Types.ScrolledToMiddle ->
            Evergreen.V144.Types.ScrolledToMiddle


migrate_Ui_Anim_Msg : Evergreen.V138.Ui.Anim.Msg -> Evergreen.V144.Ui.Anim.Msg
migrate_Ui_Anim_Msg old =
    old |> migrate_Internal_Model2_Msg


migrate_UserAgent_Browser : Evergreen.V138.UserAgent.Browser -> Evergreen.V144.UserAgent.Browser
migrate_UserAgent_Browser old =
    case old of
        Evergreen.V138.UserAgent.Chrome ->
            Evergreen.V144.UserAgent.Chrome

        Evergreen.V138.UserAgent.Firefox ->
            Evergreen.V144.UserAgent.Firefox

        Evergreen.V138.UserAgent.Safari ->
            Evergreen.V144.UserAgent.Safari

        Evergreen.V138.UserAgent.Edge ->
            Evergreen.V144.UserAgent.Edge

        Evergreen.V138.UserAgent.Opera ->
            Evergreen.V144.UserAgent.Opera

        Evergreen.V138.UserAgent.UnknownBrowser ->
            Evergreen.V144.UserAgent.UnknownBrowser


migrate_UserAgent_Device : Evergreen.V138.UserAgent.Device -> Evergreen.V144.UserAgent.Device
migrate_UserAgent_Device old =
    case old of
        Evergreen.V138.UserAgent.Desktop ->
            Evergreen.V144.UserAgent.Desktop

        Evergreen.V138.UserAgent.Mobile ->
            Evergreen.V144.UserAgent.Mobile

        Evergreen.V138.UserAgent.Tablet ->
            Evergreen.V144.UserAgent.Tablet


migrate_UserAgent_UserAgent : Evergreen.V138.UserAgent.UserAgent -> Evergreen.V144.UserAgent.UserAgent
migrate_UserAgent_UserAgent old =
    { browser = old.browser |> migrate_UserAgent_Browser
    , device = old.device |> migrate_UserAgent_Device
    }


migrate_UserSession_NotificationMode : Evergreen.V138.UserSession.NotificationMode -> Evergreen.V144.UserSession.NotificationMode
migrate_UserSession_NotificationMode old =
    case old of
        Evergreen.V138.UserSession.NoNotifications ->
            Evergreen.V144.UserSession.NoNotifications

        Evergreen.V138.UserSession.NotifyWhenRunning ->
            Evergreen.V144.UserSession.NotifyWhenRunning

        Evergreen.V138.UserSession.PushNotifications ->
            Evergreen.V144.UserSession.PushNotifications


migrate_User_AdminUiSection : Evergreen.V138.User.AdminUiSection -> Evergreen.V144.User.AdminUiSection
migrate_User_AdminUiSection old =
    case old of
        Evergreen.V138.User.UsersSection ->
            Evergreen.V144.User.UsersSection

        Evergreen.V138.User.LogSection ->
            Evergreen.V144.User.LogSection

        Evergreen.V138.User.DiscordDmChannelsSection ->
            Evergreen.V144.User.DiscordDmChannelsSection

        Evergreen.V138.User.DiscordUsersSection ->
            Evergreen.V144.User.DiscordUsersSection

        Evergreen.V138.User.DiscordGuildsSection ->
            Evergreen.V144.User.DiscordGuildsSection

        Evergreen.V138.User.GuildsSection ->
            Evergreen.V144.User.GuildsSection

        Evergreen.V138.User.ApiKeysSection ->
            Evergreen.V144.User.ApiKeysSection

        Evergreen.V138.User.ExportSection ->
            Evergreen.V144.User.ExportSection


migrate_User_NotificationLevel : Evergreen.V138.User.NotificationLevel -> Evergreen.V144.User.NotificationLevel
migrate_User_NotificationLevel old =
    case old of
        Evergreen.V138.User.NotifyOnEveryMessage ->
            Evergreen.V144.User.NotifyOnEveryMessage

        Evergreen.V138.User.NotifyOnMention ->
            Evergreen.V144.User.NotifyOnMention
