module Evergreen.Migrate.V17 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Array
import Dict
import Evergreen.V16.AiChat
import Evergreen.V16.ChannelName
import Evergreen.V16.Coord
import Evergreen.V16.CssPixels
import Evergreen.V16.Discord.Id
import Evergreen.V16.DmChannel
import Evergreen.V16.Editable
import Evergreen.V16.EmailAddress
import Evergreen.V16.Emoji
import Evergreen.V16.Geometry.Types
import Evergreen.V16.GuildName
import Evergreen.V16.Id
import Evergreen.V16.Image
import Evergreen.V16.Internal.Model2
import Evergreen.V16.Internal.Teleport
import Evergreen.V16.Local
import Evergreen.V16.LocalState
import Evergreen.V16.Log
import Evergreen.V16.LoginForm
import Evergreen.V16.Message
import Evergreen.V16.MessageInput
import Evergreen.V16.NonemptyDict
import Evergreen.V16.NonemptySet
import Evergreen.V16.OneToOne
import Evergreen.V16.Pages.Admin
import Evergreen.V16.Pagination
import Evergreen.V16.PersonName
import Evergreen.V16.Point2d
import Evergreen.V16.Ports
import Evergreen.V16.Postmark
import Evergreen.V16.RichText
import Evergreen.V16.Route
import Evergreen.V16.SecretId
import Evergreen.V16.Table
import Evergreen.V16.Touch
import Evergreen.V16.TwoFactorAuthentication
import Evergreen.V16.Types
import Evergreen.V16.Ui.Anim
import Evergreen.V16.User
import Evergreen.V17.AiChat
import Evergreen.V17.ChannelName
import Evergreen.V17.Coord
import Evergreen.V17.CssPixels
import Evergreen.V17.Discord.Id
import Evergreen.V17.DmChannel
import Evergreen.V17.Editable
import Evergreen.V17.EmailAddress
import Evergreen.V17.Emoji
import Evergreen.V17.Geometry.Types
import Evergreen.V17.GuildName
import Evergreen.V17.Id
import Evergreen.V17.Image
import Evergreen.V17.Internal.Model2
import Evergreen.V17.Internal.Teleport
import Evergreen.V17.Local
import Evergreen.V17.LocalState
import Evergreen.V17.Log
import Evergreen.V17.LoginForm
import Evergreen.V17.Message
import Evergreen.V17.MessageInput
import Evergreen.V17.NonemptyDict
import Evergreen.V17.NonemptySet
import Evergreen.V17.OneToOne
import Evergreen.V17.Pages.Admin
import Evergreen.V17.Pagination
import Evergreen.V17.PersonName
import Evergreen.V17.Point2d
import Evergreen.V17.Ports
import Evergreen.V17.Postmark
import Evergreen.V17.RichText
import Evergreen.V17.Route
import Evergreen.V17.SecretId
import Evergreen.V17.Table
import Evergreen.V17.Touch
import Evergreen.V17.TwoFactorAuthentication
import Evergreen.V17.Types
import Evergreen.V17.Ui.Anim
import Evergreen.V17.User
import Lamdera.Migrations exposing (..)
import List
import List.Nonempty
import Maybe
import Quantity
import SeqDict
import SeqSet


frontendModel : Evergreen.V16.Types.FrontendModel -> ModelMigration Evergreen.V17.Types.FrontendModel Evergreen.V17.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V16.Types.BackendModel -> ModelMigration Evergreen.V17.Types.BackendModel Evergreen.V17.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V16.Types.FrontendMsg -> MsgMigration Evergreen.V17.Types.FrontendMsg Evergreen.V17.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V16.Types.ToBackend -> MsgMigration Evergreen.V17.Types.ToBackend Evergreen.V17.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V16.Types.BackendMsg -> MsgMigration Evergreen.V17.Types.BackendMsg Evergreen.V17.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V16.Types.ToFrontend -> MsgMigration Evergreen.V17.Types.ToFrontend Evergreen.V17.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_AiChat_AiModelsStatus : Evergreen.V16.AiChat.AiModelsStatus -> Evergreen.V17.AiChat.AiModelsStatus
migrate_AiChat_AiModelsStatus old =
    case old of
        Evergreen.V16.AiChat.LoadingAiModels ->
            Evergreen.V17.AiChat.LoadingAiModels

        Evergreen.V16.AiChat.LoadedAiModels p0 ->
            Evergreen.V17.AiChat.LoadedAiModels p0

        Evergreen.V16.AiChat.LoadingFailed p0 ->
            Evergreen.V17.AiChat.LoadingFailed p0


migrate_AiChat_FrontendModel : Evergreen.V16.AiChat.FrontendModel -> Evergreen.V17.AiChat.FrontendModel
migrate_AiChat_FrontendModel old =
    { message = old.message
    , chatHistory = old.chatHistory
    , pendingResponses = old.pendingResponses |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_AiChat_ResponseId migrate_AiChat_PendingResponse) |> SeqDict.fromList
    , responseCounter = old.responseCounter
    , showOptions = old.showOptions
    , selectedModel = old.selectedModel
    , userPrefix = old.userPrefix
    , botPrefix = old.botPrefix
    , debounceCounter = old.debounceCounter
    , sendMessageWith = old.sendMessageWith |> migrate_AiChat_SendMessageWith
    , aiModels = old.aiModels |> migrate_AiChat_AiModelsStatus
    }


migrate_AiChat_Msg : Evergreen.V16.AiChat.Msg -> Evergreen.V17.AiChat.Msg
migrate_AiChat_Msg old =
    case old of
        Evergreen.V16.AiChat.TypedMessage p0 ->
            Evergreen.V17.AiChat.TypedMessage p0

        Evergreen.V16.AiChat.PressedSend ->
            Evergreen.V17.AiChat.PressedSend

        Evergreen.V16.AiChat.TypedChatHistory p0 ->
            Evergreen.V17.AiChat.TypedChatHistory p0

        Evergreen.V16.AiChat.PressedKeep p0 ->
            Evergreen.V17.AiChat.PressedKeep (p0 |> migrate_AiChat_ResponseId)

        Evergreen.V16.AiChat.PressedDelete p0 ->
            Evergreen.V17.AiChat.PressedDelete (p0 |> migrate_AiChat_ResponseId)

        Evergreen.V16.AiChat.PressedRetry p0 ->
            Evergreen.V17.AiChat.PressedRetry (p0 |> migrate_AiChat_ResponseId)

        Evergreen.V16.AiChat.PressedChatHistoryContainer ->
            Evergreen.V17.AiChat.PressedChatHistoryContainer

        Evergreen.V16.AiChat.PressedClearChatHistory ->
            Evergreen.V17.AiChat.PressedClearChatHistory

        Evergreen.V16.AiChat.PressedOptionsButton ->
            Evergreen.V17.AiChat.PressedOptionsButton

        Evergreen.V16.AiChat.SelectedAiModel p0 ->
            Evergreen.V17.AiChat.SelectedAiModel p0

        Evergreen.V16.AiChat.SelectedSendMessageWith p0 ->
            Evergreen.V17.AiChat.SelectedSendMessageWith (p0 |> migrate_AiChat_SendMessageWith)

        Evergreen.V16.AiChat.TypedUserPrefix p0 ->
            Evergreen.V17.AiChat.TypedUserPrefix p0

        Evergreen.V16.AiChat.TypedBotPrefix p0 ->
            Evergreen.V17.AiChat.TypedBotPrefix p0

        Evergreen.V16.AiChat.CheckDebounce p0 ->
            Evergreen.V17.AiChat.CheckDebounce p0

        Evergreen.V16.AiChat.GotLocalStorage p0 ->
            Evergreen.V17.AiChat.GotLocalStorage p0

        Evergreen.V16.AiChat.EditedResponse p0 p1 ->
            Evergreen.V17.AiChat.EditedResponse (p0 |> migrate_AiChat_ResponseId) p1

        Evergreen.V16.AiChat.NoOp ->
            Evergreen.V17.AiChat.NoOp

        Evergreen.V16.AiChat.GotAiModels p0 ->
            Evergreen.V17.AiChat.GotAiModels p0


migrate_AiChat_PendingResponse : Evergreen.V16.AiChat.PendingResponse -> Evergreen.V17.AiChat.PendingResponse
migrate_AiChat_PendingResponse old =
    case old of
        Evergreen.V16.AiChat.Pending ->
            Evergreen.V17.AiChat.Pending

        Evergreen.V16.AiChat.GotResponse p0 ->
            Evergreen.V17.AiChat.GotResponse p0

        Evergreen.V16.AiChat.GotError p0 ->
            Evergreen.V17.AiChat.GotError p0


migrate_AiChat_ResponseId : Evergreen.V16.AiChat.ResponseId -> Evergreen.V17.AiChat.ResponseId
migrate_AiChat_ResponseId old =
    case old of
        Evergreen.V16.AiChat.RespondId p0 ->
            Evergreen.V17.AiChat.RespondId p0


migrate_AiChat_SendMessageWith : Evergreen.V16.AiChat.SendMessageWith -> Evergreen.V17.AiChat.SendMessageWith
migrate_AiChat_SendMessageWith old =
    case old of
        Evergreen.V16.AiChat.SendWithEnter ->
            Evergreen.V17.AiChat.SendWithEnter

        Evergreen.V16.AiChat.SendWithShiftEnter ->
            Evergreen.V17.AiChat.SendWithShiftEnter


migrate_ChannelName_ChannelName : Evergreen.V16.ChannelName.ChannelName -> Evergreen.V17.ChannelName.ChannelName
migrate_ChannelName_ChannelName old =
    case old of
        Evergreen.V16.ChannelName.ChannelName p0 ->
            Evergreen.V17.ChannelName.ChannelName p0


migrate_Coord_Coord : (units_old -> units_new) -> Evergreen.V16.Coord.Coord units_old -> Evergreen.V17.Coord.Coord units_new
migrate_Coord_Coord migrate_units old =
    old |> Tuple.mapBoth migrate_Quantity_Quantity migrate_Quantity_Quantity


migrate_CssPixels_CssPixels : Evergreen.V16.CssPixels.CssPixels -> Evergreen.V17.CssPixels.CssPixels
migrate_CssPixels_CssPixels old =
    case old of
        Evergreen.V16.CssPixels.CssPixels p0 ->
            Evergreen.V17.CssPixels.CssPixels p0


migrate_Discord_Id_Id : Evergreen.V16.Discord.Id.Id idType_old -> Evergreen.V17.Discord.Id.Id idType_new
migrate_Discord_Id_Id old =
    case old of
        Evergreen.V16.Discord.Id.Id p0 ->
            Evergreen.V17.Discord.Id.Id p0


migrate_DmChannel_DmChannel : Evergreen.V16.DmChannel.DmChannel -> Evergreen.V17.DmChannel.DmChannel
migrate_DmChannel_DmChannel old =
    { messages = old.messages |> Array.map migrate_Message_Message
    , lastTypedAt = old.lastTypedAt |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Id_Id migrate_DmChannel_LastTypedAt) |> SeqDict.fromList
    , linkedMessageIds = old.linkedMessageIds |> migrate_OneToOne_OneToOne migrate_Discord_Id_Id identity
    }


migrate_DmChannel_LastTypedAt : Evergreen.V16.DmChannel.LastTypedAt -> Evergreen.V17.DmChannel.LastTypedAt
migrate_DmChannel_LastTypedAt old =
    old


migrate_Editable_Editing : Evergreen.V16.Editable.Editing -> Evergreen.V17.Editable.Editing
migrate_Editable_Editing old =
    case old of
        Evergreen.V16.Editable.NotEditing ->
            Evergreen.V17.Editable.NotEditing

        Evergreen.V16.Editable.Editing p0 ->
            Evergreen.V17.Editable.Editing p0


migrate_Editable_Model : Evergreen.V16.Editable.Model -> Evergreen.V17.Editable.Model
migrate_Editable_Model old =
    { editing = old.editing |> migrate_Editable_Editing
    , pressedSubmit = old.pressedSubmit
    }


migrate_Editable_Msg : (value_old -> value_new) -> Evergreen.V16.Editable.Msg value_old -> Evergreen.V17.Editable.Msg value_new
migrate_Editable_Msg migrate_value old =
    case old of
        Evergreen.V16.Editable.Edit p0 ->
            Evergreen.V17.Editable.Edit (p0 |> migrate_Editable_Model)

        Evergreen.V16.Editable.PressedAcceptEdit p0 ->
            Evergreen.V17.Editable.PressedAcceptEdit (p0 |> migrate_value)


migrate_EmailAddress_EmailAddress : Evergreen.V16.EmailAddress.EmailAddress -> Evergreen.V17.EmailAddress.EmailAddress
migrate_EmailAddress_EmailAddress old =
    case old of
        Evergreen.V16.EmailAddress.EmailAddress p0 ->
            Evergreen.V17.EmailAddress.EmailAddress p0


migrate_Emoji_Emoji : Evergreen.V16.Emoji.Emoji -> Evergreen.V17.Emoji.Emoji
migrate_Emoji_Emoji old =
    case old of
        Evergreen.V16.Emoji.UnicodeEmoji p0 ->
            Evergreen.V17.Emoji.UnicodeEmoji p0


migrate_Geometry_Types_Point2d : Evergreen.V16.Geometry.Types.Point2d units_old coordinates_old -> Evergreen.V17.Geometry.Types.Point2d units_new coordinates_new
migrate_Geometry_Types_Point2d old =
    case old of
        Evergreen.V16.Geometry.Types.Point2d p0 ->
            Evergreen.V17.Geometry.Types.Point2d p0


migrate_GuildName_GuildName : Evergreen.V16.GuildName.GuildName -> Evergreen.V17.GuildName.GuildName
migrate_GuildName_GuildName old =
    case old of
        Evergreen.V16.GuildName.GuildName p0 ->
            Evergreen.V17.GuildName.GuildName p0


migrate_Id_Id : Evergreen.V16.Id.Id a_old -> Evergreen.V17.Id.Id a_new
migrate_Id_Id old =
    case old of
        Evergreen.V16.Id.Id p0 ->
            Evergreen.V17.Id.Id p0


migrate_Image_Image : Evergreen.V16.Image.Image -> Evergreen.V17.Image.Image
migrate_Image_Image old =
    case old of
        Evergreen.V16.Image.Image p0 ->
            Evergreen.V17.Image.Image p0


migrate_Internal_Model2_Msg : Evergreen.V16.Internal.Model2.Msg -> Evergreen.V17.Internal.Model2.Msg
migrate_Internal_Model2_Msg old =
    case old of
        Evergreen.V16.Internal.Model2.Tick p0 ->
            Evergreen.V17.Internal.Model2.Tick p0

        Evergreen.V16.Internal.Model2.Teleported p0 p1 ->
            Evergreen.V17.Internal.Model2.Teleported (p0 |> migrate_Internal_Teleport_Trigger)
                (p1 |> migrate_Internal_Teleport_Event)


migrate_Internal_Model2_State : Evergreen.V16.Internal.Model2.State -> Evergreen.V17.Internal.Model2.State
migrate_Internal_Model2_State old =
    case old of
        Evergreen.V16.Internal.Model2.State p0 ->
            Evergreen.V17.Internal.Model2.State p0


migrate_Internal_Teleport_CssAnimation : Evergreen.V16.Internal.Teleport.CssAnimation -> Evergreen.V17.Internal.Teleport.CssAnimation
migrate_Internal_Teleport_CssAnimation old =
    old


migrate_Internal_Teleport_Data : Evergreen.V16.Internal.Teleport.Data -> Evergreen.V17.Internal.Teleport.Data
migrate_Internal_Teleport_Data old =
    case old of
        Evergreen.V16.Internal.Teleport.Css p0 ->
            Evergreen.V17.Internal.Teleport.Css (p0 |> migrate_Internal_Teleport_CssAnimation)

        Evergreen.V16.Internal.Teleport.ParentTrigger p0 ->
            Evergreen.V17.Internal.Teleport.ParentTrigger (p0 |> migrate_Internal_Teleport_ParentTriggerDetails)


migrate_Internal_Teleport_Event : Evergreen.V16.Internal.Teleport.Event -> Evergreen.V17.Internal.Teleport.Event
migrate_Internal_Teleport_Event old =
    { timestamp = old.timestamp
    , data = old.data |> List.map migrate_Internal_Teleport_Data
    }


migrate_Internal_Teleport_ParentTriggerDetails : Evergreen.V16.Internal.Teleport.ParentTriggerDetails -> Evergreen.V17.Internal.Teleport.ParentTriggerDetails
migrate_Internal_Teleport_ParentTriggerDetails old =
    old


migrate_Internal_Teleport_Trigger : Evergreen.V16.Internal.Teleport.Trigger -> Evergreen.V17.Internal.Teleport.Trigger
migrate_Internal_Teleport_Trigger old =
    case old of
        Evergreen.V16.Internal.Teleport.OnHover ->
            Evergreen.V17.Internal.Teleport.OnHover

        Evergreen.V16.Internal.Teleport.OnRender ->
            Evergreen.V17.Internal.Teleport.OnRender

        Evergreen.V16.Internal.Teleport.OnFocus ->
            Evergreen.V17.Internal.Teleport.OnFocus

        Evergreen.V16.Internal.Teleport.OnFocusWithin ->
            Evergreen.V17.Internal.Teleport.OnFocusWithin

        Evergreen.V16.Internal.Teleport.OnActive ->
            Evergreen.V17.Internal.Teleport.OnActive

        Evergreen.V16.Internal.Teleport.OnDismount ->
            Evergreen.V17.Internal.Teleport.OnDismount


migrate_List_Nonempty_Nonempty : (a_old -> a_new) -> List.Nonempty.Nonempty a_old -> List.Nonempty.Nonempty a_new
migrate_List_Nonempty_Nonempty migrate_a old =
    old |> List.Nonempty.map migrate_a


migrate_LocalState_AdminData : Evergreen.V16.LocalState.AdminData -> Evergreen.V17.LocalState.AdminData
migrate_LocalState_AdminData old =
    { users = old.users |> migrate_NonemptyDict_NonemptyDict migrate_Id_Id migrate_User_BackendUser
    , emailNotificationsEnabled = old.emailNotificationsEnabled
    , twoFactorAuthentication = old.twoFactorAuthentication |> SeqDict.toList |> List.map (Tuple.mapFirst migrate_Id_Id) |> SeqDict.fromList
    , botToken = old.botToken |> Maybe.map migrate_LocalState_DiscordBotToken
    }


migrate_LocalState_AdminStatus : Evergreen.V16.LocalState.AdminStatus -> Evergreen.V17.LocalState.AdminStatus
migrate_LocalState_AdminStatus old =
    case old of
        Evergreen.V16.LocalState.IsAdmin p0 ->
            Evergreen.V17.LocalState.IsAdmin (p0 |> migrate_LocalState_AdminData)

        Evergreen.V16.LocalState.IsNotAdmin ->
            Evergreen.V17.LocalState.IsNotAdmin


migrate_LocalState_Archived : Evergreen.V16.LocalState.Archived -> Evergreen.V17.LocalState.Archived
migrate_LocalState_Archived old =
    { archivedAt = old.archivedAt
    , archivedBy = old.archivedBy |> migrate_Id_Id
    }


migrate_LocalState_DiscordBotToken : Evergreen.V16.LocalState.DiscordBotToken -> Evergreen.V17.LocalState.DiscordBotToken
migrate_LocalState_DiscordBotToken old =
    case old of
        Evergreen.V16.LocalState.DiscordBotToken p0 ->
            Evergreen.V17.LocalState.DiscordBotToken p0


migrate_LocalState_FrontendChannel : Evergreen.V16.LocalState.FrontendChannel -> Evergreen.V17.LocalState.FrontendChannel
migrate_LocalState_FrontendChannel old =
    { createdAt = old.createdAt
    , createdBy = old.createdBy |> migrate_Id_Id
    , name = old.name |> migrate_ChannelName_ChannelName
    , messages = old.messages |> Array.map migrate_Message_Message
    , isArchived = old.isArchived |> Maybe.map migrate_LocalState_Archived
    , lastTypedAt = old.lastTypedAt |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Id_Id migrate_DmChannel_LastTypedAt) |> SeqDict.fromList
    , linkedMessageIds = old.linkedMessageIds |> migrate_OneToOne_OneToOne migrate_Discord_Id_Id identity
    }


migrate_LocalState_FrontendGuild : Evergreen.V16.LocalState.FrontendGuild -> Evergreen.V17.LocalState.FrontendGuild
migrate_LocalState_FrontendGuild old =
    { createdAt = old.createdAt
    , createdBy = old.createdBy |> migrate_Id_Id
    , name = old.name |> migrate_GuildName_GuildName
    , icon = old.icon |> Maybe.map migrate_Image_Image
    , channels = old.channels |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Id_Id migrate_LocalState_FrontendChannel) |> SeqDict.fromList
    , members = old.members |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Id_Id (\rec -> rec)) |> SeqDict.fromList
    , owner = old.owner |> migrate_Id_Id
    , invites =
        old.invites
            |> SeqDict.toList
            |> List.map
                (Tuple.mapBoth migrate_SecretId_SecretId
                    (\rec ->
                        { createdAt = rec.createdAt
                        , createdBy = rec.createdBy |> migrate_Id_Id
                        }
                    )
                )
            |> SeqDict.fromList
    , announcementChannel = old.announcementChannel |> migrate_Id_Id
    }


migrate_LocalState_JoinGuildError : Evergreen.V16.LocalState.JoinGuildError -> Evergreen.V17.LocalState.JoinGuildError
migrate_LocalState_JoinGuildError old =
    case old of
        Evergreen.V16.LocalState.AlreadyJoined ->
            Evergreen.V17.LocalState.AlreadyJoined

        Evergreen.V16.LocalState.InviteIsInvalid ->
            Evergreen.V17.LocalState.InviteIsInvalid


migrate_LocalState_LocalState : Evergreen.V16.LocalState.LocalState -> Evergreen.V17.LocalState.LocalState
migrate_LocalState_LocalState old =
    { adminData = old.adminData |> migrate_LocalState_AdminStatus
    , guilds = old.guilds |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Id_Id migrate_LocalState_FrontendGuild) |> SeqDict.fromList
    , dmChannels = old.dmChannels |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Id_Id migrate_DmChannel_DmChannel) |> SeqDict.fromList
    , joinGuildError = old.joinGuildError |> Maybe.map migrate_LocalState_JoinGuildError
    , localUser = old.localUser |> migrate_LocalState_LocalUser
    }


migrate_LocalState_LocalUser : Evergreen.V16.LocalState.LocalUser -> Evergreen.V17.LocalState.LocalUser
migrate_LocalState_LocalUser old =
    { userId = old.userId |> migrate_Id_Id
    , user = old.user |> migrate_User_BackendUser
    , otherUsers = old.otherUsers |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Id_Id migrate_User_FrontendUser) |> SeqDict.fromList
    }


migrate_LocalState_LogWithTime : Evergreen.V16.LocalState.LogWithTime -> Evergreen.V17.LocalState.LogWithTime
migrate_LocalState_LogWithTime old =
    { time = old.time
    , log = old.log |> migrate_Log_Log
    }


migrate_Local_ChangeId : Evergreen.V16.Local.ChangeId -> Evergreen.V17.Local.ChangeId
migrate_Local_ChangeId old =
    case old of
        Evergreen.V16.Local.ChangeId p0 ->
            Evergreen.V17.Local.ChangeId p0


migrate_Local_Local : (msg_old -> msg_new) -> (model_old -> model_new) -> Evergreen.V16.Local.Local msg_old model_old -> Evergreen.V17.Local.Local msg_new model_new
migrate_Local_Local migrate_msg migrate_model old =
    case old of
        Evergreen.V16.Local.Local p0 ->
            Evergreen.V17.Local.Local
                { localMsgs =
                    p0.localMsgs
                        |> Dict.map
                            (\k ->
                                \rec1 ->
                                    { createdAt = rec1.createdAt
                                    , msg = rec1.msg |> migrate_msg
                                    }
                            )
                , localModel = p0.localModel |> migrate_model
                , serverModel = p0.serverModel |> migrate_model
                , counter = p0.counter |> migrate_Local_ChangeId
                }


migrate_Log_Log : Evergreen.V16.Log.Log -> Evergreen.V17.Log.Log
migrate_Log_Log old =
    case old of
        Evergreen.V16.Log.LoginEmail p0 p1 ->
            Evergreen.V17.Log.LoginEmail (p0 |> Result.mapError migrate_Postmark_SendEmailError)
                (p1 |> migrate_EmailAddress_EmailAddress)

        Evergreen.V16.Log.LoginsRateLimited p0 ->
            Evergreen.V17.Log.LoginsRateLimited (p0 |> migrate_Id_Id)

        Evergreen.V16.Log.ChangedUsers p0 ->
            Evergreen.V17.Log.ChangedUsers (p0 |> migrate_Id_Id)

        Evergreen.V16.Log.SendLogErrorEmailFailed p0 p1 ->
            Evergreen.V17.Log.SendLogErrorEmailFailed (p0 |> migrate_Postmark_SendEmailError)
                (p1 |> migrate_EmailAddress_EmailAddress)


migrate_LoginForm_CodeStatus : Evergreen.V16.LoginForm.CodeStatus -> Evergreen.V17.LoginForm.CodeStatus
migrate_LoginForm_CodeStatus old =
    case old of
        Evergreen.V16.LoginForm.Checking ->
            Evergreen.V17.LoginForm.Checking

        Evergreen.V16.LoginForm.NotValid ->
            Evergreen.V17.LoginForm.NotValid


migrate_LoginForm_EnterEmail2 : Evergreen.V16.LoginForm.EnterEmail2 -> Evergreen.V17.LoginForm.EnterEmail2
migrate_LoginForm_EnterEmail2 old =
    old


migrate_LoginForm_EnterLoginCode2 : Evergreen.V16.LoginForm.EnterLoginCode2 -> Evergreen.V17.LoginForm.EnterLoginCode2
migrate_LoginForm_EnterLoginCode2 old =
    { sentTo = old.sentTo |> migrate_EmailAddress_EmailAddress
    , code = old.code
    , attempts = old.attempts |> SeqDict.map (\k -> migrate_LoginForm_CodeStatus)
    }


migrate_LoginForm_EnterTwoFactorCode2 : Evergreen.V16.LoginForm.EnterTwoFactorCode2 -> Evergreen.V17.LoginForm.EnterTwoFactorCode2
migrate_LoginForm_EnterTwoFactorCode2 old =
    { code = old.code
    , attempts = old.attempts |> SeqDict.map (\k -> migrate_LoginForm_CodeStatus)
    , attemptCount = old.attemptCount
    }


migrate_LoginForm_EnterUserData2 : Evergreen.V16.LoginForm.EnterUserData2 -> Evergreen.V17.LoginForm.EnterUserData2
migrate_LoginForm_EnterUserData2 old =
    { name = old.name
    , pressedSubmit = old.pressedSubmit |> migrate_LoginForm_SubmitStatus
    }


migrate_LoginForm_LoginForm : Evergreen.V16.LoginForm.LoginForm -> Evergreen.V17.LoginForm.LoginForm
migrate_LoginForm_LoginForm old =
    case old of
        Evergreen.V16.LoginForm.EnterEmail p0 ->
            Evergreen.V17.LoginForm.EnterEmail (p0 |> migrate_LoginForm_EnterEmail2)

        Evergreen.V16.LoginForm.EnterLoginCode p0 ->
            Evergreen.V17.LoginForm.EnterLoginCode (p0 |> migrate_LoginForm_EnterLoginCode2)

        Evergreen.V16.LoginForm.EnterTwoFactorCode p0 ->
            Evergreen.V17.LoginForm.EnterTwoFactorCode (p0 |> migrate_LoginForm_EnterTwoFactorCode2)

        Evergreen.V16.LoginForm.EnterUserData p0 ->
            Evergreen.V17.LoginForm.EnterUserData (p0 |> migrate_LoginForm_EnterUserData2)


migrate_LoginForm_Msg : Evergreen.V16.LoginForm.Msg -> Evergreen.V17.LoginForm.Msg
migrate_LoginForm_Msg old =
    case old of
        Evergreen.V16.LoginForm.PressedSubmitEmail ->
            Evergreen.V17.LoginForm.PressedSubmitEmail

        Evergreen.V16.LoginForm.PressedCancelLogin ->
            Evergreen.V17.LoginForm.PressedCancelLogin

        Evergreen.V16.LoginForm.TypedLoginFormEmail p0 ->
            Evergreen.V17.LoginForm.TypedLoginFormEmail p0

        Evergreen.V16.LoginForm.TypedLoginCode p0 ->
            Evergreen.V17.LoginForm.TypedLoginCode p0

        Evergreen.V16.LoginForm.TypedTwoFactorCode p0 ->
            Evergreen.V17.LoginForm.TypedTwoFactorCode p0

        Evergreen.V16.LoginForm.TypedName p0 ->
            Evergreen.V17.LoginForm.TypedName p0

        Evergreen.V16.LoginForm.PressedSubmitUserData ->
            Evergreen.V17.LoginForm.PressedSubmitUserData


migrate_LoginForm_SubmitStatus : Evergreen.V16.LoginForm.SubmitStatus -> Evergreen.V17.LoginForm.SubmitStatus
migrate_LoginForm_SubmitStatus old =
    case old of
        Evergreen.V16.LoginForm.NotSubmitted p0 ->
            Evergreen.V17.LoginForm.NotSubmitted p0

        Evergreen.V16.LoginForm.Submitting ->
            Evergreen.V17.LoginForm.Submitting


migrate_MessageInput_MentionUserDropdown : Evergreen.V16.MessageInput.MentionUserDropdown -> Evergreen.V17.MessageInput.MentionUserDropdown
migrate_MessageInput_MentionUserDropdown old =
    { charIndex = old.charIndex
    , dropdownIndex = old.dropdownIndex
    , inputElement =
        old.inputElement
            |> (\rec -> rec)
    , target = old.target |> migrate_MessageInput_MentionUserTarget
    }


migrate_MessageInput_MentionUserTarget : Evergreen.V16.MessageInput.MentionUserTarget -> Evergreen.V17.MessageInput.MentionUserTarget
migrate_MessageInput_MentionUserTarget old =
    case old of
        Evergreen.V16.MessageInput.NewMessage ->
            Evergreen.V17.MessageInput.NewMessage

        Evergreen.V16.MessageInput.EditMessage ->
            Evergreen.V17.MessageInput.EditMessage


migrate_Message_Message : Evergreen.V16.Message.Message -> Evergreen.V17.Message.Message
migrate_Message_Message old =
    case old of
        Evergreen.V16.Message.UserTextMessage p0 ->
            Evergreen.V17.Message.UserTextMessage (p0 |> migrate_Message_UserTextMessageData)

        Evergreen.V16.Message.UserJoinedMessage p0 p1 p2 ->
            Evergreen.V17.Message.UserJoinedMessage p0
                (p1 |> migrate_Id_Id)
                (p2 |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Emoji_Emoji (migrate_NonemptySet_NonemptySet migrate_Id_Id)) |> SeqDict.fromList)

        Evergreen.V16.Message.DeletedMessage ->
            Evergreen.V17.Message.DeletedMessage


migrate_Message_UserTextMessageData : Evergreen.V16.Message.UserTextMessageData -> Evergreen.V17.Message.UserTextMessageData
migrate_Message_UserTextMessageData old =
    { createdAt = old.createdAt
    , createdBy = old.createdBy |> migrate_Id_Id
    , content = old.content |> migrate_List_Nonempty_Nonempty migrate_RichText_RichText
    , reactions = old.reactions |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Emoji_Emoji (migrate_NonemptySet_NonemptySet migrate_Id_Id)) |> SeqDict.fromList
    , editedAt = old.editedAt
    , repliedTo = old.repliedTo
    }


migrate_NonemptyDict_NonemptyDict : (id_old -> id_new) -> (a_old -> a_new) -> Evergreen.V16.NonemptyDict.NonemptyDict id_old a_old -> Evergreen.V17.NonemptyDict.NonemptyDict id_new a_new
migrate_NonemptyDict_NonemptyDict migrate_id migrate_a old =
    case old of
        Evergreen.V16.NonemptyDict.NonemptyDict p0 p1 p2 ->
            Evergreen.V17.NonemptyDict.NonemptyDict (p0 |> migrate_id)
                (p1 |> migrate_a)
                (p2 |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_id migrate_a) |> SeqDict.fromList)


migrate_NonemptySet_NonemptySet : (a_old -> a_new) -> Evergreen.V16.NonemptySet.NonemptySet a_old -> Evergreen.V17.NonemptySet.NonemptySet a_new
migrate_NonemptySet_NonemptySet migrate_a old =
    case old of
        Evergreen.V16.NonemptySet.NonemptySet p0 p1 ->
            Evergreen.V17.NonemptySet.NonemptySet (p0 |> migrate_a) (p1 |> SeqSet.map migrate_a)


migrate_OneToOne_OneToOne : (a_old -> a_new) -> (b_old -> b_new) -> Evergreen.V16.OneToOne.OneToOne a_old b_old -> Evergreen.V17.OneToOne.OneToOne a_new b_new
migrate_OneToOne_OneToOne migrate_a migrate_b old =
    case old of
        Evergreen.V16.OneToOne.OneToOne p0 p1 ->
            Evergreen.V17.OneToOne.OneToOne (p0 |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_a migrate_b) |> SeqDict.fromList)
                (p1 |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_b migrate_a) |> SeqDict.fromList)


migrate_Pages_Admin_AdminChange : Evergreen.V16.Pages.Admin.AdminChange -> Evergreen.V17.Pages.Admin.AdminChange
migrate_Pages_Admin_AdminChange old =
    case old of
        Evergreen.V16.Pages.Admin.ChangeUsers p0 ->
            Evergreen.V17.Pages.Admin.ChangeUsers
                { time = p0.time
                , changedUsers = p0.changedUsers |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Id_Id migrate_Pages_Admin_EditedBackendUser) |> SeqDict.fromList
                , newUsers = p0.newUsers
                , deletedUsers = p0.deletedUsers |> SeqSet.map migrate_Id_Id
                }

        Evergreen.V16.Pages.Admin.ExpandSection p0 ->
            Evergreen.V17.Pages.Admin.ExpandSection (p0 |> migrate_User_AdminUiSection)

        Evergreen.V16.Pages.Admin.CollapseSection p0 ->
            Evergreen.V17.Pages.Admin.CollapseSection (p0 |> migrate_User_AdminUiSection)

        Evergreen.V16.Pages.Admin.LogPageChanged p0 ->
            Evergreen.V17.Pages.Admin.LogPageChanged p0

        Evergreen.V16.Pages.Admin.SetEmailNotificationsEnabled p0 ->
            Evergreen.V17.Pages.Admin.SetEmailNotificationsEnabled p0

        Evergreen.V16.Pages.Admin.SetDiscordBotToken p0 ->
            Evergreen.V17.Pages.Admin.SetDiscordBotToken (p0 |> Maybe.map migrate_LocalState_DiscordBotToken)


migrate_Pages_Admin_EditedBackendUser : Evergreen.V16.Pages.Admin.EditedBackendUser -> Evergreen.V17.Pages.Admin.EditedBackendUser
migrate_Pages_Admin_EditedBackendUser old =
    old


migrate_Pages_Admin_EditingCell : Evergreen.V16.Pages.Admin.EditingCell -> Evergreen.V17.Pages.Admin.EditingCell
migrate_Pages_Admin_EditingCell old =
    { userId = old.userId |> migrate_Pages_Admin_UserTableId
    , column = old.column |> migrate_Pages_Admin_UserColumn
    , text = old.text
    }


migrate_Pages_Admin_InitAdminData : Evergreen.V16.Pages.Admin.InitAdminData -> Evergreen.V17.Pages.Admin.InitAdminData
migrate_Pages_Admin_InitAdminData old =
    { lastLogPageViewed = old.lastLogPageViewed
    , users = old.users |> migrate_NonemptyDict_NonemptyDict migrate_Id_Id migrate_User_BackendUser
    , emailNotificationsEnabled = old.emailNotificationsEnabled
    , twoFactorAuthentication = old.twoFactorAuthentication |> SeqDict.toList |> List.map (Tuple.mapFirst migrate_Id_Id) |> SeqDict.fromList
    , botToken = old.botToken |> Maybe.map migrate_LocalState_DiscordBotToken
    }


migrate_Pages_Admin_Model : Evergreen.V16.Pages.Admin.Model -> Evergreen.V17.Pages.Admin.Model
migrate_Pages_Admin_Model old =
    { highlightLog = old.highlightLog
    , copiedLogLink = old.copiedLogLink
    , userTable = old.userTable |> migrate_Pages_Admin_UserTable
    , submitError = old.submitError |> Maybe.map migrate_Pages_Admin_UsersChangeError
    , logs = old.logs |> migrate_Pagination_Pagination migrate_LocalState_LogWithTime
    }


migrate_Pages_Admin_Msg : Evergreen.V16.Pages.Admin.Msg -> Evergreen.V17.Pages.Admin.Msg
migrate_Pages_Admin_Msg old =
    case old of
        Evergreen.V16.Pages.Admin.PressedLogPage p0 ->
            Evergreen.V17.Pages.Admin.PressedLogPage p0

        Evergreen.V16.Pages.Admin.PressedCopyLogLink p0 ->
            Evergreen.V17.Pages.Admin.PressedCopyLogLink p0

        Evergreen.V16.Pages.Admin.PressedCollapseSection p0 ->
            Evergreen.V17.Pages.Admin.PressedCollapseSection (p0 |> migrate_User_AdminUiSection)

        Evergreen.V16.Pages.Admin.DoublePressedCollapseSection p0 ->
            Evergreen.V17.Pages.Admin.DoublePressedCollapseSection (p0 |> migrate_User_AdminUiSection)

        Evergreen.V16.Pages.Admin.PressedExpandSection p0 ->
            Evergreen.V17.Pages.Admin.PressedExpandSection (p0 |> migrate_User_AdminUiSection)

        Evergreen.V16.Pages.Admin.PressedEditCell p0 p1 ->
            Evergreen.V17.Pages.Admin.PressedEditCell (p0 |> migrate_Pages_Admin_UserTableId)
                (p1 |> migrate_Pages_Admin_UserColumn)

        Evergreen.V16.Pages.Admin.TypedEditCell p0 ->
            Evergreen.V17.Pages.Admin.TypedEditCell p0

        Evergreen.V16.Pages.Admin.EditCellLostFocus p0 p1 ->
            Evergreen.V17.Pages.Admin.EditCellLostFocus (p0 |> migrate_Pages_Admin_UserTableId)
                (p1 |> migrate_Pages_Admin_UserColumn)

        Evergreen.V16.Pages.Admin.FocusedOnEditCell ->
            Evergreen.V17.Pages.Admin.FocusedOnEditCell

        Evergreen.V16.Pages.Admin.EnterKeyInEditCell p0 p1 ->
            Evergreen.V17.Pages.Admin.EnterKeyInEditCell (p0 |> migrate_Pages_Admin_UserTableId)
                (p1 |> migrate_Pages_Admin_UserColumn)

        Evergreen.V16.Pages.Admin.PressedSaveUserChanges ->
            Evergreen.V17.Pages.Admin.PressedSaveUserChanges

        Evergreen.V16.Pages.Admin.TabKeyInEditCell p0 ->
            Evergreen.V17.Pages.Admin.TabKeyInEditCell p0

        Evergreen.V16.Pages.Admin.PressedResetUserChanges ->
            Evergreen.V17.Pages.Admin.PressedResetUserChanges

        Evergreen.V16.Pages.Admin.EscapeKeyInEditCell ->
            Evergreen.V17.Pages.Admin.EscapeKeyInEditCell

        Evergreen.V16.Pages.Admin.PressedAddUserRow ->
            Evergreen.V17.Pages.Admin.PressedAddUserRow

        Evergreen.V16.Pages.Admin.PressedDeleteUser p0 ->
            Evergreen.V17.Pages.Admin.PressedDeleteUser (p0 |> migrate_Pages_Admin_UserTableId)

        Evergreen.V16.Pages.Admin.PressedResetUser p0 ->
            Evergreen.V17.Pages.Admin.PressedResetUser (p0 |> migrate_Id_Id)

        Evergreen.V16.Pages.Admin.ScrolledToSection ->
            Evergreen.V17.Pages.Admin.ScrolledToSection

        Evergreen.V16.Pages.Admin.UserTableMsg p0 ->
            Evergreen.V17.Pages.Admin.UserTableMsg (p0 |> migrate_Table_Msg)

        Evergreen.V16.Pages.Admin.ToggledEmailNotifications p0 ->
            Evergreen.V17.Pages.Admin.ToggledEmailNotifications p0

        Evergreen.V16.Pages.Admin.ToggleIsAdmin p0 p1 ->
            Evergreen.V17.Pages.Admin.ToggleIsAdmin (p0 |> migrate_Pages_Admin_UserTableId) p1


migrate_Pages_Admin_UserColumn : Evergreen.V16.Pages.Admin.UserColumn -> Evergreen.V17.Pages.Admin.UserColumn
migrate_Pages_Admin_UserColumn old =
    case old of
        Evergreen.V16.Pages.Admin.NameColumn ->
            Evergreen.V17.Pages.Admin.NameColumn

        Evergreen.V16.Pages.Admin.EmailAddressColumn ->
            Evergreen.V17.Pages.Admin.EmailAddressColumn


migrate_Pages_Admin_UserTable : Evergreen.V16.Pages.Admin.UserTable -> Evergreen.V17.Pages.Admin.UserTable
migrate_Pages_Admin_UserTable old =
    { table = old.table |> migrate_Table_Model
    , changedUsers = old.changedUsers |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Id_Id migrate_Pages_Admin_EditedBackendUser) |> SeqDict.fromList
    , editingCell = old.editingCell |> Maybe.map migrate_Pages_Admin_EditingCell
    , newUsers = old.newUsers
    , deletedUsers = old.deletedUsers |> SeqSet.map migrate_Id_Id
    }


migrate_Pages_Admin_UserTableId : Evergreen.V16.Pages.Admin.UserTableId -> Evergreen.V17.Pages.Admin.UserTableId
migrate_Pages_Admin_UserTableId old =
    case old of
        Evergreen.V16.Pages.Admin.ExistingUserId p0 ->
            Evergreen.V17.Pages.Admin.ExistingUserId (p0 |> migrate_Id_Id)

        Evergreen.V16.Pages.Admin.NewUserId p0 ->
            Evergreen.V17.Pages.Admin.NewUserId p0


migrate_Pages_Admin_UsersChangeError : Evergreen.V16.Pages.Admin.UsersChangeError -> Evergreen.V17.Pages.Admin.UsersChangeError
migrate_Pages_Admin_UsersChangeError old =
    case old of
        Evergreen.V16.Pages.Admin.EmailAddressesAreNotUnique ->
            Evergreen.V17.Pages.Admin.EmailAddressesAreNotUnique

        Evergreen.V16.Pages.Admin.InvalidChangesToUser ->
            Evergreen.V17.Pages.Admin.InvalidChangesToUser

        Evergreen.V16.Pages.Admin.ChangesAppliedToNonExistentUser p0 ->
            Evergreen.V17.Pages.Admin.ChangesAppliedToNonExistentUser (p0 |> migrate_Id_Id)

        Evergreen.V16.Pages.Admin.CantRemoveAdminRoleFromYourself ->
            Evergreen.V17.Pages.Admin.CantRemoveAdminRoleFromYourself

        Evergreen.V16.Pages.Admin.CantDeleteYourself ->
            Evergreen.V17.Pages.Admin.CantDeleteYourself

        Evergreen.V16.Pages.Admin.InvalidNewUser ->
            Evergreen.V17.Pages.Admin.InvalidNewUser


migrate_Pagination_PageStatus : (a_old -> a_new) -> Evergreen.V16.Pagination.PageStatus a_old -> Evergreen.V17.Pagination.PageStatus a_new
migrate_Pagination_PageStatus migrate_a old =
    case old of
        Evergreen.V16.Pagination.PageLoading ->
            Evergreen.V17.Pagination.PageLoading

        Evergreen.V16.Pagination.PageLoaded p0 ->
            Evergreen.V17.Pagination.PageLoaded (p0 |> Array.map migrate_a)


migrate_Pagination_Pagination : (a_old -> a_new) -> Evergreen.V16.Pagination.Pagination a_old -> Evergreen.V17.Pagination.Pagination a_new
migrate_Pagination_Pagination migrate_a old =
    { pages = old.pages |> Dict.map (\k -> migrate_Pagination_PageStatus migrate_a)
    , currentPage = old.currentPage
    , totalPages = old.totalPages
    }


migrate_PersonName_PersonName : Evergreen.V16.PersonName.PersonName -> Evergreen.V17.PersonName.PersonName
migrate_PersonName_PersonName old =
    case old of
        Evergreen.V16.PersonName.PersonName p0 ->
            Evergreen.V17.PersonName.PersonName p0


migrate_Point2d_Point2d : (units_old -> units_new) -> (coordinates_old -> coordinates_new) -> Evergreen.V16.Point2d.Point2d units_old coordinates_old -> Evergreen.V17.Point2d.Point2d units_new coordinates_new
migrate_Point2d_Point2d migrate_units migrate_coordinates old =
    old |> migrate_Geometry_Types_Point2d


migrate_Ports_NotificationPermission : Evergreen.V16.Ports.NotificationPermission -> Evergreen.V17.Ports.NotificationPermission
migrate_Ports_NotificationPermission old =
    case old of
        Evergreen.V16.Ports.NotAsked ->
            Evergreen.V17.Ports.NotAsked

        Evergreen.V16.Ports.Denied ->
            Evergreen.V17.Ports.Denied

        Evergreen.V16.Ports.Granted ->
            Evergreen.V17.Ports.Granted

        Evergreen.V16.Ports.Unsupported ->
            Evergreen.V17.Ports.Unsupported


migrate_Ports_PwaStatus : Evergreen.V16.Ports.PwaStatus -> Evergreen.V17.Ports.PwaStatus
migrate_Ports_PwaStatus old =
    case old of
        Evergreen.V16.Ports.InstalledPwa ->
            Evergreen.V17.Ports.InstalledPwa

        Evergreen.V16.Ports.BrowserView ->
            Evergreen.V17.Ports.BrowserView


migrate_Postmark_PostmarkSendResponse : Evergreen.V16.Postmark.PostmarkSendResponse -> Evergreen.V17.Postmark.PostmarkSendResponse
migrate_Postmark_PostmarkSendResponse old =
    { errorCode = old.errorCode
    , message = old.message
    , to = old.to |> List.map migrate_EmailAddress_EmailAddress
    }


migrate_Postmark_SendEmailError : Evergreen.V16.Postmark.SendEmailError -> Evergreen.V17.Postmark.SendEmailError
migrate_Postmark_SendEmailError old =
    case old of
        Evergreen.V16.Postmark.UnknownError p0 ->
            Evergreen.V17.Postmark.UnknownError p0

        Evergreen.V16.Postmark.PostmarkError p0 ->
            Evergreen.V17.Postmark.PostmarkError (p0 |> migrate_Postmark_PostmarkSendResponse)

        Evergreen.V16.Postmark.NetworkError ->
            Evergreen.V17.Postmark.NetworkError

        Evergreen.V16.Postmark.Timeout ->
            Evergreen.V17.Postmark.Timeout

        Evergreen.V16.Postmark.BadUrl p0 ->
            Evergreen.V17.Postmark.BadUrl p0


migrate_Quantity_Quantity : Quantity.Quantity number units -> Quantity.Quantity number units2
migrate_Quantity_Quantity old =
    Quantity.unwrap old |> Quantity.unsafe


migrate_RichText_Language : Evergreen.V16.RichText.Language -> Evergreen.V17.RichText.Language
migrate_RichText_Language old =
    case old of
        Evergreen.V16.RichText.Language p0 ->
            Evergreen.V17.RichText.Language p0

        Evergreen.V16.RichText.None ->
            Evergreen.V17.RichText.None


migrate_RichText_RichText : Evergreen.V16.RichText.RichText -> Evergreen.V17.RichText.RichText
migrate_RichText_RichText old =
    case old of
        Evergreen.V16.RichText.UserMention p0 ->
            Evergreen.V17.RichText.UserMention (p0 |> migrate_Id_Id)

        Evergreen.V16.RichText.NormalText p0 p1 ->
            Evergreen.V17.RichText.NormalText p0 p1

        Evergreen.V16.RichText.Bold p0 ->
            Evergreen.V17.RichText.Bold (p0 |> migrate_List_Nonempty_Nonempty migrate_RichText_RichText)

        Evergreen.V16.RichText.Italic p0 ->
            Evergreen.V17.RichText.Italic (p0 |> migrate_List_Nonempty_Nonempty migrate_RichText_RichText)

        Evergreen.V16.RichText.Underline p0 ->
            Evergreen.V17.RichText.Underline (p0 |> migrate_List_Nonempty_Nonempty migrate_RichText_RichText)

        Evergreen.V16.RichText.Strikethrough p0 ->
            Evergreen.V17.RichText.Strikethrough (p0 |> migrate_List_Nonempty_Nonempty migrate_RichText_RichText)

        Evergreen.V16.RichText.Spoiler p0 ->
            Evergreen.V17.RichText.Spoiler (p0 |> migrate_List_Nonempty_Nonempty migrate_RichText_RichText)

        Evergreen.V16.RichText.Hyperlink p0 p1 ->
            Evergreen.V17.RichText.Hyperlink p0 p1

        Evergreen.V16.RichText.InlineCode p0 p1 ->
            Evergreen.V17.RichText.InlineCode p0 p1

        Evergreen.V16.RichText.CodeBlock p0 p1 ->
            Evergreen.V17.RichText.CodeBlock (p0 |> migrate_RichText_Language) p1


migrate_Route_ChannelRoute : Evergreen.V16.Route.ChannelRoute -> Evergreen.V17.Route.ChannelRoute
migrate_Route_ChannelRoute old =
    case old of
        Evergreen.V16.Route.ChannelRoute p0 p1 ->
            Evergreen.V17.Route.ChannelRoute (p0 |> migrate_Id_Id) p1

        Evergreen.V16.Route.NewChannelRoute ->
            Evergreen.V17.Route.NewChannelRoute

        Evergreen.V16.Route.EditChannelRoute p0 ->
            Evergreen.V17.Route.EditChannelRoute (p0 |> migrate_Id_Id)

        Evergreen.V16.Route.InviteLinkCreatorRoute ->
            Evergreen.V17.Route.InviteLinkCreatorRoute

        Evergreen.V16.Route.JoinRoute p0 ->
            Evergreen.V17.Route.JoinRoute (p0 |> migrate_SecretId_SecretId)


migrate_Route_Route : Evergreen.V16.Route.Route -> Evergreen.V17.Route.Route
migrate_Route_Route old =
    case old of
        Evergreen.V16.Route.HomePageRoute ->
            Evergreen.V17.Route.HomePageRoute

        Evergreen.V16.Route.AdminRoute p0 ->
            Evergreen.V17.Route.AdminRoute p0

        Evergreen.V16.Route.GuildRoute p0 p1 ->
            Evergreen.V17.Route.GuildRoute (p0 |> migrate_Id_Id)
                (p1 |> migrate_Route_ChannelRoute)

        Evergreen.V16.Route.DmRoute p0 p1 ->
            Evergreen.V17.Route.DmRoute (p0 |> migrate_Id_Id) p1

        Evergreen.V16.Route.AiChatRoute ->
            Evergreen.V17.Route.AiChatRoute


migrate_SecretId_SecretId : Evergreen.V16.SecretId.SecretId a_old -> Evergreen.V17.SecretId.SecretId a_new
migrate_SecretId_SecretId old =
    case old of
        Evergreen.V16.SecretId.SecretId p0 ->
            Evergreen.V17.SecretId.SecretId p0


migrate_Table_Model : Evergreen.V16.Table.Model -> Evergreen.V17.Table.Model
migrate_Table_Model old =
    old


migrate_Table_Msg : Evergreen.V16.Table.Msg -> Evergreen.V17.Table.Msg
migrate_Table_Msg old =
    case old of
        Evergreen.V16.Table.PressedSortBy p0 ->
            Evergreen.V17.Table.PressedSortBy p0

        Evergreen.V16.Table.PressedShowAll ->
            Evergreen.V17.Table.PressedShowAll


migrate_Touch_ScreenCoordinate : Evergreen.V16.Touch.ScreenCoordinate -> Evergreen.V17.Touch.ScreenCoordinate
migrate_Touch_ScreenCoordinate old =
    case old of
        Evergreen.V16.Touch.ScreenCoordinate p0 ->
            Evergreen.V17.Touch.ScreenCoordinate p0


migrate_Touch_Touch : Evergreen.V16.Touch.Touch -> Evergreen.V17.Touch.Touch
migrate_Touch_Touch old =
    { client = old.client |> migrate_Point2d_Point2d migrate_CssPixels_CssPixels migrate_Touch_ScreenCoordinate
    , target = old.target
    }


migrate_TwoFactorAuthentication_Msg : Evergreen.V16.TwoFactorAuthentication.Msg -> Evergreen.V17.TwoFactorAuthentication.Msg
migrate_TwoFactorAuthentication_Msg old =
    case old of
        Evergreen.V16.TwoFactorAuthentication.PressedStart2FaSetup ->
            Evergreen.V17.TwoFactorAuthentication.PressedStart2FaSetup

        Evergreen.V16.TwoFactorAuthentication.PressedCopy p0 ->
            Evergreen.V17.TwoFactorAuthentication.PressedCopy p0

        Evergreen.V16.TwoFactorAuthentication.TypedTwoFactorCode p0 ->
            Evergreen.V17.TwoFactorAuthentication.TypedTwoFactorCode p0


migrate_TwoFactorAuthentication_TwoFactorSetupData : Evergreen.V16.TwoFactorAuthentication.TwoFactorSetupData -> Evergreen.V17.TwoFactorAuthentication.TwoFactorSetupData
migrate_TwoFactorAuthentication_TwoFactorSetupData old =
    { qrCodeUrl = old.qrCodeUrl
    , code = old.code
    , attempts = old.attempts |> SeqDict.map (\k -> migrate_LoginForm_CodeStatus)
    }


migrate_TwoFactorAuthentication_TwoFactorState : Evergreen.V16.TwoFactorAuthentication.TwoFactorState -> Evergreen.V17.TwoFactorAuthentication.TwoFactorState
migrate_TwoFactorAuthentication_TwoFactorState old =
    case old of
        Evergreen.V16.TwoFactorAuthentication.TwoFactorNotStarted ->
            Evergreen.V17.TwoFactorAuthentication.TwoFactorNotStarted

        Evergreen.V16.TwoFactorAuthentication.TwoFactorLoading ->
            Evergreen.V17.TwoFactorAuthentication.TwoFactorLoading

        Evergreen.V16.TwoFactorAuthentication.TwoFactorSetup p0 ->
            Evergreen.V17.TwoFactorAuthentication.TwoFactorSetup (p0 |> migrate_TwoFactorAuthentication_TwoFactorSetupData)

        Evergreen.V16.TwoFactorAuthentication.TwoFactorComplete ->
            Evergreen.V17.TwoFactorAuthentication.TwoFactorComplete

        Evergreen.V16.TwoFactorAuthentication.TwoFactorAlreadyComplete p0 ->
            Evergreen.V17.TwoFactorAuthentication.TwoFactorAlreadyComplete p0


migrate_Types_AdminStatusLoginData : Evergreen.V16.Types.AdminStatusLoginData -> Evergreen.V17.Types.AdminStatusLoginData
migrate_Types_AdminStatusLoginData old =
    case old of
        Evergreen.V16.Types.IsAdminLoginData p0 ->
            Evergreen.V17.Types.IsAdminLoginData (p0 |> migrate_Pages_Admin_InitAdminData)

        Evergreen.V16.Types.IsNotAdminLoginData ->
            Evergreen.V17.Types.IsNotAdminLoginData


migrate_Types_ChannelSidebarMode : Evergreen.V16.Types.ChannelSidebarMode -> Evergreen.V17.Types.ChannelSidebarMode
migrate_Types_ChannelSidebarMode old =
    case old of
        Evergreen.V16.Types.ChannelSidebarClosed ->
            Evergreen.V17.Types.ChannelSidebarClosed

        Evergreen.V16.Types.ChannelSidebarOpened ->
            Evergreen.V17.Types.ChannelSidebarOpened

        Evergreen.V16.Types.ChannelSidebarClosing p0 ->
            Evergreen.V17.Types.ChannelSidebarClosing p0

        Evergreen.V16.Types.ChannelSidebarOpening p0 ->
            Evergreen.V17.Types.ChannelSidebarOpening p0

        Evergreen.V16.Types.ChannelSidebarDragging p0 ->
            Evergreen.V17.Types.ChannelSidebarDragging p0


migrate_Types_Drag : Evergreen.V16.Types.Drag -> Evergreen.V17.Types.Drag
migrate_Types_Drag old =
    case old of
        Evergreen.V16.Types.NoDrag ->
            Evergreen.V17.Types.NoDrag

        Evergreen.V16.Types.DragStart p0 p1 ->
            Evergreen.V17.Types.DragStart p0
                (p1 |> migrate_NonemptyDict_NonemptyDict identity migrate_Touch_Touch)

        Evergreen.V16.Types.Dragging p0 ->
            Evergreen.V17.Types.Dragging
                { horizontalStart = p0.horizontalStart
                , touches = p0.touches |> migrate_NonemptyDict_NonemptyDict identity migrate_Touch_Touch
                }


migrate_Types_EditMessage : Evergreen.V16.Types.EditMessage -> Evergreen.V17.Types.EditMessage
migrate_Types_EditMessage old =
    old


migrate_Types_EmojiSelector : Evergreen.V16.Types.EmojiSelector -> Evergreen.V17.Types.EmojiSelector
migrate_Types_EmojiSelector old =
    case old of
        Evergreen.V16.Types.EmojiSelectorHidden ->
            Evergreen.V17.Types.EmojiSelectorHidden

        Evergreen.V16.Types.EmojiSelectorForReaction p0 p1 ->
            Evergreen.V17.Types.EmojiSelectorForReaction (p0 |> migrate_User_GuildOrDmId) p1

        Evergreen.V16.Types.EmojiSelectorForMessage ->
            Evergreen.V17.Types.EmojiSelectorForMessage


migrate_Types_FrontendModel : Evergreen.V16.Types.FrontendModel -> Evergreen.V17.Types.FrontendModel
migrate_Types_FrontendModel old =
    case old of
        Evergreen.V16.Types.Loading p0 ->
            Evergreen.V17.Types.Loading (p0 |> migrate_Types_LoadingFrontend)

        Evergreen.V16.Types.Loaded p0 ->
            Evergreen.V17.Types.Loaded (p0 |> migrate_Types_LoadedFrontend)


migrate_Types_FrontendMsg : Evergreen.V16.Types.FrontendMsg -> Evergreen.V17.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V16.Types.UrlClicked p0 ->
            Evergreen.V17.Types.UrlClicked p0

        Evergreen.V16.Types.UrlChanged p0 ->
            Evergreen.V17.Types.UrlChanged p0

        Evergreen.V16.Types.GotTime p0 ->
            Evergreen.V17.Types.GotTime p0

        Evergreen.V16.Types.GotWindowSize p0 p1 ->
            Evergreen.V17.Types.GotWindowSize p0 p1

        Evergreen.V16.Types.LoginFormMsg p0 ->
            Evergreen.V17.Types.LoginFormMsg (p0 |> migrate_LoginForm_Msg)

        Evergreen.V16.Types.PressedShowLogin ->
            Evergreen.V17.Types.PressedShowLogin

        Evergreen.V16.Types.AdminPageMsg p0 ->
            Evergreen.V17.Types.AdminPageMsg (p0 |> migrate_Pages_Admin_Msg)

        Evergreen.V16.Types.PressedLogOut ->
            Evergreen.V17.Types.PressedLogOut

        Evergreen.V16.Types.ElmUiMsg p0 ->
            Evergreen.V17.Types.ElmUiMsg (p0 |> migrate_Ui_Anim_Msg)

        Evergreen.V16.Types.ScrolledToLogSection ->
            Evergreen.V17.Types.ScrolledToLogSection

        Evergreen.V16.Types.PressedLink p0 ->
            Evergreen.V17.Types.PressedLink (p0 |> migrate_Route_Route)

        Evergreen.V16.Types.TypedMessage p0 p1 ->
            Evergreen.V17.Types.TypedMessage (p0 |> migrate_User_GuildOrDmId) p1

        Evergreen.V16.Types.PressedSendMessage p0 ->
            Evergreen.V17.Types.PressedSendMessage (p0 |> migrate_User_GuildOrDmId)

        Evergreen.V16.Types.NewChannelFormChanged p0 p1 ->
            Evergreen.V17.Types.NewChannelFormChanged (p0 |> migrate_Id_Id)
                (p1 |> migrate_Types_NewChannelForm)

        Evergreen.V16.Types.PressedSubmitNewChannel p0 p1 ->
            Evergreen.V17.Types.PressedSubmitNewChannel (p0 |> migrate_Id_Id)
                (p1 |> migrate_Types_NewChannelForm)

        Evergreen.V16.Types.MouseEnteredChannelName p0 p1 ->
            Evergreen.V17.Types.MouseEnteredChannelName (p0 |> migrate_Id_Id) (p1 |> migrate_Id_Id)

        Evergreen.V16.Types.MouseExitedChannelName p0 p1 ->
            Evergreen.V17.Types.MouseExitedChannelName (p0 |> migrate_Id_Id) (p1 |> migrate_Id_Id)

        Evergreen.V16.Types.EditChannelFormChanged p0 p1 p2 ->
            Evergreen.V17.Types.EditChannelFormChanged (p0 |> migrate_Id_Id)
                (p1 |> migrate_Id_Id)
                (p2 |> migrate_Types_NewChannelForm)

        Evergreen.V16.Types.PressedCancelEditChannelChanges p0 p1 ->
            Evergreen.V17.Types.PressedCancelEditChannelChanges (p0 |> migrate_Id_Id) (p1 |> migrate_Id_Id)

        Evergreen.V16.Types.PressedSubmitEditChannelChanges p0 p1 p2 ->
            Evergreen.V17.Types.PressedSubmitEditChannelChanges (p0 |> migrate_Id_Id)
                (p1 |> migrate_Id_Id)
                (p2 |> migrate_Types_NewChannelForm)

        Evergreen.V16.Types.PressedDeleteChannel p0 p1 ->
            Evergreen.V17.Types.PressedDeleteChannel (p0 |> migrate_Id_Id) (p1 |> migrate_Id_Id)

        Evergreen.V16.Types.PressedCreateInviteLink p0 ->
            Evergreen.V17.Types.PressedCreateInviteLink (p0 |> migrate_Id_Id)

        Evergreen.V16.Types.FrontendNoOp ->
            Evergreen.V17.Types.FrontendNoOp

        Evergreen.V16.Types.PressedCopyText p0 ->
            Evergreen.V17.Types.PressedCopyText p0

        Evergreen.V16.Types.PressedCreateGuild ->
            Evergreen.V17.Types.PressedCreateGuild

        Evergreen.V16.Types.NewGuildFormChanged p0 ->
            Evergreen.V17.Types.NewGuildFormChanged (p0 |> migrate_Types_NewGuildForm)

        Evergreen.V16.Types.PressedSubmitNewGuild p0 ->
            Evergreen.V17.Types.PressedSubmitNewGuild (p0 |> migrate_Types_NewGuildForm)

        Evergreen.V16.Types.PressedCancelNewGuild ->
            Evergreen.V17.Types.PressedCancelNewGuild

        Evergreen.V16.Types.DebouncedTyping ->
            Evergreen.V17.Types.DebouncedTyping

        Evergreen.V16.Types.GotPingUserPosition p0 ->
            Evergreen.V17.Types.GotPingUserPosition (p0 |> Result.map migrate_MessageInput_MentionUserDropdown)

        Evergreen.V16.Types.PressedPingUser p0 p1 ->
            Evergreen.V17.Types.PressedPingUser (p0 |> migrate_User_GuildOrDmId) p1

        Evergreen.V16.Types.SetFocus ->
            Evergreen.V17.Types.SetFocus

        Evergreen.V16.Types.RemoveFocus ->
            Evergreen.V17.Types.RemoveFocus

        Evergreen.V16.Types.PressedArrowInDropdown p0 p1 ->
            Evergreen.V17.Types.PressedArrowInDropdown (p0 |> migrate_User_GuildOrDmId) p1

        Evergreen.V16.Types.TextInputGotFocus p0 ->
            Evergreen.V17.Types.TextInputGotFocus p0

        Evergreen.V16.Types.TextInputLostFocus p0 ->
            Evergreen.V17.Types.TextInputLostFocus p0

        Evergreen.V16.Types.KeyDown p0 ->
            Evergreen.V17.Types.KeyDown p0

        Evergreen.V16.Types.MouseEnteredMessage p0 ->
            Evergreen.V17.Types.MouseEnteredMessage p0

        Evergreen.V16.Types.MouseExitedMessage p0 ->
            Evergreen.V17.Types.MouseExitedMessage p0

        Evergreen.V16.Types.AltPressedMessage p0 p1 ->
            Evergreen.V17.Types.AltPressedMessage p0
                (p1 |> migrate_Coord_Coord migrate_CssPixels_CssPixels)

        Evergreen.V16.Types.MessageMenu_PressedShowReactionEmojiSelector p0 p1 ->
            Evergreen.V17.Types.MessageMenu_PressedShowReactionEmojiSelector p0
                (p1 |> migrate_Coord_Coord migrate_CssPixels_CssPixels)

        Evergreen.V16.Types.MessageMenu_PressedEditMessage p0 ->
            Evergreen.V17.Types.MessageMenu_PressedEditMessage p0

        Evergreen.V16.Types.PressedEmojiSelectorEmoji p0 ->
            Evergreen.V17.Types.PressedEmojiSelectorEmoji (p0 |> migrate_Emoji_Emoji)

        Evergreen.V16.Types.PressedReactionEmoji_Add p0 p1 ->
            Evergreen.V17.Types.PressedReactionEmoji_Add p0 (p1 |> migrate_Emoji_Emoji)

        Evergreen.V16.Types.PressedReactionEmoji_Remove p0 p1 ->
            Evergreen.V17.Types.PressedReactionEmoji_Remove p0 (p1 |> migrate_Emoji_Emoji)

        Evergreen.V16.Types.GotPingUserPositionForEditMessage p0 ->
            Evergreen.V17.Types.GotPingUserPositionForEditMessage (p0 |> Result.map migrate_MessageInput_MentionUserDropdown)

        Evergreen.V16.Types.TypedEditMessage p0 p1 ->
            Evergreen.V17.Types.TypedEditMessage (p0 |> migrate_User_GuildOrDmId) p1

        Evergreen.V16.Types.PressedSendEditMessage p0 ->
            Evergreen.V17.Types.PressedSendEditMessage (p0 |> migrate_User_GuildOrDmId)

        Evergreen.V16.Types.PressedArrowInDropdownForEditMessage p0 p1 ->
            Evergreen.V17.Types.PressedArrowInDropdownForEditMessage (p0 |> migrate_User_GuildOrDmId) p1

        Evergreen.V16.Types.PressedPingUserForEditMessage p0 p1 ->
            Evergreen.V17.Types.PressedPingUserForEditMessage (p0 |> migrate_User_GuildOrDmId) p1

        Evergreen.V16.Types.PressedArrowUpInEmptyInput p0 ->
            Evergreen.V17.Types.PressedArrowUpInEmptyInput (p0 |> migrate_User_GuildOrDmId)

        Evergreen.V16.Types.MessageMenu_PressedReply p0 ->
            Evergreen.V17.Types.MessageMenu_PressedReply p0

        Evergreen.V16.Types.PressedCloseReplyTo p0 ->
            Evergreen.V17.Types.PressedCloseReplyTo (p0 |> migrate_User_GuildOrDmId)

        Evergreen.V16.Types.PressedSpoiler p0 p1 ->
            Evergreen.V17.Types.PressedSpoiler p0 p1

        Evergreen.V16.Types.VisibilityChanged p0 ->
            Evergreen.V17.Types.VisibilityChanged p0

        Evergreen.V16.Types.CheckedNotificationPermission p0 ->
            Evergreen.V17.Types.CheckedNotificationPermission (p0 |> migrate_Ports_NotificationPermission)

        Evergreen.V16.Types.CheckedPwaStatus p0 ->
            Evergreen.V17.Types.CheckedPwaStatus (p0 |> migrate_Ports_PwaStatus)

        Evergreen.V16.Types.TouchStart p0 p1 ->
            Evergreen.V17.Types.TouchStart p0
                (p1 |> migrate_NonemptyDict_NonemptyDict identity migrate_Touch_Touch)

        Evergreen.V16.Types.TouchMoved p0 p1 ->
            Evergreen.V17.Types.TouchMoved p0
                (p1 |> migrate_NonemptyDict_NonemptyDict identity migrate_Touch_Touch)

        Evergreen.V16.Types.TouchEnd p0 ->
            Evergreen.V17.Types.TouchEnd p0

        Evergreen.V16.Types.TouchCancel p0 ->
            Evergreen.V17.Types.TouchCancel p0

        Evergreen.V16.Types.ChannelSidebarAnimated p0 ->
            Evergreen.V17.Types.ChannelSidebarAnimated p0

        Evergreen.V16.Types.MessageMenuAnimated p0 ->
            Evergreen.V17.Types.MessageMenuAnimated p0

        Evergreen.V16.Types.ScrolledToBottom ->
            Evergreen.V17.Types.ScrolledToBottom

        Evergreen.V16.Types.PressedChannelHeaderBackButton ->
            Evergreen.V17.Types.PressedChannelHeaderBackButton

        Evergreen.V16.Types.UserScrolled p0 ->
            Evergreen.V17.Types.UserScrolled p0

        Evergreen.V16.Types.PressedBody ->
            Evergreen.V17.Types.PressedBody

        Evergreen.V16.Types.PressedReactionEmojiContainer ->
            Evergreen.V17.Types.PressedReactionEmojiContainer

        Evergreen.V16.Types.MessageMenu_PressedShowFullMenu p0 p1 ->
            Evergreen.V17.Types.MessageMenu_PressedShowFullMenu p0
                (p1 |> migrate_Coord_Coord migrate_CssPixels_CssPixels)

        Evergreen.V16.Types.MessageMenu_PressedDeleteMessage p0 p1 ->
            Evergreen.V17.Types.MessageMenu_PressedDeleteMessage (p0 |> migrate_User_GuildOrDmId) p1

        Evergreen.V16.Types.PressedReplyLink p0 ->
            Evergreen.V17.Types.PressedReplyLink p0

        Evergreen.V16.Types.ScrolledToMessage ->
            Evergreen.V17.Types.ScrolledToMessage

        Evergreen.V16.Types.MessageMenu_PressedClose ->
            Evergreen.V17.Types.MessageMenu_PressedClose

        Evergreen.V16.Types.MessageMenu_PressedContainer ->
            Evergreen.V17.Types.MessageMenu_PressedContainer

        Evergreen.V16.Types.PressedCancelMessageEdit p0 ->
            Evergreen.V17.Types.PressedCancelMessageEdit (p0 |> migrate_User_GuildOrDmId)

        Evergreen.V16.Types.PressedPingDropdownContainer ->
            Evergreen.V17.Types.PressedPingDropdownContainer

        Evergreen.V16.Types.PressedEditMessagePingDropdownContainer ->
            Evergreen.V17.Types.PressedEditMessagePingDropdownContainer

        Evergreen.V16.Types.CheckMessageAltPress p0 p1 ->
            Evergreen.V17.Types.CheckMessageAltPress p0 p1

        Evergreen.V16.Types.PressedShowUserOption ->
            Evergreen.V17.Types.PressedShowUserOption

        Evergreen.V16.Types.PressedCloseUserOptions ->
            Evergreen.V17.Types.PressedCloseUserOptions

        Evergreen.V16.Types.TwoFactorMsg p0 ->
            Evergreen.V17.Types.TwoFactorMsg (p0 |> migrate_TwoFactorAuthentication_Msg)

        Evergreen.V16.Types.AiChatMsg p0 ->
            Evergreen.V17.Types.AiChatMsg (p0 |> migrate_AiChat_Msg)

        Evergreen.V16.Types.UserNameEditableMsg p0 ->
            Evergreen.V17.Types.UserNameEditableMsg (p0 |> migrate_Editable_Msg migrate_PersonName_PersonName)

        Evergreen.V16.Types.BotTokenEditableMsg p0 ->
            Evergreen.V17.Types.BotTokenEditableMsg (p0 |> migrate_Editable_Msg (Maybe.map migrate_LocalState_DiscordBotToken))

        Evergreen.V16.Types.OneFrameAfterDragEnd ->
            Evergreen.V17.Types.OneFrameAfterDragEnd


migrate_Types_LoadStatus : Evergreen.V16.Types.LoadStatus -> Evergreen.V17.Types.LoadStatus
migrate_Types_LoadStatus old =
    case old of
        Evergreen.V16.Types.LoadingData ->
            Evergreen.V17.Types.LoadingData

        Evergreen.V16.Types.LoadSuccess p0 ->
            Evergreen.V17.Types.LoadSuccess (p0 |> migrate_Types_LoginData)

        Evergreen.V16.Types.LoadError ->
            Evergreen.V17.Types.LoadError


migrate_Types_LoadedFrontend : Evergreen.V16.Types.LoadedFrontend -> Evergreen.V17.Types.LoadedFrontend
migrate_Types_LoadedFrontend old =
    { navigationKey = old.navigationKey
    , route = old.route |> migrate_Route_Route
    , time = old.time
    , windowSize = old.windowSize |> migrate_Coord_Coord migrate_CssPixels_CssPixels
    , loginStatus = old.loginStatus |> migrate_Types_LoginStatus
    , elmUiState = old.elmUiState |> migrate_Ui_Anim_State
    , lastCopied = old.lastCopied
    , textInputFocus = old.textInputFocus
    , notificationPermission = old.notificationPermission |> migrate_Ports_NotificationPermission
    , pwaStatus = old.pwaStatus |> migrate_Ports_PwaStatus
    , drag = old.drag |> migrate_Types_Drag
    , dragPrevious = old.dragPrevious |> migrate_Types_Drag
    , scrolledToBottomOfChannel = old.scrolledToBottomOfChannel
    , aiChatModel = old.aiChatModel |> migrate_AiChat_FrontendModel
    }


migrate_Types_LoadingFrontend : Evergreen.V16.Types.LoadingFrontend -> Evergreen.V17.Types.LoadingFrontend
migrate_Types_LoadingFrontend old =
    { navigationKey = old.navigationKey
    , route = old.route |> migrate_Route_Route
    , windowSize = old.windowSize |> migrate_Coord_Coord migrate_CssPixels_CssPixels
    , time = old.time
    , loginStatus = old.loginStatus |> migrate_Types_LoadStatus
    , notificationPermission = old.notificationPermission |> migrate_Ports_NotificationPermission
    , pwaStatus = old.pwaStatus |> migrate_Ports_PwaStatus
    }


migrate_Types_LocalChange : Evergreen.V16.Types.LocalChange -> Evergreen.V17.Types.LocalChange
migrate_Types_LocalChange old =
    case old of
        Evergreen.V16.Types.Local_Invalid ->
            Evergreen.V17.Types.Local_Invalid

        Evergreen.V16.Types.Local_Admin p0 ->
            Evergreen.V17.Types.Local_Admin (p0 |> migrate_Pages_Admin_AdminChange)

        Evergreen.V16.Types.Local_SendMessage p0 p1 p2 p3 ->
            Evergreen.V17.Types.Local_SendMessage p0
                (p1 |> migrate_User_GuildOrDmId)
                (p2 |> migrate_List_Nonempty_Nonempty migrate_RichText_RichText)
                p3

        Evergreen.V16.Types.Local_NewChannel p0 p1 p2 ->
            Evergreen.V17.Types.Local_NewChannel p0
                (p1 |> migrate_Id_Id)
                (p2 |> migrate_ChannelName_ChannelName)

        Evergreen.V16.Types.Local_EditChannel p0 p1 p2 ->
            Evergreen.V17.Types.Local_EditChannel (p0 |> migrate_Id_Id)
                (p1 |> migrate_Id_Id)
                (p2 |> migrate_ChannelName_ChannelName)

        Evergreen.V16.Types.Local_DeleteChannel p0 p1 ->
            Evergreen.V17.Types.Local_DeleteChannel (p0 |> migrate_Id_Id) (p1 |> migrate_Id_Id)

        Evergreen.V16.Types.Local_NewInviteLink p0 p1 p2 ->
            Evergreen.V17.Types.Local_NewInviteLink p0
                (p1 |> migrate_Id_Id)
                (p2 |> migrate_Types_ToBeFilledInByBackend migrate_SecretId_SecretId)

        Evergreen.V16.Types.Local_NewGuild p0 p1 p2 ->
            Evergreen.V17.Types.Local_NewGuild p0
                (p1 |> migrate_GuildName_GuildName)
                (p2 |> migrate_Types_ToBeFilledInByBackend migrate_Id_Id)

        Evergreen.V16.Types.Local_MemberTyping p0 p1 ->
            Evergreen.V17.Types.Local_MemberTyping p0 (p1 |> migrate_User_GuildOrDmId)

        Evergreen.V16.Types.Local_AddReactionEmoji p0 p1 p2 ->
            Evergreen.V17.Types.Local_AddReactionEmoji (p0 |> migrate_User_GuildOrDmId)
                p1
                (p2 |> migrate_Emoji_Emoji)

        Evergreen.V16.Types.Local_RemoveReactionEmoji p0 p1 p2 ->
            Evergreen.V17.Types.Local_RemoveReactionEmoji (p0 |> migrate_User_GuildOrDmId)
                p1
                (p2 |> migrate_Emoji_Emoji)

        Evergreen.V16.Types.Local_SendEditMessage p0 p1 p2 p3 ->
            Evergreen.V17.Types.Local_SendEditMessage p0
                (p1 |> migrate_User_GuildOrDmId)
                p2
                (p3 |> migrate_List_Nonempty_Nonempty migrate_RichText_RichText)

        Evergreen.V16.Types.Local_MemberEditTyping p0 p1 p2 ->
            Evergreen.V17.Types.Local_MemberEditTyping p0 (p1 |> migrate_User_GuildOrDmId) p2

        Evergreen.V16.Types.Local_SetLastViewed p0 p1 ->
            Evergreen.V17.Types.Local_SetLastViewed (p0 |> migrate_User_GuildOrDmId) p1

        Evergreen.V16.Types.Local_DeleteMessage p0 p1 ->
            Evergreen.V17.Types.Local_DeleteMessage (p0 |> migrate_User_GuildOrDmId) p1

        Evergreen.V16.Types.Local_ViewChannel p0 p1 ->
            Evergreen.V17.Types.Local_ViewChannel (p0 |> migrate_Id_Id) (p1 |> migrate_Id_Id)

        Evergreen.V16.Types.Local_SetName p0 ->
            Evergreen.V17.Types.Local_SetName (p0 |> migrate_PersonName_PersonName)


migrate_Types_LocalMsg : Evergreen.V16.Types.LocalMsg -> Evergreen.V17.Types.LocalMsg
migrate_Types_LocalMsg old =
    case old of
        Evergreen.V16.Types.LocalChange p0 p1 ->
            Evergreen.V17.Types.LocalChange (p0 |> migrate_Id_Id)
                (p1 |> migrate_Types_LocalChange)

        Evergreen.V16.Types.ServerChange p0 ->
            Evergreen.V17.Types.ServerChange (p0 |> migrate_Types_ServerChange)


migrate_Types_LoggedIn2 : Evergreen.V16.Types.LoggedIn2 -> Evergreen.V17.Types.LoggedIn2
migrate_Types_LoggedIn2 old =
    { localState = old.localState |> migrate_Local_Local migrate_Types_LocalMsg migrate_LocalState_LocalState
    , admin = old.admin |> Maybe.map migrate_Pages_Admin_Model
    , drafts = old.drafts |> SeqDict.toList |> List.map (Tuple.mapFirst migrate_User_GuildOrDmId) |> SeqDict.fromList
    , newChannelForm = old.newChannelForm |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Id_Id migrate_Types_NewChannelForm) |> SeqDict.fromList
    , editChannelForm = old.editChannelForm |> SeqDict.toList |> List.map (Tuple.mapBoth (Tuple.mapBoth migrate_Id_Id migrate_Id_Id) migrate_Types_NewChannelForm) |> SeqDict.fromList
    , newGuildForm = old.newGuildForm
    , channelNameHover = old.channelNameHover |> Maybe.map (Tuple.mapBoth migrate_Id_Id migrate_Id_Id)
    , typingDebouncer = old.typingDebouncer
    , pingUser = old.pingUser |> Maybe.map migrate_MessageInput_MentionUserDropdown
    , messageHover = old.messageHover |> migrate_Types_MessageHover
    , showEmojiSelector = old.showEmojiSelector |> migrate_Types_EmojiSelector
    , editMessage = old.editMessage |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_User_GuildOrDmId migrate_Types_EditMessage) |> SeqDict.fromList
    , replyTo = old.replyTo |> SeqDict.toList |> List.map (Tuple.mapFirst migrate_User_GuildOrDmId) |> SeqDict.fromList
    , revealedSpoilers = old.revealedSpoilers |> Maybe.map migrate_Types_RevealedSpoilers
    , sidebarMode = old.sidebarMode |> migrate_Types_ChannelSidebarMode
    , userOptions = old.userOptions |> Maybe.map migrate_Types_UserOptionsModel
    , twoFactor = old.twoFactor |> migrate_TwoFactorAuthentication_TwoFactorState
    , filesToUpload = []
    }


migrate_Types_LoginData : Evergreen.V16.Types.LoginData -> Evergreen.V17.Types.LoginData
migrate_Types_LoginData old =
    { userId = old.userId |> migrate_Id_Id
    , adminData = old.adminData |> migrate_Types_AdminStatusLoginData
    , twoFactorAuthenticationEnabled = old.twoFactorAuthenticationEnabled
    , guilds = old.guilds |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Id_Id migrate_LocalState_FrontendGuild) |> SeqDict.fromList
    , dmChannels = old.dmChannels |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Id_Id migrate_DmChannel_DmChannel) |> SeqDict.fromList
    , user = old.user |> migrate_User_BackendUser
    , otherUsers = old.otherUsers |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Id_Id migrate_User_FrontendUser) |> SeqDict.fromList
    }


migrate_Types_LoginStatus : Evergreen.V16.Types.LoginStatus -> Evergreen.V17.Types.LoginStatus
migrate_Types_LoginStatus old =
    case old of
        Evergreen.V16.Types.LoggedIn p0 ->
            Evergreen.V17.Types.LoggedIn (p0 |> migrate_Types_LoggedIn2)

        Evergreen.V16.Types.NotLoggedIn p0 ->
            Evergreen.V17.Types.NotLoggedIn
                { loginForm = p0.loginForm |> Maybe.map migrate_LoginForm_LoginForm
                , useInviteAfterLoggedIn = p0.useInviteAfterLoggedIn |> Maybe.map migrate_SecretId_SecretId
                }


migrate_Types_MessageHover : Evergreen.V16.Types.MessageHover -> Evergreen.V17.Types.MessageHover
migrate_Types_MessageHover old =
    case old of
        Evergreen.V16.Types.NoMessageHover ->
            Evergreen.V17.Types.NoMessageHover

        Evergreen.V16.Types.MessageHover p0 p1 ->
            Evergreen.V17.Types.MessageHover (p0 |> migrate_User_GuildOrDmId) p1

        Evergreen.V16.Types.MessageMenu p0 ->
            Evergreen.V17.Types.MessageMenu (p0 |> migrate_Types_MessageMenuExtraOptions)


migrate_Types_MessageHoverMobileMode : Evergreen.V16.Types.MessageHoverMobileMode -> Evergreen.V17.Types.MessageHoverMobileMode
migrate_Types_MessageHoverMobileMode old =
    case old of
        Evergreen.V16.Types.MessageMenuClosing p0 ->
            Evergreen.V17.Types.MessageMenuClosing (p0 |> migrate_Quantity_Quantity)

        Evergreen.V16.Types.MessageMenuOpening p0 ->
            Evergreen.V17.Types.MessageMenuOpening
                { offset = p0.offset |> migrate_Quantity_Quantity
                , targetOffset = p0.targetOffset |> migrate_Quantity_Quantity
                }

        Evergreen.V16.Types.MessageMenuDragging p0 ->
            Evergreen.V17.Types.MessageMenuDragging
                { offset = p0.offset |> migrate_Quantity_Quantity
                , previousOffset = p0.previousOffset |> migrate_Quantity_Quantity
                , time = p0.time
                }

        Evergreen.V16.Types.MessageMenuFixed p0 ->
            Evergreen.V17.Types.MessageMenuFixed (p0 |> migrate_Quantity_Quantity)


migrate_Types_MessageId : Evergreen.V16.Types.MessageId -> Evergreen.V17.Types.MessageId
migrate_Types_MessageId old =
    { guildId = old.guildId |> migrate_Id_Id
    , channelId = old.channelId |> migrate_Id_Id
    , messageIndex = old.messageIndex
    }


migrate_Types_MessageMenuExtraOptions : Evergreen.V16.Types.MessageMenuExtraOptions -> Evergreen.V17.Types.MessageMenuExtraOptions
migrate_Types_MessageMenuExtraOptions old =
    { position = old.position |> migrate_Coord_Coord migrate_CssPixels_CssPixels
    , guildOrDmId = old.guildOrDmId |> migrate_User_GuildOrDmId
    , messageIndex = old.messageIndex
    , mobileMode = old.mobileMode |> migrate_Types_MessageHoverMobileMode
    }


migrate_Types_NewChannelForm : Evergreen.V16.Types.NewChannelForm -> Evergreen.V17.Types.NewChannelForm
migrate_Types_NewChannelForm old =
    old


migrate_Types_NewGuildForm : Evergreen.V16.Types.NewGuildForm -> Evergreen.V17.Types.NewGuildForm
migrate_Types_NewGuildForm old =
    old


migrate_Types_RevealedSpoilers : Evergreen.V16.Types.RevealedSpoilers -> Evergreen.V17.Types.RevealedSpoilers
migrate_Types_RevealedSpoilers old =
    { guildOrDmId = old.guildOrDmId |> migrate_User_GuildOrDmId
    , messages = old.messages |> SeqDict.map (\k -> migrate_NonemptySet_NonemptySet identity)
    }


migrate_Types_ServerChange : Evergreen.V16.Types.ServerChange -> Evergreen.V17.Types.ServerChange
migrate_Types_ServerChange old =
    case old of
        Evergreen.V16.Types.Server_SendMessage p0 p1 p2 p3 p4 ->
            Evergreen.V17.Types.Server_SendMessage (p0 |> migrate_Id_Id)
                p1
                (p2 |> migrate_User_GuildOrDmId)
                (p3 |> migrate_List_Nonempty_Nonempty migrate_RichText_RichText)
                p4

        Evergreen.V16.Types.Server_NewChannel p0 p1 p2 ->
            Evergreen.V17.Types.Server_NewChannel p0
                (p1 |> migrate_Id_Id)
                (p2 |> migrate_ChannelName_ChannelName)

        Evergreen.V16.Types.Server_EditChannel p0 p1 p2 ->
            Evergreen.V17.Types.Server_EditChannel (p0 |> migrate_Id_Id)
                (p1 |> migrate_Id_Id)
                (p2 |> migrate_ChannelName_ChannelName)

        Evergreen.V16.Types.Server_DeleteChannel p0 p1 ->
            Evergreen.V17.Types.Server_DeleteChannel (p0 |> migrate_Id_Id) (p1 |> migrate_Id_Id)

        Evergreen.V16.Types.Server_NewInviteLink p0 p1 p2 p3 ->
            Evergreen.V17.Types.Server_NewInviteLink p0
                (p1 |> migrate_Id_Id)
                (p2 |> migrate_Id_Id)
                (p3 |> migrate_SecretId_SecretId)

        Evergreen.V16.Types.Server_MemberJoined p0 p1 p2 p3 ->
            Evergreen.V17.Types.Server_MemberJoined p0
                (p1 |> migrate_Id_Id)
                (p2 |> migrate_Id_Id)
                (p3 |> migrate_User_FrontendUser)

        Evergreen.V16.Types.Server_YouJoinedGuildByInvite p0 ->
            Evergreen.V17.Types.Server_YouJoinedGuildByInvite
                (p0
                    |> Result.mapError migrate_LocalState_JoinGuildError
                    >> Result.map
                        (\rec1 ->
                            { guildId = rec1.guildId |> migrate_Id_Id
                            , guild = rec1.guild |> migrate_LocalState_FrontendGuild
                            , owner = rec1.owner |> migrate_User_FrontendUser
                            , members = rec1.members |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Id_Id migrate_User_FrontendUser) |> SeqDict.fromList
                            }
                        )
                )

        Evergreen.V16.Types.Server_MemberTyping p0 p1 p2 ->
            Evergreen.V17.Types.Server_MemberTyping p0
                (p1 |> migrate_Id_Id)
                (p2 |> migrate_User_GuildOrDmId)

        Evergreen.V16.Types.Server_AddReactionEmoji p0 p1 p2 p3 ->
            Evergreen.V17.Types.Server_AddReactionEmoji (p0 |> migrate_Id_Id)
                (p1 |> migrate_User_GuildOrDmId)
                p2
                (p3 |> migrate_Emoji_Emoji)

        Evergreen.V16.Types.Server_RemoveReactionEmoji p0 p1 p2 p3 ->
            Evergreen.V17.Types.Server_RemoveReactionEmoji (p0 |> migrate_Id_Id)
                (p1 |> migrate_User_GuildOrDmId)
                p2
                (p3 |> migrate_Emoji_Emoji)

        Evergreen.V16.Types.Server_SendEditMessage p0 p1 p2 p3 p4 ->
            Evergreen.V17.Types.Server_SendEditMessage p0
                (p1 |> migrate_Id_Id)
                (p2 |> migrate_User_GuildOrDmId)
                p3
                (p4 |> migrate_List_Nonempty_Nonempty migrate_RichText_RichText)

        Evergreen.V16.Types.Server_MemberEditTyping p0 p1 p2 p3 ->
            Evergreen.V17.Types.Server_MemberEditTyping p0
                (p1 |> migrate_Id_Id)
                (p2 |> migrate_User_GuildOrDmId)
                p3

        Evergreen.V16.Types.Server_DeleteMessage p0 p1 p2 ->
            Evergreen.V17.Types.Server_DeleteMessage (p0 |> migrate_Id_Id)
                (p1 |> migrate_User_GuildOrDmId)
                p2

        Evergreen.V16.Types.Server_DiscordDeleteMessage p0 ->
            Evergreen.V17.Types.Server_DiscordDeleteMessage (p0 |> migrate_Types_MessageId)

        Evergreen.V16.Types.Server_SetName p0 p1 ->
            Evergreen.V17.Types.Server_SetName (p0 |> migrate_Id_Id)
                (p1 |> migrate_PersonName_PersonName)

        Evergreen.V16.Types.Server_DiscordDirectMessage p0 p1 p2 p3 ->
            Evergreen.V17.Types.Server_DiscordDirectMessage p0
                (p1 |> migrate_Discord_Id_Id)
                (p2 |> migrate_Id_Id)
                (p3 |> migrate_List_Nonempty_Nonempty migrate_RichText_RichText)


migrate_Types_ToBeFilledInByBackend : (a_old -> a_new) -> Evergreen.V16.Types.ToBeFilledInByBackend a_old -> Evergreen.V17.Types.ToBeFilledInByBackend a_new
migrate_Types_ToBeFilledInByBackend migrate_a old =
    case old of
        Evergreen.V16.Types.EmptyPlaceholder ->
            Evergreen.V17.Types.EmptyPlaceholder

        Evergreen.V16.Types.FilledInByBackend p0 ->
            Evergreen.V17.Types.FilledInByBackend (p0 |> migrate_a)


migrate_Types_UserOptionsModel : Evergreen.V16.Types.UserOptionsModel -> Evergreen.V17.Types.UserOptionsModel
migrate_Types_UserOptionsModel old =
    { name = old.name |> migrate_Editable_Model
    , botToken = old.botToken |> migrate_Editable_Model
    }


migrate_Ui_Anim_Msg : Evergreen.V16.Ui.Anim.Msg -> Evergreen.V17.Ui.Anim.Msg
migrate_Ui_Anim_Msg old =
    old |> migrate_Internal_Model2_Msg


migrate_Ui_Anim_State : Evergreen.V16.Ui.Anim.State -> Evergreen.V17.Ui.Anim.State
migrate_Ui_Anim_State old =
    old |> migrate_Internal_Model2_State


migrate_User_AdminUiSection : Evergreen.V16.User.AdminUiSection -> Evergreen.V17.User.AdminUiSection
migrate_User_AdminUiSection old =
    case old of
        Evergreen.V16.User.UsersSection ->
            Evergreen.V17.User.UsersSection

        Evergreen.V16.User.LogSection ->
            Evergreen.V17.User.LogSection


migrate_User_BackendUser : Evergreen.V16.User.BackendUser -> Evergreen.V17.User.BackendUser
migrate_User_BackendUser old =
    { name = old.name |> migrate_PersonName_PersonName
    , isAdmin = old.isAdmin
    , email = old.email |> migrate_User_EmailStatus
    , recentLoginEmails = old.recentLoginEmails
    , lastLogPageViewed = old.lastLogPageViewed
    , expandedSections = old.expandedSections |> SeqSet.map migrate_User_AdminUiSection
    , createdAt = old.createdAt
    , emailNotifications = old.emailNotifications |> migrate_User_EmailNotifications
    , lastEmailNotification = old.lastEmailNotification
    , lastViewed = old.lastViewed |> SeqDict.toList |> List.map (Tuple.mapFirst migrate_User_GuildOrDmId) |> SeqDict.fromList
    , dmLastViewed = old.dmLastViewed |> SeqDict.toList |> List.map (Tuple.mapFirst migrate_Id_Id) |> SeqDict.fromList
    , lastChannelViewed = old.lastChannelViewed |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Id_Id migrate_Id_Id) |> SeqDict.fromList
    }


migrate_User_EmailNotifications : Evergreen.V16.User.EmailNotifications -> Evergreen.V17.User.EmailNotifications
migrate_User_EmailNotifications old =
    case old of
        Evergreen.V16.User.CheckEvery5Minutes ->
            Evergreen.V17.User.CheckEvery5Minutes

        Evergreen.V16.User.CheckEveryHour ->
            Evergreen.V17.User.CheckEveryHour

        Evergreen.V16.User.NeverNotifyMe ->
            Evergreen.V17.User.NeverNotifyMe


migrate_User_EmailStatus : Evergreen.V16.User.EmailStatus -> Evergreen.V17.User.EmailStatus
migrate_User_EmailStatus old =
    case old of
        Evergreen.V16.User.RegisteredFromDiscord ->
            Evergreen.V17.User.RegisteredFromDiscord

        Evergreen.V16.User.RegisteredDirectly p0 ->
            Evergreen.V17.User.RegisteredDirectly (p0 |> migrate_EmailAddress_EmailAddress)


migrate_User_FrontendUser : Evergreen.V16.User.FrontendUser -> Evergreen.V17.User.FrontendUser
migrate_User_FrontendUser old =
    { name = old.name |> migrate_PersonName_PersonName
    , isAdmin = old.isAdmin
    , createdAt = old.createdAt
    }


migrate_User_GuildOrDmId : Evergreen.V16.User.GuildOrDmId -> Evergreen.V17.User.GuildOrDmId
migrate_User_GuildOrDmId old =
    case old of
        Evergreen.V16.User.GuildOrDmId_Guild p0 p1 ->
            Evergreen.V17.User.GuildOrDmId_Guild (p0 |> migrate_Id_Id) (p1 |> migrate_Id_Id)

        Evergreen.V16.User.GuildOrDmId_Dm p0 ->
            Evergreen.V17.User.GuildOrDmId_Dm (p0 |> migrate_Id_Id)
