module Evergreen.Migrate.V25 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V24.Coord
import Evergreen.V24.CssPixels
import Evergreen.V24.Emoji
import Evergreen.V24.Geometry.Types
import Evergreen.V24.Id
import Evergreen.V24.Internal.Model2
import Evergreen.V24.Internal.Teleport
import Evergreen.V24.LoginForm
import Evergreen.V24.NonemptyDict
import Evergreen.V24.Pages.Admin
import Evergreen.V24.Pages.UserOverview
import Evergreen.V24.Point2d
import Evergreen.V24.Ports
import Evergreen.V24.Route
import Evergreen.V24.SecretId
import Evergreen.V24.Table
import Evergreen.V24.Types
import Evergreen.V24.Ui.Anim
import Evergreen.V24.User
import Evergreen.V25.Coord
import Evergreen.V25.CssPixels
import Evergreen.V25.Emoji
import Evergreen.V25.Geometry.Types
import Evergreen.V25.Id
import Evergreen.V25.Internal.Model2
import Evergreen.V25.Internal.Teleport
import Evergreen.V25.LoginForm
import Evergreen.V25.NonemptyDict
import Evergreen.V25.Pages.Admin
import Evergreen.V25.Pages.UserOverview
import Evergreen.V25.Point2d
import Evergreen.V25.Ports
import Evergreen.V25.Route
import Evergreen.V25.SecretId
import Evergreen.V25.Table
import Evergreen.V25.Types
import Evergreen.V25.Ui.Anim
import Evergreen.V25.User
import Lamdera.Migrations exposing (..)
import List
import Quantity
import SeqDict


frontendModel : Evergreen.V24.Types.FrontendModel -> ModelMigration Evergreen.V25.Types.FrontendModel Evergreen.V25.Types.FrontendMsg
frontendModel old =
    ModelUnchanged


backendModel : Evergreen.V24.Types.BackendModel -> ModelMigration Evergreen.V25.Types.BackendModel Evergreen.V25.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V24.Types.FrontendMsg -> MsgMigration Evergreen.V25.Types.FrontendMsg Evergreen.V25.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V24.Types.ToBackend -> MsgMigration Evergreen.V25.Types.ToBackend Evergreen.V25.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V24.Types.BackendMsg -> MsgMigration Evergreen.V25.Types.BackendMsg Evergreen.V25.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V24.Types.ToFrontend -> MsgMigration Evergreen.V25.Types.ToFrontend Evergreen.V25.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Coord_Coord : (units_old -> units_new) -> Evergreen.V24.Coord.Coord units_old -> Evergreen.V25.Coord.Coord units_new
migrate_Coord_Coord migrate_units old =
    old |> Tuple.mapBoth migrate_Quantity_Quantity migrate_Quantity_Quantity


migrate_CssPixels_CssPixels : Evergreen.V24.CssPixels.CssPixels -> Evergreen.V25.CssPixels.CssPixels
migrate_CssPixels_CssPixels old =
    case old of
        Evergreen.V24.CssPixels.CssPixels p0 ->
            Evergreen.V25.CssPixels.CssPixels p0


migrate_Emoji_Emoji : Evergreen.V24.Emoji.Emoji -> Evergreen.V25.Emoji.Emoji
migrate_Emoji_Emoji old =
    case old of
        Evergreen.V24.Emoji.UnicodeEmoji p0 ->
            Evergreen.V25.Emoji.UnicodeEmoji p0


migrate_Geometry_Types_Point2d : Evergreen.V24.Geometry.Types.Point2d units_old coordinates_old -> Evergreen.V25.Geometry.Types.Point2d units_new coordinates_new
migrate_Geometry_Types_Point2d old =
    case old of
        Evergreen.V24.Geometry.Types.Point2d p0 ->
            Evergreen.V25.Geometry.Types.Point2d p0


migrate_Id_Id : Evergreen.V24.Id.Id a_old -> Evergreen.V25.Id.Id a_new
migrate_Id_Id old =
    case old of
        Evergreen.V24.Id.Id p0 ->
            Evergreen.V25.Id.Id p0


migrate_Internal_Model2_Msg : Evergreen.V24.Internal.Model2.Msg -> Evergreen.V25.Internal.Model2.Msg
migrate_Internal_Model2_Msg old =
    case old of
        Evergreen.V24.Internal.Model2.Tick p0 ->
            Evergreen.V25.Internal.Model2.Tick p0

        Evergreen.V24.Internal.Model2.Teleported p0 p1 ->
            Evergreen.V25.Internal.Model2.Teleported (p0 |> migrate_Internal_Teleport_Trigger)
                (p1 |> migrate_Internal_Teleport_Event)


migrate_Internal_Teleport_CssAnimation : Evergreen.V24.Internal.Teleport.CssAnimation -> Evergreen.V25.Internal.Teleport.CssAnimation
migrate_Internal_Teleport_CssAnimation old =
    old


migrate_Internal_Teleport_Data : Evergreen.V24.Internal.Teleport.Data -> Evergreen.V25.Internal.Teleport.Data
migrate_Internal_Teleport_Data old =
    case old of
        Evergreen.V24.Internal.Teleport.Css p0 ->
            Evergreen.V25.Internal.Teleport.Css (p0 |> migrate_Internal_Teleport_CssAnimation)

        Evergreen.V24.Internal.Teleport.ParentTrigger p0 ->
            Evergreen.V25.Internal.Teleport.ParentTrigger (p0 |> migrate_Internal_Teleport_ParentTriggerDetails)


migrate_Internal_Teleport_Event : Evergreen.V24.Internal.Teleport.Event -> Evergreen.V25.Internal.Teleport.Event
migrate_Internal_Teleport_Event old =
    { timestamp = old.timestamp
    , data = old.data |> List.map migrate_Internal_Teleport_Data
    }


migrate_Internal_Teleport_ParentTriggerDetails : Evergreen.V24.Internal.Teleport.ParentTriggerDetails -> Evergreen.V25.Internal.Teleport.ParentTriggerDetails
migrate_Internal_Teleport_ParentTriggerDetails old =
    old


migrate_Internal_Teleport_Trigger : Evergreen.V24.Internal.Teleport.Trigger -> Evergreen.V25.Internal.Teleport.Trigger
migrate_Internal_Teleport_Trigger old =
    case old of
        Evergreen.V24.Internal.Teleport.OnHover ->
            Evergreen.V25.Internal.Teleport.OnHover

        Evergreen.V24.Internal.Teleport.OnRender ->
            Evergreen.V25.Internal.Teleport.OnRender

        Evergreen.V24.Internal.Teleport.OnFocus ->
            Evergreen.V25.Internal.Teleport.OnFocus

        Evergreen.V24.Internal.Teleport.OnFocusWithin ->
            Evergreen.V25.Internal.Teleport.OnFocusWithin

        Evergreen.V24.Internal.Teleport.OnActive ->
            Evergreen.V25.Internal.Teleport.OnActive

        Evergreen.V24.Internal.Teleport.OnDismount ->
            Evergreen.V25.Internal.Teleport.OnDismount


migrate_LoginForm_Msg : Evergreen.V24.LoginForm.Msg -> Evergreen.V25.LoginForm.Msg
migrate_LoginForm_Msg old =
    case old of
        Evergreen.V24.LoginForm.PressedSubmitEmail ->
            Evergreen.V25.LoginForm.PressedSubmitEmail

        Evergreen.V24.LoginForm.PressedCancelLogin ->
            Evergreen.V25.LoginForm.PressedCancelLogin

        Evergreen.V24.LoginForm.TypedLoginFormEmail p0 ->
            Evergreen.V25.LoginForm.TypedLoginFormEmail p0

        Evergreen.V24.LoginForm.TypedLoginCode p0 ->
            Evergreen.V25.LoginForm.TypedLoginCode p0

        Evergreen.V24.LoginForm.TypedTwoFactorCode p0 ->
            Evergreen.V25.LoginForm.TypedTwoFactorCode p0

        Evergreen.V24.LoginForm.TypedName p0 ->
            Evergreen.V25.LoginForm.TypedName p0

        Evergreen.V24.LoginForm.PressedSubmitUserData ->
            Evergreen.V25.LoginForm.PressedSubmitUserData


migrate_NonemptyDict_NonemptyDict : (id_old -> id_new) -> (a_old -> a_new) -> Evergreen.V24.NonemptyDict.NonemptyDict id_old a_old -> Evergreen.V25.NonemptyDict.NonemptyDict id_new a_new
migrate_NonemptyDict_NonemptyDict migrate_id migrate_a old =
    case old of
        Evergreen.V24.NonemptyDict.NonemptyDict p0 p1 p2 ->
            Evergreen.V25.NonemptyDict.NonemptyDict (p0 |> migrate_id)
                (p1 |> migrate_a)
                (p2 |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_id migrate_a) |> SeqDict.fromList)


migrate_Pages_Admin_Msg : Evergreen.V24.Pages.Admin.Msg -> Evergreen.V25.Pages.Admin.Msg
migrate_Pages_Admin_Msg old =
    case old of
        Evergreen.V24.Pages.Admin.PressedLogPage p0 ->
            Evergreen.V25.Pages.Admin.PressedLogPage p0

        Evergreen.V24.Pages.Admin.PressedCopyLogLink p0 ->
            Evergreen.V25.Pages.Admin.PressedCopyLogLink p0

        Evergreen.V24.Pages.Admin.PressedCollapseSection p0 ->
            Evergreen.V25.Pages.Admin.PressedCollapseSection (p0 |> migrate_User_AdminUiSection)

        Evergreen.V24.Pages.Admin.DoublePressedCollapseSection p0 ->
            Evergreen.V25.Pages.Admin.DoublePressedCollapseSection (p0 |> migrate_User_AdminUiSection)

        Evergreen.V24.Pages.Admin.PressedExpandSection p0 ->
            Evergreen.V25.Pages.Admin.PressedExpandSection (p0 |> migrate_User_AdminUiSection)

        Evergreen.V24.Pages.Admin.PressedEditCell p0 p1 ->
            Evergreen.V25.Pages.Admin.PressedEditCell (p0 |> migrate_Pages_Admin_UserTableId)
                (p1 |> migrate_Pages_Admin_UserColumn)

        Evergreen.V24.Pages.Admin.TypedEditCell p0 ->
            Evergreen.V25.Pages.Admin.TypedEditCell p0

        Evergreen.V24.Pages.Admin.EditCellLostFocus p0 p1 ->
            Evergreen.V25.Pages.Admin.EditCellLostFocus (p0 |> migrate_Pages_Admin_UserTableId)
                (p1 |> migrate_Pages_Admin_UserColumn)

        Evergreen.V24.Pages.Admin.FocusedOnEditCell ->
            Evergreen.V25.Pages.Admin.FocusedOnEditCell

        Evergreen.V24.Pages.Admin.EnterKeyInEditCell p0 p1 ->
            Evergreen.V25.Pages.Admin.EnterKeyInEditCell (p0 |> migrate_Pages_Admin_UserTableId)
                (p1 |> migrate_Pages_Admin_UserColumn)

        Evergreen.V24.Pages.Admin.PressedSaveUserChanges ->
            Evergreen.V25.Pages.Admin.PressedSaveUserChanges

        Evergreen.V24.Pages.Admin.TabKeyInEditCell p0 ->
            Evergreen.V25.Pages.Admin.TabKeyInEditCell p0

        Evergreen.V24.Pages.Admin.PressedResetUserChanges ->
            Evergreen.V25.Pages.Admin.PressedResetUserChanges

        Evergreen.V24.Pages.Admin.EscapeKeyInEditCell ->
            Evergreen.V25.Pages.Admin.EscapeKeyInEditCell

        Evergreen.V24.Pages.Admin.PressedAddUserRow ->
            Evergreen.V25.Pages.Admin.PressedAddUserRow

        Evergreen.V24.Pages.Admin.PressedDeleteUser p0 ->
            Evergreen.V25.Pages.Admin.PressedDeleteUser (p0 |> migrate_Pages_Admin_UserTableId)

        Evergreen.V24.Pages.Admin.PressedResetUser p0 ->
            Evergreen.V25.Pages.Admin.PressedResetUser (p0 |> migrate_Id_Id)

        Evergreen.V24.Pages.Admin.ScrolledToSection ->
            Evergreen.V25.Pages.Admin.ScrolledToSection

        Evergreen.V24.Pages.Admin.UserTableMsg p0 ->
            Evergreen.V25.Pages.Admin.UserTableMsg (p0 |> migrate_Table_Msg)

        Evergreen.V24.Pages.Admin.ToggledEmailNotifications p0 ->
            Evergreen.V25.Pages.Admin.ToggledEmailNotifications p0

        Evergreen.V24.Pages.Admin.ToggleIsAdmin p0 p1 ->
            Evergreen.V25.Pages.Admin.ToggleIsAdmin (p0 |> migrate_Pages_Admin_UserTableId) p1


migrate_Pages_Admin_UserColumn : Evergreen.V24.Pages.Admin.UserColumn -> Evergreen.V25.Pages.Admin.UserColumn
migrate_Pages_Admin_UserColumn old =
    case old of
        Evergreen.V24.Pages.Admin.NameColumn ->
            Evergreen.V25.Pages.Admin.NameColumn

        Evergreen.V24.Pages.Admin.EmailAddressColumn ->
            Evergreen.V25.Pages.Admin.EmailAddressColumn


migrate_Pages_Admin_UserTableId : Evergreen.V24.Pages.Admin.UserTableId -> Evergreen.V25.Pages.Admin.UserTableId
migrate_Pages_Admin_UserTableId old =
    case old of
        Evergreen.V24.Pages.Admin.ExistingUserId p0 ->
            Evergreen.V25.Pages.Admin.ExistingUserId (p0 |> migrate_Id_Id)

        Evergreen.V24.Pages.Admin.NewUserId p0 ->
            Evergreen.V25.Pages.Admin.NewUserId p0


migrate_Pages_UserOverview_Msg : Evergreen.V24.Pages.UserOverview.Msg -> Evergreen.V25.Pages.UserOverview.Msg
migrate_Pages_UserOverview_Msg old =
    case old of
        Evergreen.V24.Pages.UserOverview.SelectedNotificationFrequency p0 ->
            Evergreen.V25.Pages.UserOverview.SelectedNotificationFrequency (p0 |> migrate_User_EmailNotifications)

        Evergreen.V24.Pages.UserOverview.PressedStart2FaSetup ->
            Evergreen.V25.Pages.UserOverview.PressedStart2FaSetup

        Evergreen.V24.Pages.UserOverview.PressedCopyError p0 ->
            Evergreen.V25.Pages.UserOverview.PressedCopyError p0

        Evergreen.V24.Pages.UserOverview.TypedTwoFactorCode p0 ->
            Evergreen.V25.Pages.UserOverview.TypedTwoFactorCode p0


migrate_Point2d_Point2d : (units_old -> units_new) -> (coordinates_old -> coordinates_new) -> Evergreen.V24.Point2d.Point2d units_old coordinates_old -> Evergreen.V25.Point2d.Point2d units_new coordinates_new
migrate_Point2d_Point2d migrate_units migrate_coordinates old =
    old |> migrate_Geometry_Types_Point2d


migrate_Ports_NotificationPermission : Evergreen.V24.Ports.NotificationPermission -> Evergreen.V25.Ports.NotificationPermission
migrate_Ports_NotificationPermission old =
    case old of
        Evergreen.V24.Ports.NotAsked ->
            Evergreen.V25.Ports.NotAsked

        Evergreen.V24.Ports.Denied ->
            Evergreen.V25.Ports.Denied

        Evergreen.V24.Ports.Granted ->
            Evergreen.V25.Ports.Granted

        Evergreen.V24.Ports.Unsupported ->
            Evergreen.V25.Ports.Unsupported


migrate_Quantity_Quantity : Quantity.Quantity number units -> Quantity.Quantity number units2
migrate_Quantity_Quantity old =
    Quantity.unwrap old |> Quantity.unsafe


migrate_Route_ChannelRoute : Evergreen.V24.Route.ChannelRoute -> Evergreen.V25.Route.ChannelRoute
migrate_Route_ChannelRoute old =
    case old of
        Evergreen.V24.Route.ChannelRoute p0 p1 ->
            Evergreen.V25.Route.ChannelRoute (p0 |> migrate_Id_Id) p1

        Evergreen.V24.Route.NewChannelRoute ->
            Evergreen.V25.Route.NewChannelRoute

        Evergreen.V24.Route.EditChannelRoute p0 ->
            Evergreen.V25.Route.EditChannelRoute (p0 |> migrate_Id_Id)

        Evergreen.V24.Route.InviteLinkCreatorRoute ->
            Evergreen.V25.Route.InviteLinkCreatorRoute

        Evergreen.V24.Route.JoinRoute p0 ->
            Evergreen.V25.Route.JoinRoute (p0 |> migrate_SecretId_SecretId)


migrate_Route_Route : Evergreen.V24.Route.Route -> Evergreen.V25.Route.Route
migrate_Route_Route old =
    case old of
        Evergreen.V24.Route.HomePageRoute ->
            Evergreen.V25.Route.HomePageRoute

        Evergreen.V24.Route.AdminRoute p0 ->
            Evergreen.V25.Route.AdminRoute p0

        Evergreen.V24.Route.UserOverviewRoute p0 ->
            Evergreen.V25.Route.UserOverviewRoute (p0 |> migrate_Route_UserOverviewRouteData)

        Evergreen.V24.Route.GuildRoute p0 p1 ->
            Evergreen.V25.Route.GuildRoute (p0 |> migrate_Id_Id)
                (p1 |> migrate_Route_ChannelRoute)


migrate_Route_UserOverviewRouteData : Evergreen.V24.Route.UserOverviewRouteData -> Evergreen.V25.Route.UserOverviewRouteData
migrate_Route_UserOverviewRouteData old =
    case old of
        Evergreen.V24.Route.PersonalRoute ->
            Evergreen.V25.Route.PersonalRoute

        Evergreen.V24.Route.SpecificUserRoute p0 ->
            Evergreen.V25.Route.SpecificUserRoute (p0 |> migrate_Id_Id)


migrate_SecretId_SecretId : Evergreen.V24.SecretId.SecretId a_old -> Evergreen.V25.SecretId.SecretId a_new
migrate_SecretId_SecretId old =
    case old of
        Evergreen.V24.SecretId.SecretId p0 ->
            Evergreen.V25.SecretId.SecretId p0


migrate_Table_Msg : Evergreen.V24.Table.Msg -> Evergreen.V25.Table.Msg
migrate_Table_Msg old =
    case old of
        Evergreen.V24.Table.PressedSortBy p0 ->
            Evergreen.V25.Table.PressedSortBy p0

        Evergreen.V24.Table.PressedShowAll ->
            Evergreen.V25.Table.PressedShowAll


migrate_Types_FrontendMsg : Evergreen.V24.Types.FrontendMsg -> Evergreen.V25.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V24.Types.UrlClicked p0 ->
            Evergreen.V25.Types.UrlClicked p0

        Evergreen.V24.Types.UrlChanged p0 ->
            Evergreen.V25.Types.UrlChanged p0

        Evergreen.V24.Types.GotTime p0 ->
            Evergreen.V25.Types.GotTime p0

        Evergreen.V24.Types.GotWindowSize p0 p1 ->
            Evergreen.V25.Types.GotWindowSize p0 p1

        Evergreen.V24.Types.LoginFormMsg p0 ->
            Evergreen.V25.Types.LoginFormMsg (p0 |> migrate_LoginForm_Msg)

        Evergreen.V24.Types.PressedShowLogin ->
            Evergreen.V25.Types.PressedShowLogin

        Evergreen.V24.Types.AdminPageMsg p0 ->
            Evergreen.V25.Types.AdminPageMsg (p0 |> migrate_Pages_Admin_Msg)

        Evergreen.V24.Types.PressedLogOut ->
            Evergreen.V25.Types.PressedLogOut

        Evergreen.V24.Types.ElmUiMsg p0 ->
            Evergreen.V25.Types.ElmUiMsg (p0 |> migrate_Ui_Anim_Msg)

        Evergreen.V24.Types.ScrolledToLogSection ->
            Evergreen.V25.Types.ScrolledToLogSection

        Evergreen.V24.Types.PressedLink p0 ->
            Evergreen.V25.Types.PressedLink (p0 |> migrate_Route_Route)

        Evergreen.V24.Types.UserOverviewMsg p0 ->
            Evergreen.V25.Types.UserOverviewMsg (p0 |> migrate_Pages_UserOverview_Msg)

        Evergreen.V24.Types.TypedMessage p0 p1 p2 ->
            Evergreen.V25.Types.TypedMessage (p0 |> migrate_Id_Id) (p1 |> migrate_Id_Id) p2

        Evergreen.V24.Types.PressedSendMessage p0 p1 ->
            Evergreen.V25.Types.PressedSendMessage (p0 |> migrate_Id_Id) (p1 |> migrate_Id_Id)

        Evergreen.V24.Types.NewChannelFormChanged p0 p1 ->
            Evergreen.V25.Types.NewChannelFormChanged (p0 |> migrate_Id_Id)
                (p1 |> migrate_Types_NewChannelForm)

        Evergreen.V24.Types.PressedSubmitNewChannel p0 p1 ->
            Evergreen.V25.Types.PressedSubmitNewChannel (p0 |> migrate_Id_Id)
                (p1 |> migrate_Types_NewChannelForm)

        Evergreen.V24.Types.MouseEnteredChannelName p0 p1 ->
            Evergreen.V25.Types.MouseEnteredChannelName (p0 |> migrate_Id_Id) (p1 |> migrate_Id_Id)

        Evergreen.V24.Types.MouseExitedChannelName p0 p1 ->
            Evergreen.V25.Types.MouseExitedChannelName (p0 |> migrate_Id_Id) (p1 |> migrate_Id_Id)

        Evergreen.V24.Types.EditChannelFormChanged p0 p1 p2 ->
            Evergreen.V25.Types.EditChannelFormChanged (p0 |> migrate_Id_Id)
                (p1 |> migrate_Id_Id)
                (p2 |> migrate_Types_NewChannelForm)

        Evergreen.V24.Types.PressedCancelEditChannelChanges p0 p1 ->
            Evergreen.V25.Types.PressedCancelEditChannelChanges (p0 |> migrate_Id_Id) (p1 |> migrate_Id_Id)

        Evergreen.V24.Types.PressedSubmitEditChannelChanges p0 p1 p2 ->
            Evergreen.V25.Types.PressedSubmitEditChannelChanges (p0 |> migrate_Id_Id)
                (p1 |> migrate_Id_Id)
                (p2 |> migrate_Types_NewChannelForm)

        Evergreen.V24.Types.PressedDeleteChannel p0 p1 ->
            Evergreen.V25.Types.PressedDeleteChannel (p0 |> migrate_Id_Id) (p1 |> migrate_Id_Id)

        Evergreen.V24.Types.PressedCreateInviteLink p0 ->
            Evergreen.V25.Types.PressedCreateInviteLink (p0 |> migrate_Id_Id)

        Evergreen.V24.Types.FrontendNoOp ->
            Evergreen.V25.Types.FrontendNoOp

        Evergreen.V24.Types.PressedCopyText p0 ->
            Evergreen.V25.Types.PressedCopyText p0

        Evergreen.V24.Types.PressedCreateGuild ->
            Evergreen.V25.Types.PressedCreateGuild

        Evergreen.V24.Types.NewGuildFormChanged p0 ->
            Evergreen.V25.Types.NewGuildFormChanged (p0 |> migrate_Types_NewGuildForm)

        Evergreen.V24.Types.PressedSubmitNewGuild p0 ->
            Evergreen.V25.Types.PressedSubmitNewGuild (p0 |> migrate_Types_NewGuildForm)

        Evergreen.V24.Types.PressedCancelNewGuild ->
            Evergreen.V25.Types.PressedCancelNewGuild

        Evergreen.V24.Types.DebouncedTyping ->
            Evergreen.V25.Types.DebouncedTyping

        Evergreen.V24.Types.GotPingUserPosition p0 ->
            Evergreen.V25.Types.GotPingUserPosition p0

        Evergreen.V24.Types.PressedPingUser p0 p1 p2 ->
            Evergreen.V25.Types.PressedPingUser (p0 |> migrate_Id_Id) (p1 |> migrate_Id_Id) p2

        Evergreen.V24.Types.SetFocus ->
            Evergreen.V25.Types.SetFocus

        Evergreen.V24.Types.PressedArrowInDropdown p0 p1 ->
            Evergreen.V25.Types.PressedArrowInDropdown (p0 |> migrate_Id_Id) p1

        Evergreen.V24.Types.TextInputGotFocus p0 ->
            Evergreen.V25.Types.TextInputGotFocus p0

        Evergreen.V24.Types.TextInputLostFocus p0 ->
            Evergreen.V25.Types.TextInputLostFocus p0

        Evergreen.V24.Types.KeyDown p0 ->
            Evergreen.V25.Types.KeyDown p0

        Evergreen.V24.Types.MouseEnteredMessage p0 ->
            Evergreen.V25.Types.MouseEnteredMessage p0

        Evergreen.V24.Types.MouseExitedMessage p0 ->
            Evergreen.V25.Types.MouseExitedMessage p0

        Evergreen.V24.Types.AltPressedMessage p0 p1 ->
            Evergreen.V25.Types.AltPressedMessage p0
                (p1 |> migrate_Coord_Coord migrate_CssPixels_CssPixels)

        Evergreen.V24.Types.PressedShowReactionEmojiSelector p0 p1 ->
            Evergreen.V25.Types.PressedShowReactionEmojiSelector p0
                (p1 |> migrate_Coord_Coord migrate_CssPixels_CssPixels)

        Evergreen.V24.Types.PressedEditMessage p0 ->
            Evergreen.V25.Types.PressedEditMessage p0

        Evergreen.V24.Types.PressedEmojiSelectorEmoji p0 ->
            Evergreen.V25.Types.PressedEmojiSelectorEmoji (p0 |> migrate_Emoji_Emoji)

        Evergreen.V24.Types.PressedReactionEmoji_Add p0 p1 ->
            Evergreen.V25.Types.PressedReactionEmoji_Add p0 (p1 |> migrate_Emoji_Emoji)

        Evergreen.V24.Types.PressedReactionEmoji_Remove p0 p1 ->
            Evergreen.V25.Types.PressedReactionEmoji_Remove p0 (p1 |> migrate_Emoji_Emoji)

        Evergreen.V24.Types.GotPingUserPositionForEditMessage p0 ->
            Evergreen.V25.Types.GotPingUserPositionForEditMessage p0

        Evergreen.V24.Types.TypedEditMessage p0 p1 p2 ->
            Evergreen.V25.Types.TypedEditMessage (p0 |> migrate_Id_Id) (p1 |> migrate_Id_Id) p2

        Evergreen.V24.Types.PressedSendEditMessage p0 p1 ->
            Evergreen.V25.Types.PressedSendEditMessage (p0 |> migrate_Id_Id) (p1 |> migrate_Id_Id)

        Evergreen.V24.Types.PressedArrowInDropdownForEditMessage p0 p1 ->
            Evergreen.V25.Types.PressedArrowInDropdownForEditMessage (p0 |> migrate_Id_Id) p1

        Evergreen.V24.Types.PressedPingUserForEditMessage p0 p1 p2 ->
            Evergreen.V25.Types.PressedPingUserForEditMessage (p0 |> migrate_Id_Id) (p1 |> migrate_Id_Id) p2

        Evergreen.V24.Types.PressedArrowUpInEmptyInput p0 p1 ->
            Evergreen.V25.Types.PressedArrowUpInEmptyInput (p0 |> migrate_Id_Id) (p1 |> migrate_Id_Id)

        Evergreen.V24.Types.PressedReply p0 ->
            Evergreen.V25.Types.PressedReply p0

        Evergreen.V24.Types.PressedCloseReplyTo p0 p1 ->
            Evergreen.V25.Types.PressedCloseReplyTo (p0 |> migrate_Id_Id) (p1 |> migrate_Id_Id)

        Evergreen.V24.Types.PressedSpoiler p0 p1 ->
            Evergreen.V25.Types.PressedSpoiler p0 p1

        Evergreen.V24.Types.VisibilityChanged p0 ->
            Evergreen.V25.Types.VisibilityChanged p0

        Evergreen.V24.Types.CheckedNotificationPermission p0 ->
            Evergreen.V25.Types.CheckedNotificationPermission (p0 |> migrate_Ports_NotificationPermission)

        Evergreen.V24.Types.TouchStart p0 p1 ->
            Evergreen.V25.Types.TouchStart p0
                (p1 |> migrate_NonemptyDict_NonemptyDict identity migrate_Types_Touch)

        Evergreen.V24.Types.TouchMoved p0 p1 ->
            Evergreen.V25.Types.TouchMoved p0
                (p1 |> migrate_NonemptyDict_NonemptyDict identity migrate_Types_Touch)

        Evergreen.V24.Types.TouchEnd p0 ->
            Evergreen.V25.Types.TouchEnd p0

        Evergreen.V24.Types.TouchCancel p0 ->
            Evergreen.V25.Types.TouchCancel p0

        Evergreen.V24.Types.OnAnimationFrameDelta p0 ->
            Evergreen.V25.Types.OnAnimationFrameDelta p0

        Evergreen.V24.Types.ScrolledToBottom ->
            Evergreen.V25.Types.ScrolledToBottom

        Evergreen.V24.Types.PressedChannelHeaderBackButton ->
            Evergreen.V25.Types.PressedChannelHeaderBackButton

        Evergreen.V24.Types.UserScrolled p0 ->
            Evergreen.V25.Types.UserScrolled p0

        Evergreen.V24.Types.PressedBody ->
            Evergreen.V25.Types.PressedBody

        Evergreen.V24.Types.PressedReactionEmojiContainer ->
            Evergreen.V25.Types.PressedReactionEmojiContainer

        Evergreen.V24.Types.PressedShowMessageHoverExtraOptions p0 p1 ->
            Evergreen.V25.Types.PressedShowMessageHoverExtraOptions p0
                (p1 |> migrate_Coord_Coord migrate_CssPixels_CssPixels)

        Evergreen.V24.Types.PressedDeleteMessage p0 ->
            Evergreen.V25.Types.PressedDeleteMessage (p0 |> migrate_Types_MessageId)

        Evergreen.V24.Types.PressedReplyLink p0 ->
            Evergreen.V25.Types.PressedReplyLink p0

        Evergreen.V24.Types.ScrolledToMessage ->
            Evergreen.V25.Types.ScrolledToMessage


migrate_Types_MessageId : Evergreen.V24.Types.MessageId -> Evergreen.V25.Types.MessageId
migrate_Types_MessageId old =
    { guildId = old.guildId |> migrate_Id_Id
    , channelId = old.channelId |> migrate_Id_Id
    , messageIndex = old.messageIndex
    }


migrate_Types_NewChannelForm : Evergreen.V24.Types.NewChannelForm -> Evergreen.V25.Types.NewChannelForm
migrate_Types_NewChannelForm old =
    old


migrate_Types_NewGuildForm : Evergreen.V24.Types.NewGuildForm -> Evergreen.V25.Types.NewGuildForm
migrate_Types_NewGuildForm old =
    old


migrate_Types_ScreenCoordinate : Evergreen.V24.Types.ScreenCoordinate -> Evergreen.V25.Types.ScreenCoordinate
migrate_Types_ScreenCoordinate old =
    case old of
        Evergreen.V24.Types.ScreenCoordinate p0 ->
            Evergreen.V25.Types.ScreenCoordinate p0


migrate_Types_Touch : Evergreen.V24.Types.Touch -> Evergreen.V25.Types.Touch
migrate_Types_Touch old =
    { client = old.client |> migrate_Point2d_Point2d migrate_CssPixels_CssPixels migrate_Types_ScreenCoordinate
    , target = old.target
    }


migrate_Ui_Anim_Msg : Evergreen.V24.Ui.Anim.Msg -> Evergreen.V25.Ui.Anim.Msg
migrate_Ui_Anim_Msg old =
    old |> migrate_Internal_Model2_Msg


migrate_User_AdminUiSection : Evergreen.V24.User.AdminUiSection -> Evergreen.V25.User.AdminUiSection
migrate_User_AdminUiSection old =
    case old of
        Evergreen.V24.User.UsersSection ->
            Evergreen.V25.User.UsersSection

        Evergreen.V24.User.LogSection ->
            Evergreen.V25.User.LogSection


migrate_User_EmailNotifications : Evergreen.V24.User.EmailNotifications -> Evergreen.V25.User.EmailNotifications
migrate_User_EmailNotifications old =
    case old of
        Evergreen.V24.User.CheckEvery5Minutes ->
            Evergreen.V25.User.CheckEvery5Minutes

        Evergreen.V24.User.CheckEveryHour ->
            Evergreen.V25.User.CheckEveryHour

        Evergreen.V24.User.NeverNotifyMe ->
            Evergreen.V25.User.NeverNotifyMe
