module Evergreen.Migrate.V263 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Array
import Dict
import Evergreen.V262.AiChat
import Evergreen.V262.Call
import Evergreen.V262.Cloudflare
import Evergreen.V262.Coord
import Evergreen.V262.CssPixels
import Evergreen.V262.Discord
import Evergreen.V262.DmChannel
import Evergreen.V262.Editable
import Evergreen.V262.Emoji
import Evergreen.V262.FileStatus
import Evergreen.V262.Geometry.Types
import Evergreen.V262.Go
import Evergreen.V262.Id
import Evergreen.V262.IdString
import Evergreen.V262.ImageEditor
import Evergreen.V262.Internal.Model2
import Evergreen.V262.Internal.Teleport
import Evergreen.V262.LocalState
import Evergreen.V262.LoginForm
import Evergreen.V262.MessageInput
import Evergreen.V262.MessageView
import Evergreen.V262.NonemptyDict
import Evergreen.V262.NonemptySet
import Evergreen.V262.Pages.Admin
import Evergreen.V262.PersonName
import Evergreen.V262.Point2d
import Evergreen.V262.Ports
import Evergreen.V262.Postmark
import Evergreen.V262.Range
import Evergreen.V262.Route
import Evergreen.V262.SafeJson
import Evergreen.V262.SecretId
import Evergreen.V262.SessionIdHash
import Evergreen.V262.Slack
import Evergreen.V262.Table
import Evergreen.V262.TextEditor
import Evergreen.V262.Touch
import Evergreen.V262.TwoFactorAuthentication
import Evergreen.V262.Types
import Evergreen.V262.Ui.Anim
import Evergreen.V262.User
import Evergreen.V262.UserAgent
import Evergreen.V262.UserSession
import Evergreen.V263.AiChat
import Evergreen.V263.Call
import Evergreen.V263.Cloudflare
import Evergreen.V263.Coord
import Evergreen.V263.CssPixels
import Evergreen.V263.Discord
import Evergreen.V263.DmChannel
import Evergreen.V263.Editable
import Evergreen.V263.Emoji
import Evergreen.V263.FileStatus
import Evergreen.V263.Geometry.Types
import Evergreen.V263.Go
import Evergreen.V263.Id
import Evergreen.V263.IdString
import Evergreen.V263.ImageEditor
import Evergreen.V263.Internal.Model2
import Evergreen.V263.Internal.Teleport
import Evergreen.V263.LocalState
import Evergreen.V263.LoginForm
import Evergreen.V263.MessageInput
import Evergreen.V263.MessageView
import Evergreen.V263.NonemptyDict
import Evergreen.V263.NonemptySet
import Evergreen.V263.Pages.Admin
import Evergreen.V263.PersonName
import Evergreen.V263.Point2d
import Evergreen.V263.Ports
import Evergreen.V263.Postmark
import Evergreen.V263.Range
import Evergreen.V263.Route
import Evergreen.V263.SafeJson
import Evergreen.V263.SecretId
import Evergreen.V263.SessionIdHash
import Evergreen.V263.Slack
import Evergreen.V263.Table
import Evergreen.V263.TextEditor
import Evergreen.V263.Touch
import Evergreen.V263.TwoFactorAuthentication
import Evergreen.V263.Types
import Evergreen.V263.Ui.Anim
import Evergreen.V263.User
import Evergreen.V263.UserAgent
import Evergreen.V263.UserSession
import Lamdera.Migrations exposing (..)
import List
import Maybe
import Quantity
import SeqDict
import SeqSet


frontendModel : Evergreen.V262.Types.FrontendModel -> ModelMigration Evergreen.V263.Types.FrontendModel Evergreen.V263.Types.FrontendMsg
frontendModel old =
    ModelUnchanged


backendModel : Evergreen.V262.Types.BackendModel -> ModelMigration Evergreen.V263.Types.BackendModel Evergreen.V263.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V262.Types.FrontendMsg -> MsgMigration Evergreen.V263.Types.FrontendMsg Evergreen.V263.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V262.Types.ToBackend -> MsgMigration Evergreen.V263.Types.ToBackend Evergreen.V263.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V262.Types.BackendMsg -> MsgMigration Evergreen.V263.Types.BackendMsg Evergreen.V263.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V262.Types.ToFrontend -> MsgMigration Evergreen.V263.Types.ToFrontend Evergreen.V263.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_AiChat_AiModel : Evergreen.V262.AiChat.AiModel -> Evergreen.V263.AiChat.AiModel
migrate_AiChat_AiModel old =
    { id = old.id |> migrate_AiChat_AiModelName
    , inputs = old.inputs
    }


migrate_AiChat_AiModelName : Evergreen.V262.AiChat.AiModelName -> Evergreen.V263.AiChat.AiModelName
migrate_AiChat_AiModelName old =
    case old of
        Evergreen.V262.AiChat.AiModelName p0 ->
            Evergreen.V263.AiChat.AiModelName p0


migrate_AiChat_Msg : Evergreen.V262.AiChat.Msg -> Evergreen.V263.AiChat.Msg
migrate_AiChat_Msg old =
    case old of
        Evergreen.V262.AiChat.TypedMessage p0 ->
            Evergreen.V263.AiChat.TypedMessage p0

        Evergreen.V262.AiChat.PressedSend ->
            Evergreen.V263.AiChat.PressedSend

        Evergreen.V262.AiChat.TypedChatHistory p0 ->
            Evergreen.V263.AiChat.TypedChatHistory p0

        Evergreen.V262.AiChat.PressedKeep p0 ->
            Evergreen.V263.AiChat.PressedKeep (p0 |> migrate_AiChat_ResponseId)

        Evergreen.V262.AiChat.PressedDelete p0 ->
            Evergreen.V263.AiChat.PressedDelete (p0 |> migrate_AiChat_ResponseId)

        Evergreen.V262.AiChat.PressedRetry p0 ->
            Evergreen.V263.AiChat.PressedRetry (p0 |> migrate_AiChat_ResponseId)

        Evergreen.V262.AiChat.PressedChatHistoryContainer ->
            Evergreen.V263.AiChat.PressedChatHistoryContainer

        Evergreen.V262.AiChat.PressedClearChatHistory ->
            Evergreen.V263.AiChat.PressedClearChatHistory

        Evergreen.V262.AiChat.PressedOptionsButton ->
            Evergreen.V263.AiChat.PressedOptionsButton

        Evergreen.V262.AiChat.SelectedAiModel p0 p1 ->
            Evergreen.V263.AiChat.SelectedAiModel p0 (p1 |> migrate_AiChat_AiModelName)

        Evergreen.V262.AiChat.PressedAddModel ->
            Evergreen.V263.AiChat.PressedAddModel

        Evergreen.V262.AiChat.PressedRemoveModel p0 ->
            Evergreen.V263.AiChat.PressedRemoveModel p0

        Evergreen.V262.AiChat.SelectedSendMessageWith p0 ->
            Evergreen.V263.AiChat.SelectedSendMessageWith (p0 |> migrate_AiChat_SendMessageWith)

        Evergreen.V262.AiChat.CheckDebounce p0 ->
            Evergreen.V263.AiChat.CheckDebounce p0

        Evergreen.V262.AiChat.GotLocalStorage p0 ->
            Evergreen.V263.AiChat.GotLocalStorage p0

        Evergreen.V262.AiChat.EditedResponse p0 p1 ->
            Evergreen.V263.AiChat.EditedResponse (p0 |> migrate_AiChat_ResponseId) p1

        Evergreen.V262.AiChat.NoOp ->
            Evergreen.V263.AiChat.NoOp

        Evergreen.V262.AiChat.GotAiModels p0 ->
            Evergreen.V263.AiChat.GotAiModels (p0 |> Result.map (List.map migrate_AiChat_AiModel))


migrate_AiChat_ResponseId : Evergreen.V262.AiChat.ResponseId -> Evergreen.V263.AiChat.ResponseId
migrate_AiChat_ResponseId old =
    case old of
        Evergreen.V262.AiChat.RespondId p0 ->
            Evergreen.V263.AiChat.RespondId p0


migrate_AiChat_SendMessageWith : Evergreen.V262.AiChat.SendMessageWith -> Evergreen.V263.AiChat.SendMessageWith
migrate_AiChat_SendMessageWith old =
    case old of
        Evergreen.V262.AiChat.SendWithEnter ->
            Evergreen.V263.AiChat.SendWithEnter

        Evergreen.V262.AiChat.SendWithShiftEnter ->
            Evergreen.V263.AiChat.SendWithShiftEnter


migrate_Call_CallId : Evergreen.V262.Call.CallId -> Evergreen.V263.Call.CallId
migrate_Call_CallId old =
    case old of
        Evergreen.V262.Call.DmRoomId p0 ->
            Evergreen.V263.Call.DmRoomId (p0 |> migrate_Id_Id)


migrate_Call_ConnectionId : Evergreen.V262.Call.ConnectionId -> Evergreen.V263.Call.ConnectionId
migrate_Call_ConnectionId old =
    { roomId = old.roomId |> migrate_Call_CallId
    , otherClientId = old.otherClientId |> Tuple.mapFirst migrate_Id_Id
    }


migrate_Call_DeviceKind : Evergreen.V262.Call.DeviceKind -> Evergreen.V263.Call.DeviceKind
migrate_Call_DeviceKind old =
    case old of
        Evergreen.V262.Call.AudioInput ->
            Evergreen.V263.Call.AudioInput

        Evergreen.V262.Call.VideoInput ->
            Evergreen.V263.Call.VideoInput

        Evergreen.V262.Call.AudioOutput ->
            Evergreen.V263.Call.AudioOutput


migrate_Call_FromJs : Evergreen.V262.Call.FromJs -> Evergreen.V263.Call.FromJs
migrate_Call_FromJs old =
    case old of
        Evergreen.V262.Call.FromJs_PublishOffer p0 p1 ->
            Evergreen.V263.Call.FromJs_PublishOffer (p0 |> migrate_Cloudflare_Sdp) p1

        Evergreen.V262.Call.FromJs_PublishConnected ->
            Evergreen.V263.Call.FromJs_PublishConnected

        Evergreen.V262.Call.FromJs_PullAnswer p0 p1 ->
            Evergreen.V263.Call.FromJs_PullAnswer (p0 |> migrate_Call_ConnectionId)
                (p1 |> migrate_Cloudflare_Sdp)

        Evergreen.V262.Call.FromJs_RequestPullTracks p0 p1 p2 ->
            Evergreen.V263.Call.FromJs_RequestPullTracks (p0 |> migrate_Call_ConnectionId)
                (p1 |> migrate_Cloudflare_RealtimeSessionId)
                (p2 |> List.map migrate_Cloudflare_TrackName)

        Evergreen.V262.Call.FromJs_GotUserMediaDevices p0 p1 ->
            Evergreen.V263.Call.FromJs_GotUserMediaDevices (p0 |> List.map migrate_Call_MediaDevice)
                (p1 |> List.map migrate_IdString_IdString)

        Evergreen.V262.Call.FromJs_GotUserMediaDevicesError p0 ->
            Evergreen.V263.Call.FromJs_GotUserMediaDevicesError p0

        Evergreen.V262.Call.FromJs_SpeakingChanged p0 p1 ->
            Evergreen.V263.Call.FromJs_SpeakingChanged (p0 |> migrate_Call_LocalOrConnection) p1

        Evergreen.V262.Call.FromJs_StartConnectionError p0 ->
            Evergreen.V263.Call.FromJs_StartConnectionError p0


migrate_Call_LocalOrConnection : Evergreen.V262.Call.LocalOrConnection -> Evergreen.V263.Call.LocalOrConnection
migrate_Call_LocalOrConnection old =
    case old of
        Evergreen.V262.Call.IsLocal ->
            Evergreen.V263.Call.IsLocal

        Evergreen.V262.Call.IsConnection p0 ->
            Evergreen.V263.Call.IsConnection (p0 |> migrate_Call_ConnectionId)


migrate_Call_MediaDevice : Evergreen.V262.Call.MediaDevice -> Evergreen.V263.Call.MediaDevice
migrate_Call_MediaDevice old =
    { deviceId = old.deviceId |> migrate_IdString_IdString
    , groupId = old.groupId
    , kind = old.kind |> migrate_Call_DeviceKind
    , label = old.label
    }


migrate_Call_Msg : Evergreen.V262.Call.Msg -> Evergreen.V263.Call.Msg
migrate_Call_Msg old =
    case old of
        Evergreen.V262.Call.SelectedAudioInputDevice p0 ->
            Evergreen.V263.Call.SelectedAudioInputDevice (p0 |> migrate_IdString_IdString)

        Evergreen.V262.Call.SelectedVideoInputDevice p0 ->
            Evergreen.V263.Call.SelectedVideoInputDevice (p0 |> migrate_IdString_IdString)

        Evergreen.V262.Call.PressedToggleMute ->
            Evergreen.V263.Call.PressedToggleMute

        Evergreen.V262.Call.PressedTogglePauseVideo ->
            Evergreen.V263.Call.PressedTogglePauseVideo

        Evergreen.V262.Call.PressedJoinCall p0 ->
            Evergreen.V263.Call.PressedJoinCall (p0 |> migrate_Call_CallId)

        Evergreen.V262.Call.PressedLeaveCall ->
            Evergreen.V263.Call.PressedLeaveCall

        Evergreen.V262.Call.PressedDownloadRecording p0 ->
            Evergreen.V263.Call.PressedDownloadRecording (p0 |> migrate_Call_CallId)

        Evergreen.V262.Call.PressedCopyError p0 ->
            Evergreen.V263.Call.PressedCopyError p0

        Evergreen.V262.Call.ChangedVolume p0 p1 ->
            Evergreen.V263.Call.ChangedVolume (p0 |> migrate_Call_ConnectionId) p1

        Evergreen.V262.Call.MouseEnterVideoNode p0 ->
            Evergreen.V263.Call.MouseEnterVideoNode (p0 |> migrate_Call_LocalOrConnection)

        Evergreen.V262.Call.MouseExitVideoNode p0 ->
            Evergreen.V263.Call.MouseExitVideoNode (p0 |> migrate_Call_LocalOrConnection)


migrate_Cloudflare_AccountId : Evergreen.V262.Cloudflare.AccountId -> Evergreen.V263.Cloudflare.AccountId
migrate_Cloudflare_AccountId old =
    case old of
        Evergreen.V262.Cloudflare.AccountId p0 ->
            Evergreen.V263.Cloudflare.AccountId p0


migrate_Cloudflare_AnalyticsApiToken : Evergreen.V262.Cloudflare.AnalyticsApiToken -> Evergreen.V263.Cloudflare.AnalyticsApiToken
migrate_Cloudflare_AnalyticsApiToken old =
    case old of
        Evergreen.V262.Cloudflare.AnalyticsApiToken p0 ->
            Evergreen.V263.Cloudflare.AnalyticsApiToken p0


migrate_Cloudflare_AppId : Evergreen.V262.Cloudflare.AppId -> Evergreen.V263.Cloudflare.AppId
migrate_Cloudflare_AppId old =
    case old of
        Evergreen.V262.Cloudflare.AppId p0 ->
            Evergreen.V263.Cloudflare.AppId p0


migrate_Cloudflare_Location : Evergreen.V262.Cloudflare.Location -> Evergreen.V263.Cloudflare.Location
migrate_Cloudflare_Location old =
    case old of
        Evergreen.V262.Cloudflare.Location_Local ->
            Evergreen.V263.Cloudflare.Location_Local

        Evergreen.V262.Cloudflare.Location_Remote ->
            Evergreen.V263.Cloudflare.Location_Remote


migrate_Cloudflare_RealtimeApiToken : Evergreen.V262.Cloudflare.RealtimeApiToken -> Evergreen.V263.Cloudflare.RealtimeApiToken
migrate_Cloudflare_RealtimeApiToken old =
    case old of
        Evergreen.V262.Cloudflare.RealtimeApiToken p0 ->
            Evergreen.V263.Cloudflare.RealtimeApiToken p0


migrate_Cloudflare_RealtimeSessionId : Evergreen.V262.Cloudflare.RealtimeSessionId -> Evergreen.V263.Cloudflare.RealtimeSessionId
migrate_Cloudflare_RealtimeSessionId old =
    case old of
        Evergreen.V262.Cloudflare.SessionId p0 ->
            Evergreen.V263.Cloudflare.SessionId p0


migrate_Cloudflare_Sdp : Evergreen.V262.Cloudflare.Sdp -> Evergreen.V263.Cloudflare.Sdp
migrate_Cloudflare_Sdp old =
    case old of
        Evergreen.V262.Cloudflare.Sdp p0 ->
            Evergreen.V263.Cloudflare.Sdp p0


migrate_Cloudflare_SessionStateResponse : Evergreen.V262.Cloudflare.SessionStateResponse -> Evergreen.V263.Cloudflare.SessionStateResponse
migrate_Cloudflare_SessionStateResponse old =
    { tracks = old.tracks |> List.map migrate_Cloudflare_TrackObject
    }


migrate_Cloudflare_TrackName : Evergreen.V262.Cloudflare.TrackName -> Evergreen.V263.Cloudflare.TrackName
migrate_Cloudflare_TrackName old =
    case old of
        Evergreen.V262.Cloudflare.TrackName p0 ->
            Evergreen.V263.Cloudflare.TrackName p0


migrate_Cloudflare_TrackObject : Evergreen.V262.Cloudflare.TrackObject -> Evergreen.V263.Cloudflare.TrackObject
migrate_Cloudflare_TrackObject old =
    { location = old.location |> migrate_Cloudflare_Location
    , mid = old.mid
    , trackName = old.trackName
    , sessionId = old.sessionId |> Maybe.map migrate_Cloudflare_RealtimeSessionId
    , status = old.status |> migrate_Cloudflare_TrackStatus
    }


migrate_Cloudflare_TrackStatus : Evergreen.V262.Cloudflare.TrackStatus -> Evergreen.V263.Cloudflare.TrackStatus
migrate_Cloudflare_TrackStatus old =
    case old of
        Evergreen.V262.Cloudflare.TrackActive ->
            Evergreen.V263.Cloudflare.TrackActive

        Evergreen.V262.Cloudflare.TrackInactive ->
            Evergreen.V263.Cloudflare.TrackInactive

        Evergreen.V262.Cloudflare.TrackWaiting ->
            Evergreen.V263.Cloudflare.TrackWaiting


migrate_Coord_Coord : (units_old -> units_new) -> Evergreen.V262.Coord.Coord units_old -> Evergreen.V263.Coord.Coord units_new
migrate_Coord_Coord migrate_units old =
    old |> Tuple.mapBoth migrate_Quantity_Quantity migrate_Quantity_Quantity


migrate_CssPixels_CssPixels : Evergreen.V262.CssPixels.CssPixels -> Evergreen.V263.CssPixels.CssPixels
migrate_CssPixels_CssPixels old =
    case old of
        Evergreen.V262.CssPixels.CssPixels p0 ->
            Evergreen.V263.CssPixels.CssPixels p0


migrate_Discord_Id : Evergreen.V262.Discord.Id idType_old -> Evergreen.V263.Discord.Id idType_new
migrate_Discord_Id old =
    case old of
        Evergreen.V262.Discord.Id p0 ->
            Evergreen.V263.Discord.Id p0


migrate_Discord_UserAuth : Evergreen.V262.Discord.UserAuth -> Evergreen.V263.Discord.UserAuth
migrate_Discord_UserAuth old =
    { token = old.token
    , userAgent = old.userAgent
    , xSuperProperties = old.xSuperProperties |> migrate_SafeJson_SafeJson
    }


migrate_DmChannel_DmChannelId : Evergreen.V262.DmChannel.DmChannelId -> Evergreen.V263.DmChannel.DmChannelId
migrate_DmChannel_DmChannelId old =
    case old of
        Evergreen.V262.DmChannel.DmChannelId p0 p1 ->
            Evergreen.V263.DmChannel.DmChannelId (p0 |> migrate_Id_Id) (p1 |> migrate_Id_Id)


migrate_Editable_Editing : Evergreen.V262.Editable.Editing -> Evergreen.V263.Editable.Editing
migrate_Editable_Editing old =
    case old of
        Evergreen.V262.Editable.NotEditing ->
            Evergreen.V263.Editable.NotEditing

        Evergreen.V262.Editable.Editing p0 ->
            Evergreen.V263.Editable.Editing p0


migrate_Editable_Model : Evergreen.V262.Editable.Model -> Evergreen.V263.Editable.Model
migrate_Editable_Model old =
    { editing = old.editing |> migrate_Editable_Editing
    , pressedSubmit = old.pressedSubmit
    , showSecret = old.showSecret
    }


migrate_Editable_Msg : (value_old -> value_new) -> Evergreen.V262.Editable.Msg value_old -> Evergreen.V263.Editable.Msg value_new
migrate_Editable_Msg migrate_value old =
    case old of
        Evergreen.V262.Editable.Edit p0 ->
            Evergreen.V263.Editable.Edit (p0 |> migrate_Editable_Model)

        Evergreen.V262.Editable.PressedAcceptEdit p0 ->
            Evergreen.V263.Editable.PressedAcceptEdit (p0 |> migrate_value)


migrate_Emoji_CachedEmojiData : Evergreen.V262.Emoji.CachedEmojiData -> Evergreen.V263.Emoji.CachedEmojiData
migrate_Emoji_CachedEmojiData old =
    { emojis = old.emojis |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Emoji_UnicodeEmoji migrate_Emoji_EmojiData) |> SeqDict.fromList
    , categories = old.categories |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Emoji_EmojiCategory (List.map migrate_Emoji_UnicodeEmoji)) |> SeqDict.fromList
    , shortNames =
        old.shortNames
            |> Array.map
                (\rec ->
                    { shortName = rec.shortName
                    , emoji = rec.emoji |> migrate_Emoji_UnicodeEmoji
                    }
                )
    }


migrate_Emoji_Category : Evergreen.V262.Emoji.Category -> Evergreen.V263.Emoji.Category
migrate_Emoji_Category old =
    case old of
        Evergreen.V262.Emoji.EmojiCategory p0 ->
            Evergreen.V263.Emoji.EmojiCategory (p0 |> migrate_Emoji_EmojiCategory)

        Evergreen.V262.Emoji.StickerCategory ->
            Evergreen.V263.Emoji.StickerCategory

        Evergreen.V262.Emoji.CustomEmojiCategory ->
            Evergreen.V263.Emoji.CustomEmojiCategory


migrate_Emoji_EmojiCategory : Evergreen.V262.Emoji.EmojiCategory -> Evergreen.V263.Emoji.EmojiCategory
migrate_Emoji_EmojiCategory old =
    case old of
        Evergreen.V262.Emoji.Activities ->
            Evergreen.V263.Emoji.Activities

        Evergreen.V262.Emoji.AnimalsAndNature ->
            Evergreen.V263.Emoji.AnimalsAndNature

        Evergreen.V262.Emoji.Components ->
            Evergreen.V263.Emoji.Components

        Evergreen.V262.Emoji.Flags ->
            Evergreen.V263.Emoji.Flags

        Evergreen.V262.Emoji.FoodAndDrink ->
            Evergreen.V263.Emoji.FoodAndDrink

        Evergreen.V262.Emoji.Objects ->
            Evergreen.V263.Emoji.Objects

        Evergreen.V262.Emoji.PeopleAndBody ->
            Evergreen.V263.Emoji.PeopleAndBody

        Evergreen.V262.Emoji.SmileysAndEmotion ->
            Evergreen.V263.Emoji.SmileysAndEmotion

        Evergreen.V262.Emoji.Symbols ->
            Evergreen.V263.Emoji.Symbols

        Evergreen.V262.Emoji.TravelAndPlaces ->
            Evergreen.V263.Emoji.TravelAndPlaces


migrate_Emoji_EmojiData : Evergreen.V262.Emoji.EmojiData -> Evergreen.V263.Emoji.EmojiData
migrate_Emoji_EmojiData old =
    old


migrate_Emoji_EmojiOrCustomEmoji : Evergreen.V262.Emoji.EmojiOrCustomEmoji -> Evergreen.V263.Emoji.EmojiOrCustomEmoji
migrate_Emoji_EmojiOrCustomEmoji old =
    case old of
        Evergreen.V262.Emoji.EmojiOrCustomEmoji_Emoji p0 ->
            Evergreen.V263.Emoji.EmojiOrCustomEmoji_Emoji (p0 |> migrate_Emoji_UnicodeEmoji)

        Evergreen.V262.Emoji.EmojiOrCustomEmoji_CustomEmoji p0 ->
            Evergreen.V263.Emoji.EmojiOrCustomEmoji_CustomEmoji (p0 |> migrate_Id_Id)


migrate_Emoji_EmojiOrSticker : Evergreen.V262.Emoji.EmojiOrSticker -> Evergreen.V263.Emoji.EmojiOrSticker
migrate_Emoji_EmojiOrSticker old =
    case old of
        Evergreen.V262.Emoji.EmojiOrSticker_UnicodeEmoji p0 ->
            Evergreen.V263.Emoji.EmojiOrSticker_UnicodeEmoji (p0 |> migrate_Emoji_UnicodeEmoji)

        Evergreen.V262.Emoji.EmojiOrSticker_Sticker p0 ->
            Evergreen.V263.Emoji.EmojiOrSticker_Sticker (p0 |> migrate_Id_Id)

        Evergreen.V262.Emoji.EmojiOrSticker_CustomEmoji p0 ->
            Evergreen.V263.Emoji.EmojiOrSticker_CustomEmoji (p0 |> migrate_Id_Id)


migrate_Emoji_Msg : Evergreen.V262.Emoji.Msg -> Evergreen.V263.Emoji.Msg
migrate_Emoji_Msg old =
    case old of
        Evergreen.V262.Emoji.PressedContainer ->
            Evergreen.V263.Emoji.PressedContainer

        Evergreen.V262.Emoji.PressedCategory p0 ->
            Evergreen.V263.Emoji.PressedCategory (p0 |> migrate_Emoji_Category)

        Evergreen.V262.Emoji.PressedSelectEmoji p0 ->
            Evergreen.V263.Emoji.PressedSelectEmoji (p0 |> migrate_Emoji_EmojiOrSticker)

        Evergreen.V262.Emoji.PressedSkinTone p0 ->
            Evergreen.V263.Emoji.PressedSkinTone (p0 |> Maybe.map migrate_Emoji_SkinTone)

        Evergreen.V262.Emoji.MouseEnteredEmoji p0 ->
            Evergreen.V263.Emoji.MouseEnteredEmoji (p0 |> migrate_Emoji_EmojiOrSticker)

        Evergreen.V262.Emoji.KeyboardMovedHover p0 p1 ->
            Evergreen.V263.Emoji.KeyboardMovedHover (p0 |> migrate_Emoji_EmojiOrSticker) p1

        Evergreen.V262.Emoji.ClearEmojiHover ->
            Evergreen.V263.Emoji.ClearEmojiHover

        Evergreen.V262.Emoji.TypedSearchText p0 ->
            Evergreen.V263.Emoji.TypedSearchText p0

        Evergreen.V262.Emoji.PressedClearSearch ->
            Evergreen.V263.Emoji.PressedClearSearch

        Evergreen.V262.Emoji.NoOp ->
            Evergreen.V263.Emoji.NoOp


migrate_Emoji_SkinTone : Evergreen.V262.Emoji.SkinTone -> Evergreen.V263.Emoji.SkinTone
migrate_Emoji_SkinTone old =
    case old of
        Evergreen.V262.Emoji.SkinTone1 ->
            Evergreen.V263.Emoji.SkinTone1

        Evergreen.V262.Emoji.SkinTone2 ->
            Evergreen.V263.Emoji.SkinTone2

        Evergreen.V262.Emoji.SkinTone3 ->
            Evergreen.V263.Emoji.SkinTone3

        Evergreen.V262.Emoji.SkinTone4 ->
            Evergreen.V263.Emoji.SkinTone4

        Evergreen.V262.Emoji.SkinTone5 ->
            Evergreen.V263.Emoji.SkinTone5


migrate_Emoji_UnicodeEmoji : Evergreen.V262.Emoji.UnicodeEmoji -> Evergreen.V263.Emoji.UnicodeEmoji
migrate_Emoji_UnicodeEmoji old =
    case old of
        Evergreen.V262.Emoji.UnicodeEmoji p0 ->
            Evergreen.V263.Emoji.UnicodeEmoji p0


migrate_FileStatus_FileHash : Evergreen.V262.FileStatus.FileHash -> Evergreen.V263.FileStatus.FileHash
migrate_FileStatus_FileHash old =
    case old of
        Evergreen.V262.FileStatus.FileHash p0 ->
            Evergreen.V263.FileStatus.FileHash p0


migrate_FileStatus_ImageMetadata : Evergreen.V262.FileStatus.ImageMetadata -> Evergreen.V263.FileStatus.ImageMetadata
migrate_FileStatus_ImageMetadata old =
    { imageSize = old.imageSize |> migrate_Coord_Coord migrate_CssPixels_CssPixels
    , orientation = old.orientation |> Maybe.map migrate_FileStatus_Orientation
    , gpsLocation = old.gpsLocation
    , cameraOwner = old.cameraOwner
    , exposureTime = old.exposureTime
    , fNumber = old.fNumber
    , focalLength = old.focalLength
    , isoSpeedRating = old.isoSpeedRating
    , make = old.make
    , model = old.model
    , software = old.software
    , userComment = old.userComment
    }


migrate_FileStatus_Orientation : Evergreen.V262.FileStatus.Orientation -> Evergreen.V263.FileStatus.Orientation
migrate_FileStatus_Orientation old =
    case old of
        Evergreen.V262.FileStatus.NoChange ->
            Evergreen.V263.FileStatus.NoChange

        Evergreen.V262.FileStatus.Rotation90 ->
            Evergreen.V263.FileStatus.Rotation90

        Evergreen.V262.FileStatus.Rotation180 ->
            Evergreen.V263.FileStatus.Rotation180

        Evergreen.V262.FileStatus.Rotation270 ->
            Evergreen.V263.FileStatus.Rotation270

        Evergreen.V262.FileStatus.Mirrored ->
            Evergreen.V263.FileStatus.Mirrored

        Evergreen.V262.FileStatus.MirroredRotation90 ->
            Evergreen.V263.FileStatus.MirroredRotation90

        Evergreen.V262.FileStatus.MirroredRotation180 ->
            Evergreen.V263.FileStatus.MirroredRotation180

        Evergreen.V262.FileStatus.MirroredRotation270 ->
            Evergreen.V263.FileStatus.MirroredRotation270


migrate_FileStatus_UploadResponse : Evergreen.V262.FileStatus.UploadResponse -> Evergreen.V263.FileStatus.UploadResponse
migrate_FileStatus_UploadResponse old =
    { fileHash = old.fileHash |> migrate_FileStatus_FileHash
    , imageSize = old.imageSize |> Maybe.map migrate_FileStatus_ImageMetadata
    }


migrate_Geometry_Types_Point2d : Evergreen.V262.Geometry.Types.Point2d units_old coordinates_old -> Evergreen.V263.Geometry.Types.Point2d units_new coordinates_new
migrate_Geometry_Types_Point2d old =
    case old of
        Evergreen.V262.Geometry.Types.Point2d p0 ->
            Evergreen.V263.Geometry.Types.Point2d p0


migrate_Go_GameMsg : Evergreen.V262.Go.GameMsg -> Evergreen.V263.Go.GameMsg
migrate_Go_GameMsg old =
    case old of
        Evergreen.V262.Go.PressedCell p0 p1 ->
            Evergreen.V263.Go.PressedCell p0 p1

        Evergreen.V262.Go.PressedPass ->
            Evergreen.V263.Go.PressedPass

        Evergreen.V262.Go.PressedDoneMarking ->
            Evergreen.V263.Go.PressedDoneMarking

        Evergreen.V262.Go.PressedAgree ->
            Evergreen.V263.Go.PressedAgree

        Evergreen.V262.Go.PressedDisagree ->
            Evergreen.V263.Go.PressedDisagree

        Evergreen.V262.Go.SpectatorMsg p0 ->
            Evergreen.V263.Go.SpectatorMsg (p0 |> migrate_Go_SpectatorMsg)


migrate_Go_Msg : Evergreen.V262.Go.Msg -> Evergreen.V263.Go.Msg
migrate_Go_Msg old =
    case old of
        Evergreen.V262.Go.GameMsg p0 ->
            Evergreen.V263.Go.GameMsg (p0 |> migrate_Go_GameMsg)

        Evergreen.V262.Go.SetupMsg p0 ->
            Evergreen.V263.Go.SetupMsg (p0 |> migrate_Go_SetupMsg)

        Evergreen.V262.Go.SelectedMatch p0 ->
            Evergreen.V263.Go.SelectedMatch (p0 |> Maybe.map migrate_Id_Id)

        Evergreen.V262.Go.PressedReset ->
            Evergreen.V263.Go.PressedReset

        Evergreen.V262.Go.PressedShareGoMatch p0 ->
            Evergreen.V263.Go.PressedShareGoMatch (p0 |> migrate_Id_Id)

        Evergreen.V262.Go.PressedCopyLink p0 ->
            Evergreen.V263.Go.PressedCopyLink p0

        Evergreen.V262.Go.NoOpMsg ->
            Evergreen.V263.Go.NoOpMsg


migrate_Go_SetupMsg : Evergreen.V262.Go.SetupMsg -> Evergreen.V263.Go.SetupMsg
migrate_Go_SetupMsg old =
    case old of
        Evergreen.V262.Go.ChangedWidthInput p0 ->
            Evergreen.V263.Go.ChangedWidthInput p0

        Evergreen.V262.Go.ChangedHeightInput p0 ->
            Evergreen.V263.Go.ChangedHeightInput p0

        Evergreen.V262.Go.ChangedHandicapInput p0 ->
            Evergreen.V263.Go.ChangedHandicapInput p0

        Evergreen.V262.Go.ChangedKomiInput p0 ->
            Evergreen.V263.Go.ChangedKomiInput p0

        Evergreen.V262.Go.ChangedMainTimeInput p0 ->
            Evergreen.V263.Go.ChangedMainTimeInput p0

        Evergreen.V262.Go.ChangedIncrementInput p0 ->
            Evergreen.V263.Go.ChangedIncrementInput p0

        Evergreen.V262.Go.SelectedSize p0 ->
            Evergreen.V263.Go.SelectedSize (p0 |> migrate_Go_SizeSelection)

        Evergreen.V262.Go.SelectedPlayingAs p0 ->
            Evergreen.V263.Go.SelectedPlayingAs (p0 |> migrate_Go_Stone)

        Evergreen.V262.Go.PressedStartGame ->
            Evergreen.V263.Go.PressedStartGame


migrate_Go_SizeSelection : Evergreen.V262.Go.SizeSelection -> Evergreen.V263.Go.SizeSelection
migrate_Go_SizeSelection old =
    case old of
        Evergreen.V262.Go.Standard9 ->
            Evergreen.V263.Go.Standard9

        Evergreen.V262.Go.Standard13 ->
            Evergreen.V263.Go.Standard13

        Evergreen.V262.Go.Standard19 ->
            Evergreen.V263.Go.Standard19

        Evergreen.V262.Go.CustomSize ->
            Evergreen.V263.Go.CustomSize


migrate_Go_SpectatorMsg : Evergreen.V262.Go.SpectatorMsg -> Evergreen.V263.Go.SpectatorMsg
migrate_Go_SpectatorMsg old =
    case old of
        Evergreen.V262.Go.PressedArrowLeft ->
            Evergreen.V263.Go.PressedArrowLeft

        Evergreen.V262.Go.PressedArrowRight ->
            Evergreen.V263.Go.PressedArrowRight

        Evergreen.V262.Go.ChangedViewingMove p0 ->
            Evergreen.V263.Go.ChangedViewingMove p0


migrate_Go_Stone : Evergreen.V262.Go.Stone -> Evergreen.V263.Go.Stone
migrate_Go_Stone old =
    case old of
        Evergreen.V262.Go.Black ->
            Evergreen.V263.Go.Black

        Evergreen.V262.Go.White ->
            Evergreen.V263.Go.White


migrate_IdString_IdString : Evergreen.V262.IdString.IdString a_old -> Evergreen.V263.IdString.IdString a_new
migrate_IdString_IdString old =
    case old of
        Evergreen.V262.IdString.IdString p0 ->
            Evergreen.V263.IdString.IdString p0


migrate_Id_AnyGuildOrDmId : Evergreen.V262.Id.AnyGuildOrDmId -> Evergreen.V263.Id.AnyGuildOrDmId
migrate_Id_AnyGuildOrDmId old =
    case old of
        Evergreen.V262.Id.GuildOrDmId p0 ->
            Evergreen.V263.Id.GuildOrDmId (p0 |> migrate_Id_GuildOrDmId)

        Evergreen.V262.Id.DiscordGuildOrDmId p0 ->
            Evergreen.V263.Id.DiscordGuildOrDmId (p0 |> migrate_Id_DiscordGuildOrDmId)


migrate_Id_DiscordGuildOrDmId : Evergreen.V262.Id.DiscordGuildOrDmId -> Evergreen.V263.Id.DiscordGuildOrDmId
migrate_Id_DiscordGuildOrDmId old =
    case old of
        Evergreen.V262.Id.DiscordGuildOrDmId_Guild p0 p1 p2 ->
            Evergreen.V263.Id.DiscordGuildOrDmId_Guild (p0 |> migrate_Discord_Id)
                (p1 |> migrate_Discord_Id)
                (p2 |> migrate_Discord_Id)

        Evergreen.V262.Id.DiscordGuildOrDmId_Dm p0 ->
            Evergreen.V263.Id.DiscordGuildOrDmId_Dm (p0 |> migrate_Id_DiscordGuildOrDmId_DmData)


migrate_Id_DiscordGuildOrDmId_DmData : Evergreen.V262.Id.DiscordGuildOrDmId_DmData -> Evergreen.V263.Id.DiscordGuildOrDmId_DmData
migrate_Id_DiscordGuildOrDmId_DmData old =
    { currentUserId = old.currentUserId |> migrate_Discord_Id
    , channelId = old.channelId |> migrate_Discord_Id
    }


migrate_Id_GuildOrDmId : Evergreen.V262.Id.GuildOrDmId -> Evergreen.V263.Id.GuildOrDmId
migrate_Id_GuildOrDmId old =
    case old of
        Evergreen.V262.Id.GuildOrDmId_Guild p0 p1 ->
            Evergreen.V263.Id.GuildOrDmId_Guild (p0 |> migrate_Id_Id) (p1 |> migrate_Id_Id)

        Evergreen.V262.Id.GuildOrDmId_Dm p0 ->
            Evergreen.V263.Id.GuildOrDmId_Dm (p0 |> migrate_Id_Id)


migrate_Id_Id : Evergreen.V262.Id.Id a_old -> Evergreen.V263.Id.Id a_new
migrate_Id_Id old =
    case old of
        Evergreen.V262.Id.Id p0 ->
            Evergreen.V263.Id.Id p0


migrate_Id_ThreadRoute : Evergreen.V262.Id.ThreadRoute -> Evergreen.V263.Id.ThreadRoute
migrate_Id_ThreadRoute old =
    case old of
        Evergreen.V262.Id.NoThread ->
            Evergreen.V263.Id.NoThread

        Evergreen.V262.Id.ViewThread p0 ->
            Evergreen.V263.Id.ViewThread (p0 |> migrate_Id_Id)


migrate_Id_ThreadRouteWithMessage : Evergreen.V262.Id.ThreadRouteWithMessage -> Evergreen.V263.Id.ThreadRouteWithMessage
migrate_Id_ThreadRouteWithMessage old =
    case old of
        Evergreen.V262.Id.NoThreadWithMessage p0 ->
            Evergreen.V263.Id.NoThreadWithMessage (p0 |> migrate_Id_Id)

        Evergreen.V262.Id.ViewThreadWithMessage p0 p1 ->
            Evergreen.V263.Id.ViewThreadWithMessage (p0 |> migrate_Id_Id) (p1 |> migrate_Id_Id)


migrate_ImageEditor_Msg : Evergreen.V262.ImageEditor.Msg -> Evergreen.V263.ImageEditor.Msg
migrate_ImageEditor_Msg old =
    case old of
        Evergreen.V262.ImageEditor.PressedProfileImage ->
            Evergreen.V263.ImageEditor.PressedProfileImage

        Evergreen.V262.ImageEditor.SelectedImage p0 ->
            Evergreen.V263.ImageEditor.SelectedImage p0

        Evergreen.V262.ImageEditor.GotImageUrl p0 ->
            Evergreen.V263.ImageEditor.GotImageUrl p0

        Evergreen.V262.ImageEditor.MouseDownImageEditor p0 p1 ->
            Evergreen.V263.ImageEditor.MouseDownImageEditor p0 p1

        Evergreen.V262.ImageEditor.MouseUpImageEditor ->
            Evergreen.V263.ImageEditor.MouseUpImageEditor

        Evergreen.V262.ImageEditor.MovedImageEditor p0 p1 ->
            Evergreen.V263.ImageEditor.MovedImageEditor p0 p1

        Evergreen.V262.ImageEditor.TouchEndImageEditor ->
            Evergreen.V263.ImageEditor.TouchEndImageEditor

        Evergreen.V262.ImageEditor.PressedConfirmImage ->
            Evergreen.V263.ImageEditor.PressedConfirmImage

        Evergreen.V262.ImageEditor.GotImageSize p0 ->
            Evergreen.V263.ImageEditor.GotImageSize p0

        Evergreen.V262.ImageEditor.CroppedImage p0 ->
            Evergreen.V263.ImageEditor.CroppedImage p0

        Evergreen.V262.ImageEditor.PressedCancel ->
            Evergreen.V263.ImageEditor.PressedCancel

        Evergreen.V262.ImageEditor.UploadedImage p0 ->
            Evergreen.V263.ImageEditor.UploadedImage (p0 |> Result.map migrate_FileStatus_UploadResponse)


migrate_Internal_Model2_Msg : Evergreen.V262.Internal.Model2.Msg -> Evergreen.V263.Internal.Model2.Msg
migrate_Internal_Model2_Msg old =
    case old of
        Evergreen.V262.Internal.Model2.Tick p0 ->
            Evergreen.V263.Internal.Model2.Tick p0

        Evergreen.V262.Internal.Model2.Teleported p0 p1 ->
            Evergreen.V263.Internal.Model2.Teleported (p0 |> migrate_Internal_Teleport_Trigger)
                (p1 |> migrate_Internal_Teleport_Event)


migrate_Internal_Teleport_CssAnimation : Evergreen.V262.Internal.Teleport.CssAnimation -> Evergreen.V263.Internal.Teleport.CssAnimation
migrate_Internal_Teleport_CssAnimation old =
    old


migrate_Internal_Teleport_Data : Evergreen.V262.Internal.Teleport.Data -> Evergreen.V263.Internal.Teleport.Data
migrate_Internal_Teleport_Data old =
    case old of
        Evergreen.V262.Internal.Teleport.Css p0 ->
            Evergreen.V263.Internal.Teleport.Css (p0 |> migrate_Internal_Teleport_CssAnimation)

        Evergreen.V262.Internal.Teleport.ParentTrigger p0 ->
            Evergreen.V263.Internal.Teleport.ParentTrigger (p0 |> migrate_Internal_Teleport_ParentTriggerDetails)


migrate_Internal_Teleport_Event : Evergreen.V262.Internal.Teleport.Event -> Evergreen.V263.Internal.Teleport.Event
migrate_Internal_Teleport_Event old =
    { timestamp = old.timestamp
    , data = old.data |> List.map migrate_Internal_Teleport_Data
    }


migrate_Internal_Teleport_ParentTriggerDetails : Evergreen.V262.Internal.Teleport.ParentTriggerDetails -> Evergreen.V263.Internal.Teleport.ParentTriggerDetails
migrate_Internal_Teleport_ParentTriggerDetails old =
    old


migrate_Internal_Teleport_Trigger : Evergreen.V262.Internal.Teleport.Trigger -> Evergreen.V263.Internal.Teleport.Trigger
migrate_Internal_Teleport_Trigger old =
    case old of
        Evergreen.V262.Internal.Teleport.OnHover ->
            Evergreen.V263.Internal.Teleport.OnHover

        Evergreen.V262.Internal.Teleport.OnRender ->
            Evergreen.V263.Internal.Teleport.OnRender

        Evergreen.V262.Internal.Teleport.OnFocus ->
            Evergreen.V263.Internal.Teleport.OnFocus

        Evergreen.V262.Internal.Teleport.OnFocusWithin ->
            Evergreen.V263.Internal.Teleport.OnFocusWithin

        Evergreen.V262.Internal.Teleport.OnActive ->
            Evergreen.V263.Internal.Teleport.OnActive

        Evergreen.V262.Internal.Teleport.OnDismount ->
            Evergreen.V263.Internal.Teleport.OnDismount


migrate_LocalState_PrivateVapidKey : Evergreen.V262.LocalState.PrivateVapidKey -> Evergreen.V263.LocalState.PrivateVapidKey
migrate_LocalState_PrivateVapidKey old =
    case old of
        Evergreen.V262.LocalState.PrivateVapidKey p0 ->
            Evergreen.V263.LocalState.PrivateVapidKey p0


migrate_LoginForm_Msg : Evergreen.V262.LoginForm.Msg -> Evergreen.V263.LoginForm.Msg
migrate_LoginForm_Msg old =
    case old of
        Evergreen.V262.LoginForm.PressedSubmitEmail ->
            Evergreen.V263.LoginForm.PressedSubmitEmail

        Evergreen.V262.LoginForm.PressedCancelLogin ->
            Evergreen.V263.LoginForm.PressedCancelLogin

        Evergreen.V262.LoginForm.TypedLoginFormEmail p0 ->
            Evergreen.V263.LoginForm.TypedLoginFormEmail p0

        Evergreen.V262.LoginForm.TypedLoginCode p0 ->
            Evergreen.V263.LoginForm.TypedLoginCode p0

        Evergreen.V262.LoginForm.TypedTwoFactorCode p0 ->
            Evergreen.V263.LoginForm.TypedTwoFactorCode p0

        Evergreen.V262.LoginForm.TypedName p0 ->
            Evergreen.V263.LoginForm.TypedName p0

        Evergreen.V262.LoginForm.PressedSubmitUserData ->
            Evergreen.V263.LoginForm.PressedSubmitUserData


migrate_MessageInput_Msg : Evergreen.V262.MessageInput.Msg -> Evergreen.V263.MessageInput.Msg
migrate_MessageInput_Msg old =
    case old of
        Evergreen.V262.MessageInput.PressedTextInput ->
            Evergreen.V263.MessageInput.PressedTextInput

        Evergreen.V262.MessageInput.TypedMessage p0 ->
            Evergreen.V263.MessageInput.TypedMessage p0

        Evergreen.V262.MessageInput.PressedSendMessage p0 ->
            Evergreen.V263.MessageInput.PressedSendMessage p0

        Evergreen.V262.MessageInput.PressedArrowInDropdown p0 ->
            Evergreen.V263.MessageInput.PressedArrowInDropdown p0

        Evergreen.V262.MessageInput.PressedArrowUpInEmptyInput ->
            Evergreen.V263.MessageInput.PressedArrowUpInEmptyInput

        Evergreen.V262.MessageInput.PressedDropdownItem p0 ->
            Evergreen.V263.MessageInput.PressedDropdownItem p0

        Evergreen.V262.MessageInput.PressedPingDropdownContainer ->
            Evergreen.V263.MessageInput.PressedPingDropdownContainer

        Evergreen.V262.MessageInput.PressedUploadFile ->
            Evergreen.V263.MessageInput.PressedUploadFile

        Evergreen.V262.MessageInput.PressedOpenEmojiSelector ->
            Evergreen.V263.MessageInput.PressedOpenEmojiSelector

        Evergreen.V262.MessageInput.OnPasteFiles p0 ->
            Evergreen.V263.MessageInput.OnPasteFiles p0

        Evergreen.V262.MessageInput.TypedPageUp ->
            Evergreen.V263.MessageInput.TypedPageUp

        Evergreen.V262.MessageInput.TypedPageDown ->
            Evergreen.V263.MessageInput.TypedPageDown


migrate_MessageView_MessageViewMsg : Evergreen.V262.MessageView.MessageViewMsg -> Evergreen.V263.MessageView.MessageViewMsg
migrate_MessageView_MessageViewMsg old =
    case old of
        Evergreen.V262.MessageView.MessageView_PressedSpoiler p0 ->
            Evergreen.V263.MessageView.MessageView_PressedSpoiler p0

        Evergreen.V262.MessageView.MessageView_PressedNonWhitelistLink p0 ->
            Evergreen.V263.MessageView.MessageView_PressedNonWhitelistLink p0

        Evergreen.V262.MessageView.MessageView_MouseEnteredMessage ->
            Evergreen.V263.MessageView.MessageView_MouseEnteredMessage

        Evergreen.V262.MessageView.MessageView_MouseExitedMessage ->
            Evergreen.V263.MessageView.MessageView_MouseExitedMessage

        Evergreen.V262.MessageView.MessageView_TouchStart p0 p1 p2 ->
            Evergreen.V263.MessageView.MessageView_TouchStart p0
                p1
                (p2 |> migrate_NonemptyDict_NonemptyDict identity migrate_Touch_Touch)

        Evergreen.V262.MessageView.MessageView_AltPressedMessage p0 p1 ->
            Evergreen.V263.MessageView.MessageView_AltPressedMessage p0
                (p1 |> migrate_Coord_Coord migrate_CssPixels_CssPixels)

        Evergreen.V262.MessageView.MessageView_PressedReactionEmoji_Remove p0 ->
            Evergreen.V263.MessageView.MessageView_PressedReactionEmoji_Remove (p0 |> migrate_Emoji_EmojiOrCustomEmoji)

        Evergreen.V262.MessageView.MessageView_PressedReactionEmoji_Add p0 ->
            Evergreen.V263.MessageView.MessageView_PressedReactionEmoji_Add (p0 |> migrate_Emoji_EmojiOrCustomEmoji)

        Evergreen.V262.MessageView.MessageView_PressedReplyLink ->
            Evergreen.V263.MessageView.MessageView_PressedReplyLink

        Evergreen.V262.MessageView.MessageViewMsg_PressedShowReactionEmojiSelector ->
            Evergreen.V263.MessageView.MessageViewMsg_PressedShowReactionEmojiSelector

        Evergreen.V262.MessageView.MessageViewMsg_PressedEditMessage ->
            Evergreen.V263.MessageView.MessageViewMsg_PressedEditMessage

        Evergreen.V262.MessageView.MessageViewMsg_PressedReply ->
            Evergreen.V263.MessageView.MessageViewMsg_PressedReply

        Evergreen.V262.MessageView.MessageViewMsg_PressedShowFullMenu p0 p1 ->
            Evergreen.V263.MessageView.MessageViewMsg_PressedShowFullMenu p0
                (p1 |> migrate_Coord_Coord migrate_CssPixels_CssPixels)

        Evergreen.V262.MessageView.MessageView_PressedViewThreadLink ->
            Evergreen.V263.MessageView.MessageView_PressedViewThreadLink

        Evergreen.V262.MessageView.MessageView_NoOp ->
            Evergreen.V263.MessageView.MessageView_NoOp

        Evergreen.V262.MessageView.MessageViewMsg_PressedReactionEmoji p0 ->
            Evergreen.V263.MessageView.MessageViewMsg_PressedReactionEmoji (p0 |> migrate_Emoji_EmojiOrCustomEmoji)

        Evergreen.V262.MessageView.MessageViewMsg_PressedCallStartedCard ->
            Evergreen.V263.MessageView.MessageViewMsg_PressedCallStartedCard

        Evergreen.V262.MessageView.MessageViewMsg_PressedGoMatchStartedCard ->
            Evergreen.V263.MessageView.MessageViewMsg_PressedGoMatchStartedCard


migrate_NonemptyDict_NonemptyDict : (id_old -> id_new) -> (a_old -> a_new) -> Evergreen.V262.NonemptyDict.NonemptyDict id_old a_old -> Evergreen.V263.NonemptyDict.NonemptyDict id_new a_new
migrate_NonemptyDict_NonemptyDict migrate_id migrate_a old =
    case old of
        Evergreen.V262.NonemptyDict.NonemptyDict p0 p1 p2 ->
            Evergreen.V263.NonemptyDict.NonemptyDict (p0 |> migrate_id)
                (p1 |> migrate_a)
                (p2 |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_id migrate_a) |> SeqDict.fromList)


migrate_NonemptySet_NonemptySet : (a_old -> a_new) -> Evergreen.V262.NonemptySet.NonemptySet a_old -> Evergreen.V263.NonemptySet.NonemptySet a_new
migrate_NonemptySet_NonemptySet migrate_a old =
    case old of
        Evergreen.V262.NonemptySet.NonemptySet p0 p1 ->
            Evergreen.V263.NonemptySet.NonemptySet (p0 |> migrate_a) (p1 |> SeqSet.map migrate_a)


migrate_Pages_Admin_Msg : Evergreen.V262.Pages.Admin.Msg -> Evergreen.V263.Pages.Admin.Msg
migrate_Pages_Admin_Msg old =
    case old of
        Evergreen.V262.Pages.Admin.PressedLogPage p0 ->
            Evergreen.V263.Pages.Admin.PressedLogPage (p0 |> migrate_Id_Id)

        Evergreen.V262.Pages.Admin.PressedCopyLogLink p0 ->
            Evergreen.V263.Pages.Admin.PressedCopyLogLink (p0 |> migrate_Id_Id)

        Evergreen.V262.Pages.Admin.PressedCollapseSection p0 ->
            Evergreen.V263.Pages.Admin.PressedCollapseSection (p0 |> migrate_User_AdminUiSection)

        Evergreen.V262.Pages.Admin.DoublePressedCollapseSection p0 ->
            Evergreen.V263.Pages.Admin.DoublePressedCollapseSection (p0 |> migrate_User_AdminUiSection)

        Evergreen.V262.Pages.Admin.PressedExpandSection p0 ->
            Evergreen.V263.Pages.Admin.PressedExpandSection (p0 |> migrate_User_AdminUiSection)

        Evergreen.V262.Pages.Admin.PressedEditCell p0 p1 ->
            Evergreen.V263.Pages.Admin.PressedEditCell (p0 |> migrate_Pages_Admin_UserTableId)
                (p1 |> migrate_Pages_Admin_UserColumn)

        Evergreen.V262.Pages.Admin.TypedEditCell p0 ->
            Evergreen.V263.Pages.Admin.TypedEditCell p0

        Evergreen.V262.Pages.Admin.EditCellLostFocus p0 p1 ->
            Evergreen.V263.Pages.Admin.EditCellLostFocus (p0 |> migrate_Pages_Admin_UserTableId)
                (p1 |> migrate_Pages_Admin_UserColumn)

        Evergreen.V262.Pages.Admin.FocusedOnEditCell ->
            Evergreen.V263.Pages.Admin.FocusedOnEditCell

        Evergreen.V262.Pages.Admin.EnterKeyInEditCell p0 p1 ->
            Evergreen.V263.Pages.Admin.EnterKeyInEditCell (p0 |> migrate_Pages_Admin_UserTableId)
                (p1 |> migrate_Pages_Admin_UserColumn)

        Evergreen.V262.Pages.Admin.PressedSaveUserChanges ->
            Evergreen.V263.Pages.Admin.PressedSaveUserChanges

        Evergreen.V262.Pages.Admin.TabKeyInEditCell p0 ->
            Evergreen.V263.Pages.Admin.TabKeyInEditCell p0

        Evergreen.V262.Pages.Admin.PressedResetUserChanges ->
            Evergreen.V263.Pages.Admin.PressedResetUserChanges

        Evergreen.V262.Pages.Admin.EscapeKeyInEditCell ->
            Evergreen.V263.Pages.Admin.EscapeKeyInEditCell

        Evergreen.V262.Pages.Admin.PressedAddUserRow ->
            Evergreen.V263.Pages.Admin.PressedAddUserRow

        Evergreen.V262.Pages.Admin.PressedDeleteUser p0 ->
            Evergreen.V263.Pages.Admin.PressedDeleteUser (p0 |> migrate_Pages_Admin_UserTableId)

        Evergreen.V262.Pages.Admin.PressedResetUser p0 ->
            Evergreen.V263.Pages.Admin.PressedResetUser (p0 |> migrate_Id_Id)

        Evergreen.V262.Pages.Admin.ScrolledToSection ->
            Evergreen.V263.Pages.Admin.ScrolledToSection

        Evergreen.V262.Pages.Admin.UserTableMsg p0 ->
            Evergreen.V263.Pages.Admin.UserTableMsg (p0 |> migrate_Table_Msg)

        Evergreen.V262.Pages.Admin.ToggledEmailNotifications p0 ->
            Evergreen.V263.Pages.Admin.ToggledEmailNotifications p0

        Evergreen.V262.Pages.Admin.ToggledSignupsEnabled p0 ->
            Evergreen.V263.Pages.Admin.ToggledSignupsEnabled p0

        Evergreen.V262.Pages.Admin.ToggledDiscordLinkingEnabled p0 ->
            Evergreen.V263.Pages.Admin.ToggledDiscordLinkingEnabled p0

        Evergreen.V262.Pages.Admin.ToggleIsAdmin p0 p1 ->
            Evergreen.V263.Pages.Admin.ToggleIsAdmin (p0 |> migrate_Pages_Admin_UserTableId) p1

        Evergreen.V262.Pages.Admin.PressedDeleteDiscordDmChannel p0 ->
            Evergreen.V263.Pages.Admin.PressedDeleteDiscordDmChannel (p0 |> migrate_Discord_Id)

        Evergreen.V262.Pages.Admin.PressedDeleteDiscordGuild p0 ->
            Evergreen.V263.Pages.Admin.PressedDeleteDiscordGuild (p0 |> migrate_Discord_Id)

        Evergreen.V262.Pages.Admin.PressedExpandDiscordGuild p0 ->
            Evergreen.V263.Pages.Admin.PressedExpandDiscordGuild (p0 |> migrate_Discord_Id)

        Evergreen.V262.Pages.Admin.PressedExpandGuild p0 ->
            Evergreen.V263.Pages.Admin.PressedExpandGuild (p0 |> migrate_Id_Id)

        Evergreen.V262.Pages.Admin.PressedDeleteGuild p0 ->
            Evergreen.V263.Pages.Admin.PressedDeleteGuild (p0 |> migrate_Id_Id)

        Evergreen.V262.Pages.Admin.PressedRestoreGuild p0 ->
            Evergreen.V263.Pages.Admin.PressedRestoreGuild (p0 |> migrate_Id_Id)

        Evergreen.V262.Pages.Admin.SlackClientSecretEditableMsg p0 ->
            Evergreen.V263.Pages.Admin.SlackClientSecretEditableMsg (p0 |> migrate_Editable_Msg (Maybe.map migrate_Slack_ClientSecret))

        Evergreen.V262.Pages.Admin.PublicVapidKeyEditableMsg p0 ->
            Evergreen.V263.Pages.Admin.PublicVapidKeyEditableMsg (p0 |> migrate_Editable_Msg identity)

        Evergreen.V262.Pages.Admin.PrivateVapidKeyEditableMsg p0 ->
            Evergreen.V263.Pages.Admin.PrivateVapidKeyEditableMsg (p0 |> migrate_Editable_Msg migrate_LocalState_PrivateVapidKey)

        Evergreen.V262.Pages.Admin.OpenRouterKeyEditableMsg p0 ->
            Evergreen.V263.Pages.Admin.OpenRouterKeyEditableMsg (p0 |> migrate_Editable_Msg identity)

        Evergreen.V262.Pages.Admin.CloudflareRealtimeApiTokenEditableMsg p0 ->
            Evergreen.V263.Pages.Admin.CloudflareRealtimeApiTokenEditableMsg (p0 |> migrate_Editable_Msg (Maybe.map migrate_Cloudflare_RealtimeApiToken))

        Evergreen.V262.Pages.Admin.CloudflareRealtimeAppIdEditableMsg p0 ->
            Evergreen.V263.Pages.Admin.CloudflareRealtimeAppIdEditableMsg (p0 |> migrate_Editable_Msg (Maybe.map migrate_Cloudflare_AppId))

        Evergreen.V262.Pages.Admin.CloudflareAccountIdEditableMsg p0 ->
            Evergreen.V263.Pages.Admin.CloudflareAccountIdEditableMsg (p0 |> migrate_Editable_Msg (Maybe.map migrate_Cloudflare_AccountId))

        Evergreen.V262.Pages.Admin.CloudflareAnalyticsApiTokenEditableMsg p0 ->
            Evergreen.V263.Pages.Admin.CloudflareAnalyticsApiTokenEditableMsg (p0 |> migrate_Editable_Msg (Maybe.map migrate_Cloudflare_AnalyticsApiToken))

        Evergreen.V262.Pages.Admin.PostmarkKeyEditableMsg p0 ->
            Evergreen.V263.Pages.Admin.PostmarkKeyEditableMsg (p0 |> migrate_Editable_Msg migrate_Postmark_ApiKey)

        Evergreen.V262.Pages.Admin.PressedHomepageLink ->
            Evergreen.V263.Pages.Admin.PressedHomepageLink

        Evergreen.V262.Pages.Admin.PressedReloadDiscordChannel p0 p1 p2 ->
            Evergreen.V263.Pages.Admin.PressedReloadDiscordChannel (p0 |> migrate_Discord_Id)
                (p1 |> migrate_Discord_Id)
                (p2 |> migrate_Discord_Id)

        Evergreen.V262.Pages.Admin.PressedReloadDiscordDmChannel p0 p1 ->
            Evergreen.V263.Pages.Admin.PressedReloadDiscordDmChannel (p0 |> migrate_Discord_Id)
                (p1 |> migrate_Discord_Id)

        Evergreen.V262.Pages.Admin.PressedCopyText p0 ->
            Evergreen.V263.Pages.Admin.PressedCopyText p0

        Evergreen.V262.Pages.Admin.TypedInReadOnlyTextInput ->
            Evergreen.V263.Pages.Admin.TypedInReadOnlyTextInput

        Evergreen.V262.Pages.Admin.PressedExportBackend ->
            Evergreen.V263.Pages.Admin.PressedExportBackend

        Evergreen.V262.Pages.Admin.PressedExportSubsetBackend ->
            Evergreen.V263.Pages.Admin.PressedExportSubsetBackend

        Evergreen.V262.Pages.Admin.ToggledExportSubsetDmChannel p0 p1 ->
            Evergreen.V263.Pages.Admin.ToggledExportSubsetDmChannel (p0 |> migrate_DmChannel_DmChannelId) p1

        Evergreen.V262.Pages.Admin.ToggledExportSubsetDiscordDmChannel p0 p1 ->
            Evergreen.V263.Pages.Admin.ToggledExportSubsetDiscordDmChannel (p0 |> migrate_Discord_Id) p1

        Evergreen.V262.Pages.Admin.PressedConfirmExportSubset ->
            Evergreen.V263.Pages.Admin.PressedConfirmExportSubset

        Evergreen.V262.Pages.Admin.PressedCancelExportSubset ->
            Evergreen.V263.Pages.Admin.PressedCancelExportSubset

        Evergreen.V262.Pages.Admin.PressedImportBackend ->
            Evergreen.V263.Pages.Admin.PressedImportBackend

        Evergreen.V262.Pages.Admin.ImportBackendFileSelected p0 ->
            Evergreen.V263.Pages.Admin.ImportBackendFileSelected p0

        Evergreen.V262.Pages.Admin.GotImportBackendFileContent p0 ->
            Evergreen.V263.Pages.Admin.GotImportBackendFileContent p0

        Evergreen.V262.Pages.Admin.PressedHideLog p0 ->
            Evergreen.V263.Pages.Admin.PressedHideLog (p0 |> migrate_Id_Id)

        Evergreen.V262.Pages.Admin.PressedUnhideLog p0 ->
            Evergreen.V263.Pages.Admin.PressedUnhideLog (p0 |> migrate_Id_Id)

        Evergreen.V262.Pages.Admin.PressedShowHiddenLogs p0 ->
            Evergreen.V263.Pages.Admin.PressedShowHiddenLogs p0

        Evergreen.V262.Pages.Admin.PressedDisconnectClient p0 p1 ->
            Evergreen.V263.Pages.Admin.PressedDisconnectClient (p0 |> migrate_SessionIdHash_SessionIdHash) p1

        Evergreen.V262.Pages.Admin.PressedRegenerateServerSecret ->
            Evergreen.V263.Pages.Admin.PressedRegenerateServerSecret

        Evergreen.V262.Pages.Admin.PressedDeleteCall ->
            Evergreen.V263.Pages.Admin.PressedDeleteCall

        Evergreen.V262.Pages.Admin.PressedWebsocketCloseEventsPage p0 ->
            Evergreen.V263.Pages.Admin.PressedWebsocketCloseEventsPage p0

        Evergreen.V262.Pages.Admin.PressedLoadRealtimeSessionData p0 ->
            Evergreen.V263.Pages.Admin.PressedLoadRealtimeSessionData (p0 |> migrate_Cloudflare_RealtimeSessionId)

        Evergreen.V262.Pages.Admin.GotRealtimeSessionInfo p0 p1 ->
            Evergreen.V263.Pages.Admin.GotRealtimeSessionInfo (p0 |> migrate_Cloudflare_RealtimeSessionId)
                (p1 |> Result.map migrate_Cloudflare_SessionStateResponse)

        Evergreen.V262.Pages.Admin.PressedLoadCloudflareEgress ->
            Evergreen.V263.Pages.Admin.PressedLoadCloudflareEgress


migrate_Pages_Admin_UserColumn : Evergreen.V262.Pages.Admin.UserColumn -> Evergreen.V263.Pages.Admin.UserColumn
migrate_Pages_Admin_UserColumn old =
    case old of
        Evergreen.V262.Pages.Admin.NameColumn ->
            Evergreen.V263.Pages.Admin.NameColumn

        Evergreen.V262.Pages.Admin.EmailAddressColumn ->
            Evergreen.V263.Pages.Admin.EmailAddressColumn


migrate_Pages_Admin_UserTableId : Evergreen.V262.Pages.Admin.UserTableId -> Evergreen.V263.Pages.Admin.UserTableId
migrate_Pages_Admin_UserTableId old =
    case old of
        Evergreen.V262.Pages.Admin.ExistingUserId p0 ->
            Evergreen.V263.Pages.Admin.ExistingUserId (p0 |> migrate_Id_Id)

        Evergreen.V262.Pages.Admin.NewUserId p0 ->
            Evergreen.V263.Pages.Admin.NewUserId p0


migrate_PersonName_PersonName : Evergreen.V262.PersonName.PersonName -> Evergreen.V263.PersonName.PersonName
migrate_PersonName_PersonName old =
    case old of
        Evergreen.V262.PersonName.PersonName p0 ->
            Evergreen.V263.PersonName.PersonName p0


migrate_Point2d_Point2d : (units_old -> units_new) -> (coordinates_old -> coordinates_new) -> Evergreen.V262.Point2d.Point2d units_old coordinates_old -> Evergreen.V263.Point2d.Point2d units_new coordinates_new
migrate_Point2d_Point2d migrate_units migrate_coordinates old =
    old |> migrate_Geometry_Types_Point2d


migrate_Ports_NotificationPermission : Evergreen.V262.Ports.NotificationPermission -> Evergreen.V263.Ports.NotificationPermission
migrate_Ports_NotificationPermission old =
    case old of
        Evergreen.V262.Ports.NotAsked ->
            Evergreen.V263.Ports.NotAsked

        Evergreen.V262.Ports.Denied ->
            Evergreen.V263.Ports.Denied

        Evergreen.V262.Ports.Granted ->
            Evergreen.V263.Ports.Granted

        Evergreen.V262.Ports.Unsupported ->
            Evergreen.V263.Ports.Unsupported


migrate_Ports_PwaStatus : Evergreen.V262.Ports.PwaStatus -> Evergreen.V263.Ports.PwaStatus
migrate_Ports_PwaStatus old =
    case old of
        Evergreen.V262.Ports.InstalledPwa ->
            Evergreen.V263.Ports.InstalledPwa

        Evergreen.V262.Ports.BrowserView ->
            Evergreen.V263.Ports.BrowserView


migrate_Postmark_ApiKey : Evergreen.V262.Postmark.ApiKey -> Evergreen.V263.Postmark.ApiKey
migrate_Postmark_ApiKey old =
    case old of
        Evergreen.V262.Postmark.ApiKey p0 ->
            Evergreen.V263.Postmark.ApiKey p0


migrate_Quantity_Quantity : Quantity.Quantity number units -> Quantity.Quantity number units2
migrate_Quantity_Quantity old =
    Quantity.unwrap old |> Quantity.unsafe


migrate_Range_Range : Evergreen.V262.Range.Range -> Evergreen.V263.Range.Range
migrate_Range_Range old =
    old


migrate_Range_SelectionDirection : Evergreen.V262.Range.SelectionDirection -> Evergreen.V263.Range.SelectionDirection
migrate_Range_SelectionDirection old =
    case old of
        Evergreen.V262.Range.SelectForward ->
            Evergreen.V263.Range.SelectForward

        Evergreen.V262.Range.SelectBackward ->
            Evergreen.V263.Range.SelectBackward


migrate_Route_ChannelRoute : Evergreen.V262.Route.ChannelRoute -> Evergreen.V263.Route.ChannelRoute
migrate_Route_ChannelRoute old =
    case old of
        Evergreen.V262.Route.ChannelRoute p0 p1 p2 ->
            Evergreen.V263.Route.ChannelRoute (p0 |> migrate_Id_Id)
                (p1 |> migrate_Route_ThreadRouteWithFriends)
                (p2 |> Maybe.map migrate_Route_DmChannelHeaderTab)

        Evergreen.V262.Route.NewChannelRoute ->
            Evergreen.V263.Route.NewChannelRoute

        Evergreen.V262.Route.EditChannelRoute p0 ->
            Evergreen.V263.Route.EditChannelRoute (p0 |> migrate_Id_Id)

        Evergreen.V262.Route.GuildSettingsRoute ->
            Evergreen.V263.Route.GuildSettingsRoute

        Evergreen.V262.Route.JoinRoute p0 ->
            Evergreen.V263.Route.JoinRoute (p0 |> migrate_SecretId_SecretId)


migrate_Route_DiscordChannelRoute : Evergreen.V262.Route.DiscordChannelRoute -> Evergreen.V263.Route.DiscordChannelRoute
migrate_Route_DiscordChannelRoute old =
    case old of
        Evergreen.V262.Route.DiscordChannel_ChannelRoute p0 p1 p2 ->
            Evergreen.V263.Route.DiscordChannel_ChannelRoute (p0 |> migrate_Discord_Id)
                (p1 |> migrate_Route_ThreadRouteWithFriends)
                (p2 |> Maybe.map migrate_Route_DmChannelHeaderTab)

        Evergreen.V262.Route.DiscordChannel_NewChannelRoute ->
            Evergreen.V263.Route.DiscordChannel_NewChannelRoute

        Evergreen.V262.Route.DiscordChannel_EditChannelRoute p0 ->
            Evergreen.V263.Route.DiscordChannel_EditChannelRoute (p0 |> migrate_Discord_Id)

        Evergreen.V262.Route.DiscordChannel_GuildSettingsRoute ->
            Evergreen.V263.Route.DiscordChannel_GuildSettingsRoute


migrate_Route_DiscordDmRouteData : Evergreen.V262.Route.DiscordDmRouteData -> Evergreen.V263.Route.DiscordDmRouteData
migrate_Route_DiscordDmRouteData old =
    { currentDiscordUserId = old.currentDiscordUserId |> migrate_Discord_Id
    , channelId = old.channelId |> migrate_Discord_Id
    , viewingMessage = old.viewingMessage |> Maybe.map migrate_Id_Id
    , showMembersTab = old.showMembersTab |> migrate_Route_ShowMembersTab
    , tab = old.tab |> Maybe.map migrate_Route_DmChannelHeaderTab
    }


migrate_Route_DiscordGuildRouteData : Evergreen.V262.Route.DiscordGuildRouteData -> Evergreen.V263.Route.DiscordGuildRouteData
migrate_Route_DiscordGuildRouteData old =
    { currentDiscordUserId = old.currentDiscordUserId |> migrate_Discord_Id
    , guildId = old.guildId |> migrate_Discord_Id
    , channelRoute = old.channelRoute |> migrate_Route_DiscordChannelRoute
    }


migrate_Route_DmChannelHeaderTab : Evergreen.V262.Route.DmChannelHeaderTab -> Evergreen.V263.Route.DmChannelHeaderTab
migrate_Route_DmChannelHeaderTab old =
    case old of
        Evergreen.V262.Route.DmChannelHeaderTab_VoiceChat ->
            Evergreen.V263.Route.DmChannelHeaderTab_VoiceChat

        Evergreen.V262.Route.DmChannelHeaderTab_Go p0 ->
            Evergreen.V263.Route.DmChannelHeaderTab_Go (p0 |> Maybe.map migrate_Id_Id)

        Evergreen.V262.Route.DmChannelHeaderTab_ChannelDescription ->
            Evergreen.V263.Route.DmChannelHeaderTab_ChannelDescription


migrate_Route_DmRouteData : Evergreen.V262.Route.DmRouteData -> Evergreen.V263.Route.DmRouteData
migrate_Route_DmRouteData old =
    { channelId = old.channelId |> migrate_DmChannel_DmChannelId
    , threadRoute = old.threadRoute |> migrate_Route_ThreadRouteWithFriends
    , tab = old.tab |> Maybe.map migrate_Route_DmChannelHeaderTab
    }


migrate_Route_LinkDiscordError : Evergreen.V262.Route.LinkDiscordError -> Evergreen.V263.Route.LinkDiscordError
migrate_Route_LinkDiscordError old =
    case old of
        Evergreen.V262.Route.LinkDiscordExpired ->
            Evergreen.V263.Route.LinkDiscordExpired

        Evergreen.V262.Route.LinkDiscordServerError ->
            Evergreen.V263.Route.LinkDiscordServerError

        Evergreen.V262.Route.LinkDiscordInvalidData ->
            Evergreen.V263.Route.LinkDiscordInvalidData


migrate_Route_Route : Evergreen.V262.Route.Route -> Evergreen.V263.Route.Route
migrate_Route_Route old =
    case old of
        Evergreen.V262.Route.HomePageRoute ->
            Evergreen.V263.Route.HomePageRoute

        Evergreen.V262.Route.AdminRoute p0 ->
            Evergreen.V263.Route.AdminRoute
                { highlightLog = p0.highlightLog |> Maybe.map migrate_Id_Id
                }

        Evergreen.V262.Route.GuildRoute p0 p1 ->
            Evergreen.V263.Route.GuildRoute (p0 |> migrate_Id_Id)
                (p1 |> migrate_Route_ChannelRoute)

        Evergreen.V262.Route.DiscordGuildRoute p0 ->
            Evergreen.V263.Route.DiscordGuildRoute (p0 |> migrate_Route_DiscordGuildRouteData)

        Evergreen.V262.Route.DmRoute p0 ->
            Evergreen.V263.Route.DmRoute (p0 |> migrate_Route_DmRouteData)

        Evergreen.V262.Route.DiscordDmRoute p0 ->
            Evergreen.V263.Route.DiscordDmRoute (p0 |> migrate_Route_DiscordDmRouteData)

        Evergreen.V262.Route.AiChatRoute ->
            Evergreen.V263.Route.AiChatRoute

        Evergreen.V262.Route.SlackOAuthRedirect p0 ->
            Evergreen.V263.Route.SlackOAuthRedirect (p0 |> Result.map (Tuple.mapBoth migrate_Slack_OAuthCode migrate_SessionIdHash_SessionIdHash))

        Evergreen.V262.Route.TextEditorRoute ->
            Evergreen.V263.Route.TextEditorRoute

        Evergreen.V262.Route.LinkDiscord p0 ->
            Evergreen.V263.Route.LinkDiscord (p0 |> Result.mapError migrate_Route_LinkDiscordError >> Result.map migrate_Discord_UserAuth)

        Evergreen.V262.Route.PublicGoMatchRoute p0 ->
            Evergreen.V263.Route.PublicGoMatchRoute (p0 |> migrate_SecretId_SecretId)


migrate_Route_ShowMembersTab : Evergreen.V262.Route.ShowMembersTab -> Evergreen.V263.Route.ShowMembersTab
migrate_Route_ShowMembersTab old =
    case old of
        Evergreen.V262.Route.ShowMembersTab ->
            Evergreen.V263.Route.ShowMembersTab

        Evergreen.V262.Route.HideMembersTab ->
            Evergreen.V263.Route.HideMembersTab


migrate_Route_ThreadRouteWithFriends : Evergreen.V262.Route.ThreadRouteWithFriends -> Evergreen.V263.Route.ThreadRouteWithFriends
migrate_Route_ThreadRouteWithFriends old =
    case old of
        Evergreen.V262.Route.NoThreadWithFriends p0 p1 ->
            Evergreen.V263.Route.NoThreadWithFriends (p0 |> Maybe.map migrate_Id_Id)
                (p1 |> migrate_Route_ShowMembersTab)

        Evergreen.V262.Route.ViewThreadWithFriends p0 p1 p2 ->
            Evergreen.V263.Route.ViewThreadWithFriends (p0 |> migrate_Id_Id)
                (p1 |> Maybe.map migrate_Id_Id)
                (p2 |> migrate_Route_ShowMembersTab)


migrate_SafeJson_SafeJson : Evergreen.V262.SafeJson.SafeJson -> Evergreen.V263.SafeJson.SafeJson
migrate_SafeJson_SafeJson old =
    case old of
        Evergreen.V262.SafeJson.JsonString p0 ->
            Evergreen.V263.SafeJson.JsonString p0

        Evergreen.V262.SafeJson.JsonNumber p0 ->
            Evergreen.V263.SafeJson.JsonNumber p0

        Evergreen.V262.SafeJson.JsonBool p0 ->
            Evergreen.V263.SafeJson.JsonBool p0

        Evergreen.V262.SafeJson.JsonObject p0 ->
            Evergreen.V263.SafeJson.JsonObject (p0 |> Dict.map (\k -> migrate_SafeJson_SafeJson))

        Evergreen.V262.SafeJson.JsonArray p0 ->
            Evergreen.V263.SafeJson.JsonArray (p0 |> List.map migrate_SafeJson_SafeJson)

        Evergreen.V262.SafeJson.JsonNull ->
            Evergreen.V263.SafeJson.JsonNull


migrate_SecretId_SecretId : Evergreen.V262.SecretId.SecretId a_old -> Evergreen.V263.SecretId.SecretId a_new
migrate_SecretId_SecretId old =
    case old of
        Evergreen.V262.SecretId.SecretId p0 ->
            Evergreen.V263.SecretId.SecretId p0


migrate_SessionIdHash_SessionIdHash : Evergreen.V262.SessionIdHash.SessionIdHash -> Evergreen.V263.SessionIdHash.SessionIdHash
migrate_SessionIdHash_SessionIdHash old =
    case old of
        Evergreen.V262.SessionIdHash.SessionIdHash p0 ->
            Evergreen.V263.SessionIdHash.SessionIdHash p0


migrate_Slack_ClientSecret : Evergreen.V262.Slack.ClientSecret -> Evergreen.V263.Slack.ClientSecret
migrate_Slack_ClientSecret old =
    case old of
        Evergreen.V262.Slack.ClientSecret p0 ->
            Evergreen.V263.Slack.ClientSecret p0


migrate_Slack_OAuthCode : Evergreen.V262.Slack.OAuthCode -> Evergreen.V263.Slack.OAuthCode
migrate_Slack_OAuthCode old =
    case old of
        Evergreen.V262.Slack.OAuthCode p0 ->
            Evergreen.V263.Slack.OAuthCode p0


migrate_Table_Msg : Evergreen.V262.Table.Msg -> Evergreen.V263.Table.Msg
migrate_Table_Msg old =
    case old of
        Evergreen.V262.Table.PressedSortBy p0 ->
            Evergreen.V263.Table.PressedSortBy p0

        Evergreen.V262.Table.PressedShowAll ->
            Evergreen.V263.Table.PressedShowAll


migrate_TextEditor_Msg : Evergreen.V262.TextEditor.Msg -> Evergreen.V263.TextEditor.Msg
migrate_TextEditor_Msg old =
    case old of
        Evergreen.V262.TextEditor.TypedText p0 ->
            Evergreen.V263.TextEditor.TypedText p0

        Evergreen.V262.TextEditor.PressedReset ->
            Evergreen.V263.TextEditor.PressedReset

        Evergreen.V262.TextEditor.UndoChange ->
            Evergreen.V263.TextEditor.UndoChange

        Evergreen.V262.TextEditor.RedoChange ->
            Evergreen.V263.TextEditor.RedoChange


migrate_Touch_ScreenCoordinate : Evergreen.V262.Touch.ScreenCoordinate -> Evergreen.V263.Touch.ScreenCoordinate
migrate_Touch_ScreenCoordinate old =
    case old of
        Evergreen.V262.Touch.ScreenCoordinate p0 ->
            Evergreen.V263.Touch.ScreenCoordinate p0


migrate_Touch_Touch : Evergreen.V262.Touch.Touch -> Evergreen.V263.Touch.Touch
migrate_Touch_Touch old =
    { client = old.client |> migrate_Point2d_Point2d migrate_CssPixels_CssPixels migrate_Touch_ScreenCoordinate
    , target = old.target
    }


migrate_TwoFactorAuthentication_Msg : Evergreen.V262.TwoFactorAuthentication.Msg -> Evergreen.V263.TwoFactorAuthentication.Msg
migrate_TwoFactorAuthentication_Msg old =
    case old of
        Evergreen.V262.TwoFactorAuthentication.PressedStart2FaSetup ->
            Evergreen.V263.TwoFactorAuthentication.PressedStart2FaSetup

        Evergreen.V262.TwoFactorAuthentication.PressedCopy p0 ->
            Evergreen.V263.TwoFactorAuthentication.PressedCopy p0

        Evergreen.V262.TwoFactorAuthentication.TypedTwoFactorCode p0 ->
            Evergreen.V263.TwoFactorAuthentication.TypedTwoFactorCode p0

        Evergreen.V262.TwoFactorAuthentication.PressedStartDisable2Fa ->
            Evergreen.V263.TwoFactorAuthentication.PressedStartDisable2Fa

        Evergreen.V262.TwoFactorAuthentication.PressedCancelDisable2Fa ->
            Evergreen.V263.TwoFactorAuthentication.PressedCancelDisable2Fa

        Evergreen.V262.TwoFactorAuthentication.TypedDisableTwoFactorCode p0 ->
            Evergreen.V263.TwoFactorAuthentication.TypedDisableTwoFactorCode p0


migrate_Types_EditChannelForm : Evergreen.V262.Types.EditChannelForm -> Evergreen.V263.Types.EditChannelForm
migrate_Types_EditChannelForm old =
    old


migrate_Types_EditGuildForm : Evergreen.V262.Types.EditGuildForm -> Evergreen.V263.Types.EditGuildForm
migrate_Types_EditGuildForm old =
    old


migrate_Types_FrontendMsg : Evergreen.V262.Types.FrontendMsg -> Evergreen.V263.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V262.Types.UrlClicked p0 ->
            Evergreen.V263.Types.UrlClicked p0

        Evergreen.V262.Types.UrlChanged p0 ->
            Evergreen.V263.Types.UrlChanged p0

        Evergreen.V262.Types.GotTime p0 ->
            Evergreen.V263.Types.GotTime p0

        Evergreen.V262.Types.GotWindowSize p0 p1 ->
            Evergreen.V263.Types.GotWindowSize p0 p1

        Evergreen.V262.Types.GotTimezone p0 ->
            Evergreen.V263.Types.GotTimezone p0

        Evergreen.V262.Types.LoginFormMsg p0 ->
            Evergreen.V263.Types.LoginFormMsg (p0 |> migrate_LoginForm_Msg)

        Evergreen.V262.Types.PressedShowLogin ->
            Evergreen.V263.Types.PressedShowLogin

        Evergreen.V262.Types.AdminPageMsg p0 ->
            Evergreen.V263.Types.AdminPageMsg (p0 |> migrate_Pages_Admin_Msg)

        Evergreen.V262.Types.PressedLogOut ->
            Evergreen.V263.Types.PressedLogOut

        Evergreen.V262.Types.ElmUiMsg p0 ->
            Evergreen.V263.Types.ElmUiMsg (p0 |> migrate_Ui_Anim_Msg)

        Evergreen.V262.Types.ScrolledToLogSection ->
            Evergreen.V263.Types.ScrolledToLogSection

        Evergreen.V262.Types.PressedLink p0 ->
            Evergreen.V263.Types.PressedLink (p0 |> migrate_Route_Route)

        Evergreen.V262.Types.SelectedFilesToAttach p0 p1 p2 ->
            Evergreen.V263.Types.SelectedFilesToAttach (p0 |> Tuple.mapBoth migrate_Id_AnyGuildOrDmId migrate_Id_ThreadRoute)
                p1
                p2

        Evergreen.V262.Types.NewChannelFormChanged p0 p1 ->
            Evergreen.V263.Types.NewChannelFormChanged (p0 |> migrate_Id_Id)
                (p1 |> migrate_Types_NewChannelForm)

        Evergreen.V262.Types.PressedSubmitNewChannel p0 p1 ->
            Evergreen.V263.Types.PressedSubmitNewChannel (p0 |> migrate_Id_Id)
                (p1 |> migrate_Types_NewChannelForm)

        Evergreen.V262.Types.MouseEnteredChannelName p0 p1 p2 ->
            Evergreen.V263.Types.MouseEnteredChannelName (p0 |> migrate_Id_Id)
                (p1 |> migrate_Id_Id)
                (p2 |> migrate_Id_ThreadRoute)

        Evergreen.V262.Types.MouseExitedChannelName p0 p1 p2 ->
            Evergreen.V263.Types.MouseExitedChannelName (p0 |> migrate_Id_Id)
                (p1 |> migrate_Id_Id)
                (p2 |> migrate_Id_ThreadRoute)

        Evergreen.V262.Types.MouseEnteredDiscordChannelName p0 p1 p2 ->
            Evergreen.V263.Types.MouseEnteredDiscordChannelName (p0 |> migrate_Discord_Id)
                (p1 |> migrate_Discord_Id)
                (p2 |> migrate_Id_ThreadRoute)

        Evergreen.V262.Types.MouseExitedDiscordChannelName p0 p1 p2 ->
            Evergreen.V263.Types.MouseExitedDiscordChannelName (p0 |> migrate_Discord_Id)
                (p1 |> migrate_Discord_Id)
                (p2 |> migrate_Id_ThreadRoute)

        Evergreen.V262.Types.EditChannelFormChanged p0 p1 p2 ->
            Evergreen.V263.Types.EditChannelFormChanged (p0 |> migrate_Id_Id)
                (p1 |> migrate_Id_Id)
                (p2 |> migrate_Types_EditChannelForm)

        Evergreen.V262.Types.PressedResetEditChannelChanges p0 p1 ->
            Evergreen.V263.Types.PressedResetEditChannelChanges (p0 |> migrate_Id_Id) (p1 |> migrate_Id_Id)

        Evergreen.V262.Types.PressedSubmitEditChannelChanges p0 p1 p2 ->
            Evergreen.V263.Types.PressedSubmitEditChannelChanges (p0 |> migrate_Id_Id)
                (p1 |> migrate_Id_Id)
                (p2 |> migrate_Types_EditChannelForm)

        Evergreen.V262.Types.PressedDeleteChannel p0 p1 ->
            Evergreen.V263.Types.PressedDeleteChannel (p0 |> migrate_Id_Id) (p1 |> migrate_Id_Id)

        Evergreen.V262.Types.EditGuildFormChanged p0 p1 ->
            Evergreen.V263.Types.EditGuildFormChanged (p0 |> migrate_Id_Id)
                (p1 |> migrate_Types_EditGuildForm)

        Evergreen.V262.Types.PressedDeleteGuild p0 ->
            Evergreen.V263.Types.PressedDeleteGuild (p0 |> migrate_Id_Id)

        Evergreen.V262.Types.PressedCreateInviteLink p0 ->
            Evergreen.V263.Types.PressedCreateInviteLink (p0 |> migrate_Id_Id)

        Evergreen.V262.Types.PressedDeleteInviteLink p0 p1 ->
            Evergreen.V263.Types.PressedDeleteInviteLink (p0 |> migrate_Id_Id)
                (p1 |> migrate_SecretId_SecretId)

        Evergreen.V262.Types.FrontendNoOp ->
            Evergreen.V263.Types.FrontendNoOp

        Evergreen.V262.Types.PressedCopyText p0 ->
            Evergreen.V263.Types.PressedCopyText p0

        Evergreen.V262.Types.PressedCreateGuild ->
            Evergreen.V263.Types.PressedCreateGuild

        Evergreen.V262.Types.NewGuildFormChanged p0 ->
            Evergreen.V263.Types.NewGuildFormChanged (p0 |> migrate_Types_NewGuildForm)

        Evergreen.V262.Types.PressedSubmitNewGuild p0 ->
            Evergreen.V263.Types.PressedSubmitNewGuild (p0 |> migrate_Types_NewGuildForm)

        Evergreen.V262.Types.PressedCancelNewGuild ->
            Evergreen.V263.Types.PressedCancelNewGuild

        Evergreen.V262.Types.DebouncedTyping ->
            Evergreen.V263.Types.DebouncedTyping

        Evergreen.V262.Types.GotPingUserPosition p0 p1 ->
            Evergreen.V263.Types.GotPingUserPosition p0 p1

        Evergreen.V262.Types.SetFocus ->
            Evergreen.V263.Types.SetFocus

        Evergreen.V262.Types.RemoveFocus ->
            Evergreen.V263.Types.RemoveFocus

        Evergreen.V262.Types.KeyDown p0 ->
            Evergreen.V263.Types.KeyDown p0

        Evergreen.V262.Types.MessageMenu_PressedShowReactionEmojiSelector p0 p1 p2 ->
            Evergreen.V263.Types.MessageMenu_PressedShowReactionEmojiSelector (p0 |> migrate_Id_AnyGuildOrDmId)
                (p1 |> migrate_Id_ThreadRouteWithMessage)
                (p2 |> migrate_Coord_Coord migrate_CssPixels_CssPixels)

        Evergreen.V262.Types.MessageMenu_PressedReactionEmoji p0 ->
            Evergreen.V263.Types.MessageMenu_PressedReactionEmoji (p0 |> migrate_Emoji_EmojiOrCustomEmoji)

        Evergreen.V262.Types.MessageMenu_PressedEditMessage p0 p1 ->
            Evergreen.V263.Types.MessageMenu_PressedEditMessage (p0 |> migrate_Id_AnyGuildOrDmId)
                (p1 |> migrate_Id_ThreadRouteWithMessage)

        Evergreen.V262.Types.EmojiSelectorMsg p0 ->
            Evergreen.V263.Types.EmojiSelectorMsg (p0 |> migrate_Emoji_Msg)

        Evergreen.V262.Types.MessageMenu_PressedReply p0 ->
            Evergreen.V263.Types.MessageMenu_PressedReply (p0 |> migrate_Id_ThreadRouteWithMessage)

        Evergreen.V262.Types.MessageMenu_PressedOpenThread p0 ->
            Evergreen.V263.Types.MessageMenu_PressedOpenThread (p0 |> migrate_Id_Id)

        Evergreen.V262.Types.PressedCloseReplyTo p0 ->
            Evergreen.V263.Types.PressedCloseReplyTo (p0 |> Tuple.mapBoth migrate_Id_AnyGuildOrDmId migrate_Id_ThreadRoute)

        Evergreen.V262.Types.VisibilityChanged p0 ->
            Evergreen.V263.Types.VisibilityChanged p0

        Evergreen.V262.Types.CheckedNotificationPermission p0 ->
            Evergreen.V263.Types.CheckedNotificationPermission (p0 |> migrate_Ports_NotificationPermission)

        Evergreen.V262.Types.CheckedPwaStatus p0 ->
            Evergreen.V263.Types.CheckedPwaStatus (p0 |> migrate_Ports_PwaStatus)

        Evergreen.V262.Types.TouchStart p0 p1 p2 ->
            Evergreen.V263.Types.TouchStart (p0 |> Maybe.map (\( t1, t2, t3 ) -> ( t1 |> migrate_Id_AnyGuildOrDmId, t2 |> migrate_Id_ThreadRouteWithMessage, t3 )))
                p1
                (p2 |> migrate_NonemptyDict_NonemptyDict identity migrate_Touch_Touch)

        Evergreen.V262.Types.TouchMoved p0 p1 ->
            Evergreen.V263.Types.TouchMoved p0
                (p1 |> migrate_NonemptyDict_NonemptyDict identity migrate_Touch_Touch)

        Evergreen.V262.Types.TouchEnd p0 ->
            Evergreen.V263.Types.TouchEnd p0

        Evergreen.V262.Types.TouchCancel p0 ->
            Evergreen.V263.Types.TouchCancel p0

        Evergreen.V262.Types.ChannelSidebarAnimated p0 ->
            Evergreen.V263.Types.ChannelSidebarAnimated p0

        Evergreen.V262.Types.MessageMenuAnimated p0 ->
            Evergreen.V263.Types.MessageMenuAnimated p0

        Evergreen.V262.Types.SetScrollToBottom ->
            Evergreen.V263.Types.SetScrollToBottom

        Evergreen.V262.Types.PressedChannelHeaderBackButton ->
            Evergreen.V263.Types.PressedChannelHeaderBackButton

        Evergreen.V262.Types.PressedShowMembers ->
            Evergreen.V263.Types.PressedShowMembers

        Evergreen.V262.Types.UserScrolled p0 p1 p2 ->
            Evergreen.V263.Types.UserScrolled (p0 |> migrate_Id_AnyGuildOrDmId)
                (p1 |> migrate_Id_ThreadRoute)
                (p2 |> migrate_Types_ScrollPosition)

        Evergreen.V262.Types.PressedBody ->
            Evergreen.V263.Types.PressedBody

        Evergreen.V262.Types.MessageMenu_PressedDeleteMessage p0 p1 ->
            Evergreen.V263.Types.MessageMenu_PressedDeleteMessage (p0 |> migrate_Id_AnyGuildOrDmId)
                (p1 |> migrate_Id_ThreadRouteWithMessage)

        Evergreen.V262.Types.MessageMenu_PressedAddCustomEmojisToUser p0 ->
            Evergreen.V263.Types.MessageMenu_PressedAddCustomEmojisToUser (p0 |> migrate_NonemptySet_NonemptySet migrate_Id_Id)

        Evergreen.V262.Types.ScrolledToMessage ->
            Evergreen.V263.Types.ScrolledToMessage

        Evergreen.V262.Types.MessageMenu_PressedClose ->
            Evergreen.V263.Types.MessageMenu_PressedClose

        Evergreen.V262.Types.MessageMenu_PressedContainer ->
            Evergreen.V263.Types.MessageMenu_PressedContainer

        Evergreen.V262.Types.PressedCancelMessageEdit p0 ->
            Evergreen.V263.Types.PressedCancelMessageEdit (p0 |> Tuple.mapBoth migrate_Id_AnyGuildOrDmId migrate_Id_ThreadRoute)

        Evergreen.V262.Types.CheckMessageAltPress p0 p1 p2 p3 ->
            Evergreen.V263.Types.CheckMessageAltPress p0
                (p1 |> migrate_Id_AnyGuildOrDmId)
                (p2 |> migrate_Id_ThreadRouteWithMessage)
                p3

        Evergreen.V262.Types.PressedShowUserOption ->
            Evergreen.V263.Types.PressedShowUserOption

        Evergreen.V262.Types.PressedCloseUserOptions ->
            Evergreen.V263.Types.PressedCloseUserOptions

        Evergreen.V262.Types.TwoFactorMsg p0 ->
            Evergreen.V263.Types.TwoFactorMsg (p0 |> migrate_TwoFactorAuthentication_Msg)

        Evergreen.V262.Types.AiChatMsg p0 ->
            Evergreen.V263.Types.AiChatMsg (p0 |> migrate_AiChat_Msg)

        Evergreen.V262.Types.GoMsg p0 ->
            Evergreen.V263.Types.GoMsg (p0 |> migrate_Go_Msg)

        Evergreen.V262.Types.GoSpectatorMsg p0 ->
            Evergreen.V263.Types.GoSpectatorMsg (p0 |> migrate_Go_SpectatorMsg)

        Evergreen.V262.Types.UserNameEditableMsg p0 ->
            Evergreen.V263.Types.UserNameEditableMsg (p0 |> migrate_Editable_Msg migrate_PersonName_PersonName)

        Evergreen.V262.Types.ProfilePictureEditorMsg p0 ->
            Evergreen.V263.Types.ProfilePictureEditorMsg (p0 |> migrate_ImageEditor_Msg)

        Evergreen.V262.Types.GuildIconEditorMsg p0 p1 ->
            Evergreen.V263.Types.GuildIconEditorMsg (p0 |> migrate_Id_Id)
                (p1 |> migrate_ImageEditor_Msg)

        Evergreen.V262.Types.OneFrameAfterDragEnd ->
            Evergreen.V263.Types.OneFrameAfterDragEnd

        Evergreen.V262.Types.GotFileHashName p0 p1 p2 ->
            Evergreen.V263.Types.GotFileHashName (p0 |> Tuple.mapBoth migrate_Id_AnyGuildOrDmId migrate_Id_ThreadRoute)
                (p1 |> migrate_Id_Id)
                (p2 |> Result.map migrate_FileStatus_UploadResponse)

        Evergreen.V262.Types.PressedDeleteAttachedFile p0 p1 ->
            Evergreen.V263.Types.PressedDeleteAttachedFile (p0 |> Tuple.mapBoth migrate_Id_AnyGuildOrDmId migrate_Id_ThreadRoute)
                (p1 |> migrate_Id_Id)

        Evergreen.V262.Types.PressedViewAttachedFileInfo p0 p1 ->
            Evergreen.V263.Types.PressedViewAttachedFileInfo (p0 |> Tuple.mapBoth migrate_Id_AnyGuildOrDmId migrate_Id_ThreadRoute)
                (p1 |> migrate_Id_Id)

        Evergreen.V262.Types.PressedToggleAttachedFileSpoiler p0 p1 ->
            Evergreen.V263.Types.PressedToggleAttachedFileSpoiler (p0 |> Tuple.mapBoth migrate_Id_AnyGuildOrDmId migrate_Id_ThreadRoute)
                { fileId = p1.fileId |> migrate_Id_Id
                , removeSpoiler = p1.removeSpoiler
                }

        Evergreen.V262.Types.EditMessage_PressedDeleteAttachedFile p0 p1 ->
            Evergreen.V263.Types.EditMessage_PressedDeleteAttachedFile (p0 |> Tuple.mapBoth migrate_Id_AnyGuildOrDmId migrate_Id_ThreadRoute)
                (p1 |> migrate_Id_Id)

        Evergreen.V262.Types.EditMessage_PressedViewAttachedFileInfo p0 p1 ->
            Evergreen.V263.Types.EditMessage_PressedViewAttachedFileInfo (p0 |> Tuple.mapBoth migrate_Id_AnyGuildOrDmId migrate_Id_ThreadRoute)
                (p1 |> migrate_Id_Id)

        Evergreen.V262.Types.EditMessage_PressedToggleAttachedFileSpoiler p0 p1 ->
            Evergreen.V263.Types.EditMessage_PressedToggleAttachedFileSpoiler (p0 |> Tuple.mapBoth migrate_Id_AnyGuildOrDmId migrate_Id_ThreadRoute)
                { fileId = p1.fileId |> migrate_Id_Id
                , removeSpoiler = p1.removeSpoiler
                }

        Evergreen.V262.Types.EditMessage_SelectedFilesToAttach p0 p1 p2 ->
            Evergreen.V263.Types.EditMessage_SelectedFilesToAttach (p0 |> Tuple.mapBoth migrate_Id_AnyGuildOrDmId migrate_Id_ThreadRoute)
                p1
                p2

        Evergreen.V262.Types.EditMessage_GotFileHashName p0 p1 p2 p3 ->
            Evergreen.V263.Types.EditMessage_GotFileHashName (p0 |> Tuple.mapBoth migrate_Id_AnyGuildOrDmId migrate_Id_ThreadRoute)
                (p1 |> migrate_Id_Id)
                (p2 |> migrate_Id_Id)
                (p3 |> Result.map migrate_FileStatus_UploadResponse)

        Evergreen.V262.Types.FileUploadProgress p0 p1 p2 ->
            Evergreen.V263.Types.FileUploadProgress (p0 |> Tuple.mapBoth migrate_Id_AnyGuildOrDmId migrate_Id_ThreadRoute)
                (p1 |> migrate_Id_Id)
                p2

        Evergreen.V262.Types.MessageViewMsg p0 p1 p2 ->
            Evergreen.V263.Types.MessageViewMsg (p0 |> migrate_Id_AnyGuildOrDmId)
                (p1 |> migrate_Id_ThreadRouteWithMessage)
                (p2 |> migrate_MessageView_MessageViewMsg)

        Evergreen.V262.Types.GotRegisterPushSubscription p0 ->
            Evergreen.V263.Types.GotRegisterPushSubscription p0

        Evergreen.V262.Types.SelectedNotificationMode p0 ->
            Evergreen.V263.Types.SelectedNotificationMode (p0 |> migrate_UserSession_NotificationMode)

        Evergreen.V262.Types.PressedGuildNotificationLevel p0 p1 ->
            Evergreen.V263.Types.PressedGuildNotificationLevel (p0 |> migrate_Id_Id)
                (p1 |> migrate_User_NotificationLevel)

        Evergreen.V262.Types.PressedDiscordGuildNotificationLevel p0 p1 p2 ->
            Evergreen.V263.Types.PressedDiscordGuildNotificationLevel (p0 |> migrate_Discord_Id)
                (p1 |> migrate_Discord_Id)
                (p2 |> migrate_User_NotificationLevel)

        Evergreen.V262.Types.GotScrollbarWidth p0 ->
            Evergreen.V263.Types.GotScrollbarWidth p0

        Evergreen.V262.Types.PressedCloseImageInfo ->
            Evergreen.V263.Types.PressedCloseImageInfo

        Evergreen.V262.Types.PressedMemberListBack ->
            Evergreen.V263.Types.PressedMemberListBack

        Evergreen.V262.Types.GotUserAgent p0 ->
            Evergreen.V263.Types.GotUserAgent (p0 |> migrate_UserAgent_UserAgent)

        Evergreen.V262.Types.PageHasFocusChanged p0 ->
            Evergreen.V263.Types.PageHasFocusChanged p0

        Evergreen.V262.Types.GotServiceWorkerMessage p0 ->
            Evergreen.V263.Types.GotServiceWorkerMessage p0

        Evergreen.V262.Types.VisualViewportResized p0 ->
            Evergreen.V263.Types.VisualViewportResized p0

        Evergreen.V262.Types.TextEditorMsg p0 ->
            Evergreen.V263.Types.TextEditorMsg (p0 |> migrate_TextEditor_Msg)

        Evergreen.V262.Types.PressedDiscordAcknowledgment p0 ->
            Evergreen.V263.Types.PressedDiscordAcknowledgment p0

        Evergreen.V262.Types.PressedLinkDiscordUser ->
            Evergreen.V263.Types.PressedLinkDiscordUser

        Evergreen.V262.Types.PressedReloadDiscordUser p0 ->
            Evergreen.V263.Types.PressedReloadDiscordUser (p0 |> migrate_Discord_Id)

        Evergreen.V262.Types.PressedUnlinkDiscordUser p0 ->
            Evergreen.V263.Types.PressedUnlinkDiscordUser (p0 |> migrate_Discord_Id)

        Evergreen.V262.Types.PressedDiscordGuildMemberLabel p0 ->
            Evergreen.V263.Types.PressedDiscordGuildMemberLabel
                { currentUserId = p0.currentUserId |> migrate_Discord_Id
                , otherUserId = p0.otherUserId |> migrate_Discord_Id
                }

        Evergreen.V262.Types.TypedDiscordLinkBookmarklet ->
            Evergreen.V263.Types.TypedDiscordLinkBookmarklet

        Evergreen.V262.Types.GotVersionNumber p0 ->
            Evergreen.V263.Types.GotVersionNumber p0

        Evergreen.V262.Types.PressedCloseExternalLinkWarning ->
            Evergreen.V263.Types.PressedCloseExternalLinkWarning

        Evergreen.V262.Types.PressedAddDomainToWhitelist p0 ->
            Evergreen.V263.Types.PressedAddDomainToWhitelist p0

        Evergreen.V262.Types.TypedDomainWhitelist p0 ->
            Evergreen.V263.Types.TypedDomainWhitelist p0

        Evergreen.V262.Types.PressedSaveDomainWhitelist ->
            Evergreen.V263.Types.PressedSaveDomainWhitelist

        Evergreen.V262.Types.PressedResetDomainWhitelist ->
            Evergreen.V263.Types.PressedResetDomainWhitelist

        Evergreen.V262.Types.PressedContinueToSite ->
            Evergreen.V263.Types.PressedContinueToSite

        Evergreen.V262.Types.EditMessage_MessageInputMsg p0 p1 p2 ->
            Evergreen.V263.Types.EditMessage_MessageInputMsg (p0 |> migrate_Id_AnyGuildOrDmId)
                (p1 |> migrate_Id_ThreadRoute)
                (p2 |> migrate_MessageInput_Msg)

        Evergreen.V262.Types.MessageInputMsg p0 p1 p2 ->
            Evergreen.V263.Types.MessageInputMsg (p0 |> migrate_Id_AnyGuildOrDmId)
                (p1 |> migrate_Id_ThreadRoute)
                (p2 |> migrate_MessageInput_Msg)

        Evergreen.V262.Types.GotEmojiData p0 ->
            Evergreen.V263.Types.GotEmojiData (p0 |> Result.map migrate_Emoji_CachedEmojiData)

        Evergreen.V262.Types.GotEditMessageTextInputPositionForEmojiSelector p0 ->
            Evergreen.V263.Types.GotEditMessageTextInputPositionForEmojiSelector p0

        Evergreen.V262.Types.EnableToFrontendLogging ->
            Evergreen.V263.Types.EnableToFrontendLogging

        Evergreen.V262.Types.TextSelectionChanged p0 ->
            Evergreen.V263.Types.TextSelectionChanged (p0 |> Tuple.mapSecond (Maybe.map (Tuple.mapBoth migrate_Range_Range migrate_Range_SelectionDirection)))

        Evergreen.V262.Types.DomFocusChanged p0 ->
            Evergreen.V263.Types.DomFocusChanged (p0 |> Tuple.mapSecond (Maybe.map (Tuple.mapBoth migrate_Range_Range migrate_Range_SelectionDirection)))

        Evergreen.V262.Types.PageUpGotViewport p0 ->
            Evergreen.V263.Types.PageUpGotViewport p0

        Evergreen.V262.Types.GotVoiceChatSignalFromJs p0 ->
            Evergreen.V263.Types.GotVoiceChatSignalFromJs (p0 |> Result.map migrate_Call_FromJs)

        Evergreen.V262.Types.VoiceChatMsg p0 ->
            Evergreen.V263.Types.VoiceChatMsg (p0 |> migrate_Call_Msg)

        Evergreen.V262.Types.PressedChannelHeaderTab p0 ->
            Evergreen.V263.Types.PressedChannelHeaderTab (p0 |> migrate_Route_DmChannelHeaderTab)

        Evergreen.V262.Types.FileDragEnter ->
            Evergreen.V263.Types.FileDragEnter

        Evergreen.V262.Types.FileDragLeave ->
            Evergreen.V263.Types.FileDragLeave

        Evergreen.V262.Types.FileDropped p0 ->
            Evergreen.V263.Types.FileDropped p0


migrate_Types_NewChannelForm : Evergreen.V262.Types.NewChannelForm -> Evergreen.V263.Types.NewChannelForm
migrate_Types_NewChannelForm old =
    old


migrate_Types_NewGuildForm : Evergreen.V262.Types.NewGuildForm -> Evergreen.V263.Types.NewGuildForm
migrate_Types_NewGuildForm old =
    old


migrate_Types_ScrollPosition : Evergreen.V262.Types.ScrollPosition -> Evergreen.V263.Types.ScrollPosition
migrate_Types_ScrollPosition old =
    case old of
        Evergreen.V262.Types.ScrolledToBottom ->
            Evergreen.V263.Types.ScrolledToBottom

        Evergreen.V262.Types.ScrolledToTop ->
            Evergreen.V263.Types.ScrolledToTop

        Evergreen.V262.Types.ScrolledToMiddle ->
            Evergreen.V263.Types.ScrolledToMiddle


migrate_Ui_Anim_Msg : Evergreen.V262.Ui.Anim.Msg -> Evergreen.V263.Ui.Anim.Msg
migrate_Ui_Anim_Msg old =
    old |> migrate_Internal_Model2_Msg


migrate_UserAgent_Browser : Evergreen.V262.UserAgent.Browser -> Evergreen.V263.UserAgent.Browser
migrate_UserAgent_Browser old =
    case old of
        Evergreen.V262.UserAgent.Chrome ->
            Evergreen.V263.UserAgent.Chrome

        Evergreen.V262.UserAgent.Firefox ->
            Evergreen.V263.UserAgent.Firefox

        Evergreen.V262.UserAgent.Safari ->
            Evergreen.V263.UserAgent.Safari

        Evergreen.V262.UserAgent.Edge ->
            Evergreen.V263.UserAgent.Edge

        Evergreen.V262.UserAgent.Opera ->
            Evergreen.V263.UserAgent.Opera

        Evergreen.V262.UserAgent.UnknownBrowser ->
            Evergreen.V263.UserAgent.UnknownBrowser


migrate_UserAgent_Device : Evergreen.V262.UserAgent.Device -> Evergreen.V263.UserAgent.Device
migrate_UserAgent_Device old =
    case old of
        Evergreen.V262.UserAgent.Desktop ->
            Evergreen.V263.UserAgent.Desktop

        Evergreen.V262.UserAgent.Mobile ->
            Evergreen.V263.UserAgent.Mobile

        Evergreen.V262.UserAgent.Tablet ->
            Evergreen.V263.UserAgent.Tablet


migrate_UserAgent_UserAgent : Evergreen.V262.UserAgent.UserAgent -> Evergreen.V263.UserAgent.UserAgent
migrate_UserAgent_UserAgent old =
    { browser = old.browser |> migrate_UserAgent_Browser
    , device = old.device |> migrate_UserAgent_Device
    }


migrate_UserSession_NotificationMode : Evergreen.V262.UserSession.NotificationMode -> Evergreen.V263.UserSession.NotificationMode
migrate_UserSession_NotificationMode old =
    case old of
        Evergreen.V262.UserSession.NoNotifications ->
            Evergreen.V263.UserSession.NoNotifications

        Evergreen.V262.UserSession.NotifyWhenRunning ->
            Evergreen.V263.UserSession.NotifyWhenRunning

        Evergreen.V262.UserSession.PushNotifications ->
            Evergreen.V263.UserSession.PushNotifications


migrate_User_AdminUiSection : Evergreen.V262.User.AdminUiSection -> Evergreen.V263.User.AdminUiSection
migrate_User_AdminUiSection old =
    case old of
        Evergreen.V262.User.UsersSection ->
            Evergreen.V263.User.UsersSection

        Evergreen.V262.User.LogSection ->
            Evergreen.V263.User.LogSection

        Evergreen.V262.User.DmChannelsSection ->
            Evergreen.V263.User.DmChannelsSection

        Evergreen.V262.User.DiscordDmChannelsSection ->
            Evergreen.V263.User.DiscordDmChannelsSection

        Evergreen.V262.User.DiscordUsersSection ->
            Evergreen.V263.User.DiscordUsersSection

        Evergreen.V262.User.DiscordGuildsSection ->
            Evergreen.V263.User.DiscordGuildsSection

        Evergreen.V262.User.GuildsSection ->
            Evergreen.V263.User.GuildsSection

        Evergreen.V262.User.DeletedGuildsSection ->
            Evergreen.V263.User.DeletedGuildsSection

        Evergreen.V262.User.ApiKeysSection ->
            Evergreen.V263.User.ApiKeysSection

        Evergreen.V262.User.ExportSection ->
            Evergreen.V263.User.ExportSection

        Evergreen.V262.User.ConnectionsSection ->
            Evergreen.V263.User.ConnectionsSection

        Evergreen.V262.User.FilesSection ->
            Evergreen.V263.User.FilesSection

        Evergreen.V262.User.ToBackendLogsSection ->
            Evergreen.V263.User.ToBackendLogsSection

        Evergreen.V262.User.StickersAndEmojisSection ->
            Evergreen.V263.User.StickersAndEmojisSection

        Evergreen.V262.User.VoiceChatSection ->
            Evergreen.V263.User.VoiceChatSection

        Evergreen.V262.User.WebsocketCloseEventsSection ->
            Evergreen.V263.User.WebsocketCloseEventsSection


migrate_User_NotificationLevel : Evergreen.V262.User.NotificationLevel -> Evergreen.V263.User.NotificationLevel
migrate_User_NotificationLevel old =
    case old of
        Evergreen.V262.User.NotifyOnEveryMessage ->
            Evergreen.V263.User.NotifyOnEveryMessage

        Evergreen.V262.User.NotifyOnMention ->
            Evergreen.V263.User.NotifyOnMention
