module Evergreen.Migrate.V30 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V29.AiChat
import Evergreen.V29.ChannelName
import Evergreen.V29.Coord
import Evergreen.V29.CssPixels
import Evergreen.V29.Discord
import Evergreen.V29.Discord.Id
import Evergreen.V29.DmChannel
import Evergreen.V29.EmailAddress
import Evergreen.V29.Emoji
import Evergreen.V29.FileName
import Evergreen.V29.FileStatus
import Evergreen.V29.GuildName
import Evergreen.V29.Id
import Evergreen.V29.Local
import Evergreen.V29.LocalState
import Evergreen.V29.Pages.Admin
import Evergreen.V29.Pagination
import Evergreen.V29.PersonName
import Evergreen.V29.Postmark
import Evergreen.V29.RichText
import Evergreen.V29.SecretId
import Evergreen.V29.TwoFactorAuthentication
import Evergreen.V29.Types
import Evergreen.V29.User
import Evergreen.V30.AiChat
import Evergreen.V30.ChannelName
import Evergreen.V30.Coord
import Evergreen.V30.CssPixels
import Evergreen.V30.Discord
import Evergreen.V30.Discord.Id
import Evergreen.V30.DmChannel
import Evergreen.V30.EmailAddress
import Evergreen.V30.Emoji
import Evergreen.V30.FileName
import Evergreen.V30.FileStatus
import Evergreen.V30.GuildName
import Evergreen.V30.Id
import Evergreen.V30.Local
import Evergreen.V30.LocalState
import Evergreen.V30.Pages.Admin
import Evergreen.V30.Pagination
import Evergreen.V30.PersonName
import Evergreen.V30.Postmark
import Evergreen.V30.RichText
import Evergreen.V30.SecretId
import Evergreen.V30.TwoFactorAuthentication
import Evergreen.V30.Types
import Evergreen.V30.User
import Lamdera.Migrations exposing (..)
import List
import List.Nonempty
import Maybe
import Quantity


frontendModel : Evergreen.V29.Types.FrontendModel -> ModelMigration Evergreen.V30.Types.FrontendModel Evergreen.V30.Types.FrontendMsg
frontendModel old =
    ModelReset


backendModel : Evergreen.V29.Types.BackendModel -> ModelMigration Evergreen.V30.Types.BackendModel Evergreen.V30.Types.BackendMsg
backendModel old =
    ModelReset


frontendMsg : Evergreen.V29.Types.FrontendMsg -> MsgMigration Evergreen.V30.Types.FrontendMsg Evergreen.V30.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V29.Types.ToBackend -> MsgMigration Evergreen.V30.Types.ToBackend Evergreen.V30.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V29.Types.BackendMsg -> MsgMigration Evergreen.V30.Types.BackendMsg Evergreen.V30.Types.BackendMsg
backendMsg old =
    MsgOldValueIgnored


toFrontend : Evergreen.V29.Types.ToFrontend -> MsgMigration Evergreen.V30.Types.ToFrontend Evergreen.V30.Types.FrontendMsg
toFrontend old =
    MsgUnchanged
