module Evergreen.Migrate.V93 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V92.AiChat
import Evergreen.V92.Coord
import Evergreen.V92.CssPixels
import Evergreen.V92.Editable
import Evergreen.V92.Emoji
import Evergreen.V92.FileStatus
import Evergreen.V92.Geometry.Types
import Evergreen.V92.Id
import Evergreen.V92.Internal.Model2
import Evergreen.V92.Internal.Teleport
import Evergreen.V92.LocalState
import Evergreen.V92.LoginForm
import Evergreen.V92.MessageInput
import Evergreen.V92.MessageView
import Evergreen.V92.NonemptyDict
import Evergreen.V92.Pages.Admin
import Evergreen.V92.PersonName
import Evergreen.V92.Point2d
import Evergreen.V92.Ports
import Evergreen.V92.Route
import Evergreen.V92.SecretId
import Evergreen.V92.SessionIdHash
import Evergreen.V92.Slack
import Evergreen.V92.Table
import Evergreen.V92.Touch
import Evergreen.V92.TwoFactorAuthentication
import Evergreen.V92.Types
import Evergreen.V92.Ui.Anim
import Evergreen.V92.User
import Evergreen.V92.UserAgent
import Evergreen.V92.UserSession
import Evergreen.V93.AiChat
import Evergreen.V93.Coord
import Evergreen.V93.CssPixels
import Evergreen.V93.Editable
import Evergreen.V93.Emoji
import Evergreen.V93.FileStatus
import Evergreen.V93.Geometry.Types
import Evergreen.V93.Id
import Evergreen.V93.Internal.Model2
import Evergreen.V93.Internal.Teleport
import Evergreen.V93.LocalState
import Evergreen.V93.LoginForm
import Evergreen.V93.MessageInput
import Evergreen.V93.MessageView
import Evergreen.V93.NonemptyDict
import Evergreen.V93.Pages.Admin
import Evergreen.V93.PersonName
import Evergreen.V93.Point2d
import Evergreen.V93.Ports
import Evergreen.V93.Route
import Evergreen.V93.SecretId
import Evergreen.V93.SessionIdHash
import Evergreen.V93.Slack
import Evergreen.V93.Table
import Evergreen.V93.Touch
import Evergreen.V93.TwoFactorAuthentication
import Evergreen.V93.Types
import Evergreen.V93.Ui.Anim
import Evergreen.V93.User
import Evergreen.V93.UserAgent
import Evergreen.V93.UserSession
import Lamdera.Migrations exposing (..)
import List
import Maybe
import Quantity


frontendModel : Evergreen.V92.Types.FrontendModel -> ModelMigration Evergreen.V93.Types.FrontendModel Evergreen.V93.Types.FrontendMsg
frontendModel old =
    ModelUnchanged


backendModel : Evergreen.V92.Types.BackendModel -> ModelMigration Evergreen.V93.Types.BackendModel Evergreen.V93.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V92.Types.FrontendMsg -> MsgMigration Evergreen.V93.Types.FrontendMsg Evergreen.V93.Types.FrontendMsg
frontendMsg old =
    MsgOldValueIgnored


toBackend : Evergreen.V92.Types.ToBackend -> MsgMigration Evergreen.V93.Types.ToBackend Evergreen.V93.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V92.Types.BackendMsg -> MsgMigration Evergreen.V93.Types.BackendMsg Evergreen.V93.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V92.Types.ToFrontend -> MsgMigration Evergreen.V93.Types.ToFrontend Evergreen.V93.Types.FrontendMsg
toFrontend old =
    MsgUnchanged
